### ISSUE TITLE
activate-power-mode

### ISSUE THREAD

**Issue by Blue-Jing** [Glavin001/atom-beautify#1031]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.9.0-beta0
**System**: Unknown Windows Version
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.29.8

### Stack Trace

Uncaught TypeError: Cannot read property 'querySelector' of null

```
At D:\Program Files\Atom Beta\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:852

TypeError: Cannot read property 'querySelector' of null
    at Object.module.exports.ActivatePowerMode.calculateCursorOffset (file:///C:/Users/Administrator/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:60:47)
    at Object.module.exports.ActivatePowerMode.spawnParticles (file:///C:/Users/Administrator/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:100:21)
    at Object.debounced [as throttledSpawnParticles] (C:\Users\Administrator\.atom\packages\activate-power-mode\node_modules\lodash.throttle\node_modules\lodash.debounce\index.js:182:23)
    at Object.module.exports.ActivatePowerMode.onChange (file:///C:/Users/Administrator/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:75:8)
    at Function.module.exports.Emitter.simpleDispatch (D:\Program Files\Atom Beta\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (D:\Program Files\Atom Beta\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.applyChange (D:\Program Files\Atom Beta\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:711:27)
    at TextBuffer.module.exports.TextBuffer.setTextInRange (D:\Program Files\Atom Beta\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:621:12)
    at Selection.module.exports.Selection.insertText (D:\Program Files\Atom Beta\resources\app.asar\src\selection.js:480:43)
    at D:\Program Files\Atom Beta\resources\app.asar\src\text-editor.js:931:29
    at D:\Program Files\Atom Beta\resources\app.asar\src\text-editor.js:970:29
    at TextBuffer.module.exports.TextBuffer.transact (D:\Program Files\Atom Beta\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:847:18)
    at TextEditor.module.exports.TextEditor.transact (D:\Program Files\Atom Beta\resources\app.asar\src\text-editor.js:1387:26)
    at D:\Program Files\Atom Beta\resources\app.asar\src\text-editor.js:964:24
    at TextEditor.module.exports.TextEditor.mergeSelections (D:\Program Files\Atom Beta\resources\app.asar\src\text-editor.js:2362:43)
    at TextEditor.module.exports.TextEditor.mergeIntersectingSelections (D:\Program Files\Atom Beta\resources\app.asar\src\text-editor.js:2328:35)
    at TextEditor.module.exports.TextEditor.mutateSelectedText (D:\Program Files\Atom Beta\resources\app.asar\src\text-editor.js:962:19)
    at TextEditor.module.exports.TextEditor.insertText (D:\Program Files\Atom Beta\resources\app.asar\src\text-editor.js:928:19)
    at TextEditor.object.(anonymous function) [as insertText] (D:\Program Files\Atom Beta\resources\app.asar\node_modules\underscore-plus\lib\underscore-plus.js:77:27)
    at TextEditorComponent.module.exports.TextEditorComponent.onTextInput (D:\Program Files\Atom Beta\resources\app.asar\src\text-editor-component.js:504:26)
    at HTMLDivElement.<anonymous> (D:\Program Files\Atom Beta\resources\app.asar\src\text-editor-component.js:3:61)
```

### Commands

```
     -4:46.1.0 core:paste (input.hidden-input)
  2x -3:21.1.0 tree-view:toggle (input.hidden-input)
     -0:20 activate-power-mode:toggle (input.hidden-input)
  4x -0:16.5.0 core:backspace (input.hidden-input)
     -0:11.3.0 docblockr:parse-enter (input.hidden-input)
     -0:11.3.0 editor:newline (input.hidden-input)
  5x -0:09.8.0 core:backspace (input.hidden-input)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "simplified-chinese-menu",
      "simplified-chinese-menu",
      "simplified-chinese-menu",
      "simplified-chinese-menu",
      "simplified-chinese-menu",
      "simplified-chinese-menu",
      "simplified-chinese-menu",
      "atom-beautify"
    ],
    "packagesWithKeymapsDisabled": [
      "atom-beautify"
    ],
    "projectHome": "F:\\GitHub",
    "themes": [
      "atom-material-ui",
      "gruvbox-plus-syntax"
    ]
  },
  "atom-beautify": {
    "general": {
      "_analyticsUserId": "d8abbd72-1fe2-48b1-9335-8351702ee4f6"
    }
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.5.2 (active)
atom-beautify, v0.29.8 (inactive)
atom-material-ui, v1.2.13 (active)
simplified-chinese-menu, v3.4.11 (active)
autoprefixer, v3.2.0 (inactive)
docblockr, v0.7.3 (active)
emmet, v2.4.3 (active)
expose, v0.12.1 (inactive)
file-icons, v1.7.15 (active)
gruvbox-plus-syntax, v1.2.5 (active)
javascript-snippets, v1.2.1 (active)
linter, v1.11.14 (active)
linter-jshint, v2.1.0 (active)
minimap, v4.24.6 (active)
minimap-codeglance, v0.4.5 (active)
minimap-cursorline, v0.2.0 (active)
minimap-git-diff, v4.3.1 (active)
minimap-linter, v1.1.1 (active)
minimap-selection, v4.4.0 (active)
pigments, v0.29.2 (active)
seti-icons, v1.3.1 (active)
seti-ui, v1.3.2 (inactive)
terminal-panel, v1.14.1 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.1 (active)
fuzzy-finder, v1.2.0 (active)
git-diff, v1.0.1 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.1.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.3.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by Glavin001** [comment]
>     at Object.module.exports.ActivatePowerMode.calculateCursorOffset (file:///C:/Users/Administrator/.atom/packages/activate-power-mode/lib/activate-power-mode.coffee:60:47)

This is an issue with `activate-power-mode` package.
