### ISSUE TITLE
Active editor not found

### ISSUE THREAD

**Issue by Seahyt** [Glavin001/atom-beautify#1034]
### Description

The results of beautification are not what I expect.

### Expected Results

The beautified code should have looked like:

```
<INSERT CODE HERE>
```

### Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

### Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/...

#### How to create `debug.md` Gist

Note that this will include a copy of your code.
If your code is private, please create a different sample of code that reproduces the problem.

1. In the Atom [command-palette](https://atom.io/packages/command-palette), 
search for and run the command `Atom Beautify: Help Debug Editor`. 
The debugging results will be copied to your clipboard.  
2. Create a new Gist at https://gist.github.com/  
3. Create a file in your new Gist called `debug.md`.  
4. Paste your debugging results from Atom beautify into `debug.md` file in your Gist.  
5. Add a link to your Gist in your new Issue.

# Checklist

- [ ] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues 
so I know this is not a duplicate issue
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
Please provide more information describing your issue, then this Issue can be reopened. Thank you.

More specifically, adding a link to the required `debug.md` Gist which includes debugging information that answers our most commonly asked questions: https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md#how-to-create-debugmd-gist

**Comment by fintroductions** [comment]
Having the same issue, 

Active Editor not found.
Active Editor not found. 
Hide Stack Trace
Error: Active Editor not found. 
    at /Users/Sloan/.atom/packages/atom-beautify/src/beautify.coffee:152:29
    at Promise._execute (/Users/Sloan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/Sloan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/Sloan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:79:10)
    at atom-workspace.beautify (/Users/Sloan/.atom/packages/atom-beautify/src/beautify.coffee:77:14)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/private/var/folders/9n/dtdf625d7c956z6vdm0d5jm40000gn/T/AppTranslocation/202D7DA2-9F15-42AD-907B-0CCF82618F17/d/Atom.app/Contents/Resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/private/var/folders/9n/dtdf625d7c956z6vdm0d5jm40000gn/T/AppTranslocation/202D7DA2-9F15-42AD-907B-0CCF82618F17/d/Atom.app/Contents/Resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/private/var/folders/9n/dtdf625d7c956z6vdm0d5jm40000gn/T/AppTranslocation/202D7DA2-9F15-42AD-907B-0CCF82618F17/d/Atom.app/Contents/Resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/private/var/folders/9n/dtdf625d7c956z6vdm0d5jm40000gn/T/AppTranslocation/202D7DA2-9F15-42AD-907B-0CCF82618F17/d/Atom.app/Contents/Resources/app/src/atom-environment.js:1314:34)
    at EventEmitter.outerCallback (/private/var/folders/9n/dtdf625d7c956z6vdm0d5jm40000gn/T/AppTranslocation/202D7DA2-9F15-42AD-907B-0CCF82618F17/d/Atom.app/Contents/Resources/app/src/application-delegate.js:334:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)

**Comment by Glavin001** [comment]
@fintroductions,

Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.
