### ISSUE TITLE
TypeError: Bad argument

### ISSUE THREAD

**Issue by MikeLP** [Glavin001/atom-beautify#1044]
Never mind what I use - PHPCBF or PHP-CS-FIXER (was installed via brew), I always get next error. I have tried to reinstall beautify and reinstall atom and nothing. Separately (in terminal) that tools works fine.

`TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:274:26)
    at exports.spawn (child_process.js:374:9)
    at /Users/iyanello/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:136:17
    at Promise._execute (/Users/iyanello/.atom/packages/atom-beautify/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/Users/iyanello/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:475:18)
    at new Promise (/Users/iyanello/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:77:14)
    at PHPCSFixer.module.exports.Beautifier.getShellEnvironment (/Users/iyanello/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:116:16)
    at /Users/iyanello/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:261:38
    at tryCatcher (/Users/iyanello/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/iyanello/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/Users/iyanello/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/Users/iyanello/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/Users/iyanello/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/Users/iyanello/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:630:18)
    at PromiseArray._resolve (/Users/iyanello/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/Users/iyanello/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/Users/iyanello/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:566:26)
    at Promise._settlePromise0 (/Users/iyanello/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/Users/iyanello/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/Users/iyanello/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:630:18)
    at PromiseArray._resolve (/Users/iyanello/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/Users/iyanello/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/Users/iyanello/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:566:26)
    at Promise._settlePromise0 (/Users/iyanello/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/Users/iyanello/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (/Users/iyanello/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/iyanello/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:148:10)
    at Async.drainQueues (/Users/iyanello/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)`

**Comment by Glavin001** [comment]
Please follow the issue template provided. More specifically, adding a link to the required `debug.md` Gist which includes debugging information that answers our most commonly asked questions: https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md#how-to-create-debugmd-gist
Thank you.
