### ISSUE TITLE
Uncaught Error: Cannot find module 'bluebird'

### ISSUE THREAD

**Issue by Roballen** [Glavin001/atom-beautify#1075]
1. Open top nav, select packages, select Atom Beautify, click Beatify

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.2
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.29.10

### Stack Trace

Uncaught Error: Cannot find module 'bluebird'

```
At module.js:340

Error: Cannot find module 'bluebird'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/rob/.atom/packages/atom-beautify/node_modules/editorconfig/editorconfig.js:5:15)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Beautifiers.module.exports.Beautifiers.getOptionsForPath (/Users/rob/.atom/packages/atom-beautify/src/beautifiers/index.coffee:702:23)
    at atom-workspace.beautify (/Users/rob/.atom/packages/atom-beautify/src/beautify.coffee:163:27)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:327:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

### Commands

```
     -3:17.6.0 core:select-all (atom-text-editor.editor.is-focused)
     -3:16.2.0 core:paste (atom-text-editor.editor.is-focused)
  2x -3:08.8.0 core:save (atom-text-editor.editor.is-focused)
     -3:04.4.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -3:01.4.0 core:select-all (atom-text-editor.editor.is-focused)
     -2:58.6.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
  2x -2:50.8.0 core:save (atom-text-editor.editor.is-focused)
     -2:42.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.theme-one-dark-syntax.theme-atom-dark-ui.scrollbars-visible-always.find-visible)
     -0:35.6.0 atom-alignment:align (atom-text-editor.editor.is-focused)
     -0:30.6.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:01.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "atom-beautify": {
    "_analyticsUserId": "36d22709-600f-49e6-86d7-f7cc2a7e68c2",
    "js_end_with_comma": true,
    "js_end_with_newline": true
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.12.1
atom-beautify, v0.29.10
atom-handlebars, v1.3.0
autoclose-html, v0.23.0
language-ember-htmlbars, v0.3.0
linter, v1.11.14
linter-eslint, v7.2.4
minimap, v4.24.7
minimap-autohide, v0.10.1
minimap-hide, v0.3.0
pigments, v0.31.1
zentabs, v0.8.7

# Dev
No dev packages
```

**Comment by Glavin001** [comment]
Have you tried reinstalling Atom-Beautify and then restarting/reloading Atom?
