### ISSUE TITLE
bug with erb file and actionview::Helper::FormHelper.text_field

### ISSUE THREAD

**Issue by lehug** [Glavin001/atom-beautify#1097]
# Description
.erb file,code like this:
<%=f.text_field :linkto,class: "form-control",data:{toggle: "modal", target:"#modal-linkto"} %>
then bug happened 

# Steps to Reproduce

1. set "beautify on save" true with erb
2.have code like:" <%=f.text_field :linkto,class: "form-control",data:{toggle: "modal", target:"#modal-linkto"} %> ",contails data attribute
3.then save.

# Debug

Error: This TextEditor has been destroyed
    at DisplayBuffer.module.exports.DisplayBuffer.screenPositionForBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:794:15)
    at TextEditorMarker.module.exports.TextEditorMarker.getHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-marker.js:179:33)
    at Cursor.module.exports.Cursor.getScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:73:26)
    at Cursor.module.exports.Cursor.getScreenRange (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:685:20)
    at Cursor.module.exports.Cursor.autoscroll (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:690:51)
    at Cursor.module.exports.Cursor.changePosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:675:21)
    at Cursor.module.exports.Cursor.setBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:80:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1527:23
    at TextEditor.module.exports.TextEditor.moveCursors (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1780:9)
    at TextEditor.module.exports.TextEditor.setCursorBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1526:19)
    at setCursors (/Users/jyd-9062/.atom/packages/atom-beautify/src/beautify.coffee:52:14)
    at beautifyCompleted (/Users/jyd-9062/.atom/packages/atom-beautify/src/beautify.coffee:122:11)
    at tryCatcher (/Users/jyd-9062/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jyd-9062/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/Users/jyd-9062/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/Users/jyd-9062/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/Users/jyd-9062/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (/Users/jyd-9062/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/jyd-9062/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:148:10)
    at Async.drainQueues (/Users/jyd-9062/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)

**Comment by lehug** [comment]
this is my first issue,I'm Chinese,my english is poor~

**Comment by prettydiff** [comment]
@lehug Could you please produce the `debug.md` file that Atom Beautify makes?  Paste it into a gist at http://gist.github.com

> this is my first issue,I'm Chinese,my english is poor~

No problem.  We will try to help as much as we can.

**Comment by lehug** [comment]
in new version 1.9,it works,Thanks
