### ISSUE TITLE
Throws error beautifying scss file that validates

### ISSUE THREAD

**Issue by smlombardi** [Glavin001/atom-beautify#1129]
I have an [SCSS file](http://jmp.sh/JiZNt4I) that I got from a library online.  Stylelint validates it, and it compiles and works fine.  There's a section that trips up Beautify with the following error.  Admittedly, it's a complex piece of scss.

```

Line 0File 0Project 0No Issuesapp/modules/progress/assets/sass/_progress-tracker.scss243:1
LFUTF-8SCSSds3/progress-tracker
Unsupported beautification result 'Parsing error: Please check the validity of the block starting from line #237

235 | .progress-step { 236 | &:after { 237| width: calc(100% - #{$marker-size + ($marker-spacing 2)}); 238 | margin-right: ($marker-size-half + $marker-spacing); 239 | }

Gonzales PE version: 3.0.0-28 Syntax: scss'.
Unsupported beautification result 'Parsing error: Please check the validity of the block starting from line #237
235 |   .progress-step {
236 |     &:after {
237*|       width: calc(100% - #{$marker-size + ($marker-spacing * 2)});
238 |       margin-right: ($marker-size-half + $marker-spacing);
239 |     }
Gonzales PE version: 3.0.0-28
Syntax: scss'.
Hide Stack Trace
Error: Unsupported beautification result 'Parsing error: Please check the validity of the block starting from line #237
235 |   .progress-step {
236 |     &:after {
237*|       width: calc(100% - #{$marker-size + ($marker-spacing * 2)});
238 |       margin-right: ($marker-size-half + $marker-spacing);
239 |     }
Gonzales PE version: 3.0.0-28
Syntax: scss'.
    at beautifyCompleted (/Users/stevelombardi/.atom/packages/atom-beautify/src/beautify.coffee:135:21)
    at tryCatcher (/Users/stevelombardi/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/stevelombardi/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/stevelombardi/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/stevelombardi/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/stevelombardi/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:679:18)
    at Async._drainQueue (/Users/stevelombardi/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/stevelombardi/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/async.js:148:10)
    at Async.drainQueues (/Users/stevelombardi/.atom/packages/editorconfig/node_modules/editorconfig/node_modules/bluebird/js/release/async.js:17:14)

```

**Comment by prettydiff** [comment]
Could you please generate the debug.md file and paste it into a gist?  Pretty Diff is the default beautifier for SCSS, but Pretty Diff does not generate error messages like this.

**Comment by smlombardi** [comment]
The debug command does not put anything on the clipboard.

Atom 1.10.0 beta 4, OS 10.11.6

**Comment by prettydiff** [comment]
Which beautifier are you using?  I looked up Gonzales PE, which is a CSS parser, but I wasn't aware it was an option for CSS in Atom Beautify, *shows what I know ;)*.

**Comment by smlombardi** [comment]
Atom Beautify is set to use CSSComb.  I will switch it to PrettyDiff and see what happens.
