### ISSUE TITLE
Cannot read property 'getView' of undefined

### ISSUE THREAD

**Issue by v4venureddyg** [Glavin001/atom-beautify#1130]
I am trying to beautify my javascript but i am getting the error saying "Cannot read property 'getView' of undefined"

TypeError: Cannot read property 'getView' of undefined
    at getScrollTop (/Users/gagopal/.atom/packages/atom-beautify/src/beautify.coffee:31:29)
    at beautifyCompleted (/Users/gagopal/.atom/packages/atom-beautify/src/beautify.coffee:108:27)
    at tryCatcher (/Users/gagopal/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/gagopal/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/gagopal/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/gagopal/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/gagopal/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/Users/gagopal/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/gagopal/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:148:10)
    at Async.drainQueues (/Users/gagopal/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)

**Comment by prettydiff** [comment]
https://github.com/Glavin001/atom-beautify/issues/977

**Comment by mleko** [comment]
Same for me
*.html files
Atom 1.9.8 @ OSX 10.11.6
atom-beautify 0.29.10

**Comment by prettydiff** [comment]
I found I can easily toggle this error on by using the code sample at https://github.com/Glavin001/atom-beautify/issues/1138#issuecomment-240333822

Notice the extra `});` at the bottom.  Adding that extra in caused the error for me.

**Comment by amezng** [comment]
I am facing this issue in Atom 1.11.2 and atom-beautify 0.29.13 for html files as of now..

**Comment by jlndk** [comment]
Can confirm i have the same issue here. 
Running Atom 1.11.2 with atom beautify 0.29.13 on Windows 10.
Tried to beautify html (with polymer), js and json files.

**Comment by Glavin001** [comment]
Weird. Looks like it is from https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L31 and therefore `atom.views` is `undefined`.

Are you still experiencing these issues on latest Atom?

**Comment by amezng** [comment]
After upgrading, I am not facing this issue. Thanks a ton.

**Comment by Glavin001** [comment]
Awesome to hear!
