### ISSUE TITLE
Parsing: D:\TEMP\hoge as language C ???: Unable to create D:: Permission denied (13)

### ISSUE THREAD

**Issue by Rouryi** [Glavin001/atom-beautify#1189]
# Description

I can't use atom-beautify because Permission denied.
# Expected Results

The beautified code should have looked like:

```
Parsing: D:\TEMP\input116812-5960-1bird32.f0xp3nmi as language C ???: Unable to create D:: Permission denied (13)
Parsing: D:\TEMP\input116812-5960-1bird32.f0xp3nmi as language C
???: Unable to create D:: Permission denied (13)
Hide Stack Trace
Error: Parsing: D:\TEMP\input116812-5960-1bird32.f0xp3nmi as language C
???: Unable to create D:: Permission denied (13)
    at file:///C:/Users/HOGE/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:295:27
    at tryCatcher (C:\Users\HOGE\.atom\packages\atom-beautify\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\HOGE\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (C:\Users\HOGE\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (C:\Users\HOGE\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (C:\Users\HOGE\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (C:\Users\HOGE\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (C:\Users\HOGE\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:148:10)
    at Async.drainQueues (C:\Users\HOGE\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:17:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```
# Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
# Debug

When I do debug Atom beautify, there are nothing copied. sorry.
D:/ATOM/uncrustify.exe
D:/ATOM/uncrustify.cfg
I use https://gist.github.com/tesuheee/64733fa9f6a94f2157dd.
# Checklist
- [ ] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
  so I know this is not a duplicate issue
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
Maybe you need to run Atom in Administrator mode or something so it has write permission? I will need the `debug.md` Gist to help more.

I recommend updating Atom-Beautify and trying again:

> Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.

This issue can be reopened once we have the `debug.md` Gist. Thanks!

**Comment by Mayshy** [comment]
I had the same problem with you.Though I can not catch the reason, you change your temp environment path from "D/temp" to "%SystemRoot%\TEMP" ,which will solve it.
