### ISSUE TITLE
cannot find module 'event-module'

### ISSUE THREAD

**Issue by wsvdyk** [Glavin001/atom-beautify#1228]
# Description

after update I get the followinging error

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.29.13

### Stack Trace

Uncaught Error: Cannot find module 'event-kit'

```
At module.js:341

Error: Cannot find module 'event-kit'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (C:\Users\Wesley\AppData\Local\atom\app-1.10.2\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (C:\Users\Wesley\AppData\Local\atom\app-1.10.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Wesley/.atom/packages/atom-beautify/src/beautify.coffee:7:25)
    at Object.<anonymous> (file:///C:/Users/Wesley/.atom/packages/atom-beautify/src/beautify.coffee:2:1)
    at Module._compile (C:\Users\Wesley\AppData\Local\atom\app-1.10.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Wesley\AppData\Local\atom\app-1.10.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\Users\Wesley\AppData\Local\atom\app-1.10.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\Wesley\AppData\Local\atom\app-1.10.2\resources\app.asar\src\package.js:718:27)
    at Package.module.exports.Package.activateConfig (C:\Users\Wesley\AppData\Local\atom\app-1.10.2\resources\app.asar\src\package.js:225:12)
    at PackageManager.module.exports.PackageManager.packageHasSettings (C:\Users\Wesley\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\settings-view\lib\package-manager.js:55:14)
    at PackageCard.module.exports.PackageCard.hasSettings (C:\Users\Wesley\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\settings-view\lib\package-card.js:699:34)
    at PackageCard.module.exports.PackageCard.updateSettingsState (C:\Users\Wesley\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\settings-view\lib\package-card.js:397:16)
    at PackageCard.module.exports.PackageCard.updateInterfaceState (C:\Users\Wesley\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\settings-view\lib\package-card.js:390:12)
    at PackageCard.module.exports.PackageCard.initialize (C:\Users\Wesley\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\settings-view\lib\package-card.js:248:19)
    at PackageCard.View [as constructor] (C:\Users\Wesley\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\space-pen\lib\space-pen.js:184:25)
    at new PackageCard (C:\Users\Wesley\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\settings-view\lib\package-card.js:22:48)
    at Object.content (C:\Users\Wesley\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:79:57)
    at Builder.tag (C:\Users\Wesley\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\space-pen\lib\space-pen.js:281:19)
    at Function.View.(anonymous function) [as div] (C:\Users\Wesley\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\space-pen\lib\space-pen.js:83:49)
    at Object.content (C:\Users\Wesley\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:74:30)
    at Builder.tag (C:\Users\Wesley\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\space-pen\lib\space-pen.js:281:19)
    at Function.View.(anonymous function) [as div] (C:\Users\Wesley\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\space-pen\lib\space-pen.js:83:49)
    at Object.content (C:\Users\Wesley\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:71:21)
    at Builder.tag (C:\Users\Wesley\AppData\Local\atom\app-1.10.2\resources\app.asar\node_modules\space-pen\lib\space-pen.js:281:19)
```

### Commands

```
```

### Config

```json
{
  "core": {},
  "atom-beautify": {
    "general": {
      "_analyticsUserId": "3a186369-b4fd-4afd-8e85-38a701b5b221"
    },
    "php": {
      "cs_fixer_path": "C:\\xampp\\php\\php-cs-fixer.phar"
    }
  }
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.19.4 (inactive)
atom-beautify, v0.29.13 (inactive)
linter, v1.11.16 (inactive)
linter-php, v1.2.0 (inactive)
minimap, v4.25.0 (inactive)
minimap-autohide, v0.10.1 (inactive)
minimap-linter, v1.6.0 (inactive)
php-server, v0.7.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (inactive)
archive-view, v0.61.1 (inactive)
autocomplete-atom-api, v0.10.0 (inactive)
autocomplete-css, v0.11.2 (inactive)
autocomplete-html, v0.7.2 (inactive)
autocomplete-plus, v2.31.1 (inactive)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (inactive)
background-tips, v0.26.1 (inactive)
bookmarks, v0.41.0 (inactive)
bracket-matcher, v0.82.1 (inactive)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (inactive)
dev-live-reload, v0.47.0 (inactive)
encoding-selector, v0.22.0 (inactive)
exception-reporting, v0.39.0 (inactive)
find-and-replace, v0.201.0 (inactive)
fuzzy-finder, v1.3.0 (inactive)
git-diff, v1.1.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (inactive)
image-view, v0.58.2 (inactive)
incompatible-packages, v0.26.1 (inactive)
keybinding-resolver, v0.35.0 (inactive)
line-ending-selector, v0.5.0 (inactive)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v0.53.1 (inactive)
notifications, v0.65.0 (inactive)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (inactive)
snippets, v1.0.2 (inactive)
spell-check, v0.67.1 (inactive)
status-bar, v1.4.1 (inactive)
styleguide, v0.47.0 (inactive)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (inactive)
timecop, v0.33.2 (inactive)
tree-view, v0.208.2 (inactive)
update-package-dependencies, v0.10.0 (inactive)
welcome, v0.34.0 (inactive)
whitespace, v0.33.0 (inactive)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.2 (inactive)
language-csharp, v0.12.1 (inactive)
language-css, v0.37.1 (inactive)
language-gfm, v0.88.0 (inactive)
language-git, v0.15.0 (inactive)
language-go, v0.42.1 (inactive)
language-html, v0.45.1 (inactive)
language-hyperlink, v0.16.0 (inactive)
language-java, v0.23.0 (inactive)
language-javascript, v0.119.0 (inactive)
language-json, v0.18.2 (inactive)
language-less, v0.29.5 (inactive)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.2 (inactive)
language-property-list, v0.8.0 (inactive)
language-python, v0.45.0 (inactive)
language-ruby, v0.69.0 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.56.0 (inactive)
language-shellscript, v0.22.4 (inactive)
language-source, v0.9.0 (inactive)
language-sql, v0.23.0 (inactive)
language-text, v0.7.1 (inactive)
language-todo, v0.28.0 (inactive)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.9 (inactive)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by Glavin001** [comment]
Try reinstalling Atom-Beautify and reloading Atom, as this often solves problems like this.

**Comment by wsvdyk** [comment]
thx that fixed it.

**Comment by Glavin001** [comment]
Awesome, glad to hear! Thanks for letting us know.
