### ISSUE TITLE
Bad Argument error on Mac OS

### ISSUE THREAD

**Issue by karnick** [Glavin001/atom-beautify#1249]
# Description

The results of beautification are not what I expect.
# Expected Results

The beautified code should have looked like:

```
<INSERT CODE HERE>
```
# Steps to Reproduce
1. Add code to Atom editor
   print("Hello"
   );
2. Run command `Atom Beautify: Beautify Editor` or Click Atom Beautify from package
3. This beautified code does not look right!
   I get Bad argument error. Stack Trace added as well
# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/939c0d76fa88402d6f0ff5ab67859265

StackTrace
TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:278:26)
    at exports.spawn (child_process.js:379:9)
    at /Users/ksriram/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:136:17
    at Promise._execute (/Users/ksriram/.atom/packages/atom-beautify/node_modules/bluebird/js/release/debuggability.js:299:9)
    at Promise._resolveFromExecutor (/Users/ksriram/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/Users/ksriram/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:77:14)
    at PerlTidy.module.exports.Beautifier.getShellEnvironment (/Users/ksriram/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:116:16)
    at /Users/ksriram/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:269:38
    at tryCatcher (/Users/ksriram/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/ksriram/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/ksriram/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/ksriram/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/ksriram/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/ksriram/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:636:18)
    at PromiseArray._resolve (/Users/ksriram/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/Users/ksriram/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/Users/ksriram/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:572:26)
    at Promise._settlePromise0 (/Users/ksriram/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/ksriram/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/ksriram/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:636:18)
    at PromiseArray._resolve (/Users/ksriram/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/Users/ksriram/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/Users/ksriram/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:572:26)
    at Promise._settlePromise0 (/Users/ksriram/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/ksriram/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/ksriram/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/ksriram/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:148:10)
    at Async.drainQueues (/Users/ksriram/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
# Checklist
- [Yes ] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [Yes ] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [Yes] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
  so I know this is not a duplicate issue
- [Yes] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by karnick** [comment]
I'm facing the same "Bad argument" error for Java. 
However Javascript format works fine.

**Comment by Down10** [comment]
I'm having these problems, too. I run Beautify on untidy CSS code and I get an "Invalid array length" error, with similar pile of "Promise" errors (as pasted above) in the stack trace.
