### ISSUE TITLE
Uncaught Error: Cannot find module './_stream_duplex'

### ISSUE THREAD

**Issue by Nejurgis** [Glavin001/atom-beautify#1308]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.9.5
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.29.13
### Stack Trace

Uncaught Error: Cannot find module './_stream_duplex'

```
At module.js:341

Error: Cannot find module './_stream_duplex'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at BufferList.Readable (/Users/Mountain/.atom/packages/atom-beautify/node_modules/bl/node_modules/readable-stream/lib/_stream_readable.js:128:22)
    at BufferList.Duplex (/Users/Mountain/.atom/packages/atom-beautify/node_modules/bl/node_modules/readable-stream/lib/_stream_duplex.js:43:12)
    at new BufferList (/Users/Mountain/.atom/packages/atom-beautify/node_modules/bl/bl.js:32:16)
    at BufferList (/Users/Mountain/.atom/packages/atom-beautify/node_modules/bl/bl.js:7:12)
    at Request.readResponseBody (/Users/Mountain/.atom/packages/atom-beautify/node_modules/request/request.js:992:16)
    at Request.onRequestResponse (/Users/Mountain/.atom/packages/atom-beautify/node_modules/request/request.js:973:12)
    at emitOne (events.js:90:13)
    at ClientRequest.emit (events.js:182:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:458:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
    at Socket.socketOnData (_http_client.js:348:20)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:531:20)
```
### Commands

```
     -4:01.6.0 core:save (atom-text-editor.editor.is-focused)
     -3:56.2.0 atom-beautify:help-debug-editor (atom-text-editor.editor.is-focused)
     -3:35.7.0 core:select-all (atom-text-editor.editor.is-focused)
     -3:34.5.0 core:undo (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:33.3.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -3:33.3.0 core:cancel (atom-text-editor.editor.is-focused)
     -3:33 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -3:33 core:cancel (atom-text-editor.editor.is-focused)
     -2:07.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:54.9.0 open-in-browser:open (atom-text-editor.editor.is-focused)
     -0:00.6.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "atom-beautify": {
    "general": {
      "_analyticsUserId": "f8555822-43b5-4559-95b8-f741c43c8dcd"
    }
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.13 (active)
atom-jade, v0.3.0 (active)
autoprefixer, v3.3.0 (inactive)
emmet, v2.4.3 (active)
open-in-browser, v0.4.7 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (active)
one-light-ui, v1.6.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by ivanhuay** [comment]
+1

**Comment by prettydiff** [comment]
Would you mind trying this and let me know if the problem persists:

`apm install atom-beautify`

**Comment by Deekers** [comment]
The "apm install atom-beautify" seemed to resolve the problem.

**Comment by sosnet** [comment]
With `apm install atom-beautify` and a restart of `atom` the problem is resolved.
Maybe the restart after the auto-update would have been enough.

**Comment by carmelolg** [comment]
+1

**Comment by abbas133** [comment]
+1
Restarting works.

**Comment by Glavin001** [comment]
Glad to hear it is working with a restart!
