### ISSUE TITLE
error when use atom-beauty in linux

### ISSUE THREAD

**Issue by dyazincahya** [Glavin001/atom-beautify#1309]
I have error when use atom-beauty in linux zorin 10, how to fix this error ?
==========================================================
Could not find 'php-cs-fixer'. The program may not be installed.

See https://github.com/FriendsOfPHP/PHP-CS-Fixer for program installation instructions.
Your program is properly installed if running 'which php-cs-fixer' in your Terminal returns an absolute path to the executable. If this does not work then you have not installed the program correctly and so Atom Beautify will not find the program. Atom Beautify requires that the program be found in your PATH environment variable. 
Note that this is not an Atom Beautify issue if beautification does not work and the above command also does not work: this is expected behaviour, since you have not properly installed your program. Please properly setup the program and search through existing Atom Beautify issues before creating a new issue. See https://github.com/Glavin001/atom-beautify/search?q=php-cs-fixer&type=Issues for related Issues and https://github.com/Glavin001/atom-beautify/tree/master/docs for documentation. If you are still unable to resolve this issue on your own then please create a new issue and ask for help.
Hide Stack Trace
Error: Could not find 'php-cs-fixer'. The program may not be installed.
    at PHPCSFixer.module.exports.Beautifier.commandNotFoundError (/home/kang-cahya/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:204:14)
    at /home/kang-cahya/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:304:22
    at tryCatcher (/home/kang-cahya/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/kang-cahya/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/kang-cahya/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/kang-cahya/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/kang-cahya/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/home/kang-cahya/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/kang-cahya/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:148:10)
    at Async.drainQueues (/home/kang-cahya/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by Glavin001** [comment]
I really want to focus on improving the installation experience for users. I have created a new Issue, #1687, to target this problem. Please provide your feedback! Thanks in advance.
