### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setScrollTop' of null

### ISSUE THREAD

**Issue by anampiu** [Glavin001/atom-beautify#1339]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.11.2
**Electron Version**: 0.37.8
**System**: elementary OS
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.29.13

### Stack Trace

Uncaught TypeError: Cannot read property 'setScrollTop' of null

```
At /home/travis/build/atom/atom/out/app/src/text-editor-element.coffee:324

TypeError: Cannot read property 'setScrollTop' of null
    at atom-text-editor.TextEditorElement.setScrollTop (/usr/share/atom/resources/app.asar/src/text-editor-element.js:324:28)
    at setScrollTop (/home/andrew/.atom/packages/atom-beautify/src/beautify.coffee:35:9)
    at /home/andrew/.atom/packages/atom-beautify/src/beautify.coffee:131:13
```

### Commands

```
     -6:13.5.0 pane:move-active-item-to-top-of-stack (a.inline-block)
  5x -5:36.1.0 window:toggle-full-screen (atom-text-editor.editor.is-focused)
     -5:07.0 pane:split-up-and-copy-active-item (atom-text-editor.editor.is-focused)
     -4:58.6.0 pane:split-left-and-copy-active-item (atom-text-editor.editor.is-focused)
  2x -4:41.8.0 window:toggle-dev-tools (atom-text-editor.editor.is-focused)
     -3:56.8.0 pane:split-up-and-copy-active-item (a.inline-block)
     -3:46.6.0 pane:close (a.inline-block)
     -3:28 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -3:18.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:16.8.0 core:save (atom-text-editor.editor.is-focused)
     -3:14.5.0 settings-view:open (atom-text-editor.editor.is-focused)
     -3:06.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:06.3.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.mini.is-focused)
  2x -3:04.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:00.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:07.5.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "limited",
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "atom-beautify": {
    "css": {
      "beautify_on_save": true
    },
    "general": {
      "_analyticsUserId": "913adb1f-b937-4e7e-81af-1f5e7dd8785e"
    },
    "html": {
      "beautify_on_save": true
    },
    "java": {
      "beautify_on_save": true
    },
    "js": {
      "beautify_on_save": true
    },
    "markdown": {
      "beautify_on_save": true
    },
    "python": {
      "beautify_on_save": true
    },
    "ruby": {
      "beautify_on_save": true
    }
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.13 (active)
atom-html-preview, v0.1.22 (active)
emmet, v2.4.3 (active)
git-plus, v5.24.0 (active)
language-babel, v2.47.0 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.2.0 (inactive)
base16-tomorrow-light-theme, v1.2.0 (inactive)
one-dark-ui, v1.6.0 (inactive)
one-light-ui, v1.6.0 (active)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (active)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.7.0 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.201.1 (active)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.59.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v1.0.0 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2-hotfix1 (active)
snippets, v1.0.2 (active)
spell-check, v0.68.2 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.101.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.209.3 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by darrenbarklie** [comment]
```
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.6
**Electron Version**: 1.3.9
**System**: Mac OS X 10.11.3
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.29.13


### Stack Trace

Uncaught TypeError: Cannot read property 'setScrollTop' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:318

TypeError: Cannot read property 'setScrollTop' of null
    at atom-text-editor.TextEditorElement.setScrollTop (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:318:28)
    at setScrollTop (/Users/daz/.atom/packages/atom-beautify/src/beautify.coffee:35:9)
    at /Users/daz/.atom/packages/atom-beautify/src/beautify.coffee:131:13
```

### Commands

```
     -3:25 core:move-right (atom-text-editor.editor.is-focused)
     -3:23.1.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -3:20.6.0 core:select-all (atom-text-editor.editor.is-focused)
     -3:19.6.0 core:copy (atom-text-editor.editor.is-focused)
     -2:39.5.0 core:cut (atom-text-editor.editor.is-focused)
     -2:38.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:36.8.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:36.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -2:35.7.0 core:paste (atom-text-editor.editor.is-focused)
     -2:34.3.0 core:save (atom-text-editor.editor.is-focused)
     -2:33 core:select-all (atom-text-editor.editor.is-focused)
     -2:32.6.0 core:copy (atom-text-editor.editor.is-focused)
  8x -1:27.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:04.6.0 core:save (atom-text-editor.editor.is-focused)
     -1:04.1.0 core:select-all (atom-text-editor.editor.is-focused)
     -0:00.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "telemetryConsent": "no"
  },
  "atom-beautify": {
    "general": {
      "_analyticsUserId": "f2c99b15-7f53-46dc-a19c-e0021057dd67"
    },
    "html": {
      "beautify_on_save": true,
      "indent_inner_html": true,
      "indent_size": 2,
      "wrap_line_length": 0
    }
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.13 (active)
atom-spotify2, v2.1.2 (active)
autoclose-html, v0.23.0 (active)
file-icons, v1.7.19 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (active)
one-light-ui, v1.6.2 (inactive)
one-dark-syntax, v1.5.0 (active)
one-light-syntax, v1.5.0 (inactive)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

```

**Comment by steebchen** [comment]
Really annoying, that's why I used this quick fix:

change `view?.setScrollTop value` to `view?.setScrollTop? value` in `~/.atom/packages/atom-beautify/src/beautify.coffee`.

**Comment by prettydiff** [comment]
Additional information from #1475 - http://stackoverflow.com/questions/41351215/atom-editor-atom-beautify-plugin-error-uncaught-typeerror-cannot-read-propert
