### ISSUE TITLE
Issue with .phtml files

### ISSUE THREAD

**Issue by Jakub41** [Glavin001/atom-beautify#1364]
# Description

Hello,

I'm having this issue with the beautify with phtml files.
I don't have any problem with the other codes all works perfectly but when I run in the phtm file I receiving this error:  

Could not find 'php-cs-fixer'. The program may not be installed.

Error: Could not find 'php-cs-fixer'. The program may not be installed.
    at PHPCSFixer.module.exports.Beautifier.commandNotFoundError (/home/jakub/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:204:14)
    at /home/jakub/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:304:22
    at tryCatcher (/home/jakub/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/jakub/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/jakub/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/jakub/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/jakub/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/home/jakub/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/home/jakub/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:148:10)
    at Async.drainQueues (/home/jakub/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)

I have the php-cs-fixer installed on my Ubuntu but is not working only with .phtml files.
Thank you for help,
Jakub

**Comment by crobinson42** [comment]
Check the settings in the package in Atom and make sure you're pointing to where you installed php-cs-fixer OR try installing php-cs-fixer with `brew`

**Comment by Glavin001** [comment]
Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.

This issue can be reopened once we have the appropriate information to help you.

I also recommend you search through the many other related Issues before creating you own: https://github.com/Glavin001/atom-beautify/search?q=Could+not+find+%27php-cs-fixer%27.+&state=closed&type=Issues&utf8=%E2%9C%93

**Comment by Glavin001** [comment]
I really want to focus on improving the installation experience for users. I have created a new Issue, #1687, to target this problem. Please provide your feedback! Thanks in advance.

**Comment by DrCod3r** [comment]
the same problem for me what i have to do ?

**Comment by szeck87** [comment]
@DrCod3r Please look at #1687, or if you already have php-cs-fixer installed, #1864. The latter was a very recent issue similar to this.
