### ISSUE TITLE
Pure JSON format

### ISSUE THREAD

**Issue by QwertyZW** [Glavin001/atom-beautify#1365]
Need a beautifier for this kind of grammar

```
{
	"id": "0001",
	"type": "donut",
	"name": "Cake",
	"ppu": 0.55,
	"batters":
		{
			"batter":
				[
					{ "id": "1001", "type": "Regular" },
					{ "id": "1002", "type": "Chocolate" },
					{ "id": "1003", "type": "Blueberry" },
					{ "id": "1004", "type": "Devil's Food" }
				]
		},
	"topping":
		[
			{ "id": "5001", "type": "None" },
			{ "id": "5002", "type": "Glazed" },
			{ "id": "5005", "type": "Sugar" },
			{ "id": "5007", "type": "Powdered Sugar" },
			{ "id": "5006", "type": "Chocolate with Sprinkles" },
			{ "id": "5003", "type": "Chocolate" },
			{ "id": "5004", "type": "Maple" }
		]
}
```

**Comment by prettydiff** [comment]
It looks like normal JSON.  You can beautify it as JSON or JavaScript.

**Comment by QwertyZW** [comment]
I think the issue is with the size of the file. Atom lags specifically with what I'm trying to paste this large json chunk, and after beautifying it it throws this error:

![cantbeautify](https://cloud.githubusercontent.com/assets/8478946/20418033/091ad0ce-acee-11e6-979f-6aacd6d18ac7.PNG)

Currently trying to figure out if the entire chunk of the json is being pasted into atom. It's simply a json response from the network log from chrome's debugging tools.

**Comment by QwertyZW** [comment]
Can you try beatifying this file?

One of them was saved by notepad, the other by atom. The content were copied from dev tools and pasted directly into each editor. The two files are only different by a single byte. 

[cantbeatifynp.json.txt](https://github.com/Glavin001/atom-beautify/files/599037/cantbeatifynp.json.txt)

[cantbeautify.json.txt](https://github.com/Glavin001/atom-beautify/files/599042/cantbeautify.json.txt)

**Comment by prettydiff** [comment]
Could you create a debug.md file using Atom Beautify and paste it into a gist?  https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md

This will allow us to see if the problem is with a particular beautifier, atom, or something else.  It will also allow us to see the exact file contents and file name.

**Comment by QwertyZW** [comment]
running that command gives me this strace

```
TypeError: Cannot read property 'name' of null
    at atom-workspace.debug (file:///C:/Users/zaida/.atom/packages/atom-beautify/src/beautify.coffee:364:53)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\zaida\AppData\Local\atom\app-1.11.2\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\zaida\AppData\Local\atom\app-1.11.2\resources\app.asar\src\command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\zaida\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\zaida\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (C:\Users\zaida\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\zaida\AppData\Local\atom\app-1.11.2\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\zaida\AppData\Local\atom\app-1.11.2\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\zaida\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\zaida\AppData\Local\atom\app-1.11.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\zaida\AppData\Local\atom\app-1.11.2\resources\app.asar\src\window-event-handler.js:114:36)
    at HTMLDocument.<anonymous> (C:\Users\zaida\AppData\Local\atom\app-1.11.2\resources\app.asar\src\window-event-handler.js:3:61)
```
