### ISSUE TITLE
a

### ISSUE THREAD

**Issue by chan-gil** [Glavin001/atom-beautify#1389]
# Description

The results of beautification are not what I expect.

# Expected Results

The beautified code should have looked like:

```
<INSERT CODE HERE>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/1a79e896764811977001b6ec62b23e55

# Checklist

- [ ] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment]
What kind of problem are you getting?

**Comment by Bluscream** [comment]
https://gist.github.com/anonymous/1a79e896764811977001b6ec62b23e55#results

**Comment by Glavin001** [comment]
You need to install Uncrustify: https://github.com/uncrustify/uncrustify 
For example, on a Mac: https://github.com/Glavin001/atom-beautify/blob/master/.travis.yml#L99
`brew install uncrustify`

**Comment by Bluscream** [comment]
I'm on Windows 10

**Comment by Glavin001** [comment]
I don't use Windows, however these are the steps for Windows in AppVeyor: https://github.com/Glavin001/atom-beautify/blob/master/appveyor.yml#L117-L122

```
# Uncrustify
  - curl -k -L http://sourceforge.net/projects/uncrustify/files/uncrustify/uncrustify-0.61/uncrustify-0.61.3-gf65394e-win32.zip/download -o uncrustify.zip
  - cinst 7zip.commandline -y
  - 7za e uncrustify.zip -ouncrustify-d
  - "SET PATH=%cd%\\uncrustify-d;%PATH%"
  - where uncrustify
```

So I know it works on Windows, however there may be better instructions at https://github.com/uncrustify/uncrustify

**Comment by Glavin001** [comment]
I really want to focus on improving the installation experience for users. I have created a new Issue, #1687, to target this problem. Please provide your feedback! Thanks in advance.

**Comment by DaWeirdBeard** [comment]
@Glavin001 I tried `brew install uncrustify` and it still gave me this error:


`Error: Could not find 'uncrustify'. The program may not be installed.
    at Function.Executable.commandNotFoundError (/Users/moliver.ethan/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:276:14)
    at Uncrustify.module.exports.Beautifier.exe (/Users/moliver.ethan/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:76:24)
    at Uncrustify.module.exports.Uncrustify.beautify (/Users/moliver.ethan/.atom/packages/atom-beautify/src/beautifiers/uncrustify/index.coffee:52:19)
    at /Users/moliver.ethan/.atom/packages/atom-beautify/src/beautifiers/index.coffee:354:28
    at tryCatcher (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._settlePromise (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:582:21)
    at Promise._settlePromise0 (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._settlePromise (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:582:21)
    at Promise._settlePromise0 (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._settlePromise (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:582:21)
    at Promise._settlePromise0 (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/Users/moliver.ethan/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)`
