### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by Stefanbracke** [Glavin001/atom-beautify#1482]
Tried to beaufity PHP code with php-cs-fixer installed and working (macos 10.12 and latest atom). 

Got a Bad Argument error popup on screen with an error in de console:

index.js:15 Unhandled promise rejection Promise with error: TypeError: Bad argument(…)(anonymous function)
@ index.js:15emitTwo
@ events.js:106emit
@ events.js:191processEmit
@ index.js:155methodName
@ debuggability.js:186activeFireEvent
@ debuggability.js:229fireRejectionEvent
@ debuggability.js:614Promise._notifyUnhandledRejection
@ debuggability.js:61Async._drainQueue
@ async.js:138Async._drainQueues
@ async.js:146Async.drainQueues @ async.js:17

Stack Trace:
TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:289:26)
    at exports.spawn (child_process.js:392:9)
    at /Users/stef/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:136:17
    at Promise._execute (/Users/stef/.atom/packages/atom-beautify/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/stef/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/Users/stef/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:77:14)
    at PHPCSFixer.module.exports.Beautifier.getShellEnvironment (/Users/stef/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:116:16)
    at /Users/stef/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:269:38
    at tryCatcher (/Users/stef/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/stef/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/stef/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:567:18)
   at Promise._settlePromise0 (/Users/stef/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/stef/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/stef/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:636:18)
    at PromiseArray._resolve (/Users/stef/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/Users/stef/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/Users/stef/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:572:26)
    at Promise._settlePromise0 (/Users/stef/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/stef/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/stef/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:636:18)
    at PromiseArray._resolve (/Users/stef/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/Users/stef/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/Users/stef/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:572:26)
    at Promise._settlePromise0 (/Users/stef/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/stef/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/stef/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/stef/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/Users/stef/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)

**Comment by Glavin001** [comment]
This looks applicable: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/beautifier.coffee#L136 and https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/php-cs-fixer.coffee#L66-L80 

Please submit a Pull Request fixing the issue and I would be happy to review and merge it. Thanks in advance!

**Comment by Stefanbracke** [comment]
Thanks Glavin001, but I am not sure what I am supposed to do? Do you want me to fix this? I am really new in this node thing.

**Comment by prettydiff** [comment]
@Stefanbracke here is the Node documentation about spawn: https://nodejs.org/dist/latest-v7.x/docs/api/child_process.html#child_process_child_process_spawn_command_args_options

Node child processes work by creating a shell to run a command line task in.  In Windows the shell is the basic CMD shell, which is not as powerful as something like Bash but is still far less constrained than the old and more standard `/bin/sh` shell.  This shell executes as a child task under the parent node process in the OS's process tree.

I am not very familiar with PHP execution so I cannot provide much guidance to that, but I can help if you have any Node related questions.
