### ISSUE TITLE
Atom - beautify

### ISSUE THREAD

**Issue by Hectix** [Glavin001/atom-beautify#1492]
Hello guys, i had problem with atom - beuatify, i reinstalled windows for other reason and problem is the same as before... What should i do ? I found that it is because i have space between my windows name

`
 atom-beautify@0.29.17 postinstall C:\Users\DAVIDU~1\AppData\Local\Temp\apm-install-dir-117029-920-9p0ji7\node_modules\atom-beautify
 npm run build-options

C:\Users\DAVIDU~1\AppData\Local\Temp\apm-install-dir-117029-920-9p0ji7
`-- (empty)

npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.0: use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
'C:\Users\David' is not recognized as an internal or external command,
operable program or batch file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\DAVIDU~1\AppData\Local\Temp\apm-install-dir-117029-920-9p0ji7\package.json'
npm WARN apm-install-dir-117029-920-9p0ji7 No description
npm WARN apm-install-dir-117029-920-9p0ji7 No repository field.
npm WARN apm-install-dir-117029-920-9p0ji7 No README data
npm WARN apm-install-dir-117029-920-9p0ji7 No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\David Ďurčo\\AppData\\Local\\atom\\app-1.13.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\David Ďurčo\\AppData\\Local\\atom\\app-1.13.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\David Ďurčo\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\David Ďurčo\\.atom\\.apmrc" "install" "C:\\Users\\DAVIDU~1\\AppData\\Local\\Temp\\d-117029-920-69ic0l\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=ia32" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! atom-beautify@0.29.17 postinstall: `npm run build-options`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-beautify@0.29.17 postinstall script 'npm run build-options'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-beautify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-options
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-beautify
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-beautify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\DAVIDU~1\AppData\Local\Temp\apm-install-dir-117029-920-9p0ji7\npm-debug.log
npm ERR! code 1
`

**Comment by SgtMaxipad** [comment]
I have the same problem but I'm getting this error. I installed Atom for the first time and went to install beautify, the newest release. I'm being presented with this error. Does not let me format my code. Is this a current issue at the moment?

module.js:457
Hide Stack Trace
Error: Cannot find module 'event-kit'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (C:\Users\Owner\AppData\Local\atom\app-1.14.0\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (C:\Users\Owner\AppData\Local\atom\app-1.14.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (C:\Users\Owner\AppData\Local\atom\app-1.14.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Owner/.atom/packages/atom-beautify/src/beautify.coffee:7:25)
    at Object.<anonymous> (file:///C:/Users/Owner/.atom/packages/atom-beautify/src/beautify.coffee:2:1)
    at Module._compile (C:\Users\Owner\AppData\Local\atom\app-1.14.0\resources\app.asar\src\native-compile-cache.js:109:30)
    at Object.value [as .coffee] (C:\Users\Owner\AppData\Local\atom\app-1.14.0\resources\app.asar\src\compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\Owner\AppData\Local\atom\app-1.14.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\Owner\AppData\Local\atom\app-1.14.0\resources\app.asar\src\package.js:796:27)
    at Package.module.exports.Package.activateConfig (C:\Users\Owner\AppData\Local\atom\app-1.14.0\resources\app.asar\src\package.js:266:12)
    at PackageManager.module.exports.PackageManager.packageHasSettings (C:\Users\Owner\AppData\Local\atom\app-1.14.0\resources\app.asar\node_modules\settings-view\lib\package-manager.js:51:14)
    at PackageCard.module.exports.PackageCard.hasSettings (C:\Users\Owner\AppData\Local\atom\app-1.14.0\resources\app.asar\node_modules\settings-view\lib\package-card.js:728:34)
    at PackageCard.module.exports.PackageCard.updateSettingsState (C:\Users\Owner\AppData\Local\atom\app-1.14.0\resources\app.asar\node_modules\settings-view\lib\package-card.js:402:16)
    at PackageCard.module.exports.PackageCard.updateInterfaceState (C:\Users\Owner\AppData\Local\atom\app-1.14.0\resources\app.asar\node_modules\settings-view\lib\package-card.js:395:12)
    at PackageCard.module.exports.PackageCard.initialize (C:\Users\Owner\AppData\Local\atom\app-1.14.0\resources\app.asar\node_modules\settings-view\lib\package-card.js:243:19)
    at PackageCard.View [as constructor] (C:\Users\Owner\AppData\Local\atom\app-1.14.0\resources\app.asar\node_modules\space-pen\lib\space-pen.js:184:25)
    at new PackageCard (C:\Users\Owner\AppData\Local\atom\app-1.14.0\resources\app.asar\node_modules\settings-view\lib\package-card.js:20:48)
    at PackageDetailView.module.exports.PackageDetailView.completeInitialzation (C:\Users\Owner\AppData\Local\atom\app-1.14.0\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:152:28)
    at PackageDetailView.module.exports.PackageDetailView.loadPackage (C:\Users\Owner\AppData\Local\atom\app-1.14.0\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:171:21)
    at PackageDetailView.module.exports.PackageDetailView.initialize (C:\Users\Owner\AppData\Local\atom\app-1.14.0\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:146:12)
    at PackageDetailView.View [as constructor] (C:\Users\Owner\AppData\Local\atom\app-1.14.0\resources\app.asar\node_modules\space-pen\lib\space-pen.js:184:25)
    at PackageDetailView.ScrollView [as constructor] (C:\Users\Owner\AppData\Local\atom\app-1.14.0\resources\app.asar\node_modules\atom-space-pen-views\lib\scroll-view.js:12:47)
    at new PackageDetailView (C:\Users\Owner\AppData\Local\atom\app-1.14.0\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:38:54)

**Comment by ragmha** [comment]
Have you  gone  through the checklist ? 😄 

## Checklist
- [ ]  Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] Reloaded(or restarted) Atom to ensure it is not a caching issue
- [ ] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues so I know this is not a duplicate issue
- [ ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing Atom Beautify: Help Debug Editor command in Atom and added link for debug.md Gist to this issue

Ran into this issue today, got it Fixed 🎉  going through the checklist 👍

**Comment by Glavin001** [comment]
I've merged https://github.com/Glavin001/atom-beautify/pull/1598 which should resolve these issues.

Published to v0.29.21.
