### ISSUE TITLE
Uncaught Error: Cannot find module '../package.json'

### ISSUE THREAD

**Issue by GL455** [Glavin001/atom-beautify#1528]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.29.17

### Stack Trace

Uncaught Error: Cannot find module '../package.json'

```
At /Users/alkachaudhary/Desktop/Atom.app/Contents/Resources/app.asar/src/module-cache.js:379

Error: Cannot find module '../package.json'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Users/alkachaudhary/Desktop/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-beautify/src/beautify.coffee:5:9)
    at /packages/atom-beautify/src/beautify.coffee:564:4)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateConfig (/app.asar/src/package.js:266:12)
    at PackageManager.module.exports.PackageManager.packageHasSettings (/app.asar/node_modules/settings-view/lib/package-manager.js:51:14)
    at PackageCard.module.exports.PackageCard.hasSettings (/app.asar/node_modules/settings-view/lib/package-card.js:728:34)
    at PackageCard.module.exports.PackageCard.updateSettingsState (/app.asar/node_modules/settings-view/lib/package-card.js:402:16)
    at PackageCard.module.exports.PackageCard.updateInterfaceState (/app.asar/node_modules/settings-view/lib/package-card.js:395:12)
    at /app.asar/node_modules/settings-view/lib/package-card.js:665:24
    at /app.asar/node_modules/settings-view/lib/package-card.js:741:20
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (/app.asar/node_modules/settings-view/lib/package-manager.js:607:27)
    at /app.asar/node_modules/settings-view/lib/package-manager.js:446:26
    at exit (/app.asar/node_modules/settings-view/lib/package-manager.js:69:16)
    at triggerExitCallback (/app.asar/src/buffered-process.js:303:11)
    at /app.asar/src/buffered-process.js:324:11
    at /app.asar/src/buffered-process.js:185:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -8:58.9.0 core:move-down (input.hidden-input)
     -8:58.5.0 core:move-left (input.hidden-input)
     -8:57.9.0 core:move-down (input.hidden-input)
     -8:57.2.0 core:move-up (input.hidden-input)
     -8:50 core:confirm (input.hidden-input)
     -6:54.4.0 command-palette:toggle (div.package-readme.native-key-bindings)
 14x -6:49.7.0 core:backspace (input.hidden-input)
     -5:58.7.0 tabs:split-left (div.title)
     -5:53 core:move-right (input.hidden-input)
     -5:50.3.0 command-palette:toggle (div.package-detail.panels-item)
     -5:47.5.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
colorblind-wombat-dark-syntax 0.6.0 
language-diff 0.7.0 
```

**Comment by Glavin001** [comment]
Please try to reinstall. I suspect this issue has been resolved. Let me know otherwise and we can reopen.
