### ISSUE TITLE
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an al...

### ISSUE THREAD

**Issue by farbodsalimi** [Glavin001/atom-beautify#1543]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Home
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.29.17

### Stack Trace

Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

```
At C:\Users\Farbod\.atom\packages\atom-beautify\node_modules\ajv\lib\compile\index.js:171

EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at Ajv.localCompile (/packages/atom-beautify/node_modules/ajv/lib/compile/index.js:139:26)
    at Ajv.resolve (/packages/atom-beautify/node_modules/ajv/lib/compile/resolve.js:53:19)
    at Object.resolveRef (/packages/atom-beautify/node_modules/ajv/lib/compile/index.js:210:21)
    at /packages/atom-beautify/node_modules/ajv/lib/dotjs/ref.js:22:22)
    at /packages/atom-beautify/node_modules/ajv/lib/dotjs/validate.js:156:37)
    at /packages/atom-beautify/node_modules/ajv/lib/dotjs/properties.js:199:26)
    at generate_validate (/packages/atom-beautify/node_modules/ajv/lib/dotjs/validate.js:229:37)
    at localCompile (/packages/atom-beautify/node_modules/ajv/lib/compile/index.js:99:22)
    at Ajv.compile (/packages/atom-beautify/node_modules/ajv/lib/compile/index.js:67:13)
    at _compile (/packages/atom-beautify/node_modules/ajv/lib/ajv.js:328:29)
    at getSchema (/packages/atom-beautify/node_modules/ajv/lib/ajv.js:192:51)
    at validate (/packages/atom-beautify/node_modules/ajv/lib/ajv.js:91:11)
    at validateSchema (/packages/atom-beautify/node_modules/ajv/lib/ajv.js:162:19)
    at _addSchema (/packages/atom-beautify/node_modules/ajv/lib/ajv.js:288:7)
    at addSchema (/packages/atom-beautify/node_modules/ajv/lib/ajv.js:133:26)
    at addInitialSchemas (/packages/atom-beautify/node_modules/ajv/lib/ajv.js:396:39)
    at /packages/atom-beautify/node_modules/ajv/lib/ajv.js:78:3)
    at /packages/atom-beautify/node_modules/har-validator/lib/node4/promise.js:43:11)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-beautify/node_modules/request/lib/har.js:5:16)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-beautify/node_modules/request/request.js:25:31)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.17 
```

**Comment by civesolimnadobols** [comment]
Same error here.

Linux, Atom: 1.14.2, Package: 0.29.17

**Comment by prettydiff** [comment]
Please see https://github.com/epoberezkin/ajv/issues/433#event-986470593

Guys please reinstall.  If you still get this problem let me know and also look for dependency *har-validator* and note its version number.

**Comment by LegerG** [comment]
Same Problem, i have uninstall beautify and reinstall. Reboot my OS. Nothing changes. And of course the beautify-features doesn't work. This problem has came after i install clang and i tried to use clang-format in my C project.

There is the content of my .clang-format
```
IndentWidth: 4
```

**Atom**: 1.36.0 x64
**Electron**: 4.1.1
**OS**: "Manjaro Linux"
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.33.4


### Stack Trace

Failed to activate the atom-beautify package

```
At Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".


EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at /packages/atom-beautify/node_modules/prettier/index.js:40747:21
    at createCommonjsModule (/packages/atom-beautify/node_modules/prettier/index.js:188:35)
    at /packages/atom-beautify/node_modules/prettier/index.js:40554:18)
    at /packages/atom-beautify/node_modules/prettier/index.js:42567:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/atom-beautify/src/beautifiers/prettier.coffee:4:12)
    at /packages/atom-beautify/src/beautifiers/prettier.coffee:1:1)
    at /packages/atom-beautify/src/beautifiers/prettier.coffee:1:1)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .coffee] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/atom-beautify/src/beautifiers/index.coffee:120:20
    at arrayMap (/packages/atom-beautify/node_modules/lodash/lodash.js:639:23)
    at Function.map (/packages/atom-beautify/node_modules/lodash/lodash.js:9556:14)
    at /packages/atom-beautify/src/beautifiers/index.coffee:119:22)
    at /packages/atom-beautify/src/beautify.coffee:10:14)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .coffee] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at Package.requireMainModule (/usr/lib/atom/src/package.js:776:27)
```

### Commands

```
  4x -1:45.1.0 core:save (input.hidden-input)
     -1:14 core:move-up (input.hidden-input)
     -1:13.8.0 snippets:next-tab-stop (input.hidden-input)
     -1:13.8.0 snippets:expand (input.hidden-input)
     -1:13.8.0 editor:indent (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
file-icons 2.1.31 
highlight-selected 0.16.0 
minimap 4.29.9 
minimap-highlight-selected 4.6.1 
minimap-quick-highlight 1.0.1 
```

**Comment by prettydiff** [comment]
@LegerG In your case the problem appears to originate in the prettier library.  I have no idea how to reproduce this error.
