### ISSUE TITLE
Uncaught Error: Cannot find module 'underscore-plus'

### ISSUE THREAD

**Issue by gustavo-depaula** [Glavin001/atom-beautify#1545]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.29.17

### Stack Trace

Uncaught Error: Cannot find module 'underscore-plus'

```
At module.js:457

Error: Cannot find module 'underscore-plus'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Users/a2015951681/Desktop/apps/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-beautify/src/beautifiers/index.coffee:2:9)
    at /packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-beautify/src/beautify.coffee:9:15)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateConfig (/app.asar/src/package.js:266:12)
    at PackageManager.module.exports.PackageManager.packageHasSettings (/app.asar/node_modules/settings-view/lib/package-manager.js:51:14)
    at PackageCard.module.exports.PackageCard.hasSettings (/app.asar/node_modules/settings-view/lib/package-card.js:728:34)
    at PackageCard.module.exports.PackageCard.updateSettingsState (/app.asar/node_modules/settings-view/lib/package-card.js:402:16)
    at PackageCard.module.exports.PackageCard.updateInterfaceState (/app.asar/node_modules/settings-view/lib/package-card.js:395:12)
```

### Commands

```
     -0:48.3.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-light-syntax.theme-one-light-ui)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-css-comb 3.1.0 
atom-monokai 0.10.9 
color-picker 2.2.5 
emmet 2.4.3 
file-icons 2.0.17 
git-plus 7.3.3 
minimap 4.26.8 
```

**Comment by prettydiff** [comment]
That is probably a missing dependency.  From the command line try this command and let me know the result:

`apm install atom-beautify`

**Comment by HoaNguyenCoder9x** [comment]
`apm install atom-beautify` 
don't work for me
