### ISSUE TITLE
[Bash completion] wrong argument type --indent-size

### ISSUE THREAD

**Issue by StefanYohansson** [Glavin001/atom-beautify#1556]
# Description

version: beautysh==3.1

Beautysh is returning this for atom-beautify:

```
usage: beautysh [-h] [--indent-size INDENT_SIZE] [--files [FILES [FILES ...]]] [--backup]
beautysh: error: argument --indent-size/-i: invalid int value: 'tab'
```

stack trace:
```
beautysh: error: argument --indent-size/-i: invalid int value: 'tab'
    at /home/snotr/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:295:27
    at tryCatcher (/usr/lib/atom/node_modules/editorconfig/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/atom/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/lib/atom/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/lib/atom/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/lib/atom/node_modules/editorconfig/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/usr/lib/atom/node_modules/editorconfig/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/usr/lib/atom/node_modules/editorconfig/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/usr/lib/atom/node_modules/editorconfig/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

# Input Before Beautification

This is what the code looked like before:

```bash
#!/bin/sh

env=local
cmd=$1

while [ "$1" != "" ]; do
	case $1 in
             --env )           shift
	                       env=$1
		               ;;
    esac
    shift
done

```

# Expected Output

The beautified code should have looked like this:

```
#!/bin/sh

env=local
cmd=$1

while [ "$1" != "" ]; do
  case $1 in
    --env )           shift
      env=$1
    ;;
  esac
  shift
done

```

It was generated by command: `beautysh --indent-size 2 --files docker_build.sh` on console

# Actual Output

The beautified code actually looked like this:

![captura de tela de 2017-03-17 10-18-38](https://cloud.githubusercontent.com/assets/1783252/24044714/43957e8c-0afb-11e7-82e4-259d1d58df08.png)

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/StefanYohansson/03a196a452bb1473934327c3a221b627

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by stefancrain** [comment]
@StefanYohansson I've had success resolving this issue by adding the default `.editorconfig` from the [editorconfig plugin](https://github.com/sindresorhus/atom-editorconfig) to the root of my project. I haven't been able to resolve this globally.
