### ISSUE TITLE
Uncaught Error: Cannot find module './config/npm-config'

### ISSUE THREAD

**Issue by tstejl** [Glavin001/atom-beautify#1562]
What I was doing:
I was writing python code, and wanted to beautify it a little bit. I clicked beautify, and some error messages popped up. I wanted to disable and re-enable beautify, but accidentally clicked uninstall. I re-installed it, and restarted Atom, and these error messages popped up.

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.29.17

### Stack Trace

Uncaught Error: Cannot find module './config/npm-config'

```
At module.js:457

Error: Cannot find module './config/npm-config'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.15.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-beautify/node_modules/winston/lib/winston/config.js:48:17)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-beautify/node_modules/winston/lib/winston/common.js:15:14)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-beautify/node_modules/winston/lib/winston.js:24:26)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-beautify/src/logger.coffee:10:13
    at /packages/atom-beautify/src/logger.coffee:4:18)
    at /packages/atom-beautify/src/logger.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-bootstrap4 1.4.0 
atom-clock 0.1.6 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
aurora-theme 1.2.2 
autocomplete-python 1.8.61 
nord-atom-ui 0.10.2 
python-tools 0.6.9 
qolor 0.4.1 
```

**Comment by Glavin001** [comment]
Please uninstall and reinstall Atom-Beautify with `apm install atom-beautify`. If the issue still persists comment here and we can reopen. Thanks!
