### ISSUE TITLE
Error "Cannot read property 'name' of undefined" when running "Help Debug Editor"

### ISSUE THREAD

**Issue by 61ue5peed** [Glavin001/atom-beautify#1571]
# Description

The results of beautification are not what I expect.

# Input Before Beautification

This is what the code looked like before:

```
<INSERT CODE HERE>
```

# Expected Output

The beautified code should have looked like this:

```
<INSERT CODE HERE>
```

# Actual Output

The beautified code actually looked like this:

```
<INSERT CODE HERE>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
I don't see any information to work with. Please provide the error message or something. Also try running `apm install atom-beautify`, if you are not already.

**Comment by 61ue5peed** [comment]
TypeError: Cannot read property 'name' of undefined
    at atom-workspace.debug (/Users/eprokhor/.atom/packages/atom-beautify/src/beautify.coffee:359:53)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1168:28)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:325:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)

@Glavin001

**Comment by Glavin001** [comment]
> TypeError: Cannot read property 'name' of undefined
at atom-workspace.debug (/Users/eprokhor/.atom/packages/atom-beautify/src/beautify.coffee:359:53)

The issue is here: https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L359
The case where `language` is `undefined` needs to be addressed.

Pull Requests welcome!

**Comment by Glavin001** [comment]
Also it does not appear to be an installation issue. You should only experience this issue when you attempt to debug. Please clarify what you meant by "Can't install on newest atom version".
