### ISSUE TITLE
Failed to activate the atom-beautify package

### ISSUE THREAD

**Issue by cdrandin** [Glavin001/atom-beautify#1624]
[Enter steps to reproduce:]

1. ctrl+shift+r
2. broke

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.29.23

### Stack Trace

Failed to activate the atom-beautify package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-beautify/src/beautify.coffee:7:25)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateNow (/app.asar/src/package.js:207:16)
    at /app.asar/src/package.js:876:25
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:240:20)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -0:37.6.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:24.7.0 command-palette:toggle (div.panels-item)
     -0:18.8.0 editor:consolidate-selections (input.hidden-input)
     -0:18.8.0 core:cancel (input.hidden-input)
  2x -0:14.8.0 atom-beautify:beautify-editor (input.hidden-input)
```

### Non-Core Packages

```
angularjs 0.4.0 
atom-beautify 0.29.23 
atom-django 0.3.2 
atom-html-preview 0.1.22 
atom-jade 0.3.0 
atom-ternjs 0.18.2 
auto-update-packages 1.0.1 
autocomplete-modules 1.6.9 
autocomplete-python 1.8.63 
busy-signal 1.4.0 
clipboard-plus 0.5.1 
custom-title 1.0.1 
data-atom 0.25.0 
django-templates 0.5.0 
docker 0.7.0 
file-icons 2.1.3 
fonts 2.0.0 
git-plus 7.6.0 
highlight-selected 0.13.1 
intentions 1.1.2 
keybinding-cheatsheet 0.1.1 
language-docker 1.1.7 
less-than-slash 0.16.0 
linter 2.1.4 
linter-flake8 2.1.5 
linter-jsonlint 1.3.0 
linter-pylint 2.0.1 
linter-ui-default 1.2.3 
meteor-api 2.20.0 
minimap 4.27.1 
minimap-autohide 0.10.1 
minimap-bookmarks 0.4.2 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.0 
npm-install 4.0.4 
omnisharp-atom 0.31.2 
open-on-bitbucket 0.4.0 
open-recent 5.0.0 
pdf-view 0.57.0 
python-indent 1.0.2 
python-isort 0.0.7 
quick-editor 0.4.3 
react 0.16.2 
sync-settings 0.8.1 
todo-show 1.11.0 
tokamak-terminal 10.0.1 
```

**Comment by Glavin001** [comment]
I recommend reinstalling, `apm install atom-beautify`. 

`event-kit` is a package which Atom-Beautify depends on: https://github.com/Glavin001/atom-beautify/blob/69731d1ead698008f1d6022a2d4cb9dfedf4412f/package.json#L155

If you have issues with installing, `apm` team may help as well: https://github.com/atom/apm
