### ISSUE TITLE
Uncaught Error: Cannot find module './winston/transports'

### ISSUE THREAD

**Issue by andrii44** [Glavin001/atom-beautify#1626]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.29.23

### Stack Trace

Uncaught Error: Cannot find module './winston/transports'

```
At module.js:457

Error: Cannot find module './winston/transports'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-beautify/node_modules/winston/lib/winston.js:19:22)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-beautify/src/logger.coffee:10:13
    at /packages/atom-beautify/src/logger.coffee:4:18)
    at /packages/atom-beautify/src/logger.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-beautify/src/beautifiers/index.coffee:6:10)
    at /packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/atom-beautify/src/beautify.coffee:9:15)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/app.asar/src/package.js:796:27)
    at Package.module.exports.Package.activateConfig (/app.asar/src/package.js:266:12)
    at PackageManager.module.exports.PackageManager.packageHasSettings (/app.asar/node_modules/settings-view/lib/package-manager.js:53:14)
    at PackageCard.hasSettings (/app.asar/node_modules/settings-view/lib/package-card.js:785:34)
    at PackageCard.updateSettingsState (/app.asar/node_modules/settings-view/lib/package-card.js:430:16)
    at PackageCard.updateInterfaceState (/app.asar/node_modules/settings-view/lib/package-card.js:422:12)
    at /app.asar/node_modules/settings-view/lib/package-card.js:84:10)
    at PackageDetailView.completeInitialization (/app.asar/node_modules/settings-view/lib/package-detail-view.js:182:28)
    at PackageDetailView.loadPackage (/app.asar/node_modules/settings-view/lib/package-detail-view.js:201:14)
    at /app.asar/node_modules/settings-view/lib/package-detail-view.js:76:10)
    at callback (/app.asar/node_modules/settings-view/lib/settings-view.js:344:20)
    at SettingsView.getOrCreatePanel (/app.asar/node_modules/settings-view/lib/settings-view.js:349:19)
    at SettingsView.showPanel (/app.asar/node_modules/settings-view/lib/settings-view.js:407:24)
    at SettingsView.showDeferredPanel (/app.asar/node_modules/settings-view/lib/settings-view.js:394:14)
    at SettingsView.initializePanels (/app.asar/node_modules/settings-view/lib/settings-view.js:228:12)
    at /app.asar/node_modules/settings-view/lib/settings-view.js:106:20
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.23 
emmet 2.4.3 
```

**Comment by bestina75** [comment]
After updating, I get the same error.
atom-beautify 0.30.4

**Comment by Jegp** [comment]
+1

## Steps to reproduce

    1. Install atom-beautify
    2. Restart atom 

Atom: 1.22.1
OS: Ubuntu Linux 18.04
Thrown From: atom-beautify package 0.30.9

## Stacktrace 
Cannot find module './winston/transports'
Error: Cannot find module './winston/transports'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/jens/.atom/packages/atom-beautify/node_modules/winston/lib/winston.js:19:22)
    at Object.<anonymous> (/home/jens/.atom/packages/atom-beautify/node_modules/winston/lib/winston.js:166:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at /home/jens/.atom/packages/atom-beautify/src/logger.coffee:10:13
    at Object.<anonymous> (/home/jens/.atom/packages/atom-beautify/src/logger.coffee:4:18)
    at Object.<anonymous> (/home/jens/.atom/packages/atom-beautify/src/logger.coffee:1:1)
    at Object.<anonymous> (/home/jens/.atom/packages/atom-beautify/src/logger.coffee:1:1)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/jens/.atom/packages/atom-beautify/src/beautifiers/index.coffee:6:10)
    at Object.<anonymous> (/home/jens/.atom/packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at Object.<anonymous> (/home/jens/.atom/packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///usr/share/atom/resources/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/jens/.atom/packages/atom-beautify/src/beautify.coffee:9:15)
    at Object.<anonymous> (/home/jens/.atom/packages/atom-beautify/src/beautify.coffee:2:1)
    at Object.<anonymous> (/home/jens/.atom/packages/atom-beautify/src/beautify.coffee:2:1)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)

**Comment by skaraman** [comment]
Also happens - 
Error: Cannot find module './winston/transports'
    at Module._resolveFilename (module.js:470:15)

**Comment by PartyLich** [comment]
+1. Getting the same error here.
Atom: 1.35.1
OS: Windows 10 Pro
