### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getSelectedText' of undefined

### ISSUE THREAD

**Issue by odeits** [Glavin001/atom-beautify#166]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.17.3

### Stack Trace

Uncaught TypeError: Cannot read property 'getSelectedText' of undefined

```
At /c:/Users/gamer/.atom/packages/atom-beautify/lib/beautify.coffee:276

TypeError: Cannot read property 'getSelectedText' of undefined
  at atom-workspace.beautify (c:\Users\gamer\.atom\packages\atom-beautify\lib\beautify.coffee:226:25)
  at atom-workspace.handler (c:\Users\gamer\AppData\Local\atom\app-0.165.0\resources\app\src\space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (c:\Users\gamer\AppData\Local\atom\app-0.165.0\resources\app\node_modules\space-pen\vendor\jquery.js:4681:9)
  at atom-workspace.elemData.handle (c:\Users\gamer\AppData\Local\atom\app-0.165.0\resources\app\node_modules\space-pen\vendor\jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (c:\Users\gamer\AppData\Local\atom\app-0.165.0\resources\app\src\command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (c:\Users\gamer\AppData\Local\atom\app-0.165.0\resources\app\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (c:\Users\gamer\AppData\Local\atom\app-0.165.0\resources\app\src\command-registry.js:156:19)
  at Ipc.<anonymous> (c:\Users\gamer\AppData\Local\atom\app-0.165.0\resources\app\src\window-event-handler.js:65:30)
  at Ipc.emit (events.js:107:17)
  at process.<anonymous> (c:\Users\gamer\AppData\Local\atom\app-0.165.0\resources\atom\renderer\api\lib\ipc.js:22:29)
  at process.emit (events.js:110:17)

```

### Commands

```
     -9:30.9 pane:reopen-closed-item (input.hidden-input)
     -6:39.8 core:confirm (input.hidden-input)
     -0:00.0 beautify (div.settings-view.pane-item)
```

### Config

```
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
ide-haskell, v0.3.0
language-haskell, v1.0.0
seti-syntax, v0.2.1
seti-ui, v0.5.1
themed-settings, v0.8.5

# Dev
No dev packages
```

/cc @atom/core

**Comment by Glavin001** [comment]
Could you elaborate a little for me to help me reproduce? Was this error triggers on manual beautification (run `beautify` command manually), or by `Beautify On Save`, etc?

**Comment by odeits** [comment]
I had no text selected. I opened the command pallet and selected beautify.
It was a cpp file. Uncrustify was NOT in my path. I couldn't figure out the
install requirements for uncrustify on your read me so I just had it
downloaded and was waiting for an error message to tell me where to put it.

**Comment by Glavin001** [comment]
> I had no text selected. I opened the command pallet and selected beautify. It was a cpp file. 

Interesting. The above error, `'getSelectedText' of undefined` could only occur from https://github.com/Glavin001/atom-beautify/blob/v0.17.3/lib/beautify.coffee#L226 or https://github.com/Glavin001/atom-beautify/blob/v0.17.3/lib/beautify.coffee#L290 which indicates that there was no active editor found ( https://github.com/Glavin001/atom-beautify/blob/v0.17.3/lib/beautify.coffee#L224 ). This is strange and has not happened for me before.

- [ ] Add a check in to see if there is an Active Editor
  - If there is not, throw an error to be displayed to the user

---

> Uncrustify was NOT in my path. I couldn't figure out the
> install requirements for uncrustify on your read me so I just had it
> downloaded and was waiting for an error message to tell me where to put it.

The installation instructions definitely need improvement and is on my list ( #58 ).
With #164 and #165 implemented this will be made a lot clearer to users like yourself.

You have two options:
- Let Atom Beautify *attempt* to determine the executable path of Uncrustify
  - This does not always work, which is why forcing users to configure/set a fixed path for the executable will be next ( #164 ) 
- Set a fixed path for Uncrustify in the Atom Beautify package Settings
  - In your case, for C++, it would be the setting `CPP Uncrustify Path`
    - See https://github.com/Glavin001/atom-beautify/blob/v0.17.3/lib/language-options.coffee#L125 for more details

Hope this helps!

**Comment by odeits** [comment]
I had to uninstall the package to make progress on some work. After re-installing it I am not seeing the error. I will update this ticket with any information I get trying to reproduce it. Also, thanks for the information on how to get uncrustify to work.

**Comment by Glavin001** [comment]
Glad it's working so far for you now. Let me know if there's anything else I can do.
