### ISSUE TITLE
Running Beautify Editor with any python code results in Bad Argument

### ISSUE THREAD

**Issue by mbaxa** [Glavin001/atom-beautify#1674]
# Description

When running Beautify Editor with any python code, a Bad argument error happens.
I have installed autopep8 via pip, and does work when I run it from the command
line.

# Input Before Beautification

This is what the code looked like before:

```
#!/usr/bin/python3
import re
import json

def method(arg):

   return arg
print method("hi")
```

# Expected Output

The beautified code should have looked like this:

```
#!/usr/bin/python3
import re
import json


def method(arg):
    return arg


print method("hi")
```

# Actual Output

Bad argument error:

```
TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:289:26)
    at exports.spawn (child_process.js:392:9)
    at /Users/matt/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:163:17
    at Promise._execute (/Users/matt/.atom/packages/atom-beautify/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/matt/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/matt/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:79:10)
    at Autopep8.module.exports.Beautifier.getShellEnvironment (/Users/matt/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:143:16)
    at /Users/matt/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:296:38
    at tryCatcher (/Users/matt/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/matt/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/matt/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/matt/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/matt/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/matt/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/Users/matt/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/Users/matt/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/Users/matt/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Users/matt/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/matt/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/matt/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/Users/matt/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/Users/matt/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/Users/matt/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Users/matt/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/matt/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/matt/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/matt/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/Users/matt/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. Got error

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/mbaxa/8f866a1eed88aea1d8a504ae9b36e283

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by mbaxa** [comment]
This is on macOS 10.11.16 (El Cap)

**Comment by mbaxa** [comment]
On advice from this [comment](https://github.com/Glavin001/atom-beautify/issues/1395#issuecomment-268212170), I disabled iterm2 shell integration, restarted Atom and now the plugin works
