### ISSUE TITLE
PHP-CS-Fixer throws "Error: spawn EACCES" on saving document

### ISSUE THREAD

**Issue by yosefeliezrie** [Glavin001/atom-beautify#1676]
# Description

When trying to save files or run atom-beatify i get the following error

```
spawn EACCES
Hide Stack Trace
Error: spawn EACCES
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:392:9)
    at /Users/yosefeliezrie/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:349:13
    at Promise._execute (/Users/yosefeliezrie/.atom/packages/atom-beautify/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/yosefeliezrie/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/yosefeliezrie/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:79:10)
    at PHPCSFixer.module.exports.Beautifier.spawn (/Users/yosefeliezrie/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:346:16)
    at /Users/yosefeliezrie/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:308:10
    at tryCatcher (/Users/yosefeliezrie/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/yosefeliezrie/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/yosefeliezrie/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/yosefeliezrie/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/yosefeliezrie/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/yosefeliezrie/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/Users/yosefeliezrie/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/Users/yosefeliezrie/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/Users/yosefeliezrie/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Users/yosefeliezrie/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/yosefeliezrie/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/yosefeliezrie/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/yosefeliezrie/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/Users/yosefeliezrie/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
```

# Input Before Beautification

This is what the code looked like before:

```
<INSERT CODE HERE>
```

# Expected Output

The beautified code should have looked like this:

```
<INSERT CODE HERE>
```

# Actual Output

The beautified code actually looked like this:

```
<INSERT CODE HERE>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor` or save file
3. Get error

# Debug

Here is a link to the `debug.md` Gist: [https://gist.github.com/yosefeliezrie/efab2fb5acedafb56535d13749d03fc4)

# Checklist

I have:
- [x ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

# Attempts to fix
Saw https://github.com/Glavin001/atom-beautify/issues/1259 and ran 
`sudo chmod -R a+rwx /usr/local/bin/php-cs-fixer`

``

**Comment by Glavin001** [comment]
It shows the `php-cs-fixer path` as `/usr/local/Cellar/php-cs-fixer/2.3.1`. Should this be different?

**Comment by Glavin001** [comment]
Please let me know if the comment above does not fix your issue, and then this can be reopened.

**Comment by rtorrescodes** [comment]
I'm having the same problem

Error: spawn EACCES
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:399:9)
    at /home/rodrigo/.var/app/io.atom.Atom/data/packages/atom-beautify/src/beautifiers/executable.coffee:237:13
    at Promise._execute (/home/rodrigo/.var/app/io.atom.Atom/data/packages/atom-beautify/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/home/rodrigo/.var/app/io.atom.Atom/data/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/home/rodrigo/.var/app/io.atom.Atom/data/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:79:10)
    at HybridExecutable.Executable.spawn (/home/rodrigo/.var/app/io.atom.Atom/data/packages/atom-beautify/src/beautifiers/executable.coffee:234:12)
    at /home/rodrigo/.var/app/io.atom.Atom/data/packages/atom-beautify/src/beautifiers/executable.coffee:166:10
    at tryCatcher (/home/rodrigo/.var/app/io.atom.Atom/data/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/rodrigo/.var/app/io.atom.Atom/data/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/rodrigo/.var/app/io.atom.Atom/data/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/rodrigo/.var/app/io.atom.Atom/data/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/rodrigo/.var/app/io.atom.Atom/data/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/rodrigo/.var/app/io.atom.Atom/data/packages/atom-beautify/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/rodrigo/.var/app/io.atom.Atom/data/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/home/rodrigo/.var/app/io.atom.Atom/data/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)

Any ideas?

**Comment by tv-nieri** [comment]
Maybe you guys are missing the actual PHP-cs-fixer, and trying to use the atom package without it?
To install and set the permissions to it: http://cs.sensiolabs.org/
After that, you will need to go to Edit>Preferences in the Atom editor itself, in the installed packages you will look for the atom-beautify package, click on Settings>Executables, find the PHP-cs-fixer and set the path where you transferred the executable downloaded from the http://cs.sensiolabs.org/.
