### ISSUE TITLE
SQL Format Error Happen

### ISSUE THREAD

**Issue by 554943871** [Glavin001/atom-beautify#1679]
[CONTENT]

SELECT a
FROM b
WHERE 1=1 and sex="男"
=================================
above encoded on UTF8 
version:atom-beautify 0.29.24
================================
Traceback (most recent call last):
  File "/usr/local/bin/sqlformat", line 9, in <module>
    load_entry_point('sqlparse==0.2.4.dev0', 'console_scripts', 'sqlformat')()
  File "build/bdist.macosx-10.12-intel/egg/sqlparse/cli.py", line 177, in main
UnicodeEncodeError: 'ascii' codec can't encode character u'\u7537' in position 37: ordinal not in range(128)
Hide Stack Trace
Error: Traceback (most recent call last):
  File "/usr/local/bin/sqlformat", line 9, in <module>
    load_entry_point('sqlparse==0.2.4.dev0', 'console_scripts', 'sqlformat')()
  File "build/bdist.macosx-10.12-intel/egg/sqlparse/cli.py", line 177, in main
UnicodeEncodeError: 'ascii' codec can't encode character u'\u7537' in position 37: ordinal not in range(128)
    at /Users/god/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:322:27
    at tryCatcher (/Users/god/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/god/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/god/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/god/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/god/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/god/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/god/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/Users/god/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by coderbean** [comment]
same issue
