### ISSUE TITLE
Cannot read property 'is' of null after latest csscomb update

### ISSUE THREAD

**Issue by kinkwilde** [Glavin001/atom-beautify#1694]
Has anyone got an idea why this is failing? It only started after the update of CSScomb. It seems to be failing on the new comb option of lines-between-rulesets.

**Error:**

Cannot read property 'is' of null

TypeError: Cannot read property 'is' of null
    at Object.insertNewlines (C:\Users\Stephen Bull\.atom\packages\atom-beautify\node_modules\csscomb\lib\options\lines-between-rulesets.js:237:20)
    at node.forEach (C:\Users\Stephen Bull\.atom\packages\atom-beautify\node_modules\csscomb\lib\options\lines-between-rulesets.js:124:12)
    at Node.forEach (C:\Users\Stephen Bull\.atom\packages\atom-beautify\node_modules\gonzales-pe\lib\gonzales.js:175:83)
    at Object.processRuleSets (C:\Users\Stephen Bull\.atom\packages\atom-beautify\node_modules\csscomb\lib\options\lines-between-rulesets.js:123:10)
    at Object.processBlock (C:\Users\Stephen Bull\.atom\packages\atom-beautify\node_modules\csscomb\lib\options\lines-between-rulesets.js:98:12)
    at Object.process (C:\Users\Stephen Bull\.atom\packages\atom-beautify\node_modules\csscomb\lib\options\lines-between-rulesets.js:89:10)
    at C:\Users\Stephen Bull\.atom\packages\atom-beautify\node_modules\csscomb\lib\core.js:380:14
    at Array.forEach (native)
    at Comb._processTree (C:\Users\Stephen Bull\.atom\packages\atom-beautify\node_modules\csscomb\lib\core.js:379:8)

**The example SCSS rule that will cause this is:**

```
/* TEST COMB */
.test-comb {
    @include font-size(22);
    @include clearfix;
    @include position(vertical, absolute);

    background-color: gray;
    color: red;
    display: block;
    height: 100%;
    width: 100%;

    @include break-min($md-break) {
        color: blue;
    }

    @media (min-width: $xx-break) {
        color: green;
    }
}
```

**Link to my .csscomb.json:**

https://gist.github.com/kinkwilde/7b36f984bfeac75e5daf7e353e6c8071

**Comment by Glavin001** [comment]
May be some of these: https://github.com/csscomb/csscomb.js/blob/dev/src/options/lines-between-rulesets.js#L229-L241

I recommend you create a bug Issue over at https://github.com/csscomb/csscomb.js

**Comment by kinkwilde** [comment]
OK, will do - I'll update here with the response I get.

**Comment by Glavin001** [comment]
Awesome, thanks! Also if you add a link to here in your Issue over there, we will be able to see they are related and whether it is closed 👍 .

**Comment by kinkwilde** [comment]
OK - quick update. Turns out to be an issue with windows machines as it apparently works on mac. It will be fixed in csscomb version 4.3.0. So someone will need to make sure that atom-beautify will update to this version when it is released.

https://github.com/csscomb/csscomb.js/issues/525

**Comment by aljopro** [comment]
I'm seeing this (seemingly) same issue now on my mac

```
Cannot read property 'is' of null
Cannot read property 'is' of null
Hide Stack Trace
TypeError: Cannot read property 'is' of null
    at Plugin.insertNewlines (/Users/jchappell/.atom/packages/atom-beautify/node_modules/csscomb/lib/options/lines-between-rulesets.js:237:20)
    at node.forEach (/Users/jchappell/.atom/packages/atom-beautify/node_modules/csscomb/lib/options/lines-between-rulesets.js:124:12)
    at Node.forEach (/Users/jchappell/.atom/packages/atom-beautify/node_modules/gonzales-pe/lib/gonzales.js:175:83)
    at Plugin.processRuleSets (/Users/jchappell/.atom/packages/atom-beautify/node_modules/csscomb/lib/options/lines-between-rulesets.js:123:10)
    at Plugin.processBlock (/Users/jchappell/.atom/packages/atom-beautify/node_modules/csscomb/lib/options/lines-between-rulesets.js:98:12)
    at Plugin.process (/Users/jchappell/.atom/packages/atom-beautify/node_modules/csscomb/lib/options/lines-between-rulesets.js:89:10)
    at /Users/jchappell/.atom/packages/atom-beautify/node_modules/csscomb/lib/core.js:384:14
    at Array.forEach (native)
    at Comb._processTree (/Users/jchappell/.atom/packages/atom-beautify/node_modules/csscomb/lib/core.js:383:8)
```

**Comment by yoh-m** [comment]
Had the same issue, just removed the comments at the top of my file and it works!  
Apparently if it's  starting with any comment, be it line comment with `//` or block comment with `/*`, csscomb will give this `UnhandledPromiseRejectionWarning` error.

**Comment by ElsceneInc** [comment]
I'm still having this issue, and yoh-m is correct that starting with a comment seems to be the culprit. Has any fix been identified for this? I'd prefer to keep the comments in my code where they are.
