### ISSUE TITLE
Could not find 'sass-convert'. The program may not be installed.

### ISSUE THREAD

**Issue by valeksashin** [Glavin001/atom-beautify#1699]
Could not find 'sass-convert'. The program may not be installed.
Hide Stack Trace
Error: Could not find 'sass-convert'. The program may not be installed.
    at SassConvert.module.exports.Beautifier.commandNotFoundError (file:///C:/Users/aleksashin/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:231:14)
    at file:///C:/Users/aleksashin/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:331:22
    at tryCatcher (C:\Users\aleksashin\.atom\packages\atom-beautify\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\aleksashin\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\aleksashin\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\aleksashin\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\aleksashin\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:689:18)
    at Async._drainQueue (C:\Users\aleksashin\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\aleksashin\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:143:10)
    at Async.drainQueues (C:\Users\aleksashin\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:17:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by Glavin001** [comment]
If you look at the [README under **Beautifiers**](https://github.com/Glavin001/atom-beautify#beautifiers) you'll see `SassConvert` requires installing a third-party beautifier manually, as it is *not* pre-installed.

The instructions say to go to http://sass-lang.com/documentation/file.SASS_REFERENCE.html#syntax . I see there:

```bash
gem install sass
```

Have you installed `sass` as instructed?

**Comment by valeksashin** [comment]
Hi. i'm not installed? but it's first time when i catch this error. Thanks for your answer

**Comment by Glavin001** [comment]
I really want to focus on improving the installation experience for users. I have created a new Issue, #1687, to target this problem. Please provide your feedback! Thanks in advance.
