### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, statusCode=503

### ISSUE THREAD

**Issue by burningserenity** [Glavin001/atom-beautify#1701]
[Enter steps to reproduce:]

1. Run Privoxy system-wide on HTTP and HTTPS
2. In Atom, open Settings -> Packages

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Deepin 15.4
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.29.26

### Stack Trace

Uncaught Error: tunneling socket could not be established, statusCode=503

```
At stream.js:74

Error: tunneling socket could not be established, statusCode=503
    at ClientRequest.onConnect (/packages/atom-beautify/node_modules/tunnel-agent/index.js:166:19)
    at ClientRequest.g (events.js:286:16)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:194:7)
    at Socket.socketOnData (_http_client.js:393:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
     -5:32.1.0 application:add-project-folder (ul.list-inline.tab-bar.inset-panel)
```

### Non-Core Packages

```
ariake-dark-syntax 0.1.3 
atom-beautify 0.29.26 
autocomplete-html-entities 0.1.0 
autocomplete-python 1.8.63 
change-case 0.6.5 
dbg 1.6.1 
dbg-gdb 1.7.3 
emmet 2.4.3 
git-plus 7.9.2 
hey-pane 1.0.0 
html-tab 1.0.2 
node-debugger 1.10.1 
nord-atom-ui 0.11.0 
open-html-in-browser 0.1.0 
output-panel 0.3.0 
platformio-ide-debugger 1.2.2 
platformio-ide-terminal 2.5.1 
python-debugger 0.2.0 
remove-whitespace 0.2.1 
split-diff 1.4.0 
vim-mode-plus 0.93.0 
vim-mode-plus-ex-mode 0.9.1 
vim-plus-autocomplete-emmet-compatibility 0.1.0 
w3c-validation 0.4.0 
```

**Comment by Glavin001** [comment]
Looking at the logs:

> Error: tunneling socket could not be established, statusCode=503
    at ClientRequest.onConnect (/packages/atom-beautify/node_modules/tunnel-agent/index.js:166:19)

This is the appropriate package to report this issue: https://github.com/request/tunnel-agent

Please create a new Issue over at https://github.com/request/tunnel-agent/issues and link back to here so others can follow the Issue trail. Thanks!

**Comment by wang-pengju** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.31.0 x64
**Electron**: 2.0.7
**OS**: Mac OS X 10.13.6
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.33.2


### Stack Trace

Uncaught Error: tunneling socket could not be established, statusCode=503

```
At internal/streams/legacy.js:59

Error: tunneling socket could not be established, statusCode=503
    at ClientRequest.onConnect (/packages/atom-beautify/node_modules/tunnel-agent/index.js:166:19)
    at Object.onceWrapper (events.js:319:30)
    at emitThree (events.js:136:13)
    at ClientRequest.emit (events.js:217:7)
    at Socket.socketOnData (_http_client.js:472:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
```

### Commands

```
     -8:02.1.0 atom-beautify:beautify-editor (input.hidden-input)
     -7:58.8.0 core:save (input.hidden-input)
  2x -7:54.4.0 settings-view:open (input.hidden-input)
  3x -4:20.2.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.33.2 
atom-html-preview 0.2.5 
atom-material-ui 2.1.3 
atom-nodejs-snippets 2.1.1 
atomizer 0.1.2 
autoclose-html 0.23.0 
autocomplete-modules 2.2.0 
autocomplete-paths 2.12.2 
browser-plus 0.0.98 
busy-signal 1.4.3 
color-picker 2.3.0 
css-snippets 1.1.0 
docblockr 0.13.7 
emmet 2.4.3 
file-icons 2.1.25 
git-plus 8.1.0 
git-time-machine 2.1.0 
highlight-selected 0.14.0 
intentions 1.1.5 
language-babel 2.85.0 
language-ejs 0.4.0 
language-markdown 0.26.0 
language-vue 0.23.1 
last-cursor-position 0.9.3 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
merge-conflicts 1.4.5 
minimap 4.29.9 
open-in-browser 0.5.2 
pigments 0.40.2 
platformio-ide-terminal 2.8.4 
prettier-atom 0.55.2 
react-es7-snippets 0.3.13 
regex-railroad-diagram 0.19.4 
rest-client 1.3.1 
script 3.18.1 
sync-settings 0.8.6 
tool-bar 1.1.10 
vue2-autocomplete 0.1.0-alpha.4 
```
