### ISSUE TITLE
Failed to activate the atom-beautify package

### ISSUE THREAD

**Issue by MandarSant** [Glavin001/atom-beautify#1722]
Following is the error report

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 8.1 Pro with Media Center
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.29.26

### Stack Trace

Failed to activate the atom-beautify package

```
At Cannot find module 'bluebird'

Error: Cannot find module 'bluebird'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.17.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.17.2/resources/app/src/module-cache.js:354:1)
    at Module.require (~/AppData/Local/atom/app-1.17.2/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.17.2/resources/app/src/native-compile-cache.js:66:1)
    at /packages/atom-beautify/src/beautifiers/index.coffee:3:11)
    at /packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.17.2/resources/app/src/native-compile-cache.js:106:1)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.17.2/resources/app/src/compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.17.2/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.17.2/resources/app/src/native-compile-cache.js:66:1)
    at /packages/atom-beautify/src/beautify.coffee:9:15)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.17.2/resources/app/src/native-compile-cache.js:106:1)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.17.2/resources/app/src/compile-cache.js:230:1)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.17.2/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.17.2/resources/app/static/<embedded>:73:1)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:887:1)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:242:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:968:1
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/emitter.js:25:1)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/event-kit/lib/emitter.js:141:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.2/resources/app/src/command-registry.js:246:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/command-registry.js:3:1
    at Object.didConfirmSelection (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/command-palette/lib/command-palette-view.js:106:1)
    at SelectListView.confirmSelection (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/atom-select-list/src/select-list-view.js:313:1)
    at HTMLDivElement.core:confirm (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/atom-select-list/src/select-list-view.js:81:1)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.17.2/resources/app/src/command-registry.js:265:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/command-registry.js:3:1
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:1)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.17.2/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:1)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.17.2/resources/app/src/window-event-handler.js:100:1)
    at HTMLDocument.<anonymous> (~/AppData/Local/atom/app-1.17.2/resources/app/src/window-event-handler.js:3:1)
```

### Commands

```
     -2:13.2.0 intentions:highlight (input.hidden-input)
     -2:12.4.0 command-palette:toggle (input.hidden-input)
     -1:57.1.0 core:confirm (input.hidden-input)
     -1:57.1.0 application:new-file (input.hidden-input)
     -1:52 intentions:highlight (input.hidden-input)
     -1:50.6.0 core:backspace (input.hidden-input)
     -1:50 intentions:highlight (input.hidden-input)
     -1:49.3.0 command-palette:toggle (input.hidden-input)
     -1:41.6.0 core:confirm (input.hidden-input)
     -1:39.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.26 
busy-signal 1.4.3 
emmet 2.4.3 
file-icons 2.1.7 
highlight-selected 0.13.1 
intentions 1.1.2 
linter 2.1.4 
linter-csslint 1.3.4 
linter-eslint 8.2.1 
linter-htmlhint 1.3.3 
linter-ui-default 1.6.1 
minimap 4.28.2 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
pigments 0.39.1 
platformio-ide-terminal 2.5.1 
```

**Comment by johnsonz** [comment]
Same problem

**Comment by Glavin001** [comment]
Please uninstall and re-install Atom-Beautify with `apm install atom-beautify`. Bluebird is a dependency in `package.json`. If it is failing to install this indicates a problem with Atom's [apm](https://github.com/atom/apm).

**Comment by MandarSant** [comment]
@Glavin001 how to install Bluebird

**Comment by Glavin001** [comment]
@MandarSant Bluebird is a dependency of Atom-Beautify: https://github.com/Glavin001/atom-beautify/blob/master/package.json#L155

You should not need to manually install it. The above error indicates to me the installation by Atom's [apm](https://github.com/atom/apm) did not work. Thus, please try it again using `apm install atom-beautify`. If reinstalling does not fix this issue then I recommend reporting an error over at https://github.com/atom/apm since it means `apm` is not properly installing dependencies, or at least should throw an error during installation if there is in fact a problem.

**Comment by johnsonz** [comment]
Solved by re-install
