### ISSUE TITLE
I installed autopep8 through MacPorts, but Atom could not find it.

### ISSUE THREAD

**Issue by Albert-Z-Guo** [Glavin001/atom-beautify#1723]
# Description

```
Error: Could not find 'autopep8'. The program may not be installed.
    at Autopep8.module.exports.Beautifier.commandNotFoundError (/Users/Albert_Guo/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:231:14)
    at /Users/Albert_Guo/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:331:22
    at tryCatcher (/Users/Albert_Guo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Albert_Guo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/Albert_Guo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/Albert_Guo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/Albert_Guo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Users/Albert_Guo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/Albert_Guo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/Users/Albert_Guo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by Glavin001** [comment]
Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.

**Comment by Glavin001** [comment]
#1687 has been published to v0.30.0. You should now be able to configure the executable/script path in Atom-Beautify package settings:
![image](https://user-images.githubusercontent.com/1885333/27255671-b14d95ec-5379-11e7-8095-7195967f6cb1.png)

**Comment by Albert-Z-Guo** [comment]
Thank you so much for the quick response the awesome updates!

atom-beautify is working for me now!

**Comment by Glavin001** [comment]
Awesome to hear, @Albert-Z-Guo!
