### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by iv-lite** [Glavin001/atom-beautify#173]
Uncaught TypeError: undefined is not a function

**Atom Version**: 0.162.0
**System**: linux 3.17.7-300.fc21.x86_64
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.21.0

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /home/iv/.atom/packages/atom-beautify/lib/beautify.coffee:120

TypeError: undefined is not a function
  at atom-workspace.beautify (/home/iv/.atom/packages/atom-beautify/lib/beautify.coffee:120:13)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/local/share/atom/resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/usr/local/share/atom/resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/local/share/atom/resources/app/src/command-registry.js:156:19)
  at Ipc.<anonymous> (/usr/local/share/atom/resources/app/src/window-event-handler.js:65:30)
  at Ipc.emit (events.js:107:17)
  at process.<anonymous> (/usr/local/share/atom/resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:110:17)

```

/cc @atom/core

**Comment by Glavin001** [comment]
Please update your Atom to v0.165.0 and let me know if you problems still persist.

**Comment by Glavin001** [comment]
Also try updating Atom Beautify to the new patch, v0.21.1. That should fix your problem. Thanks!
