### ISSUE TITLE
No JSCS config found.

### ISSUE THREAD

**Issue by kingangelAOA** [Glavin001/atom-beautify#1731]
atom-beautify version: 0.30.0
atom version: 1.18.0
Error: No JSCS config found.
    at /Users/kingangeltot/.atom/packages/atom-beautify/src/beautifiers/jscs.coffee:29:21
    at Promise._execute (/Users/kingangeltot/.atom/packages/atom-beautify/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/kingangeltot/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/kingangeltot/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:79:10)
    at JSCSFixer.module.exports.JSCSFixer.beautify (/Users/kingangeltot/.atom/packages/atom-beautify/src/beautifiers/jscs.coffee:18:16)
    at /Users/kingangeltot/.atom/packages/atom-beautify/src/beautifiers/index.coffee:353:28
    at tryCatcher (/Users/kingangeltot/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/kingangeltot/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/kingangeltot/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/Users/kingangeltot/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/Users/kingangeltot/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/Users/kingangeltot/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/Users/kingangeltot/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)

**Comment by Glavin001** [comment]
Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.

**Comment by Glavin001** [comment]
The error is coming from https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/jscs.coffee#L29
Created by PR: https://github.com/Glavin001/atom-beautify/pull/412

Maybe @Cortys (PR author) has some ideas?
