### ISSUE TITLE
Impossible to install in Atom 0.165.0

### ISSUE THREAD

**Issue by Ducatel** [Glavin001/atom-beautify#174]
Hi,

It's impossible to install this package inside Atom 0.165.0 on Windows 7x64 computer.
(With the Atom package installer)
```
npm http GET https://registry.npmjs.org/analytics-node
npm http GET https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/coffee-formatter
npm http GET https://registry.npmjs.org/editorconfig
npm http GET https://registry.npmjs.org/atom-message-panel
npm http GET https://registry.npmjs.org/js-beautify
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/space-pen
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/loophole
npm http GET https://registry.npmjs.org/strip-json-comments
npm http GET https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/node-dir
npm http GET https://registry.npmjs.org/lodash/2.4.1
npm http GET https://registry.npmjs.org/temp
npm http GET https://registry.npmjs.org/prettydiff
npm http GET https://registry.npmjs.org/typescript-formatter
npm http GET https://registry.npmjs.org/yaml-front-matter
npm http 304 https://registry.npmjs.org/atom-message-panel
npm http 304 https://registry.npmjs.org/emissary
npm http 304 https://registry.npmjs.org/js-beautify
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/space-pen
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/strip-json-comments
npm http 304 https://registry.npmjs.org/extend
npm http 304 https://registry.npmjs.org/analytics-node
npm http 304 https://registry.npmjs.org/loophole
npm http 304 https://registry.npmjs.org/temp
npm http 304 https://registry.npmjs.org/node-dir
npm http 304 https://registry.npmjs.org/coffee-formatter
npm http 304 https://registry.npmjs.org/editorconfig
npm http 304 https://registry.npmjs.org/typescript-formatter
npm http 304 https://registry.npmjs.org/yaml-front-matter
npm http 304 https://registry.npmjs.org/lodash/2.4.1
npm http 304 https://registry.npmjs.org/prettydiff
npm http GET https://registry.npmjs.org/clone
npm http GET https://registry.npmjs.org/component-type
npm http GET https://registry.npmjs.org/join-component
npm http GET https://registry.npmjs.org/superagent-proxy
npm http GET https://registry.npmjs.org/superagent
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/uid/0.0.2
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/sigmund
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/property-accessors
npm http GET https://registry.npmjs.org/commander/1.0.0
npm http GET https://registry.npmjs.org/js-yaml
npm http GET https://registry.npmjs.org/is-browser
npm http GET https://registry.npmjs.org/grim
npm http 304 https://registry.npmjs.org/clone
npm http 304 https://registry.npmjs.org/superagent-proxy
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/config-chain
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/nopt
npm http 304 https://registry.npmjs.org/join-component
npm http GET https://registry.npmjs.org/lazy
npm http GET https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/keypress
npm http 304 https://registry.npmjs.org/property-accessors
npm http 304 https://registry.npmjs.org/superagent
npm http 304 https://registry.npmjs.org/uid/0.0.2
npm http 304 https://registry.npmjs.org/js-yaml
npm http 304 https://registry.npmjs.org/grim
npm http 304 https://registry.npmjs.org/config-chain
npm http GET https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/coffeestack
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/mixto
npm http 304 https://registry.npmjs.org/nopt
npm http 304 https://registry.npmjs.org/lazy
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/keypress
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/coffeestack
npm http GET https://registry.npmjs.org/abbrev
npm http GET https://registry.npmjs.org/proto-list
npm http GET https://registry.npmjs.org/ini
npm http 304 https://registry.npmjs.org/component-type
npm http 304 https://registry.npmjs.org/ini
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/minimist/0.0.8
npm http GET https://registry.npmjs.org/proxy-agent
npm http 304 https://registry.npmjs.org/abbrev
npm http 304 https://registry.npmjs.org/proto-list
npm http 304 https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/ms/0.6.2
npm http 304 https://registry.npmjs.org/minimist/0.0.8
npm http 304 https://registry.npmjs.org/coffee-script
npm http 304 https://registry.npmjs.org/ms/0.6.2
npm http GET https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/commander/1.0.0
npm http GET https://registry.npmjs.org/qs/0.6.5
npm http GET https://registry.npmjs.org/emitter-component/1.0.0
npm http GET https://registry.npmjs.org/formidable/1.0.14
npm http GET https://registry.npmjs.org/methods/0.0.1
npm http GET https://registry.npmjs.org/cookiejar/1.3.0
npm http GET https://registry.npmjs.org/mime/1.2.5
npm http GET https://registry.npmjs.org/reduce-component/1.0.1
npm http 304 https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/is-browser
npm http 304 https://registry.npmjs.org/emitter-component/1.0.0
npm http GET https://registry.npmjs.org/amdefine
npm http GET https://registry.npmjs.org/argparse
npm http GET https://registry.npmjs.org/esprima
npm http 304 https://registry.npmjs.org/formidable/1.0.14
npm http 304 https://registry.npmjs.org/methods/0.0.1
npm http 304 https://registry.npmjs.org/proxy-agent
npm http 304 https://registry.npmjs.org/amdefine
npm http GET https://registry.npmjs.org/http-proxy-agent
npm http GET https://registry.npmjs.org/https-proxy-agent
npm http GET https://registry.npmjs.org/pac-proxy-agent
npm http GET https://registry.npmjs.org/socks-proxy-agent
npm http 304 https://registry.npmjs.org/argparse
npm http 304 https://registry.npmjs.org/esprima
npm http 304 https://registry.npmjs.org/reduce-component/1.0.1
npm http GET https://registry.npmjs.org/underscore.string
npm http GET https://registry.npmjs.org/commander/2.2.0
npm http 304 https://registry.npmjs.org/qs/0.6.5
npm http 304 https://registry.npmjs.org/cookiejar/1.3.0
npm http 304 https://registry.npmjs.org/socks-proxy-agent
npm http 304 https://registry.npmjs.org/pac-proxy-agent
npm http 304 https://registry.npmjs.org/commander/2.2.0
npm http 304 https://registry.npmjs.org/mime/1.2.5
npm http 304 https://registry.npmjs.org/http-proxy-agent
npm http 304 https://registry.npmjs.org/https-proxy-agent
npm http GET https://registry.npmjs.org/agent-base
npm http GET https://registry.npmjs.org/pac-resolver
npm http GET https://registry.npmjs.org/stream-to-array
npm http GET https://registry.npmjs.org/get-uri
npm http GET https://registry.npmjs.org/rainbowsocks
npm http 304 https://registry.npmjs.org/underscore.string
npm http 304 https://registry.npmjs.org/stream-to-array
npm http 304 https://registry.npmjs.org/agent-base
npm http 304 https://registry.npmjs.org/pac-resolver
npm http 304 https://registry.npmjs.org/get-uri
npm http GET https://registry.npmjs.org/data-uri-to-buffer
npm http GET https://registry.npmjs.org/ftp
npm http GET https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/file-uri-to-path
npm http GET https://registry.npmjs.org/co
npm http GET https://registry.npmjs.org/netmask
npm http GET https://registry.npmjs.org/regenerator
npm http GET https://registry.npmjs.org/degenerator
npm http 304 https://registry.npmjs.org/rainbowsocks
npm http GET https://registry.npmjs.org/thunkify
npm http 304 https://registry.npmjs.org/co
npm http 304 https://registry.npmjs.org/ftp
npm http 304 https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/netmask
npm http 304 https://registry.npmjs.org/data-uri-to-buffer
npm http 304 https://registry.npmjs.org/thunkify
npm http 304 https://registry.npmjs.org/file-uri-to-path
npm http GET https://registry.npmjs.org/xregexp/2.0.0
npm http 304 https://registry.npmjs.org/degenerator
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/string_decoder
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/xregexp/2.0.0
npm http 304 https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/isarray/0.0.1
npm http 304 https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/regenerator
npm http GET https://registry.npmjs.org/ast-types
npm http GET https://registry.npmjs.org/escodegen
npm http GET https://registry.npmjs.org/private
npm http GET https://registry.npmjs.org/recast
npm http GET https://registry.npmjs.org/defs
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/ariya/esprima.git) 
npm http 304 https://registry.npmjs.org/escodegen
npm http 304 https://registry.npmjs.org/private
npm http 304 https://registry.npmjs.org/recast
npm http 304 https://registry.npmjs.org/ast-types
npm http 304 https://registry.npmjs.org/defs
npm ERR! git clone git://github.com/ariya/esprima.git Cloning into bare repository 'C:\Users\myUser.domain\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ariya-esprima-git-9077e517'...
npm ERR! git clone git://github.com/ariya/esprima.git fatal: unable to connect to github.com:
npm ERR! git clone git://github.com/ariya/esprima.git github.com[0: 192.30.252.130]: errno=No error
npm ERR! Error: Command failed: Cloning into bare repository 'C:\Users\myUser.domain\AppData\Roaming\npm-cache\_git-remotes\git-github-com-ariya-esprima-git-9077e517'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.130]: errno=No error
npm ERR! 
npm ERR! 
npm ERR!     at ChildProcess.exithandler (child_process.js:648:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:756:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:823:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Users\\myUser.domain\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\myUser.domain\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\myUser.domain\\AppData\\Local\\atom\\app-0.165.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\myUser.domain\\.atom\\.apmrc" "install" "C:\\Users\\myUser.domain\\AppData\\Local\\Temp\\d-11505-6760-dl2r1s\\package.tgz" "--target=0.18.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! cwd C:\Users\myUser.domain\AppData\Local\Temp\apm-install-dir-11505-6760-uu9aop
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! code 128
npm
```

No problem if I execute this line directly in my command line.
```
git clone git://github.com/ariya/esprima.git
```

So have fun ;)

**Comment by Akarienta** [comment]
Exactly the same for me.

my conf
```
windows 7x64
atom 0.165.0
npm 2.1.18
git 1.9.4.msysgit.2
```

**Comment by Glavin001** [comment]
@kevinsawicki or @nathansobo thanks for helping me out with previous problems. I am hoping someone who works on Atom can shed some light on to why users keep having these problems. However, I don't think there's anything I can do from an Atom Beautify perspective.

**Comment by moortaube** [comment]
**As a side note:** Same problem inside atom 0.166.0 on OS X *(both: update and re-install)*.

```
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/atom-message-panel
npm http GET https://registry.npmjs.org/coffee-formatter
npm http GET https://registry.npmjs.org/editorconfig
npm http GET https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/js-beautify
npm http GET https://registry.npmjs.org/lodash/2.4.1
npm http GET https://registry.npmjs.org/node-dir
npm http GET https://registry.npmjs.org/strip-json-comments
npm http GET https://registry.npmjs.org/loophole
npm http GET https://registry.npmjs.org/prettydiff
npm http GET https://registry.npmjs.org/analytics-node
npm http GET https://registry.npmjs.org/temp
npm http 304 https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/typescript-formatter
npm http GET https://registry.npmjs.org/yaml-front-matter
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/space-pen
npm http 304 https://registry.npmjs.org/extend
npm http 304 https://registry.npmjs.org/js-beautify
npm http 304 https://registry.npmjs.org/atom-message-panel
npm http 304 https://registry.npmjs.org/coffee-formatter
npm http 304 https://registry.npmjs.org/strip-json-comments
npm http 304 https://registry.npmjs.org/emissary
npm http 304 https://registry.npmjs.org/loophole
npm http 200 https://registry.npmjs.org/prettydiff
npm http 304 https://registry.npmjs.org/editorconfig
npm http GET https://registry.npmjs.org/prettydiff/-/prettydiff-1.7.1.tgz
npm http 304 https://registry.npmjs.org/lodash/2.4.1
npm http 304 https://registry.npmjs.org/node-dir
npm http 304 https://registry.npmjs.org/node-uuid
npm http 200 https://registry.npmjs.org/prettydiff/-/prettydiff-1.7.1.tgz
npm http 304 https://registry.npmjs.org/temp
npm http 304 https://registry.npmjs.org/analytics-node
npm http 200 https://registry.npmjs.org/space-pen
npm http 304 https://registry.npmjs.org/typescript-formatter
npm http 304 https://registry.npmjs.org/yaml-front-matter
npm http GET https://registry.npmjs.org/clone
npm http GET https://registry.npmjs.org/join-component
npm http GET https://registry.npmjs.org/component-type
npm http GET https://registry.npmjs.org/superagent
npm http GET https://registry.npmjs.org/uid/0.0.2
npm http GET https://registry.npmjs.org/superagent-proxy
npm http 304 https://registry.npmjs.org/clone
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/superagent-proxy
npm http 200 https://registry.npmjs.org/superagent
npm http 200 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/component-type
npm http GET https://registry.npmjs.org/is-browser
npm http GET https://registry.npmjs.org/js-yaml
npm http GET https://registry.npmjs.org/commander/1.0.0
npm http 304 https://registry.npmjs.org/join-component
npm http 304 https://registry.npmjs.org/uid/0.0.2
npm http 304 https://registry.npmjs.org/js-yaml
npm http 200 https://registry.npmjs.org/commander/1.0.0
npm http 304 https://registry.npmjs.org/is-browser
npm http GET https://registry.npmjs.org/commander/-/commander-1.0.0.tgz
npm http GET https://registry.npmjs.org/keypress
npm http 200 https://registry.npmjs.org/commander/-/commander-1.0.0.tgz
npm http GET https://registry.npmjs.org/proxy-agent
npm http 304 https://registry.npmjs.org/keypress
npm http GET https://registry.npmjs.org/ms/0.6.2
npm http 304 https://registry.npmjs.org/proxy-agent
npm http 304 https://registry.npmjs.org/ms/0.6.2
npm http GET https://registry.npmjs.org/socks-proxy-agent
npm http GET https://registry.npmjs.org/https-proxy-agent
npm http GET https://registry.npmjs.org/pac-proxy-agent
npm http GET https://registry.npmjs.org/http-proxy-agent
npm http GET https://registry.npmjs.org/cookiejar/1.3.0
npm http GET https://registry.npmjs.org/reduce-component/1.0.1
npm http GET https://registry.npmjs.org/formidable/1.0.14
npm http GET https://registry.npmjs.org/qs/0.6.5
npm http GET https://registry.npmjs.org/emitter-component/1.0.0
npm http GET https://registry.npmjs.org/methods/0.0.1
npm http GET https://registry.npmjs.org/mime/1.2.5
npm http 304 https://registry.npmjs.org/socks-proxy-agent
npm http 304 https://registry.npmjs.org/http-proxy-agent
npm http 304 https://registry.npmjs.org/formidable/1.0.14
npm http 304 https://registry.npmjs.org/cookiejar/1.3.0
npm http 304 https://registry.npmjs.org/reduce-component/1.0.1
npm http 304 https://registry.npmjs.org/methods/0.0.1
npm http GET https://registry.npmjs.org/lazy
npm http GET https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/pac-proxy-agent
npm http 304 https://registry.npmjs.org/mime/1.2.5
npm http 304 https://registry.npmjs.org/https-proxy-agent
npm http 200 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/lazy
npm http 304 https://registry.npmjs.org/qs/0.6.5
npm http 304 https://registry.npmjs.org/emitter-component/1.0.0
npm http GET https://registry.npmjs.org/agent-base
npm http GET https://registry.npmjs.org/rainbowsocks
npm http GET https://registry.npmjs.org/pac-resolver
npm http GET https://registry.npmjs.org/stream-to-array
npm http GET https://registry.npmjs.org/get-uri
npm http 304 https://registry.npmjs.org/agent-base
npm http 304 https://registry.npmjs.org/stream-to-array
npm http 304 https://registry.npmjs.org/rainbowsocks
npm http 304 https://registry.npmjs.org/pac-resolver
npm http 304 https://registry.npmjs.org/get-uri
npm http GET https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/argparse
npm http GET https://registry.npmjs.org/esprima
npm http 304 https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/esprima
npm http 304 https://registry.npmjs.org/argparse
npm http GET https://registry.npmjs.org/data-uri-to-buffer
npm http GET https://registry.npmjs.org/file-uri-to-path
npm http GET https://registry.npmjs.org/ftp
npm http GET https://registry.npmjs.org/netmask
npm http GET https://registry.npmjs.org/co
npm http GET https://registry.npmjs.org/degenerator
npm http GET https://registry.npmjs.org/thunkify
npm http GET https://registry.npmjs.org/regenerator
npm http GET https://registry.npmjs.org/underscore.string
npm http 304 https://registry.npmjs.org/data-uri-to-buffer
npm http 304 https://registry.npmjs.org/netmask
npm http 304 https://registry.npmjs.org/ftp
npm http 304 https://registry.npmjs.org/thunkify
npm http 304 https://registry.npmjs.org/regenerator
npm http 304 https://registry.npmjs.org/underscore.string
npm http 304 https://registry.npmjs.org/file-uri-to-path
npm http 304 https://registry.npmjs.org/co
npm http 304 https://registry.npmjs.org/degenerator
npm http GET https://registry.npmjs.org/xregexp/2.0.0
npm http GET https://registry.npmjs.org/escodegen
npm http GET https://registry.npmjs.org/ast-types
npm ERR! Error: ENOENT, lstat '/private/var/folders/qj/qryhck0j7jl1wcrnh1jpx04000010b/T/apm-install-dir-11507-3064-4pzhsk/node_modules/atom-beautify/node_modules/analytics-node/node_modules/superagent-proxy/node_modules/proxy-agent/node_modules/pac-proxy-agent/node_modules/pac-resolver/node_modules/regenerator/lib/visit.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.0.0
npm ERR! command "/Users/myUser/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/bin/node" "/Users/myUser/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/myUser/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/.apmrc" "--userconfig" "/Users/myUser/.atom/.apmrc" "install" "/private/var/folders/qj/qryhck0j7jl1wcrnh1jpx04000010b/T/d-11507-3064-1ghbysq/package.tgz" "--target=0.18.0" "--arch=x64"
npm ERR! cwd /private/var/folders/qj/qryhck0j7jl1wcrnh1jpx04000010b/T/apm-install-dir-11507-3064-4pzhsk
npm ERR! node -v v0.10.33

npm ERR! npm -v 1.4.4
npm ERR! path /private/var/folders/qj/qryhck0j7jl1wcrnh1jpx04000010b/T/apm-install-dir-11507-3064-4pzhsk/node_modules/atom-beautify/node_modules/analytics-node/node_modules/superagent-proxy/node_modules/proxy-agent/node_modules/pac-proxy-agent/node_modules/pac-resolver/node_modules/regenerator/lib/visit.js
npm ERR! fstream_path /private/var/folders/qj/qryhck0j7jl1wcrnh1jpx04000010b/T/apm-install-dir-11507-3064-4pzhsk/node_modules/atom-beautify/node_modules/analytics-node/node_modules/superagent-proxy/node_modules/proxy-agent/node_modules/pac-proxy-agent/node_modules/pac-resolver/node_modules/regenerator/lib/visit.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /Users/myUser/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 304 https://registry.npmjs.org/escodegen
npm http 304 https://registry.npmjs.org/ast-types
npm ERR! not found: git
npm ERR! 
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! System Darwin 14.0.0
npm ERR! command "/Users/myUser/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/bin/node" "/Users/myUser/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/myUser/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/.apmrc" "--userconfig" "/Users/myUser/.atom/.apmrc" "install" "/private/var/folders/qj/qryhck0j7jl1wcrnh1jpx04000010b/T/d-11507-3064-1ghbysq/package.tgz" "--target=0.18.0" "--arch=x64"
npm ERR! cwd /private/var/folders/qj/qryhck0j7jl1wcrnh1jpx04000010b/T/apm-install-dir-11507-3064-4pzhsk
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! code ENOGIT
npm http 200 https://registry.npmjs.org/xregexp/2.0.0
npm http GET https://registry.npmjs.org/xregexp/-/xregexp-2.0.0.tgz
npm ERR! Error: ENOENT, lstat '/private/var/folders/qj/qryhck0j7jl1wcrnh1jpx04000010b/T/apm-install-dir-11507-3064-4pzhsk/node_modules/atom-beautify/node_modules/typescript-formatter/typescript-toolbox/typescript/0.9.5/typescriptServices.js'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.0.0
npm ERR! command "/Users/myUser/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/bin/node" "/Users/myUser/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/myUser/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/.apmrc" "--userconfig" "/Users/myUser/.atom/.apmrc" "install" "/private/var/folders/qj/qryhck0j7jl1wcrnh1jpx04000010b/T/d-11507-3064-1ghbysq/package.tgz" "--target=0.18.0" "--arch=x64"
npm ERR! cwd /private/var/folders/qj/qryhck0j7jl1wcrnh1jpx04000010b/T/apm-install-dir-11507-3064-4pzhsk
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.4
npm ERR! path /private/var/folders/qj/qryhck0j7jl1wcrnh1jpx04000010b/T/apm-install-dir-11507-3064-4pzhsk/node_modules/atom-beautify/node_modules/typescript-formatter/typescript-toolbox/typescript/0.9.5/typescriptServices.js
npm ERR! fstream_path /private/var/folders/qj/qryhck0j7jl1wcrnh1jpx04000010b/T/apm-install-dir-11507-3064-4pzhsk/node_modules/atom-beautify/node_modules/typescript-formatter/typescript-toolbox/typescript/0.9.5/typescriptServices.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /Users/myUser/Applications/Atom.app/Contents/Resources/app/apm/node_modules/atom-package-manager/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm http 200 https://registry.npmjs.org/xregexp/-/xregexp-2.0.0.tgz
npm http GET https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/underscore-plus
npm http 304 https://registry.npmjs.org/mixto
npm http 304 https://registry.npmjs.org/underscore-plus
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /private/var/folders/qj/qryhck0j7jl1wcrnh1jpx04000010b/T/apm-install-dir-11507-3064-4pzhsk/npm-debug.log
npm ERR! not ok code 0
```

**Comment by Glavin001** [comment]
@moortaube try https://alicoding.com/how-to-fix-error-enoent-lstat-npm-when-trying-to-install-modules/

```bash
npm cache clean
```

**Comment by Ducatel** [comment]
It doesn't fix my problem

**Comment by Akarienta** [comment]
either for me

**Comment by kevinsawicki** [comment]
> npm ERR! fatal: unable to connect to github.com:

This is a proxy error I'm guessing and you can configure apm proxy settings via [this](https://github.com/atom/apm#behind-a-firewall)

> npm ERR! code ENOGIT

This suggests that Git it not on the `Path` environment variable

**Comment by CAFxX** [comment]
Same error here (and I'm behind a corporate proxy)

**Comment by Akarienta** [comment]
Just a note: an update of apm in atom release 0.170.0 doesn't fix this problem.

**Comment by Akarienta** [comment]
atom release 0.176.0

it seems better now but still getting very similar error

```
npm ERR! git fetch -a origin (https://github.com/Benvie/harmony-collections.git) fatal: Unable to find remote helper for 'https'
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/ariya/esprima.git)
npm ERR! git clone git://github.com/ariya/esprima.git Cloning into bare repository 'C:\Users\pc00120\.atom\.node-gyp\.atom\.apm\_git-remotes\git-github-com-ariya-esprima-git-9077e517'...
npm ERR! git clone git://github.com/ariya/esprima.git fatal: Unable to look up github.com (port 9418) (Nen� zn�m ��dn� takov� hostitel. )
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\\Users\\pc00120\\AppData\\Local\\atom\\app-0.176.0\\resources\\app\\apm\\bin\\node.exe" "c:\\Users\\pc00120\\AppData\\Local\\atom\\app-0.176.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\pc00120\\AppData\\Local\\atom\\app-0.176.0\\resources\\app\\apm\\.apmrc" "--userconfig" "C:\\Users\\pc00120\\.atom\\.apmrc" "install" "C:\\Users\\pc00120\\AppData\\Local\\Temp\\d-115029-4180-1mvqz47\\package.tgz" "--target=0.20.0" "--arch=ia32" "--msvs_version=2012"
npm ERR! node v0.10.35
npm ERR! npm  v2.3.0
npm ERR! code 128

npm ERR! Command failed: fatal: Unable to find remote helper for 'https'
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
```

**Comment by Glavin001** [comment]
I'd recommend posting on a forum more tailored to solving this issue, such as [stackoverflow](http://stackoverflow.com/). If you then find a solution please post back here for others. Thanks.

**Comment by Akarienta** [comment]
Here is the question if someone else is interesting in this topic: http://stackoverflow.com/questions/28216987/impossible-to-install-atom-beautify-on-windows-7-64bit-machine-with-apm

**Comment by Akarienta** [comment]
We have solved this problem finally, there are two bugs: one in npm and second in msysgit. More information [here](http://stackoverflow.com/questions/28216987/impossible-to-install-atom-beautify-on-windows-7-64bit-machine-with-apm).
