### ISSUE TITLE
SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by vdubus** [Glavin001/atom-beautify#1745]
# Information

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Windows 7 Entreprise Service Pack 1
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.30.3

# Steps to reproduce:

1. Start Atom.

# Stack Trace

Failed to activate the atom-beautify package

```
At Invalid or unexpected token

SyntaxError: Invalid or unexpected token
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:94:52)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-beautify/node_modules/winston/lib/winston.js:19:22)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-beautify/src/logger.coffee:10:13
    at /packages/atom-beautify/src/logger.coffee:4:18)
    at /packages/atom-beautify/src/logger.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-beautify/src/beautifiers/index.coffee:6:10)
    at /packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-beautify/src/beautify.coffee:9:15)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.18.0/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:887:35)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:242:22)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:1014:34
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PackageManager.module.exports.PackageManager.triggerDeferredActivationHooks (~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:676:42)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:607:23
```

# Commands

```
     -5:17.5.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-always)
```

# Non-Core Packages

```
asciidoc-assistant 0.2.2 
asciidoc-image-helper 1.0.0 
asciidoc-preview 2.10.2 
atom-beautify 0.30.3 
atom-typescript 11.0.3 
autocomplete-asciidoc 0.1.2 
busy-signal 1.4.3 
editorconfig 2.2.2 
file-icons 2.1.7 
highlight-selected 0.13.1 
intentions 1.1.2 
language-asciidoc 1.10.0 
language-docker 1.1.8 
linter 2.2.0 
linter-ui-default 1.6.2 
minimap 4.28.2 
minimap-highlight-selected 4.6.1 
prettier-atom 0.34.0 
```

# What did I try?

- Updating all packages
- Restarting Atom

**Comment by FEAGRI** [comment]
Estou na 1.21.0 x64 e também não funciona

**Comment by stormbornboy** [comment]
i have same problem in ### windows 10 enterprise
can anybody help me please?
