### ISSUE TITLE
Could not find 'hh_format'. The program may not be installed. But it is.

### ISSUE THREAD

**Issue by ryanpcmcquen** [Glavin001/atom-beautify#1749]
# Description

`hh_format` cannot be found despite being installed.

```
$ which hh_format
/usr/local/bin/hh_format
```

```
Could not find 'hh_format'. The program may not be installed.
See hh_format installation instructions at https://github.com/Glavin001/atom-beautify#beautifiers or go to http://hhvm.com/
Your program is properly installed if running 'which hh_format' in your Terminal returns an absolute path to the executable.
Hide Stack Trace
Error: Could not find 'hh_format'. The program may not be installed.
    at Function.Executable.commandNotFoundError (/Users/ryan.mcquen/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:276:14)
    at HybridExecutable.Executable.commandNotFoundError (/Users/ryan.mcquen/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:268:18)
    at /Users/ryan.mcquen/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:196:22
    at tryCatcher (/Users/ryan.mcquen/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/ryan.mcquen/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/ryan.mcquen/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/ryan.mcquen/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/ryan.mcquen/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Users/ryan.mcquen/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/ryan.mcquen/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/Users/ryan.mcquen/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

# Steps to Reproduce

1. `brew tap hhvm/hhvm && brew install hhvm`
2. Run command `Atom Beautify: Beautify Editor`
3. Get the error!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/ryanpcmcquen/fdc205104c5fa7127c6f98e01a6bc8d8

# Checklist

I have:
- [X] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [X] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [X] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [X] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [X] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
> $ which hh_format
/usr/local/bin/hh_format

From your logs:

> 2017-06-29T18:56:02.945Z - debug: [] PATH: /usr/bin:/bin:/usr/sbin:/sbin

Looks like Atom-Beautify would not be able to find the `hh_format` executable because it is missing from `PATH`.
Can you check your PATH environment variable is being persisted properly? `echo $PATH`.

Properly extracting the environment variables, such as `PATH`, is the responsibility of Atom. See https://github.com/atom/atom/blob/7b1aadc9b361c4e6257f88d94fe9bf531341a407/src/update-process-env.js
Either you are missing some configuration to set the correct `PATH` or Atom is failing to pick up your change and you should report a bug to Atom. Hope that helps! Please let us know back here what worked for you.

**Comment by ryanpcmcquen** [comment]
Atom is definitely not getting my `PATH`:

```
$ echo $PATH
/Applications/Zed.app/bin:/Users/ryan.mcquen/.local/bin:/usr/local/php5/bin:/usr/local/php5-5.6.30-20170506-093822/bin:/usr/local/Homebrew/bin:/opt/X11/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin:/Applications/Zed.app/bin:/Users/ryan.mcquen/.local/bin:/Users/ryan.mcquen/bin:/usr/local/php5/bin:/usr/local/php5-5.6.30-20170506-093822/bin:/usr/local/Homebrew/bin
```

**Comment by ryanpcmcquen** [comment]
I submitted an issue there, hopefully it can get resolved:

https://github.com/atom/atom/issues/14924
