### ISSUE TITLE
Performing "Beautify File" on C++ file throws error: "unknown option 'undefined':"

### ISSUE THREAD

**Issue by IanMin1022** [Glavin001/atom-beautify#1764]
I tried to beautify files on the project section with right click the file and click Beautify File then it showed me these 

117615-3358-s33prr.8r0no5stt9.cfg:1 for the assignment: unknown option 'undefined':
117615-3358-s33prr.8r0no5stt9.cfg:1
  for the assignment: unknown option 'undefined':
Hide Stack Trace
Error: 117615-3358-s33prr.8r0no5stt9.cfg:1
  for the assignment: unknown option 'undefined':
    at /home/ian/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:182:27
    at tryCatcher (/home/ian/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ian/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ian/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ian/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ian/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/ian/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/ian/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/home/ian/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)

But then, when I just edited in command window with defining it with certain language like cpp it worked. 
 
Was I supposed to set up which language I am gonna use whenever I edit it?

**Comment by Glavin001** [comment]
Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.

**Comment by pmarella2** [comment]
I have this issue, any fix?
