### ISSUE TITLE
pybeautifier - connection refused

### ISSUE THREAD

**Issue by JGH1000** [Glavin001/atom-beautify#1788]
When I try to run pybeautifier I get the following error:

connect ECONNREFUSED 127.0.0.1:36805
connect ECONNREFUSED 127.0.0.1:36805
Hide Stack Trace
Error: connect ECONNREFUSED 127.0.0.1:36805
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)

yapf or autopep8 works fine. Many thanks!

**Comment by JGH1000** [comment]
Strange, started to work after additional restart!

**Comment by guyskk** [comment]
Duplicated with #2272
