### ISSUE TITLE
Cannot find module './lib/rng'

### ISSUE THREAD

**Issue by gustavkarlsson** [Glavin001/atom-beautify#1800]
# Description

When I start Atom, I'm shown an error message saying ./lib/rng cannot be found.

**Atom:** 1.18.0 x64
**Electron:** 1.3.15
**OS:** Ubuntu Gnome 16.10
**Package version:** 0.30.4

# Stack Trace
Failed to activate the atom-beautify package
```
Cannot find module './lib/rng'

Error: Cannot find module './lib/rng'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/opt/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/opt/atom/resources/app/src/module-cache.js:354:58)
    at Module.require (file:///opt/atom/resources/app/static/index.js:40:43)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/gustav/.atom/packages/atom-beautify/node_modules/request/node_modules/uuid/v1.js:1:90)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (file:///opt/atom/resources/app/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/gustav/.atom/packages/atom-beautify/node_modules/request/node_modules/uuid/index.js:1:89)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (file:///opt/atom/resources/app/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/gustav/.atom/packages/atom-beautify/node_modules/request/lib/auth.js:4:12)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (file:///opt/atom/resources/app/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/gustav/.atom/packages/atom-beautify/node_modules/request/request.js:26:33)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (file:///opt/atom/resources/app/static/index.js:47:45)
```

**Comment by BukkitPlaysMC** [comment]
Still an issue.

**Comment by velykov** [comment]
Cannot find module './lib/rng'

**Comment by velykov** [comment]
clear node_modules and issue fixed
