### ISSUE TITLE
Beautify for php does not work

### ISSUE THREAD

**Issue by Samnan** [Glavin001/atom-beautify#1811]
# Description

The results of beautification are not what I expect. It always generates the php cs fixer path warning, although I have added it in settings and ensured it works.

# Input Before Beautification
Included in debug.md

# Expected Output
Should be formatted output as expected

# Actual Output
It didn't work at all, with warning about cs fixer path.

# Steps to Reproduce

1. Open php file
2. Run command `Atom Beautify: Beautify Editor`
3. Generates warning and does not beautify

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/Samnan/81a3c442a8f789bc8e22bba7fe372ae5

# Checklist

I have:
- [ x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ]x Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by Samnan** [comment]
Within two minutes of submitting the bug, I got this email. The links given in the email point to some http://0.0.xxx.xxx domain. Is this some kind of malware?

![mail](https://user-images.githubusercontent.com/872992/29257729-c98bda0c-80cd-11e7-90fc-3fbdf4ea4dec.png)

**Comment by mharding7va** [comment]
Same Error Here:

`Could not find 'php-cs-fixer'. The program may not be installed.

See php-cs-fixer installation instructions at https://github.com/Glavin001/atom-beautify#beautifiers or go to https://github.com/FriendsOfPHP/PHP-CS-Fixer
Your program is properly installed if running 'which php-cs-fixer' in your Terminal returns an absolute path to the executable.

Error: Could not find 'php-cs-fixer'. The program may not be installed.
    at Function.Executable.commandNotFoundError (/Users/mharding/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:276:14)
    at HybridExecutable.Executable.commandNotFoundError (/Users/mharding/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:268:18)
    at /Users/mharding/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:196:22
    at tryCatcher (/Users/mharding/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/mharding/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/mharding/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/mharding/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/mharding/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Users/mharding/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/mharding/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/Users/mharding/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)`

**Comment by mharding7va** [comment]
Yes it is installed. I’m on a Mac.

Thank you,

Michael Harding
Senior Project Manager
Genesis Digital

(704) 727-8033 - Office

mharding@genesisdla.com <mharding@genesisgroupusa.com> - E-Mail
www.genesisdla.com - Website

**Comment by catchchances** [comment]
I hava a issue like this .

Could not find 'sqlformat'. The program may not be installed.
See sqlformat installation instructions at https://github.com/Glavin001/atom-beautify#beautifiers or go to https://github.com/andialbrecht/sqlparse
Your program is properly installed if running 'where.exe sqlformat' in your CMD prompt returns an absolute path to the executable.

**Comment by Glavin001** [comment]
@Samnan : Here is an extract from your logs:

```
2017-08-14T03:36:16.877Z - debug: [] spawn F:\Servers\AMPPS\php-cs-fixer.bat 0=fix, 1=--allow-risky=no, 2=--using-cache=no, 3=C:\Users\Sam\AppData\Local\Temp\temp117714-4908-1s4yyt3.3nm56ogvi.php
2017-08-14T03:36:19.642Z - debug: [] spawn done 3221225477  
C:\Users\Sam\AppData\Local\Temp>F:\Servers\AMPPS\php\php "F:/Servers/AMPPS/php-cs-fixer.phar" fix --allow-risky=no --using-cache=no C:\Users\Sam\AppData\Local\Temp\temp117714-4908-qbwl8a.clabdquxr.php 

2017-08-14T03:36:19.642Z - verbose: [] spawn result, returnCode 3221225477
```

It looks like Atom-Beautify ran correctly, and there was an error from within PHP-CS-Fixer with return code 3221225477.

Here is the command Atom-Beautify used:

```
F:\Servers\AMPPS\php-cs-fixer.bat fix --allow-risky=no --using-cache=no FILE_NAME.php
```

I recommend trying it on the same file and confirming the expected result.

**Comment by Glavin001** [comment]
@mharding7va : Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.

**Comment by jaychu28** [comment]
gem install rubocop
