### ISSUE TITLE
"spawn EACCES" error occured when beautify python-code by command "ctl alt b"

### ISSUE THREAD

**Issue by TyouSF** [Glavin001/atom-beautify#1816]
# Description

"spawn EACCES" error occured when beautify python-code by command "ctl alt b"

# ERROR Code

```
Error: spawn EACCES
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:399:9)
    at /Users/fiter/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:237:13
    at Promise._execute (/Users/fiter/.atom/packages/atom-beautify/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/fiter/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/fiter/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:79:10)
    at HybridExecutable.Executable.spawn (/Users/fiter/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:234:16)
    at /Users/fiter/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:166:10
    at tryCatcher (/Users/fiter/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/fiter/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/fiter/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/fiter/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/fiter/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/fiter/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/fiter/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/Users/fiter/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
```

# Settings

In atom beautify settings -> executables -> autopep8:

`/Users/programs/venv/lib/python3.6/site-packages`

**Comment by KinglittleQ** [comment]
I hvae the same problem...

**Comment by jgs1202** [comment]
I have the same...

**Comment by szeck87** [comment]
@TyouSF Try putting the absolute path to autopep script into that field.

**Comment by TyouSF** [comment]
@szeck87 3Q!
I solved with the below step:
With installing autopep8 in primary python environment instead of installing in virtual env, I had solved this problem. After installing, reset ‘/Library/Frameworks/Python.framework/Versions/3.6/bin/autopep8’ atom beautify settings -> executables -> autopep8.

**Comment by asterikx** [comment]
What finally worked for me was [installing autopep8 using the `--user` option](https://github.com/hhatto/autopep8#installation)
 
First remove any existing autopep8 installation
```
sudo -H pip uninstall autopep8
```
Then install it again, but this time using the `--user` option
```
pip install --user --upgrade autopep8
```
Finally go to `Settings -> Executables -> autopep8` and set the path to the autopep8 executable to `/Users/yourusername/Library/Python/2.7/bin/autopep8`.

Note that setting the executable path to the `bin` folder will also result in the `spawn EACCES` error.

**Comment by xelarep** [comment]
THX!
