### ISSUE TITLE
Installation behind a proxy

### ISSUE THREAD

**Issue by ericrange** [Glavin001/atom-beautify#184]
in the last issues there was a problem for the installation behind a proxy. non-npm packages were responsible for that. it seems that "git://github.com/ariya/esprima.git" is the only package left that is non-npm and which interrupts the installation.

would it be possible to transfer esprima to npm?

**Comment by Glavin001** [comment]
I do not host that package. Could you check with their maintainer?

**Comment by ericrange** [comment]
oh i found it: https://www.npmjs.com/package/esprima
could you replace that "git://" thing with "esprima"?

**Comment by Glavin001** [comment]
It's not Atom Beautify direct dependency: https://github.com/Glavin001/atom-beautify/blob/master/package.json#L46-L65

**Comment by Glavin001** [comment]
I tried to look thru all of the failed / error installation logs however I could not determine which dependent package had the broken dependency. I cannot even reproduce this, since I am not behind a firewall / proxy. I hope someone is able to track it down and resolve this. Good luck.

**Comment by ericrange** [comment]
here is my error log. do you see something that cause the error?
```
npm http GET https://registry.npmjs.org/analytics-node
npm http GET https://registry.npmjs.org/atom-message-panel
npm http GET https://registry.npmjs.org/coffee-formatter
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/editorconfig
npm http GET https://registry.npmjs.org/lodash/2.4.1
npm http GET https://registry.npmjs.org/js-beautify
npm http GET https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/emissary
npm http GET https://registry.npmjs.org/strip-json-comments
npm http GET https://registry.npmjs.org/node-dir
npm http GET https://registry.npmjs.org/loophole
npm http GET https://registry.npmjs.org/typescript-formatter
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/temp
npm http GET https://registry.npmjs.org/space-pen
npm http GET https://registry.npmjs.org/yaml-front-matter
npm http GET https://registry.npmjs.org/prettydiff
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/temp
npm http 304 https://registry.npmjs.org/space-pen
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/strip-json-comments
npm http 304 https://registry.npmjs.org/editorconfig
npm http 200 https://registry.npmjs.org/typescript-formatter
npm http 304 https://registry.npmjs.org/extend
npm http 304 https://registry.npmjs.org/coffee-formatter
npm http 304 https://registry.npmjs.org/atom-message-panel
npm http 304 https://registry.npmjs.org/node-dir
npm http 304 https://registry.npmjs.org/emissary
npm http 304 https://registry.npmjs.org/prettydiff
npm http 304 https://registry.npmjs.org/loophole
npm http 304 https://registry.npmjs.org/yaml-front-matter
npm http 304 https://registry.npmjs.org/js-beautify
npm http 200 https://registry.npmjs.org/lodash/2.4.1
npm http 304 https://registry.npmjs.org/analytics-node
npm http GET https://registry.npmjs.org/lodash/-/lodash-2.4.1.tgz
npm http 200 https://registry.npmjs.org/lodash/-/lodash-2.4.1.tgz
npm http GET https://registry.npmjs.org/join-component
npm http GET https://registry.npmjs.org/component-type
npm http GET https://registry.npmjs.org/superagent-proxy
npm http GET https://registry.npmjs.org/superagent
npm http GET https://registry.npmjs.org/clone
npm http GET https://registry.npmjs.org/uid/0.0.2
npm http GET https://registry.npmjs.org/debug
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/lru-cache
npm http GET https://registry.npmjs.org/mixto
npm http GET https://registry.npmjs.org/sigmund
npm http GET https://registry.npmjs.org/underscore-plus
npm http GET https://registry.npmjs.org/commander
npm http GET https://registry.npmjs.org/property-accessors
npm http GET https://registry.npmjs.org/js-yaml
npm http GET https://registry.npmjs.org/commander/1.0.0
npm http GET https://registry.npmjs.org/is-browser
npm http 304 https://registry.npmjs.org/clone
npm http 304 https://registry.npmjs.org/superagent
npm http 304 https://registry.npmjs.org/debug
npm http 304 https://registry.npmjs.org/component-type
npm http 304 https://registry.npmjs.org/superagent-proxy
npm http GET https://registry.npmjs.org/grim
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/lru-cache
npm http 304 https://registry.npmjs.org/sigmund
npm http 304 https://registry.npmjs.org/commander
npm http 304 https://registry.npmjs.org/uid/0.0.2
npm http 304 https://registry.npmjs.org/join-component
npm http 304 https://registry.npmjs.org/underscore-plus
npm http 304 https://registry.npmjs.org/js-yaml
npm http 304 https://registry.npmjs.org/is-browser
npm http GET https://registry.npmjs.org/proxy-agent
npm http 304 https://registry.npmjs.org/grim
npm http GET https://registry.npmjs.org/keypress
npm http GET https://registry.npmjs.org/ms/0.6.2
npm http GET https://registry.npmjs.org/coffeestack
npm http GET https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/mixto
npm http 304 https://registry.npmjs.org/property-accessors
npm http 304 https://registry.npmjs.org/commander/1.0.0
npm http GET https://registry.npmjs.org/optimist
npm http GET https://registry.npmjs.org/lazy
npm http GET https://registry.npmjs.org/qs/0.6.5
npm http GET https://registry.npmjs.org/methods/0.0.1
npm http GET https://registry.npmjs.org/mime/1.2.5
npm http GET https://registry.npmjs.org/formidable/1.0.14
npm http GET https://registry.npmjs.org/reduce-component/1.0.1
npm http GET https://registry.npmjs.org/emitter-component/1.0.0
npm http GET https://registry.npmjs.org/cookiejar/1.3.0
npm http GET https://registry.npmjs.org/mkdirp
npm http GET https://registry.npmjs.org/nopt
npm http GET https://registry.npmjs.org/config-chain
npm http 304 https://registry.npmjs.org/keypress
npm http 304 https://registry.npmjs.org/proxy-agent
npm http 304 https://registry.npmjs.org/ms/0.6.2
npm http 304 https://registry.npmjs.org/underscore
npm http GET https://registry.npmjs.org/http-proxy-agent
npm http GET https://registry.npmjs.org/socks-proxy-agent
npm http GET https://registry.npmjs.org/pac-proxy-agent
npm http GET https://registry.npmjs.org/https-proxy-agent
npm http 304 https://registry.npmjs.org/optimist
npm http 304 https://registry.npmjs.org/lazy
npm http 200 https://registry.npmjs.org/coffeestack
npm http 304 https://registry.npmjs.org/qs/0.6.5
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/source-map
npm http 304 https://registry.npmjs.org/nopt
npm http 304 https://registry.npmjs.org/config-chain
npm http 304 https://registry.npmjs.org/reduce-component/1.0.1
npm http 304 https://registry.npmjs.org/formidable/1.0.14
npm http 304 https://registry.npmjs.org/mkdirp
npm http 304 https://registry.npmjs.org/emitter-component/1.0.0
npm http 304 https://registry.npmjs.org/https-proxy-agent
npm http 304 https://registry.npmjs.org/methods/0.0.1
npm http 304 https://registry.npmjs.org/socks-proxy-agent
npm http 304 https://registry.npmjs.org/http-proxy-agent
npm http 304 https://registry.npmjs.org/mime/1.2.5
npm http 304 https://registry.npmjs.org/cookiejar/1.3.0
npm http GET https://registry.npmjs.org/abbrev
npm http 304 https://registry.npmjs.org/source-map
npm http GET https://registry.npmjs.org/proto-list
npm http GET https://registry.npmjs.org/ini
npm http GET https://registry.npmjs.org/wordwrap
npm http GET https://registry.npmjs.org/minimist/0.0.8
npm http 304 https://registry.npmjs.org/pac-proxy-agent
npm http GET https://registry.npmjs.org/argparse
npm http GET https://registry.npmjs.org/esprima
npm http 304 https://registry.npmjs.org/abbrev
npm http GET https://registry.npmjs.org/rainbowsocks
npm http GET https://registry.npmjs.org/agent-base
npm http GET https://registry.npmjs.org/pac-resolver
npm http GET https://registry.npmjs.org/get-uri
npm http GET https://registry.npmjs.org/stream-to-array
npm http 304 https://registry.npmjs.org/coffee-script
npm http 304 https://registry.npmjs.org/ini
npm http 304 https://registry.npmjs.org/proto-list
npm http 304 https://registry.npmjs.org/wordwrap
npm http 304 https://registry.npmjs.org/minimist/0.0.8
npm http 304 https://registry.npmjs.org/esprima
npm http 304 https://registry.npmjs.org/argparse
npm http 304 https://registry.npmjs.org/rainbowsocks
npm http 304 https://registry.npmjs.org/agent-base
npm http 304 https://registry.npmjs.org/pac-resolver
npm http 304 https://registry.npmjs.org/get-uri
npm http 304 https://registry.npmjs.org/stream-to-array
npm http GET https://registry.npmjs.org/data-uri-to-buffer
npm http GET https://registry.npmjs.org/ftp
npm http GET https://registry.npmjs.org/file-uri-to-path
npm http GET https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/ftp
npm http 304 https://registry.npmjs.org/data-uri-to-buffer
npm http 304 https://registry.npmjs.org/file-uri-to-path
npm http 304 https://registry.npmjs.org/readable-stream
npm http GET https://registry.npmjs.org/netmask
npm http GET https://registry.npmjs.org/co
npm http GET https://registry.npmjs.org/degenerator
npm http GET https://registry.npmjs.org/regenerator
npm http GET https://registry.npmjs.org/thunkify
npm http GET https://registry.npmjs.org/underscore.string
npm http 304 https://registry.npmjs.org/degenerator
npm http 304 https://registry.npmjs.org/netmask
npm http 304 https://registry.npmjs.org/thunkify
npm http 304 https://registry.npmjs.org/co
npm http GET https://registry.npmjs.org/amdefine
npm http 200 https://registry.npmjs.org/regenerator
npm http 304 https://registry.npmjs.org/underscore.string
npm http 304 https://registry.npmjs.org/amdefine
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/string_decoder
npm http GET https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/isarray/0.0.1
npm http 304 https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/inherits
npm http GET https://registry.npmjs.org/escodegen
npm http GET https://registry.npmjs.org/ast-types
npm http 304 https://registry.npmjs.org/ast-types
npm http 200 https://registry.npmjs.org/escodegen
npm http GET https://registry.npmjs.org/private
npm http GET https://registry.npmjs.org/recast
npm http GET https://registry.npmjs.org/defs
npm http 304 https://registry.npmjs.org/private
npm http 304 https://registry.npmjs.org/defs
npm http 304 https://registry.npmjs.org/recast
npm http GET https://registry.npmjs.org/commander/2.2.0
npm http 304 https://registry.npmjs.org/commander/2.2.0
npm ERR! git fetch -a origin (git://github.com/ariya/esprima.git) fatal: unable to connect to github.com:
npm ERR! git fetch -a origin (git://github.com/ariya/esprima.git) github.com[0: 192.30.252.131]: errno=No error
npm ERR! Error: Command failed: fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.131]: errno=No error
npm ERR! 
npm ERR! 
npm ERR!     at ChildProcess.exithandler (child_process.js:658:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:766:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Users\\eric.range\\AppData\\Local\\atom\\app-0.170.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\Users\\eric.range\\AppData\\Local\\atom\\app-0.170.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "c:\\Users\\eric.range\\AppData\\Local\\atom\\app-0.170.0\\resources\\app\\apm\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "c:\\Users\\eric.range\\.atom\\.apmrc" "install" "c:\\Users\\eric.range\\.atom\\.node-gyp\\.atom\\.apm\\atom-beautify\\0.21.2\\package.tgz" "--target=0.20.0" "--arch=ia32"
npm ERR! cwd C:\Users\ERIC~1.RAN\AppData\Local\Temp\apm-install-dir-115013-6640-3olzw9
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.4
npm ERR! code 128
npm
```

**Comment by jackmaney** [comment]
I'm having prettymuch the same error on Atom 0.180.0

```
$ apm --version
apm  0.140.0
npm  2.5.1
node 0.10.35
python 2.7.9
git 2.3.0
```

I also have my `.apmrc` set up with the relevant proxy info.

Here is the stack trace when trying to install via the GUI in `Atom > Packages > Install`:

```
npm ERR! git clone git://github.com/ariya/esprima.git Cloning into bare repository '/Users/[username]/.atom/.apm/_git-remotes/git-github-com-ariya-esprima-git-9077e517'...
npm ERR! git clone git://github.com/ariya/esprima.git fatal: unable to connect to github.com:
npm ERR! git clone git://github.com/ariya/esprima.git github.com[0: 192.30.252.128]: errno=Connection refused
npm ERR! Darwin 13.4.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/[username]/.atom/.apm/.apmrc" "--userconfig" "/Users/[username]/.atom/.apmrc" "install" "/private/var/folders/kk/r0v_bq3x6bj58dyn_b3rb_wh0000gp/T/d-115118-19100-1rg23u9/package.tgz" "--target=0.21.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository '/Users/[username]/.atom/.apm/_git-remotes/git-github-com-ariya-esprima-git-9077e517'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.128]: errno=Connection refused
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/kk/r0v_bq3x6bj58dyn_b3rb_wh0000gp/T/apm-install-dir-115118-19100-7jbi5k/npm-debug.log
```

The same issue arises when installing via the command line (`apm install atom-beautify`).

**Comment by ericrange** [comment]
the problem is the git://github.com/ariya/esprima.git package. its not a npm package. but its not atom-beautifyers fault. a dependency of ab has this git://github.com/ariya/esprima.git in its package.json.
