### ISSUE TITLE
Cannot correctly beautify c++17 "if constexpr" statement

### ISSUE THREAD

**Issue by NGC2070** [Glavin001/atom-beautify#1871]
# Description

I have written some c++17 code using the new "if constexpr" statement, compiled and ran normally. However the beautifier does not recognise this pattern and unable to tidy up the code.

# Input Before Beautification

This is what the code looked like before, I scrambled the code rather messily:
```
#include <variant>
#include <iostream>


int main(){

        constexpr std::variant<int, double> vec = 1;

        if
        constexpr (std::holds_alternative<int>(vec)){
std::cout << "Print int" << '\n';}
                       else if
                       constexpr (std::holds_alternative<double>(vec)){
std::cout << "Print double" << '\n';}

}
```
# Expected Output

The beautified code should have looked like this or something similar:
```
#include <variant>
#include <iostream>

int main(){

        constexpr std::variant<int, double> vec = 1;

        if constexpr (std::holds_alternative<int>(vec)){
        std::cout << "Print int" << '\n';
        }else if constexpr (std::holds_alternative<double>(vec)){
        std::cout << "Print double" << '\n';
        }
}
```
# Actual Output
```
Error message:
Parsing: input117830-7385-qap3ke.gfwp7j5rk9.cpp as language CPP input117830-7385-qap3ke.gfwp7j5rk9.cpp:9 Error: Expected '(', got 'constexpr' for 'IF' input117830-7385-qap3ke.gfwp7j5rk9.cpp:11 Error: Expected '(', got 'constexpr' for 'ELSEIF'
Parsing: input117830-7385-qap3ke.gfwp7j5rk9.cpp as language CPP
input117830-7385-qap3ke.gfwp7j5rk9.cpp:9 Error: Expected '(', got 'constexpr' for 'IF'
input117830-7385-qap3ke.gfwp7j5rk9.cpp:11 Error: Expected '(', got 'constexpr' for 'ELSEIF'

Stack trace:
Error: Parsing: input117830-7385-qap3ke.gfwp7j5rk9.cpp as language CPP
input117830-7385-qap3ke.gfwp7j5rk9.cpp:9 Error: Expected '(', got 'constexpr' for 'IF'
input117830-7385-qap3ke.gfwp7j5rk9.cpp:11 Error: Expected '(', got 'constexpr' for 'ELSEIF'
    at /home/user/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:182:27
    at tryCatcher (/home/user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/home/user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```
# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. Then you see a lot of red stuff :(

Thx

**Comment by szeck87** [comment]
This looks to be a issue with Uncrustify.  I receive the same error when I run uncrustify through a terminal for those contents.  I would open an issue there:  https://github.com/uncrustify/uncrustify
