### ISSUE TITLE
PATH set but autopep8 still not installed 

### ISSUE THREAD

**Issue by jackjameshoward** [Glavin001/atom-beautify#1906]
# Description

I am running Atom in the "portable-mode", so basically the '.atom' folder is stored locally on the external drive. 
I am also running python portably on the same external drive. 
I have added the absolute path to autopep8 to the Settings-Executables-autopep8 but autopep8 still cannot be found.

# Debug

Here is a link to the `debug.md` Gist: [Gist](https://gist.github.com/jackjameshoward/22fe655fc68b9d66004e904906cd5633)

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by szeck87** [comment]
Hi @jackjameshoward, can you run `which autopep8` from the command line and paste the output? Also, what kind of machine/OS are you using?

**Comment by jackjameshoward** [comment]
E:\program_files\python3\python-3.6.2.amd64\Scripts>where autopep8
E:\program_files\python3\python-3.6.2.amd64\Scripts\autopep8.exe

E:\program_files\python3\python-3.6.2.amd64\Scripts>systeminfo

OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.14393 N/A Build 14393
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
System Manufacturer:       HP
System Model:              HP EliteBook 840 G3
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 78 Stepping 3 GenuineIntel ~2396 Mhz

**Comment by szeck87** [comment]
Try appending `\\autopep8.exe` to the end of the executable path in the settings.

**Comment by szeck87** [comment]
@jackjameshoward Did you give that a try?

**Comment by ggabriel96** [comment]
Hello there! This is happening to me too (PC info at the end). I have installed it with `pip install autopep8`. It is not on my PATH, so I tried to manually set its absolute path on the settings.
The path is: `C:\Users\ggabr\AppData\Roaming\Python\Python36\site-packages\autopep8`. With this exact string, I get the following error:

```
Error: spawn UNKNOWN
    at exports._errnoException (util.js:1050:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at exports.spawn (child_process.js:390:9)
    at file:///C:/Users/ggabr/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:237:13
    at Promise._execute (C:\Users\ggabr\.atom\packages\atom-beautify\node_modules\bluebird\js\release\debuggability.js:303:9)
    at Promise._resolveFromExecutor (C:\Users\ggabr\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (C:\Users\ggabr\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:79:10)
    at HybridExecutable.Executable.spawn (file:///C:/Users/ggabr/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:234:12)
    at file:///C:/Users/ggabr/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:166:10
    at tryCatcher (C:\Users\ggabr\.atom\packages\atom-beautify\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\ggabr\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\ggabr\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\ggabr\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\ggabr\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\ggabr\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\ggabr\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:143:10)
    at Async.drainQueues (C:\Users\ggabr\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:17:14)
    at <anonymous>
```

I don't know if I understood correctly what you meant with that `\\autopep8.exe`, but the path `C:\Users\ggabr\AppData\Roaming\Python\Python36\site-packages\autopep8.py\\autopep8.exe` didn't work and threw the error below.

```
Error: Could not find 'autopep8'. The program may not be installed.
    at Function.Executable.commandNotFoundError (file:///C:/Users/ggabr/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:276:10)
    at HybridExecutable.Executable.commandNotFoundError (file:///C:/Users/ggabr/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:268:18)
    at file:///C:/Users/ggabr/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:196:22
    at tryCatcher (C:\Users\ggabr\.atom\packages\atom-beautify\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\ggabr\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\ggabr\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\ggabr\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\ggabr\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:689:18)
    at Async._drainQueue (C:\Users\ggabr\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\ggabr\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:143:10)
    at Async.drainQueues (C:\Users\ggabr\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:17:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

So my PC info is:

```
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.16299 N/A Build 16299
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
System Manufacturer:       Avell High Performance
System Model:              1513
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 94 Stepping 3 GenuineIntel ~2301 Mhz
```

**Comment by ggabriel96** [comment]
Oh, I just ran `pip install autopep8 --upgrade` on a PowerShell that *I ran as Administrator* and it's now on my System PATH, it is a `.exe` file and is working like a charm :)
