### ISSUE TITLE
Failed to activate the atom-beautify package v. 30.6

### ISSUE THREAD

**Issue by sgehrman** [Glavin001/atom-beautify#1921]
# Description
Failed to activate the atom-beautify package

TypeError: Beautifiers is not a constructor
    at Object.<anonymous> (file:///C:/Users/Steve/.atom/packages/atom-beautify/src/beautify.coffee:10:18)
    at Object.<anonymous> (file:///C:/Users/Steve/.atom/packages/atom-beautify/src/beautify.coffee:2:1)
    at Object.<anonymous> (file:///C:/Users/Steve/.atom/packages/atom-beautify/src/beautify.coffee:2:1)
    at Module.get_Module._compile (C:\Users\Steve\AppData\Local\atom\app-1.21.1\resources\app\src\native-compile-cache.js:106:36)
    at Object.value [as .coffee] (C:\Users\Steve\AppData\Local\atom\app-1.21.1\resources\app\src\compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///C:/Users/Steve/AppData/Local/atom/app-1.21.1/resources/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (C:\Users\Steve\AppData\Local\atom\app-1.21.1\resources\app\static\<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (C:\Users\Steve\AppData\Local\atom\app-1.21.1\resources\app\src\package.js:903:35)
    at Package.module.exports.Package.activateNow (C:\Users\Steve\AppData\Local\atom\app-1.21.1\resources\app\src\package.js:242:22)
    at C:\Users\Steve\AppData\Local\atom\app-1.21.1\resources\app\src\package.js:1030:34
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Steve\AppData\Local\atom\app-1.21.1\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (C:\Users\Steve\AppData\Local\atom\app-1.21.1\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
    at triggeredActivationHooks.forEach.hook (C:\Users\Steve\AppData\Local\atom\app-1.21.1\resources\app\src\package-manager.js:700:86)
    at Set.forEach (native)
    at PackageManager.activatePackage (C:\Users\Steve\AppData\Local\atom\app-1.21.1\resources\app\src\package-manager.js:700:43)
    at C:\Users\Steve\AppData\Local\atom\app-1.21.1\resources\app\node_modules\settings-view\lib\package-manager.js:535:35
    at exit (C:\Users\Steve\AppData\Local\atom\app-1.21.1\resources\app\node_modules\settings-view\lib\package-manager.js:128:22)
    at triggerExitCallback (C:\Users\Steve\AppData\Local\atom\app-1.21.1\resources\app\src\buffered-process.js:338:17)
    at ChildProcess.<anonymous> (C:\Users\Steve\AppData\Local\atom\app-1.21.1\resources\app\src\buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/chi
# Input Before Beautification

This is what the code looked like before:

```
<INSERT CODE HERE>
```

# Expected Output

The beautified code should have looked like this:

```
<INSERT CODE HERE>
```

# Actual Output

I tried uninstall/reinstall and it didn't help.

The beautified code actually looked like this:

```
<INSERT CODE HERE>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>

# Checklist

I have:
- [ ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by sgehrman** [comment]
nevermind.

**Comment by szeck87** [comment]
What was the issue?

**Comment by sgehrman** [comment]
I did have to do the uninstall/reinstall, but I think the error message was still up from the first update and I assumed it had failed the second time since the dialog was still visible.

**Comment by szeck87** [comment]
https://github.com/Glavin001/atom-beautify/issues/1734#issuecomment-340922061
