### ISSUE TITLE
installing uncrustify - HOW TO ¿¿

### ISSUE THREAD

**Issue by gnkarn** [Glavin001/atom-beautify#2037]
on the docker link, there is no instructions on how to get and install uncrustify ( in order to make beautify to work in Atom)  , in fact there is no single mention to it on the linked page .

i would suggest to add this information and delete the non-relevant links as the information provided there is not useful for the install purpose .

thank you

**Comment by szeck87** [comment]
The instructions are at the bottom. If you're on a Mac or Linux, I'd suggest using Whalebrew. Otherwise you can run `docker pull unibeautify/uncrustify`.

Also, if you have Docker installed it should install the Docker image automatically when you run the beautify command for an uncrustify supported language.

**Comment by gnkarn** [comment]
Thank you for your answer , I have installed  docker today , I will test it tomorrow but I think that docker is “ empty” after installation, so I’m not sure if it will be able to find the source , will test it tomorrow .

**Comment by Glavin001** [comment]
@gnkarn : Thank you for providing your feedback. We are always trying to improve the user experience.

If I am not mistaken, the "non-relevant links" you are referring to can be found at https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/uncrustify/index.coffee#L18-L19 . Pull Requests are very welcome! Thanks again!

**Comment by gnkarn** [comment]
it worked fine , i would suggest to remark, those two steps : install Docker , and the fact that it will automatically detect and install the uncrustify container . thank you

**Comment by Glavin001** [comment]
@gnkarn : Great to here everything is working now! If you have no more questions, please close this issue 😃 .

**Comment by g-uru** [comment]
This does not work on Win 10 x64 pro, docker is installed, it also automatically pulls the docker on intending to beautify a .java file but then you get the following error:

load_option_file: fopen(C:\Users\myusername\AppData\Local\Temp\118319-16936-rvqr0u.5da7c.cfg) failed: Invalid argument (22) Unable to load the config file Try running with -h for usage information

--
Error: load_option_file: fopen(C:\Users\myusername\AppData\Local\Temp\118319-16936-rvqr0u.5da7c.cfg) failed: Invalid argument (22)
Unable to load the config file
Try running with -h for usage information
    at file:///C:/Users/myusername/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:182:23
    at tryCatcher (C:\Users\myusername\.atom\packages\atom-beautify\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\myusername\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\myusername\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\myusername\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\myusername\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\myusername\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\myusername\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:143:10)
    at Async.drainQueues (C:\Users\myusername\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:17:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by dumblole** [comment]
@g-uru  it doesn't work for me either and I have win 10 x64  pro

**Comment by yankee14** [comment]
I think I am having the same issue.

```
user@windows{~}>> UNCRUSTIFY_CONFIG=/cygdrive/c/Users/edp/.babun/cygwin/home/edp/.uncrustify.conf uncrustify -l C main.c
unc_getenv: name=UNCRUSTIFY_CONFIG len=61 value=/cygdrive/c/Users/edp/.babun/cygwin/home/edp/.uncrustify.conf
load_option_file: fopen(/cygdrive/c/Users/edp/.babun/cygwin/home/edp/.uncrustify.conf) failed: No such file or directory (2)
Unable to load the config file
Try running with -h for usage information
```
