### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by AhmedHelalAhmed** [Glavin001/atom-beautify#2109]
# Cannot read property 'split' of undefined

The results of beautification are not what I expect.

# Input Before Beautification

I write PHP code and just clicked on beautify editor contents

```
<?php
public function FunctionName($value='')
{
  return "hello";
}

$value="hello world";
foreach ($variable as $key => $value) {
  echo "$key      $value";
}
```

# Expected Output

formated code

# Actual Output

The beautified code actually looked like this:

```
Cannot read property 'split' of undefined
Cannot read property 'split' of undefined
Hide Stack Trace
TypeError: Cannot read property 'split' of undefined
    at PHPCSFixer.module.exports.Beautifier.findFile (/home/ahmedhelal/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:138:24)
    at PHPCSFixer.module.exports.PHPCSFixer.beautify (/home/ahmedhelal/.atom/packages/atom-beautify/src/beautifiers/php-cs-fixer.coffee:65:39)
    at /home/ahmedhelal/.atom/packages/atom-beautify/src/beautifiers/index.coffee:361:28
    at tryCatcher (/home/ahmedhelal/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ahmedhelal/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ahmedhelal/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/home/ahmedhelal/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/home/ahmedhelal/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/home/ahmedhelal/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/home/ahmedhelal/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by Glavin001** [comment]
Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.

**Comment by AhmedHelalAhmed** [comment]
I found the solution.
I was not save the file. when i saved it.the program give no problem but it do nothing ?!
