### ISSUE TITLE
Sometimes error with message; Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by pu3antasyah** [Glavin001/atom-beautify#2113]
Sometimes when I try to beautifier the JS or PHP Codes with step `Cntrl + a` then `Cntrl + Shift + b`, I got error - below is full messages body:

```
TypeError: Cannot read property 'split' of undefined
    at PHPCSFixer.module.exports.Beautifier.findFile (/home/my-ubuntu-1604-user/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:138:24)
    at PHPCSFixer.module.exports.PHPCSFixer.beautify (/home/my-ubuntu-1604-user/.atom/packages/atom-beautify/src/beautifiers/php-cs-fixer.coffee:65:39)
    at /home/my-ubuntu-1604-user/.atom/packages/atom-beautify/src/beautifiers/index.coffee:361:28
    at tryCatcher (/home/my-ubuntu-1604-user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/my-ubuntu-1604-user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/my-ubuntu-1604-user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/home/my-ubuntu-1604-user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/home/my-ubuntu-1604-user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/home/my-ubuntu-1604-user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/home/my-ubuntu-1604-user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at <anonymous>
TypeError: Cannot read property 'split' of undefined
    at PHPCSFixer.module.exports.Beautifier.findFile (/home/my-ubuntu-1604-user/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:138:24)
    at PHPCSFixer.module.exports.PHPCSFixer.beautify (/home/my-ubuntu-1604-user/.atom/packages/atom-beautify/src/beautifiers/php-cs-fixer.coffee:65:39)
    at /home/my-ubuntu-1604-user/.atom/packages/atom-beautify/src/beautifiers/index.coffee:361:28
    at tryCatcher (/home/my-ubuntu-1604-user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/my-ubuntu-1604-user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/my-ubuntu-1604-user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/home/my-ubuntu-1604-user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/home/my-ubuntu-1604-user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/home/my-ubuntu-1604-user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/home/my-ubuntu-1604-user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at <anonymous>
```

ATOM Details
```
Atom    : 1.25.1
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

Package details:
`atom-beautify 0.32.2`

OS Details:
`Ubuntu 16:04 LTS`

**Comment by pu3antasyah** [comment]
Especially when try to beautify JS codes

**Comment by helloromero** [comment]
+1

**Comment by rishabhgupta54** [comment]
Facing error when trying to beautify php and html code
Cannot read property 'split' of undefined

TypeError: Cannot read property 'split' of undefined
    at PHPCSFixer.module.exports.Beautifier.findFile (file:///C:/Users/Isha Kwatra/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:138:25)
    at PHPCSFixer.module.exports.PHPCSFixer.beautify (file:///C:/Users/Isha Kwatra/.atom/packages/atom-beautify/src/beautifiers/php-cs-fixer.coffee:65:39)
    at file:///C:/Users/Isha Kwatra/.atom/packages/atom-beautify/src/beautifiers/index.coffee:363:28
    at tryCatcher (C:\Users\Isha Kwatra\.atom\packages\atom-beautify\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Isha Kwatra\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (C:\Users\Isha Kwatra\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromiseCtx (C:\Users\Isha Kwatra\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:611:10)
    at _drainQueueStep (C:\Users\Isha Kwatra\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:142:12)
    at _drainQueue (C:\Users\Isha Kwatra\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\Users\Isha Kwatra\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:147:5)
    at Async.drainQueues (C:\Users\Isha Kwatra\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:17:14)
    at <anonymous>
