### ISSUE TITLE
error is not defined

### ISSUE THREAD

**Issue by linjialiang** [Glavin001/atom-beautify#2132]
```shell
ReferenceError: error is not defined
    at file:///C:/Users/linji/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:412:24
    at tryCatcher (C:\Users\linji\.atom\packages\atom-beautify\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\linji\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\linji\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\linji\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\linji\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:689:18)
    at Async._drainQueue (C:\Users\linji\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\linji\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:143:10)
    at Async.drainQueues (C:\Users\linji\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:17:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by fenixjz** [comment]
Same error on Win 7 x64, Atom 1.26.1 x64, atom-beautify 0.32.3

**Comment by szeck87** [comment]
Published to v0.32.4

**Comment by linjialiang** [comment]
thank you very much
