### ISSUE TITLE
CSV - Unsupported beautification result in Osx (no tested in windows)

### ISSUE THREAD

**Issue by borisalmonacid** [Glavin001/atom-beautify#2142]
# Description

The results of beautification are not what I expect.

# Input Before Beautification

This is what the code looked like before:

file name: "a.csv"
```
Year,Make,Model
1997,Ford,E350
2000,Mercury,Cougar
```

# Expected Output

The beautified code should have looked like this:

A beautiful .csv file.

# Actual Output

The beautified code actually looked like this:

<img width="893" alt="screenshot 2018-05-24 16 21 20" src="https://user-images.githubusercontent.com/28852633/40496152-f8c39166-5f70-11e8-8b7d-78a7ba51c301.png">

# Steps to Reproduce

1. Add the csv file
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: [debug.md](https://gist.github.com/borisalmonacid/b89054f366c6152e9e5b1f7430e9a2c3)

**Another information**

Unsupported beautification result 'Year,Make,Model,1997,Ford,E350,2000,Mercury,Cougar'.
Unsupported beautification result 'Year,Make,Model,1997,Ford,E350,2000,Mercury,Cougar'.
Hide Stack Trace
Error: Unsupported beautification result 'Year,Make,Model,1997,Ford,E350,2000,Mercury,Cougar'.
    at beautifyCompleted (/Users/User/.atom/packages/atom-beautify/src/beautify.coffee:140:17)
    at tryCatcher (/Users/User/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/User/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/User/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/User/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/User/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/User/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/User/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/Users/User/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at <anonymous>

# Checklist

I have:
- [ x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by ccanaria** [comment]
Same issue here. Running Atom over Ubuntu.
