### ISSUE TITLE
Uncaught Error: Cannot find module 'fuzzaldrin'

### ISSUE THREAD

**Issue by nhanthien211** [Glavin001/atom-beautify#2155]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.2 x64
**Electron**: 1.7.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.32.5

### Stack Trace

Uncaught Error: Cannot find module 'fuzzaldrin'

```
At module.js:472

Error: Cannot find module 'fuzzaldrin'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.27.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.27.2/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.27.2/resources/app/src/native-compile-cache.js:66:33)
    at AutocompleteView.module.exports.SelectListView.populateList (/packages/atom-beautify/node_modules/atom-space-pen-views/lib/select-list-view.js:193:25)
    at AutocompleteView.module.exports.AutocompleteView.populateList (/packages/autocomplete/lib/autocomplete-view.coffee:336:54)
    at /packages/atom-beautify/node_modules/atom-space-pen-views/lib/select-list-view.js:350:26
```

### Commands

```
     -8:16.3.0 core:close (input.hidden-input)
     -8:07.7.0 core:save (input#toggleKeybindings.input-checkbox)
     -7:59 command-palette:toggle (input.hidden-input)
  3x -7:57 core:backspace (input.hidden-input)
     -7:55.7.0 core:move-down (input.hidden-input)
     -7:53.7.0 core:confirm (input.hidden-input)
     -7:53.7.0 atom-live-server:start-9000 (input.hidden-input)
  2x -1:14.7.0 tree-view:paste (div.header.list-item)
     -0:55.4.0 tree-view:show-current-file-in-file-manager (div.line)
     -0:45.4.0 command-palette:toggle (input.hidden-input)
 11x -0:42.9.0 core:backspace (input.hidden-input)
     -0:37 tree-view:show-current-file-in-file-manager (div.line)
     -0:21.4.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -0:21.3.0 editor:newline (input.hidden-input)
     -0:20.3.0 emmet:expand-abbreviation-with-tab (input.hidden-input)
     -0:19 autocomplete:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.32.5 
atom-live-server 2.3.0 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.1.3 
autocomplete-paths 2.12.2 
color-picker 2.3.0 
emmet 2.4.3 
file-icons 2.1.21 
pigments 0.40.2 
```

**Comment by szeck87** [comment]
@nhanthien211 Can you please try uninstalling and reinstalling atom beautify?
