### ISSUE TITLE
Docker missing/configuration errors when beautifying code

### ISSUE THREAD

**Issue by entropicdevelopment** [Glavin001/atom-beautify#2161]
# Description

Beautify will not run on Python source code. May also effect other languages but I only use Python at the moment.

# Input Before Beautification

This is what the code looked like before:

```
if __name__ == '__main__':
    valid_ids = []
    invalid_ids = []
    invalid_file = open('invalid_list','w')
    valid_file = open('valid_list','w')
    for i in range(100000,999999):
        url = 'https://support.apple.com/en-us/HT'+ str(i)
        print(url)
        page = requests.get(url)
        if page.status_code == requests.codes.ok:
            valid_pages.append(i)
            valid_file.write(str(i)+'\n')
        else:
            invalid_pages.append(i)
            invalid_file.write(str(i)+'\n')
    invalid_file.close()
    valid_file.close()
    print(valid_pages)
    print(invalid_pages)
```

# Expected Output

The beautified code should have looked like this:

```
if __name__ == '__main__':
    valid_ids = []
    invalid_ids = []
    invalid_file = open('invalid_list', 'w')
    valid_file = open('valid_list', 'w')
    for i in range(100000, 999999):
        url = 'https://support.apple.com/en-us/HT' + str(i)
        print(url)
        page = requests.get(url)
        if page.status_code == requests.codes.ok:
            valid_pages.append(i)
            valid_file.write(str(i) + '\n')
        else:
            invalid_pages.append(i)
            invalid_file.write(str(i) + '\n')
    invalid_file.close()
    valid_file.close()
    print(valid_pages)
    print(invalid_pages)
```

# Actual Output

The beautified code actually looked like this:

```
Code unchanged from input. Beautify did not run.
```

# Steps to Reproduce

1. Add code to Atom editor
2. Save file (Beautify on Save is on for Python) autopep8 also installed
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/twodox6/b7df5b34b70f7b5c4e21a2b6ce6738be

Other Notes: The issue presented itself after updating to the latest version.
Error from Atom:
Could not find 'docker'. The program may not be installed.
See docker installation instructions at https://github.com/Glavin001/atom-beautify#beautifiers or go to https://www.docker.com/get-docker
You can configure Atom Beautify with the absolute path to 'docker' by setting 'Executable - Docker - Path' in the Atom Beautify package settings.
Your program is properly installed if running 'which docker' in your Terminal returns an absolute path to the executable.
Hide Stack Trace
Error: Could not find 'docker'. The program may not be installed.
    at Function.Executable.commandNotFoundError (/home/andrew/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:277:10)
    at Executable.commandNotFoundError (/home/andrew/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:269:18)
    at /home/andrew/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:197:22
    at tryCatcher (/home/andrew/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/andrew/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/andrew/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/andrew/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/andrew/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/home/andrew/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/andrew/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/home/andrew/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

With Docker installed:
/usr/bin/docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?. See '/usr/bin/docker run --help'.
/usr/bin/docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See '/usr/bin/docker run --help'.
Hide Stack Trace
Error: /usr/bin/docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See '/usr/bin/docker run --help'.
    at /home/andrew/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:183:23
    at tryCatcher (/home/andrew/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/andrew/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/andrew/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/andrew/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/andrew/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/andrew/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/andrew/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/home/andrew/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues so I know this is not a duplicate issue.
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by twodox6** [comment]
Upon Googling the issue there seem to be related issues but they were posted prior to the update as far as I can tell.

**Comment by lilywang4** [comment]
I am seeing the same problem here.

**Comment by szeck87** [comment]
The actual error in @twodox6 case is:

`ModuleNotFoundError: No module named 'isort'`

The fact that it's displaying an error about Docker will be fixed with https://github.com/Glavin001/atom-beautify/issues/2146.

**Comment by AeternumStudios** [comment]
> See docker installation instructions at https://github.com/Glavin001/atom-beautify#beautifiers or go to https://www.docker.com/get-docker
You can configure Atom Beautify with the absolute path to 'docker' by setting 'Executable - Docker - Path' in the Atom Beautify package settings.
Your program is properly installed if running 'where.exe docker' in your CMD prompt returns an absolute path to the executable.
Hide Stack Trace
Error: Could not find 'docker'. The program may not be installed.
    at Function.Executable.commandNotFoundError (file:///C:/Users/avilt/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:277:10)
    at Executable.commandNotFoundError (file:///C:/Users/avilt/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:269:18)
    at file:///C:/Users/avilt/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:197:22
    at tryCatcher (C:\Users\avilt\.atom\packages\atom-beautify\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\avilt\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\avilt\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\avilt\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\avilt\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:689:18)
    at Async._drainQueue (C:\Users\avilt\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\avilt\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:143:10)
    at Async.drainQueues (C:\Users\avilt\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:17:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by AeternumStudios** [comment]
https://github.com/Glavin001/atom-beautify/issues/2161#issuecomment-399626034
That issue is closed however, and the actual problem is not fixed.

**Comment by Glavin001** [comment]
@entropicdevelopment Your Gist is showing 404.

@entropicdevelopment  @lilywang4 @AeternumStudios Please each provide `debug.md` Gists so we can help. Thanks!
