### ISSUE TITLE
Could not find 'C:\Users\sarcher\.atom\packages\atom-beautify\node_modules.bin\cljfmt'. The program may not be installed.

### ISSUE THREAD

**Issue by scarcher2** [Glavin001/atom-beautify#2167]
# Description

Could not find 'C:\Users\sarcher\.atom\packages\atom-beautify\node_modules.bin\cljfmt'. The program may not be installed.
```
See C:\Users\sarcher\.atom\packages\atom-beautify\node_modules\.bin\cljfmt installation instructions at https://github.com/Glavin001/atom-beautify#beautifiers or go to https://github.com/snoe/node-cljfmt
Your program is properly installed if running 'where.exe C:\Users\sarcher\.atom\packages\atom-beautify\node_modules\.bin\cljfmt' in your CMD prompt returns an absolute path to the executable.
Hide Stack Trace
Error: Could not find 'C:\Users\sarcher\.atom\packages\atom-beautify\node_modules\.bin\cljfmt'. The program may not be installed.
    at Function.Executable.commandNotFoundError (file:///C:/Users/sarcher/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:277:10)
    at HybridExecutable.Executable.commandNotFoundError (file:///C:/Users/sarcher/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:269:18)
    at file:///C:/Users/sarcher/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:197:22
    at tryCatcher (C:\Users\sarcher\.atom\packages\atom-beautify\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\sarcher\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\sarcher\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\sarcher\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\sarcher\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:689:18)
    at Async._drainQueue (C:\Users\sarcher\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\sarcher\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:143:10)
    at Async.drainQueues (C:\Users\sarcher\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:17:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

1. Install atom and Atom Beautify on Windows
2. Attempt to beautify clojure

It looks like path resolution of cljfmt is broken in 

```.atom/packages/atom-beautify/src/beautifiers/cljfmt/index.coffee```

if I replace 

```cljfmt = path.resolve(__dirname, "..", "..", "..", "node_modules/.bin/cljfmt")```
with
```cljfmt = "C:/Users/sarcher/.atom/packages/atom-beautify/node_modules/.bin/cljfmt.cmd"```

I can get past the error by changing the path, but then Atom crashes. 
This actually worked on one computer with 0.32.4, but it crashes under 0.32.5. 

The crash was due to the cljfmt.cmd not finding nodejs. 
I installed nodejs separately and can now run the plugin with my altered path.

**Comment by szeck87** [comment]
@scarcher2 can you please run the debug command?

> The crash was due to the cljfmt.cmd not finding nodejs. I installed nodejs separately and can now run the plugin with my altered path.

What do you mean by this?  Did you not have nodejs installed?

**Comment by scarcher2** [comment]
@szeck87 I did not have nodejs installed "separately" from Atom. I think the issue was nodejs was not on the path, and the cljfmt.cmd powershell script couldn't find nodejs to run, so I just installed nodejs (which put it on the path) and it resolved that part of the issue for me.

**Comment by szeck87** [comment]
OK, I'll have to play around with that.  I can't say I've ever tried using Atom without node installed.

**Comment by scarcher2** [comment]
This is still an issue.

**Comment by scarcher2** [comment]
I've provided all the information necessary, I'm sorry the close bot can't interpret the information provided as it doesn't fit the model supported by the bot, but it doesn't change the fact that this is indeed an issue and the description of the issue has been provided.

**Comment by alzadude** [comment]
Hi,

I'm also seeing this same issue. Windows 10 x64, Atom 1.30.0, atom-beautify 0.33.0

Please can this issue be re-opened and investigated?

Thanks!

**Comment by alzadude** [comment]
This worked for me (similar to above workaround, but without hard-coded path):

In
```
.atom/packages/atom-beautify/src/beautifiers/cljfmt/index.coffee
```
I replaced
```
cljfmt = path.resolve(__dirname, "..", "..", "..", "node_modules/.bin/cljfmt")
```
with
```
cljfmt = path.resolve(__dirname, "..", "..", "..", "node_modules/.bin/cljfmt.cmd")
```

And the error goes away, formatting works. Does it just need an `if windows ... else ...` check?

How is this working for the other formatters?
