### ISSUE TITLE
Docker version check broke on nightly docker build

### ISSUE THREAD

**Issue by robobenklein** [Glavin001/atom-beautify#2190]
# Description

Seems that it's just a `Docker` vs `docker` issue with the external call:

```
2018-07-30T21:05:38.441Z - debug: [] args 0=--version
2018-07-30T21:05:38.441Z - debug: [] relativized args 0=--version
2018-07-30T21:05:38.442Z - debug: [] spawnOptions cwd=/tmp, ATOM_HOME=/home/robo/.atom, NODE_PATH=/usr/share/atom/resources/app.asar/exports, NODE_ENV=production, J2SDKDIR=/usr/lib/jvm/java-10-oracle, USER=robo, TEXTDOMAIN=im-config, XDG_SEAT=seat0, SSH_AGENT_PID=3074, XDG_SESSION_TYPE=x11, J2REDIR=/usr/lib/jvm/java-10-oracle, SHLVL=0, QT4_IM_MODULE=xim, HOME=/home/robo, DESKTOP_SESSION=gnome, GTK_MODULES=gail:atk-bridge, DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus, MANDATORY_PATH=/usr/share/gconf/gnome.mandatory.path, IM_CONFIG_PHASE=2, LOGNAME=robo, GTK_IM_MODULE=ibus, DEFAULTS_PATH=/usr/share/gconf/gnome.default.path, USERNAME=robo, XDG_SESSION_ID=11, GNOME_DESKTOP_SESSION_ID=this-is-deprecated, WINDOWPATH=2, PATH=/home/robo/bin:/home/robo/.local/bin:/home/robo/.pythonz/bin:/home/robo/.zplugin/plugins/ogham---exa:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-10-oracle/bin:/usr/lib/jvm/java-10-oracle/db/bin:/home/robo/code/go/bin, DERBY_HOME=/usr/lib/jvm/java-10-oracle/db, SESSION_MANAGER=local/robo-unseptium:@/tmp/.ICE-unix/13113,unix/robo-unseptium:/tmp/.ICE-unix/13113, XDG_MENU_PREFIX=gnome-, XDG_RUNTIME_DIR=/run/user/1000, DISPLAY=:1, LANG=en_US.UTF-8, XDG_CURRENT_DESKTOP=GNOME, XDG_SESSION_DESKTOP=gnome, XMODIFIERS=@im=ibus, XAUTHORITY=/run/user/1000/gdm/Xauthority, SSH_AUTH_SOCK=/run/user/1000/keyring/ssh, SHELL=/bin/zsh, QT_ACCESSIBILITY=1, GDMSESSION=gnome, TEXTDOMAINDIR=/usr/share/locale/, GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1, XDG_VTNR=2, QT_IM_MODULE=ibus, JAVA_HOME=/usr/lib/jvm/java-10-oracle, PWD=/home/robo, CLUTTER_IM_MODULE=xim, XDG_DATA_DIRS=/usr/share/gnome:/usr/local/share:/usr/share:/var/lib/snapd/desktop, XDG_CONFIG_DIRS=/etc/xdg/xdg-gnome:/etc/xdg, GIO_LAUNCHED_DESKTOP_FILE=/usr/share/applications/atom.desktop, GIO_LAUNCHED_DESKTOP_FILE_PID=23426, GJS_DEBUG_OUTPUT=stderr, GJS_DEBUG_TOPICS=JS ERROR;JS LOG, GOOGLE_API_KEY=~~[REDACTED]~~, CHROME_DESKTOP=Atom.desktop, OLDPWD=/home/robo, ZSH_THEME=fishy, Z_LSBASE=exa, Z_LSARG_LONG=--long, Z_LSARG_ALL=-aa, Z_LSARG_HUMAN=--git, Z_LSARG_FORCE_COLOR=--color=always, ZPFX=/home/robo/.zplugin/polaris, MANPATH=:/home/robo/.zplugin/polaris/share/man, PAGER=less, LESS=-R, LC_CTYPE=en_US.UTF-8, FPATH=/home/robo/.zplugin/completions:/usr/local/share/zsh/site-functions:/usr/share/zsh/vendor-functions:/usr/share/zsh/vendor-completions:/usr/share/zsh/functions/Calendar:/usr/share/zsh/functions/Chpwd:/usr/share/zsh/functions/Completion:/usr/share/zsh/functions/Completion/AIX:/usr/share/zsh/functions/Completion/BSD:/usr/share/zsh/functions/Completion/Base:/usr/share/zsh/functions/Completion/Cygwin:/usr/share/zsh/functions/Completion/Darwin:/usr/share/zsh/functions/Completion/Debian:/usr/share/zsh/functions/Completion/Linux:/usr/share/zsh/functions/Completion/Mandriva:/usr/share/zsh/functions/Completion/Redhat:/usr/share/zsh/functions/Completion/Solaris:/usr/share/zsh/functions/Completion/Unix:/usr/share/zsh/functions/Completion/X:/usr/share/zsh/functions/Completion/Zsh:/usr/share/zsh/functions/Completion/openSUSE:/usr/share/zsh/functions/Exceptions:/usr/share/zsh/functions/MIME:/usr/share/zsh/functions/Math:/usr/share/zsh/functions/Misc:/usr/share/zsh/functions/Newuser:/usr/share/zsh/functions/Prompts:/usr/share/zsh/functions/TCP:/usr/share/zsh/functions/VCS_Info:/usr/share/zsh/functions/VCS_Info/Backends:/usr/share/zsh/functions/Zftp:/usr/share/zsh/functions/Zle:/home/robo/code/configs/zsh/fpath, LSCOLORS=Gxfxcxdxbxegedabagacad, LS_COLORS=, RTAB_PWD=~, GOPATH=/home/robo/code/go, Z_LSARG_DEFAULTS=-g, EDITOR=nvim, _=/usr/bin/env
2018-07-30T21:05:38.442Z - debug: [] spawn /usr/bin/docker 0=--version
2018-07-30T21:05:38.461Z - debug: [] spawn done -2  
2018-07-30T21:05:38.505Z - debug: [] spawn done 0  Docker version 0.0.0-20180727163649-46d3079, build 46d3079

2018-07-30T21:05:38.505Z - verbose: [] spawn result, returnCode 0
2018-07-30T21:05:38.505Z - verbose: [] spawn result, stdout Docker version 0.0.0-20180727163649-46d3079, build 46d3079

2018-07-30T21:05:38.505Z - verbose: [] spawn result, stderr 
2018-07-30T21:05:38.505Z - info: [] Version text: Docker version 0.0.0-20180727163649-46d3079, build 46d3079

2018-07-30T21:05:38.506Z - error: []  TypeError: Cannot read property 'slice' of null
    at Executable.parse [as versionParse] (/home/robo/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:384:94)
    at /home/robo/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:92:18
    at tryCatcher (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
2018-07-30T21:05:38.506Z - debug: []  Error: Could not find 'Docker'. The program may not be installed.
    at Function.Executable.commandNotFoundError (/home/robo/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:277:10)
    at Executable.commandNotFoundError (/home/robo/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:269:18)
    at /home/robo/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:115:25
    at tryCatcher (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
2018-07-30T21:05:38.506Z - debug: [beautifiers/beautifier.coffee] Error loading executables Error: Could not find 'Docker'. The program may not be installed.
    at Function.Executable.commandNotFoundError (/home/robo/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:277:10)
    at Executable.commandNotFoundError (/home/robo/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:269:18)
    at /home/robo/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:115:25
    at tryCatcher (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
2018-07-30T21:05:38.506Z - error: [beautifiers/index.coffee]  Error: Could not find 'Docker'. The program may not be installed.
    at Function.Executable.commandNotFoundError (/home/robo/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:277:10)
    at Executable.commandNotFoundError (/home/robo/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:269:18)
    at /home/robo/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:115:25
    at tryCatcher (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
2018-07-30T21:05:38.506Z - info: [beautifiers/index.coffee] Analytics is enabled.
```

# Steps to Reproduce

1. Add code to Atom editor that uses a docker beautifier engine
2. Run command `Atom Beautify: Beautify Editor`
3. Get this error:

```
See Docker installation instructions at https://github.com/Glavin001/atom-beautify#beautifiers or go to https://www.docker.com/get-docker
You can configure Atom Beautify with the absolute path to 'docker' by setting 'Executable - Docker - Path' in the Atom Beautify package settings.
Your program is properly installed if running 'which Docker' in your Terminal returns an absolute path to the executable.

Error: Could not find 'Docker'. The program may not be installed.
    at Function.Executable.commandNotFoundError (/home/robo/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:277:10)
    at Executable.commandNotFoundError (/home/robo/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:269:18)
    at /home/robo/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:115:25
    at tryCatcher (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/home/robo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/robobenklein/9e90c723f3634a89d590d3ed4b21e454

Also - just FYI having people upload these gists that also spit out envvars is a security risk and I think that should be addressed at some point. (E.x. API keys and IDs used for user tracking.)

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by szeck87** [comment]
It's trying to run beautysh, but fails:
```
2018-07-30T21:05:38.438Z - debug: [] error Error: spawn beautysh ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
2018-07-30T21:05:38.438Z - debug: [] error Error: spawn beautysh ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

It then looks for Docker with the regex `[version [0]*([1-9]\d*).[0]*([0-9]\d*).[0]*([0-9]\d*)](https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/executable.coffee#L384)`.  Since the version you have installed starts is 0.0.0, it doesn't match since the first needs to match a number between 1 and 9.

Where did you download Docker from?

**Comment by robobenklein** [comment]
```
Docker version 0.0.0-20180727163649-46d3079, build 46d3079
```
That's very bizarre...

My Docker source:
```
deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic nightly
# deb-src [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
```

I'll try the stable branch and see if that changes...

**Comment by robobenklein** [comment]
Just switched to `deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable` and it works as expected.

```
Docker version 18.06.0-ce, build 0ffa825
```

Did docker change the nightly versioning scheme?

**Comment by szeck87** [comment]
I'm not sure, I only use stable Mac.  Their docs aren't very clear on the version naming scheme, https://docs.docker.com/install/.

**Comment by Glavin001** [comment]
[Sounds like the solution is to use the stable version of Docker.](https://github.com/Glavin001/atom-beautify/issues/2190#issuecomment-409038239)

@robobenklein: I would accept a PR changing https://github.com/Glavin001/atom-beautify/blob/bb9428a4fa483fa6ffe958cdcb519b27e00cb770/src/beautifiers/executable.coffee#L384 to be more robust.

**Comment by Glavin001** [comment]
I'll leave this open as a `bug`, assuming someone else would like to contribute a fix to the `parse` function I referenced above.

**Comment by robobenklein** [comment]
For more information on this, it's specifically because the nightly builds are being tagged with versions composed of `0.0.0-DATE-HASH` instead of positive versioning.

Just checked the bionic nightly of today:

```
Docker version 0.0.0-20180926205650-117ee8c, build 117ee8c
```

**Comment by Glavin001** [comment]
Once again, we are accepting PRs to fix this: https://github.com/Glavin001/atom-beautify/issues/2190#issuecomment-425608736 👍
