### ISSUE TITLE
SQL: UnicodeEncodeError: 'ascii' codec can't encode character u'\xd6'

### ISSUE THREAD

**Issue by JamborJan** [Glavin001/atom-beautify#2197]
# Description

The results of beautification are not what I expect.

# Input Before Beautification

This is what the code looked like before: [debug.md Gist](https://gist.github.com/JamborJan/f803054d666bcaaef2b207dcda4153e3#original-file-contents) 

# Expected Output

The code should be nicely displayed.

# Actual Output

Nothing happens. An error is displayed.

![bildschirmfoto 2018-08-07 um 10 10 03](https://user-images.githubusercontent.com/7508960/43763080-0ee8951a-9a2a-11e8-8879-337ed4359119.png)

```
Traceback (most recent call last):
  File "/usr/local/bin/sqlformat", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/sqlparse/cli.py", line 180, in main
    stream.write(s)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xd6' in position 479: ordinal not in range(128)
Hide Stack Trace
Error: Traceback (most recent call last):
  File "/usr/local/bin/sqlformat", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/sqlparse/cli.py", line 180, in main
    stream.write(s)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xd6' in position 479: ordinal not in range(128)
    at /Users/jj/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:183:23
    at tryCatcher (/Users/jj/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jj/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/jj/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/jj/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/jj/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/jj/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/jj/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/Users/jj/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. The mentioned error occurs

# Debug

Here is a link to the `debug.md` Gist: [debug.md Gist](https://gist.github.com/JamborJan/f803054d666bcaaef2b207dcda4153e3) to this issue

# Checklist

I have:
- [X] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [X] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [X] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [X] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [X] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for [debug.md Gist](https://gist.github.com/JamborJan/f803054d666bcaaef2b207dcda4153e3) to this issue

**Comment by szeck87** [comment]
@Glavin001 Not sure on this one, something happens with Node's spawn process, it works from the terminal without a problem.  Ideas?

**Comment by szeck87** [comment]
Yea this is weird, it works from the terminal/command line on both the original file and the temp file it generates.  So guessing it's an issue with Node's spawn.

**Comment by JamborJan** [comment]
Thanks for checking the issue in detail @szeck87. I did uninstall all 3rd party Python 2.x versions from my Mac. Only the build in version 2.7 from Apple is still there (and as far as I know this one should not be removed).

After that I installed python3 with Homebrew.

But still: Atom uses the 2.7 python. Do you have any idea how I can change that?

Thanks again.

**Comment by szeck87** [comment]
I'm not sure, I tried using pyenv but it still used Mac's built-in Python version when using `pip install`.  Installing sqlparse via Homebrew automatically uses python 2.x as that's apart of the keg.

I don't even know for sure if using Python 3.x will help or not.  You could download Docker and use the sqlformat image.  Otherwise I need more time to try and figure out where it's going wrong.  Coffeescript debugging isn't easy.

**Comment by JamborJan** [comment]
That is still an issue. Nothing changed so far. Please let me know if I can help to debug this.
