### ISSUE TITLE
Uncaught TypeError: Beautifier is not a constructor

### ISSUE THREAD

**Issue by igor-viblyy** [Glavin001/atom-beautify#2200]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.29.0 x64
**Electron**: 2.0.5
**OS**: Linux Mint
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.33.0

### Stack Trace

Uncaught TypeError: Beautifier is not a constructor

```
At /home/igor-laptop/.atom/packages/atom-beautify/src/beautifiers/index.coffee:119

TypeError: Beautifier is not a constructor
    at /packages/atom-beautify/src/beautifiers/index.coffee:119:7
    at arrayMap (/packages/atom-beautify/node_modules/lodash/lodash.js:639:23)
    at Function.map (/packages/atom-beautify/node_modules/lodash/lodash.js:9554:14)
    at /packages/atom-beautify/src/beautifiers/index.coffee:117:22)
    at /packages/atom-beautify/src/beautify.coffee:10:18)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .coffee] (/usr/share/atom/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:96:26)
    at Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:782:33)
    at Package.activateConfig (/usr/share/atom/resources/app/src/package.js:267:16)
    at PackageManager.module.exports.PackageManager.packageHasSettings (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:68:20)
    at PackageCard.hasSettings (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:794:40)
    at PackageCard.updateSettingsState (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:439:22)
    at PackageCard.updateInterfaceState (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:431:18)
    at new PackageCard (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:92:16)
    at PackageDetailView.completeInitialization (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-detail-view.js:206:34)
    at PackageDetailView.loadPackage (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-detail-view.js:225:20)
    at new PackageDetailView (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-detail-view.js:100:16)
    at callback (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:366:26)
    at SettingsView.getOrCreatePanel (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:371:25)
    at SettingsView.showPanel (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:429:30)
    at SettingsView.showDeferredPanel (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:416:20)
    at SettingsView.initializePanels (/usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:250:18)
    at /usr/share/atom/resources/app/node_modules/settings-view/lib/settings-view.js:122:26
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.0 
atom-clock 0.1.16 
atom-html-preview 0.2.5 
atom-ide-ui 0.13.0 
atom-shell-commands 1.5.0 
autocomplete-elixir 1.5.16 
autocomplete-ruby 0.2.8 
block-cursor 0.13.3 
browser-plus 0.0.98 
busy-signal 1.4.3 
data-atom 0.29.0 
emberjs-atom 0.10.0 
emmet 2.4.3 
file-icons 2.1.22 
fonts 3.1.0 
gitkraken-glo 1.0.1 
gitlab 0.1.3-7 
hey-pane 1.1.0 
ide-css 0.3.0 
ide-json 0.2.1 
ide-vue 0.1.9 
intentions 1.1.5 
language-elixir 0.22.0 
language-ember-htmlbars 0.4.0 
language-haml 0.31.1 
language-rspec 0.11.0 
language-slim 1.0.0 
language-vue 0.23.1 
linter 2.2.0 
linter-elixirc 1.7.0 
linter-rails-best-practices 0.2.2 
linter-rubocop 2.2.3 
linter-ruby 1.2.6 
linter-slim 1.0.0 
linter-ui-default 1.7.1 
merge-conflicts 1.4.5 
pdf-view 0.70.0 
pigments 0.40.2 
platformio-ide-terminal 2.8.3 
project-manager 3.3.6 
rails-atom-schema 1.1.1 
rails-rspec 0.3.2 
rest-client 1.3.1 
rspec 0.4.0 
ruby-block 0.3.6 
ruby-navigator 0.5.0 
ruby-slim 0.2.0 
ruby-test-switcher 1.2.3 
spacegray-atom-dark-syntax 1.3.2 
teletype 0.13.3 
tree-view-autoresize 2.3.0 
wakatime 7.0.4 
```

**Comment by jkroes** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.33.4


### Stack Trace

Uncaught TypeError: Beautifier is not a constructor

```
At C:\Users\jkroes\.atom\packages\atom-beautify\src\beautifiers\index.coffee:121

TypeError: Beautifier is not a constructor
    at /packages/atom-beautify/src/beautifiers/index.coffee:121:7
    at arrayMap (/packages/atom-beautify/node_modules/lodash/lodash.js:639:23)
    at Function.map (/packages/atom-beautify/node_modules/lodash/lodash.js:9556:14)
    at /packages/atom-beautify/src/beautifiers/index.coffee:119:22)
    at /packages/atom-beautify/src/beautify.coffee:10:14)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:146385)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:1:623185)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:3044548)
    at Package.activateConfig (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:3033907)
    at PackageManager.t.exports.PackageManager.packageHasSettings (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:907432)
    at PackageCard.hasSettings (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:14:2945211)
    at PackageCard.updateSettingsState (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:14:2935491)
    at PackageCard.updateInterfaceState (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:14:2935314)
    at new PackageCard (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:14:2927099)
    at PackageDetailView.completeInitialization (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:14:729142)
    at PackageDetailView.loadPackage (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:14:729709)
    at new PackageDetailView (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:14:726427)
    at s (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:929020)
    at SettingsView.getOrCreatePanel (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:929088)
    at SettingsView.showPanel (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:929856)
    at SettingsView.showDeferredPanel (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:929780)
    at SettingsView.initializePanels (~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:927036)
    at ~/AppData/Local/atom/app-1.32.2/resources/app/static/<embedded>:11:924280
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ide-debugger-python 0.7.3 
atom-ide-ui 0.13.0 
atom-material-ui 2.1.3 
atom-runner 2.7.1 
autocomplete-python 1.11.0 
cursor-history 0.13.1 
Hydrogen 2.6.0 
ide-css 0.3.0 
ide-json 0.2.1 
ide-powershell 0.1.0 
ide-python 1.0.0 
ide-r 0.1.8 
language-powershell 5.0.0 
language-sas 0.2.4 
scroll-through-time 0.3.0 
sync-settings 0.8.6 
terminal-tab-service 0.1.4 
```

**Comment by Glavin001** [comment]
I've seen reinstalling and/or restarting Atom helps. See https://github.com/Glavin001/atom-beautify/issues/952#issuecomment-214869463 for one example. Let me know how that goes.

Duplicate of https://github.com/Glavin001/atom-beautify/issues/2269
