### ISSUE TITLE
Uncaught TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by andyday** [Glavin001/atom-beautify#221]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.182.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.21.3

### Stack Trace

Uncaught TypeError: Cannot read property 'data' of undefined

```
At C:\Users\Andy\.atom\packages\atom-beautify\node_modules\atom-message-panel\lib\MessagePanelView.js:206

TypeError: Cannot read property 'data' of undefined
  at [object Object].MessagePanelView.resizeStopped (C:\Users\Andy\.atom\packages\atom-beautify\node_modules\atom-message-panel\lib\MessagePanelView.js:206:6)
  at [object Object].MessagePanelView.close (C:\Users\Andy\.atom\packages\atom-beautify\node_modules\atom-message-panel\lib\MessagePanelView.js:108:12)
  at HTMLDivElement.<anonymous> (C:\Users\Andy\.atom\packages\atom-beautify\node_modules\space-pen\lib\space-pen.js:214:36)
  at HTMLDivElement.jQuery.event.dispatch (C:\Users\Andy\.atom\packages\atom-beautify\node_modules\space-pen\vendor\jquery.js:4676:9)
  at HTMLDivElement.elemData.handle (C:\Users\Andy\.atom\packages\atom-beautify\node_modules\space-pen\vendor\jquery.js:4360:46)

```

### Commands

```
 15x -0:43.9 core:move-right (atom-text-editor.editor)
     -0:41.6 core:backspace (atom-text-editor.editor)
     -0:41.0 core:move-up (atom-text-editor.editor)
     -0:40.7 core:move-right (atom-text-editor.editor)
     -0:40.3 core:backspace (atom-text-editor.editor)
     -0:39.5 core:save (atom-text-editor.editor)
     -0:32.3 fuzzy-finder:toggle-file-finder (div.am-panel.tool-panel.panel-bottom.native-key-bindings)
 16x -0:25.1 core:backspace (atom-text-editor.editor.mini)
 23x -0:19.9 core:move-down (atom-text-editor.editor.mini)
     -0:17.8 core:move-up (atom-text-editor.editor.mini)
  8x -0:17.3 core:backspace (atom-text-editor.editor.mini)
     -0:12.5 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:12.5 core:cancel (atom-text-editor.editor.mini)
     -0:11.1 command-palette:toggle (div.am-panel.tool-panel.panel-bottom.native-key-bindings)
     -0:08.0 core:confirm (atom-text-editor.editor.mini)
     -0:08.0 jsonlint:lint (div.am-panel.tool-panel.panel-bottom.native-key-bindings)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "view-tail-large-files"
    ]
  },
  "atom-beautify": {
    "_analyticsUserId": "87ec0f53-9f87-4f96-8ffe-28ddf1ae0132"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.21.3
jsonlint, v1.0.1
language-csharp, v0.5.0
save-session, v0.11.5

# Dev
No dev packages
```

**Comment by Glavin001** [comment]
Can you please provide some steps to reproduce? Such as your file contents before beautifying.

**Comment by andyday** [comment]
Don't recall the steps I took...  If I see it again, I'll open a new issue...
