### ISSUE TITLE
Could not find 'php'. The program may not be installed.

### ISSUE THREAD

**Issue by DokolkoMax** [Glavin001/atom-beautify#2230]
See php installation instructions at https://github.com/Glavin001/atom-beautify#beautifiers or go to http://php.net/manual/en/install.php
You can configure Atom Beautify with the absolute path to 'php' by setting 'Executable - PHP - Path' in the Atom Beautify package settings.
Your program is properly installed if running 'where.exe php' in your CMD prompt returns an absolute path to the executable.

Error: Could not find 'php'. The program may not be installed.
    at Function.Executable.commandNotFoundError (file:///C:/Users/Dokolko-pc/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:277:10)
    at HybridExecutable.Executable.commandNotFoundError (file:///C:/Users/Dokolko-pc/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:269:18)
    at file:///C:/Users/Dokolko-pc/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:197:22
    at tryCatcher (C:\Users\Dokolko-pc\.atom\packages\atom-beautify\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Dokolko-pc\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\Dokolko-pc\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\Dokolko-pc\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\Dokolko-pc\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:690:18)
    at _drainQueueStep (C:\Users\Dokolko-pc\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (C:\Users\Dokolko-pc\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\Users\Dokolko-pc\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:147:5)
    at Async.drainQueues (C:\Users\Dokolko-pc\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:17:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

I have 0.33.1 version installed

**Comment by szeck87** [comment]
You need to have php installed and the path set in Atom Beautify's settings.  `Settings > Executables > PHP > Path`
