### ISSUE TITLE
Problem installing version 0.33.2

### ISSUE THREAD

**Issue by stojsavljevic** [Glavin001/atom-beautify#2236]
# Description

Problem installing version `0.33.2`

# Input Before Beautification

This is what the code looked like before:

```
N/A
```

# Expected Output

The beautified code should have looked like this:

```
N/A
```

# Actual Output

The beautified code actually looked like this:

```
N/A
```

# Steps to Reproduce

1. Start Atom editor (Windows 7, Atom `1.30.0` x64)
2. Go to _Settings_ - _Updates_ - _Check for Updates_
3. Press _Update to 0.33.2_ (for _atom-beautify_)
4. Error happens:
```
Updating to “atom-beautify@0.33.2” failed.Hide output…

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Tools\\Atom\\resources\\app\\apm\\bin\\node.exe" "D:\\Tools\\Atom\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\aleksandars\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\aleksandars\\.atom\\.apmrc" "install" "D:\\Tools\\Temp\\d-118827-11448-r290q8.zgylrqkt9\\package.tgz" "--runtime=electron" "--target=2.0.5" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10

npm ERR! tar.Extract is not a function
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Tools\Temp\apm-install-dir-118827-11448-1jgf3ht.mkv6l84cxr\npm-debug.log
```
I tried to reinstall `atom-beautify` but I couldn't install it again - tried both through UI and using `apm`. I couldn't even install `0.33.1`. I'm getting the same error.

# Debug

Here is a link to the `debug.md` Gist:

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by stevenzeck** [comment]
Which version of Atom are you using?

**Comment by stojsavljevic** [comment]
Windows 7, Atom `1.30.0` x64

**Comment by stevenzeck** [comment]
Does it have the same error when running `apm install atom-beautify`?

**Comment by stojsavljevic** [comment]
Yes, the same error.

**Comment by stevenzeck** [comment]
@stojsavljevic @yoann1103  Can you also upload the npm-debug.log mentioned in the error as a gist?  Feel free to find/replace any personal info that might be in there beforehand.

**Comment by kucits** [comment]
Same - update fails.

**Comment by stevenzeck** [comment]
@kucits please share the npm-debug log mentioned in the error.

**Comment by stojsavljevic** [comment]
I tried to reinstall `atom-beautify` but after I uninstalled it I couldn't install it again.
Here is the error I'm getting on installation:
```
commitCommentView_item.graphql.js:112 
Installing package atom-beautify failed Error: Installing “atom-beautify@0.33.4” failed.
    at D:\Tools\Atom\resources\app\node_modules\settings-view\lib\package-manager.js:503:27
    at exit (D:\Tools\Atom\resources\app\node_modules\settings-view\lib\package-manager.js:128:22)
    at triggerExitCallback (D:\Tools\Atom\resources\app\src\buffered-process.js:267:15)
    at ChildProcess.process.on (D:\Tools\Atom\resources\app\src\buffered-process.js:297:15)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12) 
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\Tools\\Atom\\resources\\app\\apm\\bin\\node.exe" "D:\\Tools\\Atom\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\aleksandars\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\aleksandars\\.atom\\.apmrc" "install" "D:\\Tools\\Temp\\d-11891-6116-13rpi5a.axtq2dquxr\\package.tgz" "--runtime=electron" "--target=2.0.5" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10

npm ERR! tar.Extract is not a function
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Tools\Temp\apm-install-dir-11891-6116-1eei1wa.2j7ix80k9\npm-debug.log
```

**Comment by stojsavljevic** [comment]
I resolved the issue by removing `.atom` folder from users folder :/

**Comment by stevenzeck** [comment]
Thanks @stojsavljevic. @kucits @yoann1103 please try doing that if you still have issues installing/updating.
