### ISSUE TITLE
Cannot Find Module 'editorconfig'

### ISSUE THREAD

**Issue by yapdan** [Glavin001/atom-beautify#2245]
# Description

Getting an error on all attempts to beatify. Below is just a simple css example. I get the error 
"Cannot find module 'editorconfig' " below is the stack trace. Not sure what I need to be doing? Just installed atom and this package today on a new PC. I've yet to run into this issue on my Mac and other PC with Atom and the same packages.

```
Error: Cannot find module 'editorconfig'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (C:\Users\dkmya\AppData\Local\atom\app-1.31.2\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (C:\Users\dkmya\AppData\Local\atom\app-1.31.2\resources\app\src\module-cache.js:354:58)
    at Module.require (file:///C:/Users/dkmya/AppData/Local/atom/app-1.31.2/resources/app.asar/static/index.js:40:43)
    at require (C:\Users\dkmya\AppData\Local\atom\app-1.31.2\resources\app\src\native-compile-cache.js:66:33)
    at Beautifiers.module.exports.Beautifiers.getOptionsForPath (file:///C:/Users/dkmya/.atom/packages/atom-beautify/src/beautifiers/index.coffee:589:23)
    at file:///C:/Users/dkmya/.atom/packages/atom-beautify/src/beautify.coffee:166:29
    at Promise._execute (C:\Users\dkmya\.atom\packages\atom-beautify\node_modules\bluebird\js\release\debuggability.js:313:9)
    at Promise._resolveFromExecutor (C:\Users\dkmya\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (C:\Users\dkmya\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:79:10)
    at beautify (file:///C:/Users/dkmya/.atom/packages/atom-beautify/src/beautify.coffee:77:10)
    at beautifyOnSaveHandler (file:///C:/Users/dkmya/.atom/packages/atom-beautify/src/beautify.coffee:536:9)
    at file:///C:/Users/dkmya/.atom/packages/atom-beautify/src/beautify.coffee:544:7
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\dkmya\AppData\Local\atom\app-1.31.2\resources\app\node_modules\event-kit\lib\emitter.js:27:20)
    at Emitter.<anonymous> (C:\Users\dkmya\AppData\Local\atom\app-1.31.2\resources\app\node_modules\event-kit\lib\emitter.js:169:50)
    at Emitter.module.exports.Emitter.emitAsync (C:\Users\dkmya\AppData\Local\atom\app-1.31.2\resources\app\node_modules\event-kit\lib\emitter.js:172:18)
    at C:\Users\dkmya\AppData\Local\atom\app-1.31.2\resources\app\node_modules\text-buffer\lib\text-buffer.js:1349:38
    at <anonymous>
```

# Input Before Beautification

This is what the code looked like before:

```
body {
  background: red ;


}
```

# Expected Output

The beautified code should have looked like this:

```
body {
  background: red;
}
```

# Actual Output

The beautified code actually looked like this:

Did not beautify

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by yapdan** [comment]
Uninstalled and reinstalled atom beautify today for the 6th time since 2 days ago via apm. All seems to be working now!
