### ISSUE TITLE
Failed to activate the atom-beautify package

### ISSUE THREAD

**Issue by Cerbur** [Glavin001/atom-beautify#2286]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.33.1 x64
**Electron**: 2.0.16
**OS**: Unknown Windows version
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.33.4

### Stack Trace

Failed to activate the atom-beautify package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.33.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:154667)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:145974)
    at /packages/atom-beautify/src/beautify.coffee:7:25)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:146684)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:1:639369)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:3041061)
    at Package.activateNow (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:3029195)
    at string.e.trim.length.activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:14:2445)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:1190759)
    at Emitter.emit (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:1192200)
    at PackageManager.triggerDeferredActivationHooks (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:383101)
    at Promise.all.then (~/AppData/Local/atom/app-1.33.1/resources/app/static/<embedded>:11:381899)
    at <anonymous>
```

### Commands

```
  9x -0:30.6.0 atom-beautify:beautify-editor (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-runner 2.7.1 
chinese-translator 1.1.2 
gcc-make-run 0.2.12 
GobbieGobGoo 1.0.4 
linter-gcc 0.7.1 
simplified-chinese-menu 5.3.5 
```

**Comment by clockelliptic** [comment]
Just installed Atom for the first time. Also experiencing this issue.

**Comment by kushal-jain-eronkan** [comment]
Facing similar issue

OS: Windows 7
Atom Version: 1.33.1 x64

Stack trace:-

Error: Cannot find module './compile'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:154667)
    at Module.require (file:///C:/Users/Admin/AppData/Local/atom/app-1.33.1/resources/app.asar/static/index.js:40:43)
    at require (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:145974)
    at Object.<anonymous> (C:\Users\Admin\.atom\packages\atom-beautify\node_modules\har-validator\node_modules\ajv\lib\ajv.js:3:21)
    at Object.<anonymous> (C:\Users\Admin\.atom\packages\atom-beautify\node_modules\har-validator\node_modules\ajv\lib\ajv.js:498:3)
    at Module.get_Module._compile (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:146684)
    at Object.value [as .js] (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///C:/Users/Admin/AppData/Local/atom/app-1.33.1/resources/app.asar/static/index.js:47:45)
    at require (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:145974)
    at Object.<anonymous> (C:\Users\Admin\.atom\packages\atom-beautify\node_modules\har-validator\lib\promise.js:1:166)
    at Object.<anonymous> (C:\Users\Admin\.atom\packages\atom-beautify\node_modules\har-validator\lib\promise.js:104:3)
    at Module.get_Module._compile (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:146684)
    at Object.value [as .js] (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///C:/Users/Admin/AppData/Local/atom/app-1.33.1/resources/app.asar/static/index.js:47:45)
    at require (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:145974)
    at Object.<anonymous> (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app.asar\node_modules\request\lib\har.js:5:16)
    at Object.<anonymous> (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app.asar\node_modules\request\lib\har.js:207:3)
    at Module.get_Module._compile (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:146684)
    at Object.value [as .js] (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///C:/Users/Admin/AppData/Local/atom/app-1.33.1/resources/app.asar/static/index.js:47:45)
    at require (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:145974)
    at Object.<anonymous> (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app.asar\node_modules\request\request.js:23:11)
    at Object.<anonymous> (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app.asar\node_modules\request\request.js:1553:3)
    at Module.get_Module._compile (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:146684)
    at Object.value [as .js] (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///C:/Users/Admin/AppData/Local/atom/app-1.33.1/resources/app.asar/static/index.js:47:45)
    at require (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:145974)
    at Object.<anonymous> (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app.asar\node_modules\request\index.js:143:19)
    at Object.<anonymous> (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app.asar\node_modules\request\index.js:157:3)
    at Module.get_Module._compile (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:146684)
    at Object.value [as .js] (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///C:/Users/Admin/AppData/Local/atom/app-1.33.1/resources/app.asar/static/index.js:47:45)
    at require (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:145974)
    at Object.<anonymous> (C:\Users\Admin\.atom\packages\atom-beautify\node_modules\universal-analytics\lib\index.js:2:15)
    at Object.<anonymous> (C:\Users\Admin\.atom\packages\atom-beautify\node_modules\universal-analytics\lib\index.js:565:3)
    at Module.get_Module._compile (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:146684)
    at Object.value [as .js] (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///C:/Users/Admin/AppData/Local/atom/app-1.33.1/resources/app.asar/static/index.js:47:45)
    at require (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:145974)
    at Object.<anonymous> (C:\Users\Admin\.atom\packages\atom-beautify\node_modules\universal-analytics\index.js:2:18)
    at Object.<anonymous> (C:\Users\Admin\.atom\packages\atom-beautify\node_modules\universal-analytics\index.js:4:3)
    at Module.get_Module._compile (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:146684)
    at Object.value [as .js] (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///C:/Users/Admin/AppData/Local/atom/app-1.33.1/resources/app.asar/static/index.js:47:45)
    at require (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:145974)
    at file:///C:/Users/Admin/.atom/packages/atom-beautify/src/beautifiers/index.coffee:20:8
    at exports.allowUnsafeEval (C:\Users\Admin\.atom\packages\atom-ternjs\node_modules\loophole\lib\loophole.js:14:14)
    at Object.<anonymous> (file:///C:/Users/Admin/.atom/packages/atom-beautify/src/beautifiers/index.coffee:19:1)
    at Object.<anonymous> (file:///C:/Users/Admin/.atom/packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at Object.<anonymous> (file:///C:/Users/Admin/.atom/packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at Module.get_Module._compile (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:146684)
    at Object.value [as .coffee] (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///C:/Users/Admin/AppData/Local/atom/app-1.33.1/resources/app.asar/static/index.js:47:45)
    at require (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:145974)
    at Object.<anonymous> (file:///C:/Users/Admin/.atom/packages/atom-beautify/src/beautify.coffee:9:15)
    at Object.<anonymous> (file:///C:/Users/Admin/.atom/packages/atom-beautify/src/beautify.coffee:2:1)
    at Object.<anonymous> (file:///C:/Users/Admin/.atom/packages/atom-beautify/src/beautify.coffee:2:1)
    at Module.get_Module._compile (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:146684)
    at Object.value [as .coffee] (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (file:///C:/Users/Admin/AppData/Local/atom/app-1.33.1/resources/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:1:639369)
    at Package.requireMainModule (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:3041061)
    at Package.activateNow (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:3029195)
    at string.e.trim.length.activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:14:2445)
    at Function.simpleDispatch (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:1190759)
    at Emitter.emit (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:1192200)
    at deferredActivationHooks.triggeredActivationHooks.forEach.e (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:382947)
    at Set.forEach (<anonymous>)
    at PackageManager.activatePackage (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:382909)
    at C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:917626
    at r (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:11:912232)
    at o (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:14:1037419)
    at ChildProcess.n.process.on.e (C:\Users\Admin\AppData\Local\atom\app-1.33.1\resources\app\static\<embedded>:14:1037625)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)

**Comment by clayreiche** [comment]
> Just installed Atom for the first time. Also experiencing this issue.

Same
