### ISSUE TITLE
Failed to activate the atom-beautify package - compile issue

### ISSUE THREAD

**Issue by justwes** [Glavin001/atom-beautify#2297]
[Enter steps to reproduce:]

1. Installing beautify
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.33.4

### Stack Trace

Failed to activate the atom-beautify package

```
At Cannot find module './compile'

Error: Cannot find module './compile'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.34.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:154667)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:145974)
    at /packages/atom-beautify/node_modules/har-validator/node_modules/ajv/lib/ajv.js:3:21)
    at /packages/atom-beautify/node_modules/har-validator/node_modules/ajv/lib/ajv.js:498:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:145974)
    at /packages/atom-beautify/node_modules/har-validator/lib/promise.js:1:166)
    at /packages/atom-beautify/node_modules/har-validator/lib/promise.js:104:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:145974)
    at /packages/atom-beautify/node_modules/request/lib/har.js:5:16)
    at /packages/atom-beautify/node_modules/request/lib/har.js:207:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:145974)
    at /packages/atom-beautify/node_modules/request/request.js:23:11)
    at /packages/atom-beautify/node_modules/request/request.js:1553:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:145974)
    at /packages/atom-beautify/node_modules/request/index.js:143:19)
    at /packages/atom-beautify/node_modules/request/index.js:157:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:145974)
    at /packages/atom-beautify/node_modules/universal-analytics/lib/index.js:2:15)
    at /packages/atom-beautify/node_modules/universal-analytics/lib/index.js:565:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:145974)
    at /packages/atom-beautify/node_modules/universal-analytics/index.js:2:18)
    at /packages/atom-beautify/node_modules/universal-analytics/index.js:4:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:145974)
    at /packages/atom-beautify/src/beautifiers/index.coffee:20:8
    at exports.allowUnsafeEval (/packages/atom-beautify/node_modules/loophole/lib/loophole.js:14:14)
    at /packages/atom-beautify/src/beautifiers/index.coffee:19:1)
    at /packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at /packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:145974)
    at /packages/atom-beautify/src/beautify.coffee:9:15)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:146684)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:1:641362)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3029314)
    at Package.activateNow (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3017448)
    at string.e.trim.length.activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:2445)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:1172318)
    at Emitter.emit (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:1173759)
    at PackageManager.triggerDeferredActivationHooks (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:383087)
    at Promise.all.then (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:381885)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
compare-files 0.8.1 
markdown-preview-plus 3.7.1 
markdown-writer 2.11.3 
```

**Comment by Glavin001** [comment]
Please try reinstalling Atom-Beautify:

```bash
apm install atom-beautify
```

**Comment by Erinasoa1213** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.33.4


### Stack Trace

Failed to activate the atom-beautify package

```
At Invalid or unexpected token

SyntaxError: Invalid or unexpected token
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:146461)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:150231)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:1:641362)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3029314)
    at Package.activateNow (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:3017448)
    at string.e.trim.length.activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:2445)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:1172318)
    at Emitter.emit (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:1173759)
    at deferredActivationHooks.triggeredActivationHooks.forEach.e (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:382933)
    at Set.forEach (<anonymous>)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:382895)
    at ~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:899185
    at r (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:11:893791)
    at o (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:1032547)
    at ChildProcess.n.process.on.e (~/AppData/Local/atom/app-1.34.0/resources/app/static/<embedded>:14:1032753)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ternjs 0.18.3 
autoclose-html 0.23.0 
busy-signal 2.0.0 
csslint 1.2.0 
emmet 2.4.3 
intentions 1.1.5 
language-ejs 0.4.0 
linter 2.3.0 
linter-eslint 8.5.2 
linter-jshint 3.1.14 
linter-ui-default 1.7.1 
pigments 0.40.2 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by LukeNecklace** [comment]
Hello.

I am also experiencing this issue. Does anyone have any solutions for this issue?

**Comment by M1CK431** [comment]
Hi,

This issue come from prettier. You can workaround it by replacing line 40747 in file `~/.atom/packages/atom-beautify/node_modules/prettier/index.js` with:
```javascript
  var utilInspect = require('util').inspect;
```

An issue is already open at Prettier side here: https://github.com/prettier/prettier/issues/6053
