### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by iamkylescode** [Glavin001/atom-beautify#2327]
Expected Results

atom-beautify should install without error.

Actual Output
```

Installing “atom-beautify@0.33.4” failed.

npm ERR! Unexpected end of JSON input while parsing near '...LCuUW75t6FgEfElf\nLu8'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kmcdowell\.atom\.apm\_logs\2019-03-07T15_40_23_193Z-debug.log
```
complete log:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Users\\km\\AppData\\Local\\atom\\app-1.34.0\\resources\\app\\apm\\bin\\node.exe',
1 verbose cli   'C:\\Users\\km\\AppData\\Local\\atom\\app-1.34.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   'C:\\Users\\km\\.atom\\.apm\\.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   'C:\\Users\\km\\.atom\\.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/atom-beautify/versions/0.33.4/tarball',
1 verbose cli   '--runtime=electron',
1 verbose cli   '--target=2.0.16',
1 verbose cli   '--dist-url=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style',
1 verbose cli   '--msvs_version=2015' ]
2 info using npm@6.2.0
3 info using node@v8.9.3
4 verbose npm-session d9d7b06b9eea7677
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://www.atom.io/api/packages/atom-beautify/versions/0.33.4/tarball 866ms
8 silly pacote remote manifest for undefined@https://www.atom.io/api/packages/atom-beautify/versions/0.33.4/tarball fetched in 927ms
9 timing stage:loadCurrentTree Completed in 1518ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule atom-beautify@0.33.4 checking installable status
17 http fetch GET 200 https://registry.npmjs.org/atom-space-pen-views 189ms
18 http fetch GET 200 https://registry.npmjs.org/csscomb 190ms
19 http fetch GET 200 https://registry.npmjs.org/coffeescript 196ms
20 http fetch GET 200 https://registry.npmjs.org/atom-message-panel 199ms
21 http fetch GET 200 https://registry.npmjs.org/align-yaml 203ms
22 http fetch GET 200 https://registry.npmjs.org/coffee-fmt 202ms
23 http fetch GET 200 https://registry.npmjs.org/coffee-formatter 211ms
24 http fetch GET 200 https://registry.npmjs.org/bluebird 213ms
25 silly fetchPackageMetaData error for bluebird@^3.5.1 Unexpected end of JSON input while parsing near '...nt":"~0.6.4","grunt-c'
26 http fetch GET 200 https://registry.npmjs.org/diff 208ms
27 silly pacote range manifest for csscomb@^4.2.0 fetched in 236ms
28 silly resolveWithNewModule csscomb@4.2.0 checking installable status
29 silly pacote range manifest for atom-space-pen-views@^2.2.0 fetched in 242ms
30 silly resolveWithNewModule atom-space-pen-views@2.2.0 checking installable status
31 silly pacote range manifest for align-yaml@^0.1.8 fetched in 259ms
32 silly resolveWithNewModule align-yaml@0.1.8 checking installable status
33 silly pacote range manifest for atom-message-panel@^1.3.0 fetched in 254ms
34 silly resolveWithNewModule atom-message-panel@1.3.0 checking installable status
35 silly pacote range manifest for coffee-fmt@^0.12.0 fetched in 270ms
36 silly resolveWithNewModule coffee-fmt@0.12.0 checking installable status
37 silly pacote range manifest for coffee-formatter@^0.1.2 fetched in 283ms
38 silly resolveWithNewModule coffee-formatter@0.1.2 checking installable status
39 silly pacote range manifest for diff@^3.4.0 fetched in 278ms
40 silly resolveWithNewModule diff@3.5.0 checking installable status
41 http fetch GET 200 https://registry.npmjs.org/async 290ms
42 silly fetchPackageMetaData error for async@^2.6.0 Unexpected end of JSON input while parsing near '...a-mocha":"^1.2.0","ka'
43 http fetch GET 200 https://registry.npmjs.org/editorconfig 135ms
44 http fetch GET 200 https://registry.npmjs.org/coffeescript/-/coffeescript-1.12.7.tgz 149ms
45 http fetch GET 200 https://registry.npmjs.org/extend 106ms
46 http fetch GET 200 https://registry.npmjs.org/expand-home-dir 114ms
47 http fetch GET 200 https://registry.npmjs.org/gherkin 98ms
48 http fetch GET 200 https://registry.npmjs.org/event-kit 122ms
49 http fetch GET 200 https://registry.npmjs.org/eslint 133ms
50 http fetch GET 200 https://registry.npmjs.org/handlebars 104ms
51 http fetch GET 200 https://registry.npmjs.org/js-beautify 112ms
52 silly pacote range manifest for coffeescript@^1.12.6 fetched in 417ms
53 silly resolveWithNewModule coffeescript@1.12.7 checking installable status
54 silly pacote range manifest for editorconfig@^0.15.0 fetched in 201ms
55 silly resolveWithNewModule editorconfig@0.15.3 checking installable status
56 silly pacote range manifest for extend@^3.0.1 fetched in 364ms
57 silly resolveWithNewModule extend@3.0.2 checking installable status
58 silly pacote version manifest for expand-home-dir@0.0.3 fetched in 375ms
59 silly resolveWithNewModule expand-home-dir@0.0.3 checking installable status
60 silly pacote range manifest for event-kit@^2.4.0 fetched in 384ms
61 silly resolveWithNewModule event-kit@2.5.3 checking installable status
62 silly pacote range manifest for handlebars@^4.0.11 fetched in 353ms
63 silly resolveWithNewModule handlebars@4.1.0 checking installable status
64 silly pacote range manifest for eslint@^4.16.0 fetched in 396ms
65 silly resolveWithNewModule eslint@4.19.1 checking installable status
66 silly pacote range manifest for js-beautify@^1.8.1 fetched in 359ms
67 silly resolveWithNewModule js-beautify@1.9.0 checking installable status
68 http fetch GET 200 https://registry.npmjs.org/jscs 362ms
69 http fetch GET 200 https://registry.npmjs.org/loophole 241ms
70 http fetch GET 200 https://registry.npmjs.org/lodash 243ms
71 http fetch GET 200 https://registry.npmjs.org/gherkin/-/gherkin-2.12.2.tgz 283ms
72 silly pacote range manifest for jscs@^3.0.7 fetched in 408ms
73 silly resolveWithNewModule jscs@3.0.7 checking installable status
74 silly pacote range manifest for gherkin@^2.12.2 fetched in 430ms
75 silly resolveWithNewModule gherkin@2.12.2 checking installable status
76 silly pacote range manifest for loophole@^1.1.0 fetched in 286ms
77 silly resolveWithNewModule loophole@1.1.0 checking installable status
78 http fetch GET 200 https://registry.npmjs.org/node-cljfmt 82ms
79 silly pacote range manifest for lodash@^4.17.4 fetched in 293ms
80 silly resolveWithNewModule lodash@4.17.11 checking installable status
81 http fetch GET 200 https://registry.npmjs.org/nginxbeautify 86ms
82 http fetch GET 200 https://registry.npmjs.org/open 79ms
83 http fetch GET 200 https://registry.npmjs.org/prettydiff2 73ms
84 http fetch GET 200 https://registry.npmjs.org/prettier 89ms
85 silly pacote range manifest for nginxbeautify@^2.0.1 fetched in 118ms
86 silly resolveWithNewModule nginxbeautify@2.0.1 checking installable status
87 http fetch GET 200 https://registry.npmjs.org/node-dir 116ms
88 silly pacote version manifest for open@0.0.5 fetched in 115ms
89 silly resolveWithNewModule open@0.0.5 checking installable status
90 http fetch GET 200 https://registry.npmjs.org/pug-beautify 66ms
91 silly pacote range manifest for prettydiff2@^2.2.7 fetched in 119ms
92 silly resolveWithNewModule prettydiff2@2.2.8 checking installable status
93 silly pacote range manifest for prettier@^1.11.1 fetched in 123ms
94 silly resolveWithNewModule prettier@1.16.4 checking installable status
95 http fetch GET 200 https://registry.npmjs.org/remark 70ms
96 silly pacote version manifest for node-dir@0.1.17 fetched in 229ms
97 silly resolveWithNewModule node-dir@0.1.17 checking installable status
98 silly pacote range manifest for pug-beautify@^0.1.1 fetched in 171ms
99 silly resolveWithNewModule pug-beautify@0.1.1 checking installable status
100 http fetch GET 200 https://registry.npmjs.org/temp 114ms
101 http fetch GET 200 https://registry.npmjs.org/shell-env 137ms
102 http fetch GET 200 https://registry.npmjs.org/space-pen 132ms
103 http fetch GET 200 https://registry.npmjs.org/node-cljfmt/-/node-cljfmt-0.5.3.tgz 171ms
104 http fetch GET 200 https://registry.npmjs.org/strip-json-comments 120ms
105 http fetch GET 200 https://registry.npmjs.org/semver 185ms
106 http fetch GET 200 https://registry.npmjs.org/remark/-/remark-6.0.1.tgz 101ms
107 silly pacote version manifest for node-cljfmt@0.5.3 fetched in 321ms
108 silly resolveWithNewModule node-cljfmt@0.5.3 checking installable status
109 silly pacote version manifest for space-pen@5.1.2 fetched in 218ms
110 silly resolveWithNewModule space-pen@5.1.2 checking installable status
111 http fetch GET 200 https://registry.npmjs.org/tidy-markdown 114ms
112 silly pacote range manifest for strip-json-comments@^2.0.1 fetched in 211ms
113 silly resolveWithNewModule strip-json-comments@2.0.1 checking installable status
114 silly pacote range manifest for semver@^5.5.0 fetched in 266ms
115 silly resolveWithNewModule semver@5.6.0 checking installable status
116 http fetch GET 200 https://registry.npmjs.org/season 291ms
117 silly pacote version manifest for remark@6.0.1 fetched in 344ms
118 silly resolveWithNewModule remark@6.0.1 checking installable status
119 http fetch GET 200 https://registry.npmjs.org/shell-env/-/shell-env-0.3.0.tgz 191ms
120 http fetch GET 200 https://registry.npmjs.org/temp/-/temp-0.8.3.tgz 193ms
121 silly pacote version manifest for tidy-markdown@2.0.4 fetched in 234ms
122 silly resolveWithNewModule tidy-markdown@2.0.4 checking installable status
123 http fetch GET 200 https://registry.npmjs.org/typescript-formatter 151ms
124 silly pacote range manifest for season@^6.0.2 fetched in 400ms
125 silly resolveWithNewModule season@6.0.2 checking installable status
126 http fetch GET 200 https://registry.npmjs.org/universal-analytics 137ms
127 http fetch GET 200 https://registry.npmjs.org/underscore-plus 142ms
128 http fetch GET 200 https://registry.npmjs.org/uuid 145ms
129 http fetch GET 200 https://registry.npmjs.org/typescript 257ms
130 silly pacote range manifest for shell-env@^0.3.0 fetched in 439ms
131 silly resolveWithNewModule shell-env@0.3.0 checking installable status
132 silly pacote range manifest for temp@^0.8.3 fetched in 416ms
133 silly resolveWithNewModule temp@0.8.3 checking installable status
134 http fetch GET 200 https://registry.npmjs.org/which 221ms
135 silly pacote range manifest for typescript-formatter@^7.0.0 fetched in 322ms
136 silly resolveWithNewModule typescript-formatter@7.2.2 checking installable status
137 silly pacote range manifest for universal-analytics@^0.4.16 fetched in 298ms
138 silly resolveWithNewModule universal-analytics@0.4.20 checking installable status
139 silly pacote range manifest for underscore-plus@^1.6.6 fetched in 301ms
140 silly resolveWithNewModule underscore-plus@1.6.8 checking installable status
141 silly pacote range manifest for uuid@^3.1.0 fetched in 301ms
142 silly resolveWithNewModule uuid@3.3.2 checking installable status
143 http fetch GET 200 https://registry.npmjs.org/yaml-front-matter 168ms
144 http fetch GET 200 https://registry.npmjs.org/winston 186ms
145 silly pacote range manifest for typescript@^2.6.2 fetched in 416ms
146 silly resolveWithNewModule typescript@2.9.2 checking installable status
147 silly pacote range manifest for which@^1.3.0 fetched in 251ms
148 silly resolveWithNewModule which@1.3.1 checking installable status
149 silly pacote range manifest for winston@^2.4.0 fetched in 205ms
150 silly resolveWithNewModule winston@2.4.4 checking installable status
151 silly pacote version manifest for yaml-front-matter@3.4.1 fetched in 190ms
152 silly resolveWithNewModule yaml-front-matter@3.4.1 checking installable status
153 timing stage:rollbackFailedOptional Completed in 1ms
154 timing stage:runTopLevelLifecycles Completed in 2885ms
155 silly saveTree apm-install-dir-11927-7060-tkn421.xnosr
155 silly saveTree `-- atom-beautify@0.33.4
155 silly saveTree   +-- align-yaml@0.1.8
155 silly saveTree   +-- atom-message-panel@1.3.0
155 silly saveTree   | `-- atom-space-pen-views@2.2.0
155 silly saveTree   |   `-- space-pen@5.1.2
155 silly saveTree   |     `-- underscore-plus@1.6.8
155 silly saveTree   +-- atom-space-pen-views@2.2.0
155 silly saveTree   +-- coffee-fmt@0.12.0
155 silly saveTree   +-- coffee-formatter@0.1.2
155 silly saveTree   +-- coffeescript@1.12.7
155 silly saveTree   +-- csscomb@4.2.0
155 silly saveTree   +-- diff@3.5.0
155 silly saveTree   +-- editorconfig@0.15.3
155 silly saveTree   | `-- semver@5.6.0
155 silly saveTree   +-- eslint@4.19.1
155 silly saveTree   | +-- lodash@4.17.11
155 silly saveTree   | `-- strip-json-comments@2.0.1
155 silly saveTree   +-- event-kit@2.5.3
155 silly saveTree   +-- expand-home-dir@0.0.3
155 silly saveTree   +-- extend@3.0.2
155 silly saveTree   +-- gherkin@2.12.2
155 silly saveTree   +-- handlebars@4.1.0
155 silly saveTree   +-- js-beautify@1.9.0
155 silly saveTree   +-- jscs@3.0.7
155 silly saveTree   +-- lodash@4.17.11
155 silly saveTree   +-- loophole@1.1.0
155 silly saveTree   +-- nginxbeautify@2.0.1
155 silly saveTree   +-- node-cljfmt@0.5.3
155 silly saveTree   +-- node-dir@0.1.17
155 silly saveTree   +-- open@0.0.5
155 silly saveTree   +-- prettier@1.16.4
155 silly saveTree   +-- prettydiff2@2.2.8
155 silly saveTree   +-- pug-beautify@0.1.1
155 silly saveTree   +-- remark@6.0.1
155 silly saveTree   +-- season@6.0.2
155 silly saveTree   +-- semver@5.6.0
155 silly saveTree   +-- shell-env@0.3.0
155 silly saveTree   +-- space-pen@5.1.2
155 silly saveTree   +-- strip-json-comments@2.0.1
155 silly saveTree   +-- temp@0.8.3
155 silly saveTree   +-- tidy-markdown@2.0.4
155 silly saveTree   +-- typescript-formatter@7.2.2
155 silly saveTree   +-- typescript@2.9.2
155 silly saveTree   +-- underscore-plus@1.6.8
155 silly saveTree   +-- universal-analytics@0.4.20
155 silly saveTree   | `-- uuid@3.3.2
155 silly saveTree   +-- uuid@3.3.2
155 silly saveTree   +-- which@1.3.1
155 silly saveTree   +-- winston@2.4.4
155 silly saveTree   `-- yaml-front-matter@3.4.1
156 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...nt":"~0.6.4","grunt-c'
156 verbose stack     at JSON.parse (<anonymous>)
156 verbose stack     at parseJson (C:\Users\km\AppData\Local\atom\app-1.34.0\resources\app\apm\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
156 verbose stack     at consumeBody.call.then.buffer (C:\Users\km\AppData\Local\atom\app-1.34.0\resources\app\apm\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50)
156 verbose stack     at <anonymous>
156 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
157 verbose cwd C:\Users\KMCDOW~1\AppData\Local\Temp\apm-install-dir-11927-7060-tkn421.xnosr
158 verbose Windows_NT 10.0.17134
159 verbose argv "C:\\Users\\km\\AppData\\Local\\atom\\app-1.34.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\km\\AppData\\Local\\atom\\app-1.34.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\km\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\km\\.atom\\.apmrc" "install" "https://www.atom.io/api/packages/atom-beautify/versions/0.33.4/tarball" "--runtime=electron" "--target=2.0.16" "--dist-url=https://atom.io/download/electron" "--arch=x64" "--global-style" "--msvs_version=2015"
160 verbose node v8.9.3
161 verbose npm  v6.2.0
162 error Unexpected end of JSON input while parsing near '...nt":"~0.6.4","grunt-c'
163 verbose exit [ 1, true ]

```

# Steps to Reproduce

1. Click the Install button from the Install Packages section of Atom's Settings

I have tried:
- [x] npm install nmp@latest -g
- [x] apm clean
- [x] deleting everything in /apm/

**Comment by iamkylescode** [comment]
I also tried:
uninstalling/reinstalling atom
uninstalling/reinstalling node
tired over different internet connections
tried to look at the problem files directly for any actual syntax issues (didn't see any):
    https://registry.npmjs.org/async
    https://registry.npmjs.org/eslint
    https://registry.npmjs.org/bluebird

**Comment by iamkylescode** [comment]
The problem was simply that I kept getting incomplete files. bluebird and async were particularly problematic. I solve, I simply had to keep deleting the ~/.atom/.apm/_cacache folder and retrying the install. After about 15 tries it finally worked.
