### ISSUE TITLE
error after upgrade to 1.36

### ISSUE THREAD

**Issue by ftaiolivista** [Glavin001/atom-beautify#2338]
[Enter steps to reproduce:]

1. Install atom-beautify
2. Restart Atom

**Atom**: 1.36.0 x64
**Electron**: 4.1.1
**OS**: linux 5.0.7-zen1-1-zen
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.33.4

### Stack Trace

Failed to activate the atom-beautify package

```
At Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".


EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at /packages/atom-beautify/node_modules/prettier/index.js:33160:21
    at createCommonjsModule (/packages/atom-beautify/node_modules/prettier/index.js:181:35)
    at /packages/atom-beautify/node_modules/prettier/index.js:32967:18)
    at /packages/atom-beautify/node_modules/prettier/index.js:34971:3)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/atom-beautify/src/beautifiers/prettier.coffee:4:12)
    at /packages/atom-beautify/src/beautifiers/prettier.coffee:1:1)
    at /packages/atom-beautify/src/beautifiers/prettier.coffee:1:1)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .coffee] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at /packages/atom-beautify/src/beautifiers/index.coffee:120:20
    at arrayMap (/packages/fast-eslint/node_modules/lodash/lodash.js:639:23)
    at Function.map (/packages/fast-eslint/node_modules/lodash/lodash.js:9556:14)
    at /packages/atom-beautify/src/beautifiers/index.coffee:119:22)
    at /packages/atom-beautify/src/beautify.coffee:10:18)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .coffee] (/usr/lib/atom/src/compile-cache.js:235:23)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at Package.requireMainModule (/usr/lib/atom/src/package.js:776:27)
```

### Commands

```
```

### Non-Core Packages

```
atom-arc-ui 1.1.0 
atom-beautify 0.33.4 
atom-charcoal-syntax 1.7.0 
atom-debug-ui 1.0.4 
atom-easy-jsdoc 4.12.5 
atom-ide-ui 0.13.0 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.1.3 
base16-syntax 1.8.1 
busy-signal 2.0.1 
cursor-history 0.13.2 
dark-flat-ui 1.2.4 
docblockr 0.13.7 
fast-eslint 4.10.0 
file-icons 2.1.31 
file-types 1.0.1 
genesis-syntax 1.0.9 
genesis-syntax-fbn 1.0.9 
genesis-ui 0.5.0 
genesis-uii-fbn 0.5.0 
git-diff-details 1.4.0 
git-diff-popup 0.1.8 
git-time-machine 2.1.0 
goto-definition 1.3.4 
ide-php 0.7.18 
ide-reason 1.1.9 
intentions 1.1.5 
language-docker 1.1.8 
language-gradle 0.1.0 
language-groovy 0.7.0 
language-htaccess 0.2.0 
language-javascript-jsx 0.3.7 
language-ocaml 1.9.5 
language-reason 0.0.5 
language-twig 1.6.3 
line-ending-converter 1.3.2 
linter 2.3.0 
linter-eslint 8.5.3 
linter-js-standard 6.1.1 
linter-jshint 3.1.15 
linter-phpcs 1.6.13 
linter-phpmd 2.0.1 
linter-ui-default 1.7.1 
local-history 4.3.1 
lorem 4.0.0 
markdown-writer 2.11.5 
material 2.2.0 
material-ui 1.0.10 
minimap 4.29.9 
minimap-pigments 0.2.2 
nucleus-dark-ui 0.12.3 
one-dark-vivid-syntax 1.8.1 
php-debug 0.3.5 
php-twig 4.0.0 
pigments 0.40.2 
prettier-atom 0.56.4 
print-atom 0.1.1 
project-plus 1.0.0 
project-view 0.6.5 
project-viewer 1.3.1 
reason-refmt 0.3.3 
slim-dark-ui 0.12.0 
solarized-dark-ui 0.3.2 
split-diff 1.6.0 
sync-settings 0.8.6 
tablr 1.8.3 
tabs-to-spaces 1.0.5 
tester 1.4.0 
tester-phpunit 1.0.6 
tool-bar 1.1.11 
vim-mode-plus 1.36.0 
```

**Comment by darekmeco** [comment]
I made some research, and not allowed evals are in prettier.

**Comment by ftaiolivista** [comment]
Thank you @darekmeco  I confirm your workaround

**Comment by GHLandy** [comment]
I met this in plugin `prettier-atom` after updating its dependency. Awful.
