### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by vkamelin** [Glavin001/atom-beautify#2380]
TypeError: Cannot read property 'split' of undefined
    at PHPCSFixer.module.exports.Beautifier.findFile (/home/gadjet/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:138:25)
    at PHPCSFixer.module.exports.PHPCSFixer.beautify (/home/gadjet/.atom/packages/atom-beautify/src/beautifiers/php-cs-fixer.coffee:65:39)
    at /home/gadjet/.atom/packages/atom-beautify/src/beautifiers/index.coffee:363:28
    at tryCatcher (/home/gadjet/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/gadjet/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/home/gadjet/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromiseCtx (/home/gadjet/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:611:10)
    at _drainQueueStep (/home/gadjet/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/home/gadjet/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/gadjet/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:147:5)
    at Async.drainQueues (/home/gadjet/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at <anonymous>

**Comment by ghost** [comment]
got this issue some time ago , 
just go to beautify setting,
 remove cs-fixer phar path from exutable, and put into php setting, 
at this point beautify will notice you that is deprecated,
 just go to to you user folder (i'm assuming you are uing win10) ".../.atom\packages\atom-beautify\src\beautifiers" and edit file "php-cs-fixer.coffee" at line 46 from "cs_fixer_path: true" to "cs_fixer_path: false"
and it should work again
