### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, statusCode=500

### ISSUE THREAD

**Issue by tanjian917** [Glavin001/atom-beautify#2400]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.33.4

### Stack Trace

Uncaught Error: tunneling socket could not be established, statusCode=500

```
At internal/streams/legacy.js:57

Error: tunneling socket could not be established, statusCode=500
    at ClientRequest.onConnect (/packages/atom-beautify/node_modules/tunnel-agent/index.js:166:19)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketOnData (_http_client.js:465:11)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:279:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:636:20)
```

### Commands

```
     -1:39.1.0 command-palette:toggle (input.hidden-input)
     -1:27.7.0 update-package-dependencies:update (input.hidden-input)
     -1:19.2.0 command-palette:toggle (input.hidden-input)
     -1:13.7.0 settings-view:uninstall-packages (input.hidden-input)
 16x -0:56.7.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ide-debugger-react-native 0.7.3 
atom-python-run 0.9.7 
atom-ternjs 0.19.1 
atom-toolbar 0.1.6 
atom-typescript 13.2.1 
atom-vue 0.6.0 
autoclose-html 0.23.0 
autocomplete-clang 0.12.0 
autocomplete-paths 2.12.2 
autocomplete-solidity 0.3.4 
build 0.70.0 
busy-signal 2.0.1 
dart 1.0.1 
emmet 2.4.3 
file-icons 2.1.33 
hyperclick 0.1.5 
ide-python 1.4.2 
intentions 1.1.5 
language-ethereum 0.3.9 
language-ini 1.21.0 
language-solidity 0.1.1 
language-vue 0.23.1 
language-vue-component 0.5.0 
linter 2.2.0 
linter-gcc 0.7.1 
linter-scss-lint 3.1.1 
linter-solidity 0.5.0 
linter-solium 0.0.5 
linter-ui-default 1.7.1 
native-color-picker 0.2.5 
platformio-ide-debugger 1.2.6 
platformio-ide-terminal 2.9.1 
react 0.18.0 
react-native-snippets 0.3.0 
react-snippets 1.1.3 
script 3.18.1 
tool-bar 1.1.12 
vue-atom-snippets 1.2.0 
vuejs2-snippets 1.1.0 
```

**Comment by SilentGlasses** [comment]
@tanjian917 If you still need this and are looking for something to fill the spot that Atom left, I am using [Pulsar](https://pulsar-edit.dev/) _the successor to Atom_...   This package is working except for one deprecated error listed in #2605

If you don't need this anymore, can you please close this out so it's not just sitting there? Thanks
