### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by SuperMario22922** [Glavin001/atom-beautify#2412]
# Issue
Cannot beautify PHP code

# Description
Cannot read property 'split' of undefined

# Error Message
TypeError: Cannot read property 'split' of undefined
    at PHPCSFixer.module.exports.Beautifier.findFile (/Users/hsak/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:138:25)
    at PHPCSFixer.module.exports.PHPCSFixer.beautify (/Users/hsak/.atom/packages/atom-beautify/src/beautifiers/php-cs-fixer.coffee:65:39)
    at /Users/hsak/.atom/packages/atom-beautify/src/beautifiers/index.coffee:363:28
    at tryCatcher (/Users/hsak/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/hsak/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/Users/hsak/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromiseCtx (/Users/hsak/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:611:10)
    at _drainQueueStep (/Users/hsak/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/Users/hsak/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/hsak/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:147:5)
    at Async.drainQueues (/Users/hsak/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue

**Comment by WeArtStudioNL** [comment]
Same problem here trying to beautify php:

`Cannot read property 'split' of undefined
Hide Stack Trace
TypeError: Cannot read property 'split' of undefined
    at PHPCSFixer.module.exports.Beautifier.findFile (file:///C:/Users/Gebruiker/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:138:25)
    at PHPCSFixer.module.exports.PHPCSFixer.beautify (file:///C:/Users/Gebruiker/.atom/packages/atom-beautify/src/beautifiers/php-cs-fixer.coffee:65:39)
    at file:///C:/Users/Gebruiker/.atom/packages/atom-beautify/src/beautifiers/index.coffee:363:28
    at tryCatcher (C:\Users\Gebruiker\.atom\packages\atom-beautify\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Gebruiker\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\Gebruiker\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (C:\Users\Gebruiker\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (C:\Users\Gebruiker\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (C:\Users\Gebruiker\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\Gebruiker\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (C:\Users\Gebruiker\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:15:14)`

Has this been looked into?
