### ISSUE TITLE
Failed to activate the atom-beautify package

### ISSUE THREAD

**Issue by ghost** [Glavin001/atom-beautify#2428]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.33.4

### Stack Trace

Failed to activate the atom-beautify package

```
At Cannot read property 'toLowerCase' of undefined

TypeError: Cannot read property 'toLowerCase' of undefined
    at /packages/atom-beautify/src/beautify.coffee:605:111
    at Object.plugin.addLanguageCommands (/packages/atom-beautify/src/beautify.coffee:604:5)
    at Object.plugin.activate (/packages/atom-beautify/src/beautify.coffee:621:4)
    at Package.activateNow (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:3313556)
    at string.e.trim.length.activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:2607)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:1211909)
    at Emitter.emit (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:1213350)
    at deferredActivationHooks.triggeredActivationHooks.forEach.e (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:382844)
    at Set.forEach (<anonymous>)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:382806)
    at ~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:940004
    at r (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:11:934610)
    at n (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:1128190)
    at ChildProcess.o.process.on.e (~/AppData/Local/atom/app-1.41.0/resources/app/static/<embedded>:14:1128396)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
autoclose 0.0.2 
busy-signal 2.0.1 
csslint 1.2.0 
emmet 2.4.3 
intentions 1.1.5 
language-ejs 0.4.0 
linter 2.3.1 
linter-eslint 8.5.5 
linter-jshint 3.1.17 
linter-ui-default 1.8.0 
pigments 0.40.2 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by ghost** [comment]
Also, I get this message:

Atom Beautify could not find a supported beautifier for this file

Atom Beautify could not determine a supported beautifier to handle this file with grammar "HTML" and extension "html". If you would like to request support for this file and its language, please create an issue for Atom Beautify at https://github.com/Glavin001/atom-beautify/issues

**Comment by Shimura233** [comment]
I encountered similar issue but with different type error:cannot find module './black'

**Atom:** 1.42.0 x64
**OS:** Microsoft Windows 10 Home Single Language
**Thrown From:** atom-beautify package 0.33.4

**stack trace**
```
Error: Cannot find module './black'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (C:\Users\kagura\AppData\Local\atom\app-1.42.0\resources\electron.asar\common\reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (C:\Users\kagura\AppData\Local\atom\app-1.42.0\resources\app\static\<embedded>:11:155413)
    at Module.require (file:///C:/Users/kagura/AppData/Local/atom/app-1.42.0/resources/app.asar/static/index.js:61:43)
    at require (C:\Users\kagura\AppData\Local\atom\app-1.42.0\resources\app\static\<embedded>:11:146745)
    at file:///C:/Users/kagura/.atom/packages/atom-beautify/src/beautifiers/index.coffee:120:20
    at arrayMap (C:\Users\kagura\.atom\packages\atom-beautify\node_modules\lodash\lodash.js:639:23)
    at Function.map (C:\Users\kagura\.atom\packages\atom-beautify\node_modules\lodash\lodash.js:9554:14)
    at new Beautifiers (file:///C:/Users/kagura/.atom/packages/atom-beautify/src/beautifiers/index.coffee:119:22)
    at Object.<anonymous> (file:///C:/Users/kagura/.atom/packages/atom-beautify/src/beautify.coffee:10:14)
    at Object.<anonymous> (file:///C:/Users/kagura/.atom/packages/atom-beautify/src/beautify.coffee:2:1)
    at Object.<anonymous> (file:///C:/Users/kagura/.atom/packages/atom-beautify/src/beautify.coffee:2:1)
    at Module.get_Module._compile (C:\Users\kagura\AppData\Local\atom\app-1.42.0\resources\app\static\<embedded>:11:147429)
    at Object.value [as .coffee] (C:\Users\kagura\AppData\Local\atom\app-1.42.0\resources\app\static\<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///C:/Users/kagura/AppData/Local/atom/app-1.42.0/resources/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (C:\Users\kagura\AppData\Local\atom\app-1.42.0\resources\app\static\<embedded>:1:728962)
    at Package.requireMainModule (C:\Users\kagura\AppData\Local\atom\app-1.42.0\resources\app\static\<embedded>:11:3328046)
    at Package.activateNow (C:\Users\kagura\AppData\Local\atom\app-1.42.0\resources\app\static\<embedded>:11:3316030)
    at string.e.trim.length.activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (C:\Users\kagura\AppData\Local\atom\app-1.42.0\resources\app\static\<embedded>:14:2607)
    at Function.simpleDispatch (C:\Users\kagura\AppData\Local\atom\app-1.42.0\resources\app\static\<embedded>:11:1211760)
    at Emitter.emit (C:\Users\kagura\AppData\Local\atom\app-1.42.0\resources\app\static\<embedded>:11:1213201)
    at deferredActivationHooks.triggeredActivationHooks.forEach.e (C:\Users\kagura\AppData\Local\atom\app-1.42.0\resources\app\static\<embedded>:11:382837)
    at Set.forEach (<anonymous>)
    at PackageManager.activatePackage (C:\Users\kagura\AppData\Local\atom\app-1.42.0\resources\app\static\<embedded>:11:382799)
    at C:\Users\kagura\AppData\Local\atom\app-1.42.0\resources\app\static\<embedded>:11:939855
    at r (C:\Users\kagura\AppData\Local\atom\app-1.42.0\resources\app\static\<embedded>:11:934461)
    at n (C:\Users\kagura\AppData\Local\atom\app-1.42.0\resources\app\static\<embedded>:14:1125023)
    at ChildProcess.o.process.on.e (C:\Users\kagura\AppData\Local\atom\app-1.42.0\resources\app\static\<embedded>:14:1125229)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
```

**Comment by kaji-hiro** [comment]
I encountered similar issue too but with different type error:cannot find module './logger'

**Atom**: 1.44.0 x64
**Electron**: 4.2.7
**OS**: "Fedora release
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.33.4


### Stack Trace

Failed to activate the atom-beautify package

```
At Cannot find module './logger'

Error: Cannot find module './logger'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/atom-beautify/src/beautify.coffee:12:10)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:694510)
    at Package.requireMainModule (/usr/share/atom/resources/app/static/<embedded>:11:3224163)
    at Package.activateNow (/usr/share/atom/resources/app/static/<embedded>:11:3212147)
    at string.e.trim.length.activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (/usr/share/atom/resources/app/static/<embedded>:14:2607)
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1212986)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1214427)
    at deferredActivationHooks.triggeredActivationHooks.forEach.e (/usr/share/atom/resources/app/static/<embedded>:11:382742)
    at Set.forEach (<anonymous>)
    at PackageManager.activatePackage (/usr/share/atom/resources/app/static/<embedded>:11:382704)
    at /usr/share/atom/resources/app/static/<embedded>:11:941081
    at r (/usr/share/atom/resources/app/static/<embedded>:11:935687)
    at n (/usr/share/atom/resources/app/static/<embedded>:14:1124792)
    at t.bufferStream (/usr/share/atom/resources/app/static/<embedded>:14:1124946)
    at Socket.e.on (/usr/share/atom/resources/app/static/<embedded>:14:1123548)
    at Socket.emit (events.js:187:15)
    at Pipe._handle.close (net.js:606:12)
```

### Commands

```
     -4:16.7.0 intentions:highlight (input.hidden-input)
     -4:16.6.0 core:paste (input.hidden-input)
     -4:15.5.0 core:save (input.hidden-input)
     -4:13.3.0 intentions:highlight (input.hidden-input)
     -4:12.3.0 editor:toggle-line-comments (input.hidden-input)
     -4:11.7.0 intentions:highlight (input.hidden-input)
     -4:11.3.0 core:save (input.hidden-input)
     -3:14.2.0 intentions:highlight (input.hidden-input)
  3x -3:02.8.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
busy-signal 2.0.1 
file-types 1.0.1 
intentions 1.1.5 
linter 2.3.1 
linter-rubocop 2.5.7 
linter-ui-default 1.8.1 
```

**Comment by alppike** [comment]
anyone got a solution for this?

**Comment by Sardonikk** [comment]
Just got this too

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.33.4


### Stack Trace

Failed to activate the atom-beautify package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.46.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:146745)
    at /packages/atom-beautify/src/beautify.coffee:7:25)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:1:721712)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:3299000)
    at Package.activateNow (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:3286984)
    at string.e.trim.length.activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:2607)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:1215907)
    at Emitter.emit (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:1217348)
    at PackageManager.triggerDeferredActivationHooks (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:383144)
    at activatePromise.Promise.all.then (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:381895)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
emmet 2.4.3 
exec-in-cmd 3.1.2 
highlight-selected 0.17.0 
script 3.26.0 
```

**Comment by rooky06** [comment]
On Windows 10 familiale version 10.0.18362

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.46.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.33.4


### Stack Trace

Failed to activate the atom-beautify package

```
At Cannot find module './config/npm-config'

Error: Cannot find module './config/npm-config'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.46.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:146745)
    at /packages/atom-beautify/node_modules/winston/lib/winston/config.js:48:17)
    at /packages/atom-beautify/node_modules/winston/lib/winston/config.js:70:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:146745)
    at /packages/atom-beautify/node_modules/winston/lib/winston/common.js:15:14)
    at /packages/atom-beautify/node_modules/winston/lib/winston/common.js:506:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:146745)
    at /packages/atom-beautify/node_modules/winston/lib/winston.js:24:26)
    at /packages/atom-beautify/node_modules/winston/lib/winston.js:166:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:146745)
    at /packages/atom-beautify/src/logger.coffee:10:13
    at /packages/atom-beautify/src/logger.coffee:4:18)
    at /packages/atom-beautify/src/logger.coffee:1:1)
    at /packages/atom-beautify/src/logger.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:146745)
    at /packages/atom-beautify/src/beautifiers/index.coffee:6:10)
    at /packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at /packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:146745)
    at /packages/atom-beautify/src/beautify.coffee:9:15)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:147429)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:1:721712)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:3299000)
    at Package.activateNow (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:3286984)
    at string.e.trim.length.activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:14:2607)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:1215907)
    at Emitter.emit (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:1217348)
    at PackageManager.triggerDeferredActivationHooks (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:383144)
    at activatePromise.Promise.all.then (~/AppData/Local/atom/app-1.46.0/resources/app/static/<embedded>:11:381895)
```

### Commands

```
  4x -1:19.2.0 click (a.btn-issue.btn.btn-error)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.33.4 
atom-file-icons 0.7.1 
autoclose-html 0.23.0 
drunken-php 0.2.4 
emmet 2.4.3 
highlight-selected 0.17.0 
php-analyser 0.2.0 
php-extract-method 0.2.1 
php-hyperclick 1.2.1 
php-integrator-autocomplete-plus 1.6.2 
```

**Comment by rojeesingh** [comment]
I have  issue-
Atom: 1.46.0 x64
Electron: 4.2.7
OS: Microsoft Windows 10 Pro
Thrown From: atom-beautify package 0.33.4

Stack Trace

Failed to activate the atom-beautify package

**Comment by Jyoti-k259** [comment]
Any solution for this error ??

**Comment by jinruozai** [comment]
Mac os the same err

**Comment by Glavin001** [comment]
Possible duplicate of https://github.com/Glavin001/atom-beautify/issues/2470

Proposed solution: https://github.com/Glavin001/atom-beautify/issues/2470#issuecomment-621140429

> Ran to this problem myself. Just restart your atom and install and wait for it to finish.

Also recommend trying in your Terminal/shell:

```bash
apm clean
apm install atom-beautify
```

**Comment by snowthecoder** [comment]
This doesn't solve the error message, it continues to appear after multiple restarts and reinstalling of atom.
