### ISSUE TITLE
Bash beautifier call incorrect / Ciritical error

### ISSUE THREAD

**Issue by MalteKiefer** [Glavin001/atom-beautify#2436]
Hello,
I installed the latest version from `atom-beautify` and the latest version from `beautysh`.
When I call the beautifier over atom on a shell script I get this error message:

```
Error: usage: beautysh [--indent-size INDENT_SIZE] [--backup] [--check] [--tab]
                [--force-function-style FORCE_FUNCTION_STYLE] [--version]
                [--help]
                [FILE [FILE ...]]
beautysh: error: unrecognized arguments: -f
    at /home/malte/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:183:23
    at tryCatcher (/home/malte/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/malte/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/malte/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/malte/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/malte/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/malte/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/malte/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/malte/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues (/home/malte/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:15:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by bbodenmiller** [comment]
Workaround: https://github.com/Glavin001/atom-beautify/issues/2378#issuecomment-580570646
