### ISSUE TITLE
atom-beautify could not find 'Uncrustify' which has already been installed

### ISSUE THREAD

**Issue by EAimTY** [Glavin001/atom-beautify#2453]
# Description

I've installed uncrustify using Manjaro Linux official pacman repo, and it runs properly when beautifying codes in terminal.

However, atom-beautify seems cannot detect uncrustify. Error thrown : `Could not find 'Uncrustify'. The program may not be installed.`

Stack Trace: 
```
Error: Could not find 'Uncrustify'. The program may not be installed.
    at Function.Executable.commandNotFoundError (/home/eaimty/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:277:10)
    at HybridExecutable.Executable.commandNotFoundError (/home/eaimty/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:269:18)
    at /home/eaimty/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:115:25
    at tryCatcher (/home/eaimty/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/eaimty/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/eaimty/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/eaimty/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/eaimty/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/eaimty/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/eaimty/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/eaimty/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues (/home/eaimty/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:15:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I tried to fill uncrustify executable path in atom beautify's settings with the output of `which uncrustify`, but it didn't make sense.

# Debug

Here is a link to the `debug.md` Gist: 
https://gist.github.com/EAimTY/e458ae7c3e8c161b62104637b259a27a

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by naidoo88** [comment]
I am having the same issue.  Uncrustify is in in path; tried explicitly setting the path; Uncrustify works when used in terminal.

**Comment by hucuyuu** [comment]
Have you solved this?

I am using Manjaro too. But Atom Beautify works fine in Ubuntu and Windows 10 on my device, I am really confuded. 

```
Could not find 'Uncrustify'. The program may not be installed.

See Uncrustify installation instructions at https://github.com/Glavin001/atom-beautify#beautifiers or go to https://github.com/uncrustify/uncrustify
You can configure Atom Beautify with the absolute path to 'uncrustify' by setting 'Executable - Uncrustify - Path' in the Atom Beautify package settings.
Your program is properly installed if running 'which Uncrustify' in your Terminal returns an absolute path to the executable.
Hide Stack Trace
Error: Could not find 'Uncrustify'. The program may not be installed.
    at Function.Executable.commandNotFoundError (/home/hucuyuu/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:277:10)
    at HybridExecutable.Executable.commandNotFoundError (/home/hucuyuu/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:269:18)
    at /home/hucuyuu/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:115:25
    at tryCatcher (/home/hucuyuu/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/hucuyuu/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/hucuyuu/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/hucuyuu/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/hucuyuu/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/hucuyuu/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/hucuyuu/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/hucuyuu/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues (/home/hucuyuu/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:15:14)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)

```

**Comment by miguelcarcamov** [comment]
Same issue here, uncrustify works in the terminal but I cannot make it work in atom

**Comment by MRHirsch20** [comment]
having the same problem with fedora 33
