### ISSUE TITLE
Failed to load the language-javascript-semantic package

### ISSUE THREAD

**Issue by emoarmy** [Glavin001/atom-beautify#247]
[Enter steps to reproduce below:]

1. I get this error every time I load up Atom

**Atom Version**: 0.187.0
**System**: Microsoft Windows 10 Pro Technical Preview
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.23.0

### Stack Trace

Failed to load the language-javascript-semantic package

```
At Cannot find module './acorn-modified.js'

Error: Cannot find module './acorn-modified.js'
    at Module._resolveFilename (module.js:351:15)
    at Function.Module._resolveFilename (C:\Users\Justin\AppData\Local\atom\app-0.187.0\resources\app\src\module-cache.js:383:52)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/C:/Users/Justin/.atom/packages/language-javascript-semantic/lib/javascript-semantic-grammar.coffee:11:11)
    at Object.<anonymous> (/C:/Users/Justin/.atom/packages/language-javascript-semantic/lib/javascript-semantic-grammar.coffee:184:4)
    at Module._compile (module.js:475:26)
    at Object.requireCoffeeScript (C:\Users\Justin\AppData\Local\atom\app-0.187.0\resources\app\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
    at Module.load (module.js:370:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-jshint"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ]
  },
  "atom-beautify": {
    "_analyticsUserId": "b333f613-8249-43dc-bc63-038653b791d9"
  }
}
```

### Installed Packages

```coffee
# User
atom-ternjs, v0.5.6
autoclose-html, v0.15.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.6.0
autocomplete-snippets, v1.2.0
color-picker, v1.5.0
jshint, v1.3.0
language-javascript-semantic, v0.1.0
linter, v0.12.0
linter-csslint, v0.0.11
linter-jshint, v0.1.0
minimap, v4.6.0
monokai, v0.12.0

# Dev
No dev packages
```

**Comment by Glavin001** [comment]
I do not know why this is an Atom Beautify issue, sounds like a `language-javascript-semantic, v0.1.0` issue?

See https://atom.io/packages/language-javascript-semantic
