### ISSUE TITLE
Failed to activate the atom-beautify package

### ISSUE THREAD

**Issue by yassine-bennkhay** [Glavin001/atom-beautify#2470]
Error: Cannot find module 'event-kit'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Module._resolveFilename (C:\Users\hp\AppData\Local\atom\app-1.45.0\resources\electron.asar\common\reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (C:\Users\hp\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:155413)
    at Module.require (file:///C:/Users/hp/AppData/Local/atom/app-1.45.0/resources/app.asar/static/index.js:61:43)
    at require (C:\Users\hp\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:146745)
    at Object.<anonymous> (file:///C:/Users/hp/.atom/packages/atom-beautify-master/src/beautify.coffee:7:25)
    at Object.<anonymous> (file:///C:/Users/hp/.atom/packages/atom-beautify-master/src/beautify.coffee:2:1)
    at Object.<anonymous> (file:///C:/Users/hp/.atom/packages/atom-beautify-master/src/beautify.coffee:2:1)
    at Module.get_Module._compile (C:\Users\hp\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:147429)
    at Object.value [as .coffee] (C:\Users\hp\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (file:///C:/Users/hp/AppData/Local/atom/app-1.45.0/resources/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (C:\Users\hp\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:1:721712)
    at Package.requireMainModule (C:\Users\hp\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:3338526)
    at Package.activateNow (C:\Users\hp\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:3326510)
    at string.e.trim.length.activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (C:\Users\hp\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:14:2607)
    at Function.simpleDispatch (C:\Users\hp\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:1214120)
    at Emitter.emit (C:\Users\hp\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:1215561)
    at PackageManager.triggerDeferredActivationHooks (C:\Users\hp\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:382896)
    at activatePromise.Promise.all.then (C:\Users\hp\AppData\Local\atom\app-1.45.0\resources\app\static\<embedded>:11:381647)

**Comment by sherwyco** [comment]
Ran to this problem myself. Just restart your atom and install and wait for it to finish.

**Comment by yassine-bennkhay** [comment]
Thank you I fixed the problem
