### ISSUE TITLE
Could not find 'php-cs-fixer'. 

### ISSUE THREAD

**Issue by guajars** [Glavin001/atom-beautify#2488]
# Description

Could not find 'php-cs-fixer'. The program may not be installed...

Error: Could not find 'php-cs-fixer'. The program may not be installed.
    at Function.Executable.commandNotFoundError (/Users/osx/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:277:10)
    at HybridExecutable.Executable.commandNotFoundError (/Users/osx/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:269:18)
    at /Users/osx/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:197:22
    at tryCatcher (/Users/osx/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/osx/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/osx/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/osx/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/osx/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/Users/osx/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/osx/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/osx/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues (/Users/osx/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:15:14)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)

**Comment by bornemisza** [comment]
Same here
