### ISSUE TITLE
Failed to activate the atom-beautify package

### ISSUE THREAD

**Issue by vincenthauser** [Glavin001/atom-beautify#250]
[Enter steps to reproduce below:]

1. git clone git@github.com:Glavin001/atom-beautify.git into `/Users/<user>/.atom/packages/`
2. start Atom
3. Paste xml
4. Choose (menu) packages -> atom-beautify -> beautify

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.23.0

### Stack Trace

Failed to activate the atom-beautify package

```
At Cannot find module 'lodash'

Error: Cannot find module 'lodash'
  at Module._resolveFilename (module.js:351:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:293:25)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/Vincent/.atom/packages/atom-beautify/lib/beautify.coffee:7:5)
  at Object.<anonymous> (/Users/Vincent/.atom/packages/atom-beautify/lib/beautify.coffee:3:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:672:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app/src/package.js:257:12)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:236:14)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:742:29
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:227:20)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:159:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:75:30)
  at EventEmitter.emit (events.js:116:17)

```

### Commands

```
     -0:09.2 core:paste (atom-text-editor.editor.is-focused)
     -0:08.6 editor:scroll-to-cursor (atom-text-editor.editor.is-focused)
     -0:08.6 core:undo (atom-text-editor.editor.is-focused)
     -0:04.3 fuzzy-finder:toggle-buffer-finder (atom-text-editor.editor.is-focused)
     -0:04.3 core:paste (atom-text-editor.editor.is-focused)
     -0:00.3 beautify:beautify-editor (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.23.0
esprima, v2.1.0

# Dev
No dev packages
```

**Comment by vincenthauser** [comment]
Didn't realize I needed other stuff as well, such as Node etc. Closing.

**Comment by sinkingshriek** [comment]
@vincenthauser I have `node v0.12.2` installed and it suddenly stopped working for me after an upgrade. My current `atom` version is `v0.187.0` with `atom-beautify` version being `v0.26.5`.

**Stacktrace:-**
```
TypeError: undefined is not a function
  at Writable.<anonymous> (.atom/packages/atom-beautify/node_modules/winston/lib/winston/transports/file.js:60:12)
  at Writable.emit (events.js:138:20)
  at onwriteError (_stream_writable.js:319:10)
  at onwrite (_stream_writable.js:337:5)
  at WritableState.onwrite (_stream_writable.js:107:5)
  at Writable._write (_stream_writable.js:432:3)
  at doWrite (_stream_writable.js:303:12)
  at writeOrBuffer (_stream_writable.js:290:5)
  at Writable.write (_stream_writable.js:219:11)
  at [object Object].File._write (.atom/packages/atom-beautify/node_modules/winston/lib/winston/transports/file.js:195:18)
  at [object Object].File.log (.atom/packages/atom-beautify/node_modules/winston/lib/winston/transports/file.js:167:10)
  at emit (.atom/packages/atom-beautify/node_modules/winston/lib/winston/logger.js:186:17)
  at /usr/share/atom/resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:125:13
  at Array.forEach (native)
  at _each (/usr/share/atom/resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:46:24)
  at Object.async.each (/usr/share/atom/resources/app/node_modules/less-cache/node_modules/less/node_modules/request/node_modules/form-data/node_modules/async/lib/async.js:124:9)
  at [object Object].Logger.log (.atom/packages/atom-beautify/node_modules/winston/lib/winston/logger.js:214:9)
  at Uncrustify.target.(anonymous function) [as verbose] (.atom/packages/atom-beautify/node_modules/winston/lib/winston/common.js:52:18)
  at Uncrustify.module.exports.Beautifier.setupLogger (.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:197:10)
  at Uncrustify.Beautifier (.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:204:10)
  at new Uncrustify (.atom/packages/atom-beautify/src/beautifiers/uncrustify/index.coffee:12:5)
  at .atom/packages/atom-beautify/src/beautifiers/index.coffee:79:17
  at Function.map (/usr/share/atom/resources/app/node_modules/cheerio/node_modules/lodash/dist/lodash.js:3508:27)
  at new Beautifiers (.atom/packages/atom-beautify/src/beautifiers/index.coffee:77:26)
  at Object.<anonymous> (.atom/packages/atom-beautify/src/beautify.coffee:9:18)
  at Object.<anonymous> (.atom/packages/atom-beautify/src/beautify.coffee:3:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app/src/package.js:672:34)
  at Package.module.exports.Package.activateConfig (/usr/share/atom/resources/app/src/package.js:257:12)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:236:14)
  at /usr/share/atom/resources/app/src/package.js:742:29
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:227:20)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:182:20)
```

**Comment by Glavin001** [comment]
@sinkingshriek I am not sure how your issue is related. Please create another issue. Thanks.

**Comment by sinkingshriek** [comment]
@Glavin001 :smile: Atom Issue popup directed me to this page and thought it was related. Created a [new](https://github.com/Glavin001/atom-beautify/issues/328) one.
