### ISSUE TITLE
HELP who can help me out with the error ? 

### ISSUE THREAD

**Issue by sai2828** [Glavin001/atom-beautify#2500]
I'm now here and cant install Atom-beautify! below is my error, what should I do  ? 

Error: Cannot find module '/Users/mac/.atom/packages/atom-beautify/node_modules/event-kit/dist/event-kit'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:240:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:378:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:670:27)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:155482)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:61:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146814)
    at Object.<anonymous> (/Users/mac/.atom/packages/atom-beautify/src/beautify.coffee:7:25)
    at Object.<anonymous> (/Users/mac/.atom/packages/atom-beautify/src/beautify.coffee:2:1)
    at Object.<anonymous> (/Users/mac/.atom/packages/atom-beautify/src/beautify.coffee:2:1)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147498)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:695414)
    at Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3204227)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3192211)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1201500)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1202941)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:383233
    at Set.forEach (<anonymous>)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:383195)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:926825
    at r (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:921431)
    at n (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1063432)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1063586
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1062188)
    at Socket.emit (events.js:199:15)
    at Pipe.<anonymous> (net.js:593:12)

**Comment by mvkrein** [comment]
I have the same issue.  Any resolution?  This is not the same issue as "Failed to activate the atom-beautify package #2342".  #2342 is where I am directed when I click on "View Issue" from my failure message.
