### ISSUE TITLE
beautysh: error: unrecognized arguments: -f

### ISSUE THREAD

**Issue by rednectar** [Glavin001/atom-beautify#2510]
# Description

I have a bash shell script open regocnised as type "shell-script"

# Problem description

When I run Atom Beautify, an error occurs: beautysh: error: unrecognized arguments: -f

# Error analysis
`usage: beautysh [--indent-size INDENT_SIZE] [--backup] [--check] [--tab]
                [--force-function-style FORCE_FUNCTION_STYLE] [--version]
                [--help]
                [FILE [FILE ...]]
beautysh: error: unrecognized arguments: -f
Hide Stack Trace
Error: usage: beautysh [--indent-size INDENT_SIZE] [--backup] [--check] [--tab]
                [--force-function-style FORCE_FUNCTION_STYLE] [--version]
                [--help]
                [FILE [FILE ...]]
beautysh: error: unrecognized arguments: -f
    at /Users/chriswelsh/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:183:23
    at tryCatcher (/Users/chriswelsh/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/chriswelsh/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/chriswelsh/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/chriswelsh/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/chriswelsh/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/Users/chriswelsh/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/Users/chriswelsh/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/chriswelsh/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:147:5)
    at Async.drainQueues (/Users/chriswelsh/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)`

Severity | Provider | Description | Line
-- | -- | -- | --

# Steps to Reproduce

1. Open bash file
2. Run command `Atom Beautify: Beautify Editor`

I have:
- [x ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x ] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ -] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue
I have no idea what you mean. Attached generated debug.md file here renamed to debug.md.log to pass unintelligent file filter on Github
[debug.md.log](https://github.com/Glavin001/atom-beautify/files/5059465/debug.md.log)

**Comment by chriswhite199** [comment]
While waiting for an official fix, the following wrapper script works for me (amend your beautify executable for beautysh to point at this script file, and make the file itself executable. Also check the final line references your beautysh path)

```bash
#!/usr/bin/env bash

for arg do
    shift
    # strip the -f argument
    [ "$arg" = "-f" ] && continue
    set -- "$@" "$arg"
done

/usr/local/bin/beautysh $@
```

**Comment by ryantimjohn** [comment]
I am getting same error.

**Comment by lroehrs** [comment]
Same here

**Comment by Stronautt** [comment]
> While waiting for an official fix, the following wrapper script works for me (amend your beautify executable for beautysh to point at this script file, and make the file itself executable. Also check the final line references your beautysh path)
> 
> ```shell
> #!/usr/bin/env bash
> 
> for arg do
>     shift
>     # strip the -f argument
>     [ "$arg" = "-f" ] && continue
>     set -- "$@" "$arg"
> done
> 
> /usr/local/bin/beautysh $@
> ```

Here is the same script in Batch for Windows:
```batch
@echo off
setlocal enabledelayedexpansion

set args=
(for %%x in (%*) do (
  REM strip the -f argument
  if "%%x" NEQ "-f" set args=!args! %%x
))

beautysh %args%

endlocal
```

**Comment by max1mvs** [comment]
+1 from me. Tried the same as OP. I also tried to reinstall/update beautysh since a previous error from atom-beautify told me to do so. Not sure how to use the wrapper script, though…

```
usage: beautysh [--indent-size INDENT_SIZE] [--backup] [--check] [--tab] [--force-function-style FORCE_FUNCTION_STYLE] [--version] [--help] [FILE ...] beautysh: error: unrecognized arguments: -f

usage: beautysh [--indent-size INDENT_SIZE] [--backup] [--check] [--tab]
                [--force-function-style FORCE_FUNCTION_STYLE] [--version]
                [--help]
                [FILE ...]
beautysh: error: unrecognized arguments: -f
[Hide Stack Trace]()
Error: usage: beautysh [--indent-size INDENT_SIZE] [--backup] [--check] [--tab]
                [--force-function-style FORCE_FUNCTION_STYLE] [--version]
                [--help]
                [FILE ...]
beautysh: error: unrecognized arguments: -f
    at /Users/massimo/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:183:23
    at tryCatcher (/Users/massimo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/massimo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/massimo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/massimo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/massimo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/massimo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/massimo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/massimo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues (/Users/massimo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:15:14)
```

**Comment by WolfgangFahl** [comment]
**beautysh**
to be put in the PATH e.g. $HOME/bin
```bash
#!/bin/bash
#https://github.com/Glavin001/atom-beautify/issues/2510#issuecomment-677825594
#which beautysh
beauty="/Users/wf/Library/Python/3.12/bin/beautysh"

for arg do
  shift
  # strip the -f argument
  [ "$arg" = "-f" ] && continue
  set -- "$@" "$arg"
done

$beauty $@
```
