### ISSUE TITLE
Uncaught SyntaxError: Unexpected end of input on Windows 8.1

### ISSUE THREAD

**Issue by ultimatemonty** [Glavin001/atom-beautify#252]
Stack trace below. Let me know if you need any additional information and I'll be happy to provide it.

[Enter steps to reproduce below:]

1. Open Atom
2. Error message immediately appears

**Atom Version**: 0.187.0
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.23.1

### Stack Trace

Uncaught SyntaxError: Unexpected end of input

```
At file:///C:/Users/chris/AppData/Local/atom/app-0.187.0/resources/app/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22E%3A%5C%5CDocuments%5C%5CSynapse%5C%5CProjects%5C%5CSynapse%5C%5CSynapse%20MX%5C%5Csynapse-mx-client-ember-cli%22%7D%5D%2C%22bootstrapScript%22%3A%22C%3A%5C%5CUsers%5C%5Cchris%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-0.187.0%5C%5Cresources%5C%5Capp%5C%5Csrc%5C%5Cwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22C%3A%5C%5CUsers%5C%5Cchris%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-0.187.0%5C%5Cresources%5C%5Capp%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22appVersion%22%3A%220.187.0%22%2C%22shellLoadTime%22%3A219%2C%22initialPaths%22%3A%5B%22E%3A%5C%5CDocuments%5C%5CSynapse%5C%5CProjects%5C%5CSynapse%5C%5CSynapse%20MX%5C%5Csynapse-mx-client-ember-cli%22%5D%7D:0

SyntaxError: Unexpected end of input
  at Object.parse (native)
  at C:\Users\chris\.atom\packages\terminal-status\lib\command-output-view.coffee:39:26
  at ChildProcess.exithandler (child_process.js:756:5)
  at ChildProcess.emit (events.js:119:17)
  at maybeClose (child_process.js:1013:16)
  at Socket.<anonymous> (child_process.js:1181:11)
  at Socket.emit (events.js:116:17)
  at Pipe.close (net.js:477:12)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "brogrammer-ui",
      "base16-railscasts"
    ],
    "ignoredNames": [
      "node_modules/",
      "bower_components/",
      "dist/",
      "tmp/",
      ".git/",
      ".*"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-handlebars, v0.4.0
autocomplete-plus, v2.6.0
base16-railscasts, v0.5.0
brogrammer-ui, v0.4.0
ember-cli-helper, v0.7.2
ember-snippets, v1.0.0
keybinding-cheatsheet, v0.0.8
language-powershell, v2.0.0
linter, v0.12.0
linter-handlebars, v0.1.1
terminal-status, v1.6.0

# Dev
No dev packages
```

**Comment by Glavin001** [comment]
Looks like this is from the `terminal-status` package. Atom was reporting incorrect packages that were causing errors. This has since been fixed in Atom. That is likely what happened: `terminal-status` had a bug and Atom reported it accidently as Atom Beautify's.
