### ISSUE TITLE
Failed to activate the atom-beautify package

### ISSUE THREAD

**Issue by yywxdgy** [Glavin001/atom-beautify#2522]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Unknown Windows version
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.33.4

### Stack Trace

Failed to activate the atom-beautify package

```
At Cannot find module 'event-kit'
Require stack:
- C:\Users\Stuedent\.atom\packages\atom-beautify-master\src\beautify.coffee
- C:\Users\Stuedent\AppData\Local\atom\app-1.51.0\resources\app.asar\static\index.html

Error: Cannot find module 'event-kit'
Require stack:
- C:\Users\Stuedent\.atom\packages\atom-beautify-master\src\beautify.coffee
- C:\Users\Stuedent\AppData\Local\atom\app-1.51.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:683:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.51.0/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:155481)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:146814)
    at /packages/atom-beautify/src/beautify.coffee:7:25)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:14:16)
    at customRequire (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:1:722026)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:3299964)
    at Package.activateNow (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:3287948)
    at ~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:1190297)
    at Emitter.emit (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:1191738)
    at PackageManager.triggerDeferredActivationHooks (~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:383481)
    at ~/AppData/Local/atom/app-1.51.0/resources/app/static/<embedded>:11:382232
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-beautify 0.33.4 
atom-material-syntax 1.0.8 
atom-material-syntax-dark 1.0.0 
atom-material-ui 2.1.3 
burn 0.2.1 
busy-signal 2.0.1 
cfg undefined 
Clouds-ui 1.1.0 
doc undefined 
file-icons 2.1.43 
file-types 1.0.1 
gcc-make-run 0.2.12 
handsome-light-syntax 0.3.6 
Hydrogen 2.14.4 
intentions 1.1.5 
linter 2.3.1 
linter-gcc 0.9.0 
linter-ui-default 1.8.1 
miku-blue-syntax 0.2.0 
minimap 4.29.9 
pure-light-syntax 1.0.0 
rocket-dark-syntax 1.0.0 
simplified-chinese-menu 5.3.5 
unibeautify 0.17.1 
vector-syntax 1.0.0 
ZenScript 0.2.5 
```

**Comment by vamsivk18** [comment]
Same issue for me

**Comment by amansahu112** [comment]
any solution?

**Comment by yywxdgy** [comment]
I'm not so sure...but now it's okey, I forgot exactly how.

**Comment by CerJaja** [comment]
Any update on this?

**Comment by jp20indian** [comment]
1. Open cmd
2.C:\Users\username>cd .atom
3.C:\Users\KIIT\.atom>cd .apm
4.C:\Users\KIIT\.atom\.apm>apm install atom-beautify
Installing atom-beautify to C:\Users\KIIT\.atom\packages done

BEAUTIFY HAS BEEN INSTALLED !!!

5.Open Atom
6.Check in the packages,you will find Atom Beautify there.

**Comment by 1amCharlie** [comment]
i tried this jp20indian the respone is:

apm command not found

**Comment by Tkadu30** [comment]
1.Open cmd
2.C:\Users\username>cd .atom
3.C:\Users\cd .atom>
4.C:\Users\cd .atom>apm install atom-beautify
Installing atom-beautify to C:\Users\cd .atom\packages done
BEAUTIFY HAS BEEN INSTALLED !!!

5.Open Atom
6.Check in the packages, you will find Atom Beautify there.

**Comment by Gabitil** [comment]
C:\Users\gabri>cd .atom

C:\Users\gabri\.atom>apm install atom-beautify
'apm' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

C:\Users\gabri\.atom>cd .apm

C:\Users\gabri\.atom\.apm>apm install atom-beautify
'apm' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

C:\Users\gabri\.atom\.apm>

**Comment by Nitin-00** [comment]
Any command for linux ???

**Comment by NicholasKyleHoffman** [comment]
Thanks @jp20indian - worked perfectly

**Comment by kulcsarrudolf** [comment]
Thanks @jp20indian! It worked for me too!

**Comment by mrb-x** [comment]
> Any command for linux ???

On my Linux Mint 20.1 Cinnamon
Launch terminal and type :
`cd .atom`
`cd .apm`
`apm install atom-beautify`

**Comment by masihuzzaman** [comment]
@jp20indian -- it worked for me.
Open cmd
`C:\Users\Masihuzzaman\.atom\.apm>apm install atom-beautify`
Installing atom-beautify to `C:\Users\Masihuzzaman\.atom\packages` done
![image](https://user-images.githubusercontent.com/24731748/118151442-404b3580-b431-11eb-97fd-30e44e0aa851.png)

**Comment by AlankritVerma01** [comment]
@jp20indian Hey i ,did the same , but the it is not process, from last 5 minutes it is stuck at a place ,  it is not saying done 
it is stuck at installing...... only 
please help if you know how can I get this thing resolved . and how much time does it usually takes . ? should I wait more?

**Comment by masihuzzaman** [comment]
> @jp20indian Hey i ,did the same , but the it is not process, from last 5 minutes it is stuck at a place , it is not saying done
> it is stuck at installing...... only
> please help if you know how can I get this thing resolved . and how much time does it usually takes . ? should I wait more?

Hey @AlankritVerma01. It takes only a few seconds in installing.  Has it worked or not. If not can you post some screenshot.

**Comment by AlankritVerma01** [comment]
> > @jp20indian Hey i ,did the same , but the it is not process, from last 5 minutes it is stuck at a place , it is not saying done
> > it is stuck at installing...... only
> > please help if you know how can I get this thing resolved . and how much time does it usually takes . ? should I wait more?
> 
> Hey @AlankritVerma01. It takes only a few seconds in installing. Has it worked or not. If not can you post some screenshot.

@masihuzzaman 
Hello sir , thankyou , it has worked now. I don't know but when i restarted the laptop next day ( today)  and then tried the same , it got completed and now i can use that properly , thankyou

**Comment by iconic-shri** [comment]
See clang-format installation instructions at https://github.com/Glavin001/atom-beautify#beautifiers or go to https://clang.llvm.org/docs/ClangFormat.html
You can configure Atom Beautify with the absolute path to 'clang-format' by setting 'Executable - ClangFormat - Path' in the Atom Beautify package settings.
Your program is properly installed if running 'where.exe clang-format' in your CMD prompt returns an absolute path to the executable.





this happens when you save c++ code anyone have solution

**Comment by SilentGlasses** [comment]
If you still need this and are looking for something to fill the spot that Atom left, I am using [Pulsar](https://pulsar-edit.dev/) _the successor to Atom_...   This package is working except for one deprecated error listed in #2605

If you don't need this anymore, can you please close this out so it's not just sitting there? Thanks
