### ISSUE TITLE
Uncaught Error: Cannot find module 'event-kit'Require stack:- $ATOM_HOME/packages\atom-beautify...

### ISSUE THREAD

**Issue by Spacemonke** [Glavin001/atom-beautify#2540]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.53.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.33.4

### Stack Trace

Uncaught Error: Cannot find module 'event-kit'
Require stack:
- C:\Users\user\.atom\packages\atom-beautify-0.33.4\src\beautify.coffee
- C:\Users\user\AppData\Local\atom\app-1.53.0\resources\app.asar\static\index.html

```
At internal/modules/cjs/loader.js:630

Error: Cannot find module 'event-kit'
Require stack:
- C:\Users\user\.atom\packages\atom-beautify-0.33.4\src\beautify.coffee
- C:\Users\user\AppData\Local\atom\app-1.53.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.53.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:155481)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:146814)
    at /packages/atom-beautify-0.33.4/src/beautify.coffee:7:25)
    at /packages/atom-beautify-0.33.4/src/beautify.coffee:2:1)
    at /packages/atom-beautify-0.33.4/src/beautify.coffee:2:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:147498)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:151046)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:1:736531)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:3711337)
    at Package.activateConfig (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:3700625)
    at PackageManager.packageHasSettings (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:910108)
    at PackageCard.hasSettings (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:14:2640328)
    at PackageCard.updateSettingsState (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:14:2630596)
    at PackageCard.updateInterfaceState (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:14:2630419)
    at new PackageCard (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:14:2622016)
    at PackageDetailView.completeInitialization (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:14:804690)
    at PackageDetailView.loadPackage (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:14:805257)
    at new PackageDetailView (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:14:801843)
    at SettingsView.getOrCreatePanel (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:932187)
    at SettingsView.showPanel (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:932908)
    at SettingsView.showDeferredPanel (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:932832)
    at SettingsView.initializePanels (~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:930289)
    at ~/AppData/Local/atom/app-1.53.0/resources/app/static/<embedded>:11:927465
    at processTicksAndRejections (internal/process/task_queues.js:82:9)
```

### Commands

```
```

### Non-Core Packages

```

```

**Comment by SilentGlasses** [comment]
If you still need this and are looking for something to fill the spot that Atom left, I am using [Pulsar](https://pulsar-edit.dev/) _the successor to Atom_...   This package is working except for one deprecated error listed in #2605

If you don't need this anymore, can you please close this out so it's not just sitting there? Thanks
