### ISSUE TITLE
Uncaught Error: Cannot find module '$ATOM_HOME/packages\atom-beautify\node_modules\winston\lib\wi...

### ISSUE THREAD

**Issue by Phanthomaz** [Glavin001/atom-beautify#2549]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.33.4

### Stack Trace

Uncaught Error: Cannot find module 'C:\Users\FANTOMAS\.atom\packages\atom-beautify\node_modules\winston\lib\winston'. Please verify that the package.json has a valid "main" entry

```
At internal/modules/cjs/loader.js:240

Error: Cannot find module 'C:\Users\FANTOMAS\.atom\packages\atom-beautify\node_modules\winston\lib\winston'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:232:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:369:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:614:27)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.54.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:155387)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:146720)
    at /packages/atom-beautify/src/logger.coffee:10:13
    at /packages/atom-beautify/src/logger.coffee:4:18)
    at /packages/atom-beautify/src/logger.coffee:1:1)
    at /packages/atom-beautify/src/logger.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:146720)
    at /packages/atom-beautify/src/beautifiers/index.coffee:6:10)
    at /packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at /packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:146720)
    at /packages/atom-beautify/src/beautify.coffee:9:15)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:1:723602)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
csslint 1.2.0 
emmet 2.4.3 
language-ejs 0.4.0 
linter-eslint 8.5.5 
pigments 0.40.6 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by SilentGlasses** [comment]
If you still need this and are looking for something to fill the spot that Atom left, I am using [Pulsar](https://pulsar-edit.dev/) _the successor to Atom_...   This package is working except for one deprecated error listed in #2605

If you don't need this anymore, can you please close this out so it's not just sitting there? Thanks
