### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Bamlak11** [Glavin001/atom-beautify#2558]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: macOS 11.2.1
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.33.4

### Stack Trace

Uncaught RangeError: Maximum call stack size exceeded

```
At /Users/Bh20x/.atom/packages/atom-beautify/node_modules/jquery/dist/jquery.js:855

RangeError: Maximum call stack size exceeded
    at String.replace (<anonymous>)
    at Sizzle (/packages/atom-beautify/node_modules/jquery/dist/jquery.js:855:26)
    at Function.Sizzle.matches (/packages/atom-beautify/node_modules/jquery/dist/jquery.js:1396:9)
    at Function.jQuery.filter (/packages/atom-beautify/node_modules/jquery/dist/jquery.js:2672:15)
    at /packages/atom-beautify/node_modules/jquery/dist/jquery.js:3010:21)
    at OpenInBrowsersView.openBrowser (/packages/open-in-browsers/lib/open-in-browsers-view.coffee:58:6)
    at OpenInBrowsersView.open (/packages/open-in-browsers/lib/open-in-browsers-view.coffee:86:8)
    at OpenInBrowsersView.openBrowser (/packages/open-in-browsers/lib/open-in-browsers-view.coffee:60:8)
    at OpenInBrowsersView.open (/packages/open-in-browsers/lib/open-in-browsers-view.coffee:86:8)
    at OpenInBrowsersView.openBrowser (/packages/open-in-browsers/lib/open-in-browsers-view.coffee:60:8)
    at OpenInBrowsersView.open (/packages/open-in-browsers/lib/open-in-browsers-view.coffee:86:8)
    at OpenInBrowsersView.openBrowser (/packages/open-in-browsers/lib/open-in-browsers-view.coffee:60:8)
    at OpenInBrowsersView.open (/packages/open-in-browsers/lib/open-in-browsers-view.coffee:86:8)
    at OpenInBrowsersView.openBrowser (/packages/open-in-browsers/lib/open-in-browsers-view.coffee:60:8)
    at OpenInBrowsersView.open (/packages/open-in-browsers/lib/open-in-browsers-view.coffee:86:8)
    at OpenInBrowsersView.openBrowser (/packages/open-in-browsers/lib/open-in-browsers-view.coffee:60:8)
    at OpenInBrowsersView.open (/packages/open-in-browsers/lib/open-in-browsers-view.coffee:86:8)
    at OpenInBrowsersView.openBrowser (/packages/open-in-browsers/lib/open-in-browsers-view.coffee:60:8)
    at OpenInBrowsersView.open (/packages/open-in-browsers/lib/open-in-browsers-view.coffee:86:8)
    at OpenInBrowsersView.openBrowser (/packages/open-in-browsers/lib/open-in-browsers-view.coffee:60:8)
    at OpenInBrowsersView.open (/packages/open-in-browsers/lib/open-in-browsers-view.coffee:86:8)
    at OpenInBrowsersView.openBrowser (/packages/open-in-browsers/lib/open-in-browsers-view.coffee:60:8)
    at OpenInBrowsersView.open (/packages/open-in-browsers/lib/open-in-browsers-view.coffee:86:8)
    at OpenInBrowsersView.openBrowser (/packages/open-in-browsers/lib/open-in-browsers-view.coffee:60:8)
    at OpenInBrowsersView.open (/packages/open-in-browsers/lib/open-in-browsers-view.coffee:86:8)
    at OpenInBrowsersView.openBrowser (/packages/open-in-browsers/lib/open-in-browsers-view.coffee:60:8)
    at OpenInBrowsersView.open (/packages/open-in-browsers/lib/open-in-browsers-view.coffee:86:8)
    at OpenInBrowsersView.openBrowser (/packages/open-in-browsers/lib/open-in-browsers-view.coffee:60:8)
    at OpenInBrowsersView.open (/packages/open-in-browsers/lib/open-in-browsers-view.coffee:86:8)
    at OpenInBrowsersView.openBrowser (/packages/open-in-browsers/lib/open-in-browsers-view.coffee:60:8)
    at OpenInBrowsersView.open (/packages/open-in-browsers/lib/open-in-browsers-view.coffee:86:8)
    at OpenInBrowsersView.openBrowser (/packages/open-in-browsers/lib/open-in-browsers-view.coffee:60:8)
    at OpenInBrowsersView.open (/packages/open-in-browsers/lib/open-in-browsers-view.coffee:86:8)
    at OpenInBrowsersView.openBrowser (/packages/open-in-browsers/lib/open-in-browsers-view.coffee:60:8)
    at OpenInBrowsersView.open (/packages/open-in-browsers/lib/open-in-browsers-view.coffee:86:8)
    at OpenInBrowsersView.openBrowser (/packages/open-in-browsers/lib/open-in-browsers-view.coffee:60:8)
```

### Commands

```
     -0:13.5.0 open-in-browsers:IE (span.name.icon.icon-file-text)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-live-server 2.3.0 
linter 3.3.0 
linter-htmllint 1.1.14 
linter-lesshint 6.0.2 
linter-ui-default 3.2.5 
open-in-browsers 0.0.30 
```

**Comment by SilentGlasses** [comment]
If you still need this and are looking for something to fill the spot that Atom left, I am using [Pulsar](https://pulsar-edit.dev/) _the successor to Atom_...   This package is working except for one deprecated error listed in #2605

If you don't need this anymore, can you please close this out so it's not just sitting there? Thanks
