### ISSUE TITLE
Uncaught Error: Cannot find module './winston/transports/transport'Require stack:- $ATOM_HOME/p...

### ISSUE THREAD

**Issue by nddev341** [Glavin001/atom-beautify#2559]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: Unknown Windows version
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.33.4

### Stack Trace

Uncaught Error: Cannot find module './winston/transports/transport'
Require stack:
- C:\Users\VortX\.atom\packages\atom-beautify\node_modules\winston\lib\winston.js
- C:\Users\VortX\.atom\packages\atom-beautify\src\logger.coffee
- C:\Users\VortX\.atom\packages\atom-beautify\src\beautifiers\index.coffee
- C:\Users\VortX\.atom\packages\atom-beautify\src\beautify.coffee
- C:\Users\VortX\AppData\Local\atom\app-1.55.0\resources\app.asar\static\index.html

```
At internal/modules/cjs/loader.js:627

Error: Cannot find module './winston/transports/transport'
Require stack:
- C:\Users\VortX\.atom\packages\atom-beautify\node_modules\winston\lib\winston.js
- C:\Users\VortX\.atom\packages\atom-beautify\src\logger.coffee
- C:\Users\VortX\.atom\packages\atom-beautify\src\beautifiers\index.coffee
- C:\Users\VortX\.atom\packages\atom-beautify\src\beautify.coffee
- C:\Users\VortX\AppData\Local\atom\app-1.55.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.55.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:155387)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:146720)
    at /packages/atom-beautify/node_modules/winston/lib/winston.js:37:26)
    at /packages/atom-beautify/node_modules/winston/lib/winston.js:167:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:146720)
    at /packages/atom-beautify/src/logger.coffee:10:13
    at /packages/atom-beautify/src/logger.coffee:4:18)
    at /packages/atom-beautify/src/logger.coffee:1:1)
    at /packages/atom-beautify/src/logger.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:146720)
    at /packages/atom-beautify/src/beautifiers/index.coffee:6:10)
    at /packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at /packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:146720)
    at /packages/atom-beautify/src/beautify.coffee:9:15)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:147404)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
csslint 1.2.0 
emmet 2.4.3 
kite 0.204.0 
language-ejs 0.4.0 
linter 3.3.0 
linter-eslint 8.5.5 
pigments 0.40.6 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by SilentGlasses** [comment]
If you still need this and are looking for something to fill the spot that Atom left, I am using [Pulsar](https://pulsar-edit.dev/) _the successor to Atom_...   This package is working except for one deprecated error listed in #2605

If you don't need this anymore, can you please close this out so it's not just sitting there? Thanks
