### ISSUE TITLE
Help: beautify permission deined in ubuntu

### ISSUE THREAD

**Issue by kenhutaiwan** [Glavin001/atom-beautify#2560]
# Description

When use atom-beautify to beautify my code, it always fails with warning: permission denied.

# Actual Output

Stack trace:

```
Parsing: input2021218-16452-7lsgli.nwn4f.c as language C
do_source_file: Unable to create output2021218-16452-a8uu9e.f5jkn.c: Permission denied (13)
Hide Stack Trace
Error: Parsing: input2021218-16452-7lsgli.nwn4f.c as language C
do_source_file: Unable to create output2021218-16452-a8uu9e.f5jkn.c: Permission denied (13)
    at /home/ken/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:183:23
    at tryCatcher (/home/ken/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ken/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/ken/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/ken/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/ken/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/ken/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/ken/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/ken/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues (/home/ken/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:15:14)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: <https://gist.github.com/kenhutaiwan/1058044c4a9e2abe3c9417684cccc343>

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [X] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by SilentGlasses** [comment]
If you still need this and are looking for something to fill the spot that Atom left, I am using [Pulsar](https://pulsar-edit.dev/) _the successor to Atom_...   This package is working except for one deprecated error listed in #2605

If you don't need this anymore, can you please close this out so it's not just sitting there? Thanks
