### ISSUE TITLE
Not installing the pacakage

### ISSUE THREAD

**Issue by adityajadhav2004** [Glavin001/atom-beautify#2564]
The package is not working in windows seven

It is telling that no module found.

It is showing this error.

 Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:232:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:369:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:614:27)
    at Module._resolveFilename (C:\Users\Aditya\AppData\Local\atom\app-1.55.0\resources\electron.asar\common\reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (C:\Users\Aditya\AppData\Local\atom\app-1.55.0\resources\app\static\<embedded>:11:155387)
    at Module.require (file:///C:/Users/Aditya/AppData/Local/atom/app-1.55.0/resources/app.asar/static/index.js:61:43)
    at require (C:\Users\Aditya\AppData\Local\atom\app-1.55.0\resources\app\static\<embedded>:11:146720)
    at Object.<anonymous> (file:///C:/Users/Aditya/.atom/packages/atom-beautify/src/beautify.coffee:7:25)
    at Object.<anonymous> (file:///C:/Users/Aditya/.atom/packages/atom-beautify/src/beautify.coffee:2:1)
    at Object.<anonymous> (file:///C:/Users/Aditya/.atom/packages/atom-beautify/src/beautify.coffee:2:1)
    at Module.get_Module._compile (C:\Users\Aditya\AppData\Local\atom\app-1.55.0\resources\app\static\<embedded>:11:147404)
    at Object.value [as .coffee] (C:\Users\Aditya\AppData\Local\atom\app-1.55.0\resources\app\static\<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (file:///C:/Users/Aditya/AppData/Local/atom/app-1.55.0/resources/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (C:\Users\Aditya\AppData\Local\atom\app-1.55.0\resources\app\static\<embedded>:1:736637)
    at requireModule (C:\Users\Aditya\AppData\Local\atom\app-1.55.0\resources\app\static\<embedded>:14:1122229)
    at Package.requireMainModule (C:\Users\Aditya\AppData\Local\atom\app-1.55.0\resources\app\static\<embedded>:11:3509026)
    at Package.activateNow (C:\Users\Aditya\AppData\Local\atom\app-1.55.0\resources\app\static\<embedded>:11:3497010)
    at C:\Users\Aditya\AppData\Local\atom\app-1.55.0\resources\app\static\<embedded>:14:2607
    at Function.simpleDispatch (C:\Users\Aditya\AppData\Local\atom\app-1.55.0\resources\app\static\<embedded>:11:1190181)
    at Emitter.emit (C:\Users\Aditya\AppData\Local\atom\app-1.55.0\resources\app\static\<embedded>:11:1191622)
    at PackageManager.triggerDeferredActivationHooks (C:\Users\Aditya\AppData\Local\atom\app-1.55.0\resources\app\static\<embedded>:11:384090)
    at C:\Users\Aditya\AppData\Local\atom\app-1.55.0\resources\app\static\<embedded>:11:382841

**Comment by SilentGlasses** [comment]
If you still need this and are looking for something to fill the spot that Atom left, I am using [Pulsar](https://pulsar-edit.dev/) _the successor to Atom_...   This package is working except for one deprecated error listed in #2605

If you don't need this anymore, can you please close this out so it's not just sitting there? Thanks
