### ISSUE TITLE
Cannot read property 'error' of undefined

### ISSUE THREAD

**Issue by harmtemolder** [Glavin001/atom-beautify#2565]
# Description

When I try to run atom-beautify on a Markdown file I get this:

```
TypeError: Cannot read property 'error' of undefined
    at /Users/harmtemolder/.atom/packages/atom-beautify/src/beautifiers/remark.coffee:42:10
    at Promise._execute (/Users/harmtemolder/.atom/packages/atom-beautify/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/Users/harmtemolder/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/Users/harmtemolder/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:103:10)
    at Remark.module.exports.Remark.beautify (/Users/harmtemolder/.atom/packages/atom-beautify/src/beautifiers/remark.coffee:36:12)
    at /Users/harmtemolder/.atom/packages/atom-beautify/src/beautifiers/index.coffee:363:28
    at tryCatcher (/Users/harmtemolder/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/harmtemolder/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/harmtemolder/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/Users/harmtemolder/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/Users/harmtemolder/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/Users/harmtemolder/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/harmtemolder/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues (/Users/harmtemolder/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:15:14)
```

Looks like what happend in 2016 when a newer version Remark was included (#1196).

# Steps to Reproduce

1. Open any `.md` file
2. Run command `Atom Beautify: Beautify Editor`
3. Receive an `Cannot read property 'error' of undefined` error
4. Setting “Default Beautifier” to “Tidy Markdown” instead of “Remark” fixes this

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/harmtemolder/d626240c35be8f91fdaf9ea2a493603a

**Comment by SilentGlasses** [comment]
If you still need this and are looking for something to fill the spot that Atom left, I am using [Pulsar](https://pulsar-edit.dev/) _the successor to Atom_...   This package is working except for one deprecated error listed in #2605

If you don't need this anymore, can you please close this out so it's not just sitting there? Thanks
