### ISSUE TITLE
Uncaught Error: Cannot find module '$ATOM_HOME/packages\atom-beautify\node_modules\underscore-plu...

### ISSUE THREAD

**Issue by merarymm3** [Glavin001/atom-beautify#2567]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: Unknown Windows version
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.33.4

### Stack Trace

Uncaught Error: Cannot find module 'C:\Users\Merary\.atom\packages\atom-beautify\node_modules\underscore-plus\lib\underscore-plus.js'. Please verify that the package.json has a valid "main" entry

```
At internal/modules/cjs/loader.js:240

Error: Cannot find module 'C:\Users\Merary\.atom\packages\atom-beautify\node_modules\underscore-plus\lib\underscore-plus.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:232:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:369:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:614:27)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.55.0/resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:155387)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:146720)
    at /packages/atom-beautify/src/beautifiers/index.coffee:2:9)
    at /packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at /packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:146720)
    at /packages/atom-beautify/src/beautify.coffee:9:15)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:1:736637)
    at requireModule (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:14:1122229)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:3509026)
    at Package.activateConfig (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:3498314)
    at PackageManager.packageHasSettings (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:910238)
    at PackageCard.hasSettings (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:14:2652788)
    at PackageCard.updateSettingsState (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:14:2643056)
    at PackageCard.updateInterfaceState (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:14:2642879)
    at ~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:14:2650547
    at ~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:14:2653039
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:1190181)
    at Emitter.emit (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:1191622)
    at PackageManager.emitPackageEvent (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:919695)
    at PackageManager.uninstall (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:917314)
    at PackageCard.uninstall (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:14:2654057)
    at HTMLButtonElement.uninstallButtonClickHandler (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:14:2639459)
```

### Commands

```
     -5:19 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-live-server 2.3.0 
emmet 2.4.3 
file-icons 2.1.46 
my-package 0.0.0 
```

**Comment by SilentGlasses** [comment]
If you still need this and are looking for something to fill the spot that Atom left, I am using [Pulsar](https://pulsar-edit.dev/) _the successor to Atom_...   This package is working except for one deprecated error listed in #2605

If you don't need this anymore, can you please close this out so it's not just sitting there? Thanks
