### ISSUE TITLE
failed  to activate atom beautify

### ISSUE THREAD

**Issue by hadisy92** [Glavin001/atom-beautify#2568]
# Description

The results of beautification are not what I expect.

# Input Before Beautification

This is what the code looked like before:

```
<INSERT CODE HERE>
```

# Expected Output

The beautified code should have looked like this:

```
<INSERT CODE HERE>
```

# Actual Output

The beautified code actually looked like this:

```
<INSERT CODE HERE>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>

# Checklist

I have:
- [ ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by hadisy92** [comment]
Cannot find module './compile'
Require stack:
- C:\Users\hp\.atom\packages\atom-beautify\node_modules\har-validator\node_modules\ajv\lib\ajv.js
- C:\Users\hp\.atom\packages\atom-beautify\node_modules\har-validator\lib\promise.js
- C:\Users\hp\.atom\packages\atom-beautify\node_modules\request\lib\har.js
- C:\Users\hp\.atom\packages\atom-beautify\node_modules\request\request.js
- C:\Users\hp\.atom\packages\atom-beautify\node_modules\request\index.js
- C:\Users\hp\.atom\packages\atom-beautify\node_modules\universal-analytics\lib\index.js
- C:\Users\hp\.atom\packages\atom-beautify\node_modules\universal-analytics\index.js
- C:\Users\hp\.atom\packages\atom-beautify\src\beautifiers\index.coffee
- C:\Users\hp\.atom\packages\atom-beautify\src\beautify.coffee
- C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app.asar\static\index.html
Hide Stack Trace
Error: Cannot find module './compile'
Require stack:
- C:\Users\hp\.atom\packages\atom-beautify\node_modules\har-validator\node_modules\ajv\lib\ajv.js
- C:\Users\hp\.atom\packages\atom-beautify\node_modules\har-validator\lib\promise.js
- C:\Users\hp\.atom\packages\atom-beautify\node_modules\request\lib\har.js
- C:\Users\hp\.atom\packages\atom-beautify\node_modules\request\request.js
- C:\Users\hp\.atom\packages\atom-beautify\node_modules\request\index.js
- C:\Users\hp\.atom\packages\atom-beautify\node_modules\universal-analytics\lib\index.js
- C:\Users\hp\.atom\packages\atom-beautify\node_modules\universal-analytics\index.js
- C:\Users\hp\.atom\packages\atom-beautify\src\beautifiers\index.coffee
- C:\Users\hp\.atom\packages\atom-beautify\src\beautify.coffee
- C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:157820)
    at Module.require (file:///C:/Users/hp/AppData/Local/atom/app-1.56.0/resources/app.asar/static/index.js:61:43)
    at require (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:149153)
    at Object.<anonymous> (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app.asar\node_modules\ajv\lib\ajv.js:3:21)
    at Object.<anonymous> (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app.asar\node_modules\ajv\lib\ajv.js:508:3)
    at Module.get_Module._compile (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:149837)
    at Object.value [as .js] (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (file:///C:/Users/hp/AppData/Local/atom/app-1.56.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:149153)
    at Object.<anonymous> (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app.asar\node_modules\har-validator\lib\promise.js:1:166)
    at Object.<anonymous> (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app.asar\node_modules\har-validator\lib\promise.js:104:3)
    at Module.get_Module._compile (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:149837)
    at Object.value [as .js] (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (file:///C:/Users/hp/AppData/Local/atom/app-1.56.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:149153)
    at Object.<anonymous> (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app.asar\node_modules\request\lib\har.js:5:16)
    at Object.<anonymous> (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app.asar\node_modules\request\lib\har.js:207:3)
    at Module.get_Module._compile (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:149837)
    at Object.value [as .js] (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (file:///C:/Users/hp/AppData/Local/atom/app-1.56.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:149153)
    at Object.<anonymous> (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app.asar\node_modules\request\request.js:23:11)
    at Object.<anonymous> (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app.asar\node_modules\request\request.js:1555:3)
    at Module.get_Module._compile (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:149837)
    at Object.value [as .js] (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (file:///C:/Users/hp/AppData/Local/atom/app-1.56.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:149153)
    at Object.<anonymous> (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app.asar\node_modules\request\index.js:143:19)
    at Object.<anonymous> (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app.asar\node_modules\request\index.js:157:3)
    at Module.get_Module._compile (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:149837)
    at Object.value [as .js] (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (file:///C:/Users/hp/AppData/Local/atom/app-1.56.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:149153)
    at Object.<anonymous> (C:\Users\hp\.atom\packages\dli-atom-beautify\node_modules\universal-analytics\lib\index.js:2:15)
    at Object.<anonymous> (C:\Users\hp\.atom\packages\dli-atom-beautify\node_modules\universal-analytics\lib\index.js:565:3)
    at Module.get_Module._compile (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:149837)
    at Object.value [as .js] (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (file:///C:/Users/hp/AppData/Local/atom/app-1.56.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:149153)
    at Object.<anonymous> (C:\Users\hp\.atom\packages\dli-atom-beautify\node_modules\universal-analytics\index.js:2:18)
    at Object.<anonymous> (C:\Users\hp\.atom\packages\dli-atom-beautify\node_modules\universal-analytics\index.js:4:3)
    at Module.get_Module._compile (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:149837)
    at Object.value [as .js] (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (file:///C:/Users/hp/AppData/Local/atom/app-1.56.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:149153)
    at C:\Users\hp\.atom\packages\dli-atom-beautify\src\beautifiers\index.coffee:37:17
    at exports.allowUnsafeEval (C:\Users\hp\.atom\packages\dli-atom-beautify\node_modules\loophole\lib\loophole.js:14:14)
    at Object.<anonymous> (C:\Users\hp\.atom\packages\dli-atom-beautify\src\beautifiers\index.coffee:36:3)
    at Object.<anonymous> (C:\Users\hp\.atom\packages\dli-atom-beautify\src\beautifiers\index.coffee:674:4)
    at Object.<anonymous> (C:\Users\hp\.atom\packages\dli-atom-beautify\src\beautifiers\index.coffee:678:3)
    at Module.get_Module._compile (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:149837)
    at Object.value [as .coffee] (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (file:///C:/Users/hp/AppData/Local/atom/app-1.56.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:149153)
    at Object.<anonymous> (C:\Users\hp\.atom\packages\dli-atom-beautify\src\beautify.coffee:13:17)
    at Object.<anonymous> (C:\Users\hp\.atom\packages\dli-atom-beautify\src\beautify.coffee:587:4)
    at Object.<anonymous> (C:\Users\hp\.atom\packages\dli-atom-beautify\src\beautify.coffee:591:3)
    at Module.get_Module._compile (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:149837)
    at Object.value [as .coffee] (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (file:///C:/Users/hp/AppData/Local/atom/app-1.56.0/resources/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:1:802769)
    at requireModule (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:14:1126115)
    at Package.requireMainModule (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:3496608)
    at Package.activateNow (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:3484592)
    at C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:14:2607
    at Function.simpleDispatch (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:1182710)
    at Emitter.emit (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:1184151)
    at PackageManager.triggerDeferredActivationHooks (C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:385466)
    at C:\Users\hp\AppData\Local\atom\app-1.56.0\resources\app\static\<embedded>:11:384217

**Comment by SilentGlasses** [comment]
If you still need this and are looking for something to fill the spot that Atom left, I am using [Pulsar](https://pulsar-edit.dev/) _the successor to Atom_...   This package is working except for one deprecated error listed in #2605

If you don't need this anymore, can you please close this out so it's not just sitting there? Thanks
