### ISSUE TITLE
Failed to activate the atom-beautify package

### ISSUE THREAD

**Issue by rahulsah02** [Glavin001/atom-beautify#2577]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.33.4

### Stack Trace

Failed to activate the atom-beautify package

```
At Cannot find module './uncrustify'
Require stack:
- C:\Users\sahra\.atom\packages\atom-beautify\src\beautifiers\index.coffee
- C:\Users\sahra\.atom\packages\atom-beautify\src\beautify.coffee
- C:\Users\sahra\AppData\Local\atom\app-1.57.0\resources\app.asar\static\index.html

Error: Cannot find module './uncrustify'
Require stack:
- C:\Users\sahra\.atom\packages\atom-beautify\src\beautifiers\index.coffee
- C:\Users\sahra\.atom\packages\atom-beautify\src\beautify.coffee
- C:\Users\sahra\AppData\Local\atom\app-1.57.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:157820)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149153)
    at /packages/atom-beautify/src/beautifiers/index.coffee:120:20
    at arrayMap (/packages/atom-beautify/node_modules/lodash/lodash.js:653:23)
    at Function.map (/packages/atom-beautify/node_modules/lodash/lodash.js:9622:14)
    at /packages/atom-beautify/src/beautifiers/index.coffee:119:22)
    at /packages/atom-beautify/src/beautify.coffee:10:14)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149837)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:1:802772)
    at requireModule (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:1191588)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:3520819)
    at Package.activateNow (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:3508803)
    at ~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1186190)
    at Emitter.emit (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:1187631)
    at PackageManager.triggerDeferredActivationHooks (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:385941)
    at ~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:384692
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ternjs 0.20.0 
```

**Comment by Josiseh** [comment]
I have issues in installing this package atom-beautify to my atom editor, how #2292  I rectify this please

**Comment by AshwathMittal** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.57.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.33.4


### Stack Trace

Failed to activate the atom-beautify package

```
At Cannot find module 'C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\sshpk\lib\index.js'. Please verify that the package.json has a valid "main" entry

Error: Cannot find module 'C:\Users\Administrator\.atom\packages\atom-beautify\node_modules\sshpk\lib\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:301:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:532:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:784:27)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:157820)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149153)
    at /app.asar/node_modules/http-signature/lib/utils.js:4:13)
    at /app.asar/node_modules/http-signature/lib/utils.js:114:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149153)
    at /app.asar/node_modules/http-signature/lib/parser.js:5:13)
    at /app.asar/node_modules/http-signature/lib/parser.js:317:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149153)
    at /app.asar/node_modules/http-signature/lib/index.js:3:14)
    at /app.asar/node_modules/http-signature/lib/index.js:31:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149837)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:153385)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.57.0/resources/app/static/<embedded>:11:149153)
    at /app.asar/node_modules/request/request.js:11:21)
    at /app.asar/node_modules/request/request.js:1555:3)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
```

How do i fix this ???

**Comment by ridarida2209** [comment]
Failed to activate the atom-beautify package

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Education
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.33.4


### Stack Trace

Failed to activate the atom-beautify package

```
At Cannot find module 'event-kit'
Require stack:
- C:\Users\janna\.atom\packages\atom-beautify\src\beautify.coffee
- C:\Users\janna\AppData\Local\atom\app-1.58.0\resources\app.asar\static\index.html

Error: Cannot find module 'event-kit'
Require stack:
- C:\Users\janna\.atom\packages\atom-beautify\src\beautify.coffee
- C:\Users\janna\AppData\Local\atom\app-1.58.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:157920)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149207)
    at /packages/atom-beautify/src/beautify.coffee:7:25)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149891)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:1:802772)
    at requireModule (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:1195622)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3520513)
    at Package.activateNow (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3508497)
    at ~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:1186925)
    at Emitter.emit (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:1188366)
    at PackageManager.triggerDeferredActivationHooks (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:386056)
    at ~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:384807
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.6 
atom-ternjs 0.20.0 
csslint 1.2.0 
emmet 2.4.3 
language-ejs 0.4.0 
linter 3.4.0 
linter-eslint 8.6.6 
pigments 0.40.6 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by AshwathMittal** [comment]
> Failed to activate the atom-beautify package
> 
> 1. ...
> 2. ...
> 
> **Atom**: 1.58.0 x64
> **Electron**: 9.4.4
> **OS**: Microsoft Windows 10 Education
> **Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.33.4
> 
> ### Stack Trace
> Failed to activate the atom-beautify package
> 
> ```
> At Cannot find module 'event-kit'
> Require stack:
> - C:\Users\janna\.atom\packages\atom-beautify\src\beautify.coffee
> - C:\Users\janna\AppData\Local\atom\app-1.58.0\resources\app.asar\static\index.html
> 
> Error: Cannot find module 'event-kit'
> Require stack:
> - C:\Users\janna\.atom\packages\atom-beautify\src\beautify.coffee
> - C:\Users\janna\AppData\Local\atom\app-1.58.0\resources\app.asar\static\index.html
>     at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
>     at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
>     at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:157920)
>     at Module.require (/app.asar/static/index.js:61:43)
>     at require (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149207)
>     at /packages/atom-beautify/src/beautify.coffee:7:25)
>     at /packages/atom-beautify/src/beautify.coffee:2:1)
>     at /packages/atom-beautify/src/beautify.coffee:2:1)
>     at Module.get_Module._compile (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149891)
>     at Object.value [as .coffee] (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:153485)
>     at Module.load (internal/modules/cjs/loader.js:815:32)
>     at Module._load (internal/modules/cjs/loader.js:727:14)
>     at Function.Module._load (electron/js2c/asar.js:769:28)
>     at Module.require (/app.asar/static/index.js:72:46)
>     at require (internal/modules/cjs/helpers.js:74:18)
>     at customRequire (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:1:802772)
>     at requireModule (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:1195622)
>     at Package.requireMainModule (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3520513)
>     at Package.activateNow (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3508497)
>     at ~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:2607
>     at Function.simpleDispatch (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:1186925)
>     at Emitter.emit (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:1188366)
>     at PackageManager.triggerDeferredActivationHooks (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:386056)
>     at ~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:384807
> ```
> 
> ### Commands
> ### Non-Core Packages
> ```
> atom-beautify 0.33.4 
> atom-html-preview 0.2.6 
> atom-ternjs 0.20.0 
> csslint 1.2.0 
> emmet 2.4.3 
> language-ejs 0.4.0 
> linter 3.4.0 
> linter-eslint 8.6.6 
> pigments 0.40.6 
> Sublime-Style-Column-Selection 1.7.5 
> ```


Reinstall it simple

**Comment by chriswakare** [comment]
A reinstall worked for me on mac 10.15.6

**Comment by Franriv88** [comment]
Hello! I have an error with the atom-beautify package:

Error: Cannot find module 'winston'
Require stack:
- C:\Users\SRV\.atom\packages\atom-beautify\src\logger.coffee
- C:\Users\SRV\.atom\packages\atom-beautify\src\beautifiers\index.coffee
- C:\Users\SRV\.atom\packages\atom-beautify\src\beautify.coffee
- C:\Users\SRV\AppData\Local\atom\app-1.58.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (C:\Users\SRV\AppData\Local\atom\app-1.58.0\resources\app\static\<embedded>:11:157920)
    at Module.require (file:///C:/Users/SRV/AppData/Local/atom/app-1.58.0/resources/app.asar/static/index.js:61:43)
    at require (C:\Users\SRV\AppData\Local\atom\app-1.58.0\resources\app\static\<embedded>:11:149207)
    at file:///C:/Users/SRV/.atom/packages/atom-beautify/src/logger.coffee:10:13
    at Object.<anonymous> (file:///C:/Users/SRV/.atom/packages/atom-beautify/src/logger.coffee:4:18)
    at Object.<anonymous> (file:///C:/Users/SRV/.atom/packages/atom-beautify/src/logger.coffee:1:1)
    at Object.<anonymous> (file:///C:/Users/SRV/.atom/packages/atom-beautify/src/logger.coffee:1:1)
    at Module.get_Module._compile (C:\Users\SRV\AppData\Local\atom\app-1.58.0\resources\app\static\<embedded>:11:149891)
    at Object.value [as .coffee] (C:\Users\SRV\AppData\Local\atom\app-1.58.0\resources\app\static\<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (file:///C:/Users/SRV/AppData/Local/atom/app-1.58.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\SRV\AppData\Local\atom\app-1.58.0\resources\app\static\<embedded>:11:149207)
    at Object.<anonymous> (file:///C:/Users/SRV/.atom/packages/atom-beautify/src/beautifiers/index.coffee:6:10)
    at Object.<anonymous> (file:///C:/Users/SRV/.atom/packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at Object.<anonymous> (file:///C:/Users/SRV/.atom/packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at Module.get_Module._compile (C:\Users\SRV\AppData\Local\atom\app-1.58.0\resources\app\static\<embedded>:11:149891)
    at Object.value [as .coffee] (C:\Users\SRV\AppData\Local\atom\app-1.58.0\resources\app\static\<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (file:///C:/Users/SRV/AppData/Local/atom/app-1.58.0/resources/app.asar/static/index.js:72:46)
    at require (C:\Users\SRV\AppData\Local\atom\app-1.58.0\resources\app\static\<embedded>:11:149207)
    at Object.<anonymous> (file:///C:/Users/SRV/.atom/packages/atom-beautify/src/beautify.coffee:9:15)
    at Object.<anonymous> (file:///C:/Users/SRV/.atom/packages/atom-beautify/src/beautify.coffee:2:1)
    at Object.<anonymous> (file:///C:/Users/SRV/.atom/packages/atom-beautify/src/beautify.coffee:2:1)
    at Module.get_Module._compile (C:\Users\SRV\AppData\Local\atom\app-1.58.0\resources\app\static\<embedded>:11:149891)
    at Object.value [as .coffee] (C:\Users\SRV\AppData\Local\atom\app-1.58.0\resources\app\static\<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (file:///C:/Users/SRV/AppData/Local/atom/app-1.58.0/resources/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)

**Comment by chema64** [comment]
Cannot find module 'C:\Users\jerem\.atom\packages\atom-beautify\node_modules\event-kit\dist\event-kit'. Please verify that the package.json has a valid "main" entry
Hide Stack Trace
Error: Cannot find module 'C:\Users\jerem\.atom\packages\atom-beautify\node_modules\event-kit\dist\event-kit'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:301:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:532:18)
    at Module._resolveFilename (internal/modules/cjs/loader.js:784:27)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (C:\Users\jerem\AppData\Local\atom\app-1.58.0\resources\app\static\<embedded>:11:157920)
    at Module.require (file:///C:/Users/jerem/AppData/Local/atom/app-1.58.0/resources/app.asar/static/index.js:61:43)
    at require (C:\Users\jerem\AppData\Local\atom\app-1.58.0\resources\app\static\<embedded>:11:149207)
    at Object.<anonymous> (file:///C:/Users/jerem/.atom/packages/atom-beautify/src/beautify.coffee:7:25)
    at Object.<anonymous> (file:///C:/Users/jerem/.atom/packages/atom-beautify/src/beautify.coffee:2:1)
    at Object.<anonymous> (file:///C:/Users/jerem/.atom/packages/atom-beautify/src/beautify.coffee:2:1)
    at Module.get_Module._compile (C:\Users\jerem\AppData\Local\atom\app-1.58.0\resources\app\static\<embedded>:11:149891)
    at Object.value [as .coffee] (C:\Users\jerem\AppData\Local\atom\app-1.58.0\resources\app\static\<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (file:///C:/Users/jerem/AppData/Local/atom/app-1.58.0/resources/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (C:\Users\jerem\AppData\Local\atom\app-1.58.0\resources\app\static\<embedded>:1:802772)
    at requireModule (C:\Users\jerem\AppData\Local\atom\app-1.58.0\resources\app\static\<embedded>:14:1195622)
    at Package.requireMainModule (C:\Users\jerem\AppData\Local\atom\app-1.58.0\resources\app\static\<embedded>:11:3520513)
    at Package.activateNow (C:\Users\jerem\AppData\Local\atom\app-1.58.0\resources\app\static\<embedded>:11:3508497)
    at C:\Users\jerem\AppData\Local\atom\app-1.58.0\resources\app\static\<embedded>:14:2607
    at Function.simpleDispatch (C:\Users\jerem\AppData\Local\atom\app-1.58.0\resources\app\static\<embedded>:11:1186925)
    at Emitter.emit (C:\Users\jerem\AppData\Local\atom\app-1.58.0\resources\app\static\<embedded>:11:1188366)
    at PackageManager.triggerDeferredActivationHooks (C:\Users\jerem\AppData\Local\atom\app-1.58.0\resources\app\static\<embedded>:11:386056)
    at C:\Users\jerem\AppData\Local\atom\app-1.58.0\resources\app\static\<embedded>:11:384807

**Comment by PoojaShah9573** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Home
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.33.4


### Stack Trace

Failed to activate the atom-beautify package

```
At Cannot find module 'event-kit'
Require stack:
- C:\Users\pooja\.atom\packages\atom-beautify\src\beautify.coffee
- C:\Users\pooja\AppData\Local\atom\app-1.58.0\resources\app.asar\static\index.html

Error: Cannot find module 'event-kit'
Require stack:
- C:\Users\pooja\.atom\packages\atom-beautify\src\beautify.coffee
- C:\Users\pooja\AppData\Local\atom\app-1.58.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:157920)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149207)
    at /packages/atom-beautify/src/beautify.coffee:7:25)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149891)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:1:802772)
    at requireModule (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:1195622)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3520513)
    at Package.activateNow (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3508497)
    at ~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:1186925)
    at Emitter.emit (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:1188366)
    at PackageManager.triggerDeferredActivationHooks (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:386056)
    at ~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:384807
```

### Commands

```
     -1:25.6.0 intentions:highlight (input.hidden-input)
     -1:25.5.0 core:select-all (input.hidden-input)
     -1:21.7.0 prettier:format (input.hidden-input)
     -1:19.5.0 linter:lint (atom-text-editor.editor.is-focused.has-selection)
     -1:13.2.0 intentions:highlight (input.hidden-input)
     -1:13 core:select-all (input.hidden-input)
     -1:09.1.0 core:move-right (input.hidden-input)
     -1:08.8.0 editor:newline (input.hidden-input)
     -1:08.1.0 core:move-down (input.hidden-input)
  2x -1:07.6.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-formatter-jsbeautify 1.1.2 
atom-material-ui 2.1.3 
busy-signal 2.0.1 
devmind-beautifier 1.3.0 
intentions 2.1.1 
linter 3.4.0 
linter-ui-default 3.4.1 
prettier-atom 0.60.1 
```

**Comment by rir7890** [comment]
if you are window user then it is difficult to use so, what is solution .
answer is simple use visual studio code.

**Comment by Light023** [comment]
hello pls help me out 

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.59.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.33.4


### Stack Trace

Failed to activate the atom-beautify package

```
At Cannot read property 'File' of undefined

TypeError: Cannot read property 'File' of undefined
    at /packages/atom-beautify/src/logger.coffee:33:41
    at /packages/atom-beautify/src/beautifiers/index.coffee:6:10)
    at /packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at /packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:11:149891)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:11:149207)
    at /packages/atom-beautify/src/beautify.coffee:9:15)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:11:149891)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:1:789785)
    at requireModule (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:14:1173504)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:11:3542837)
    at Package.activateNow (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:11:3530836)
    at ~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:11:1187446)
    at Emitter.emit (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:11:1188887)
    at ~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:11:386316
    at Set.forEach (<anonymous>)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:11:386278)
    at ~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:11:915554
    at r (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:11:910160)
    at s (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:14:1172827)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:14:1173033)
    at ChildProcess.emit (events.js:223:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.7 
atom-ternjs 0.20.0 
autoclose-html-plus 0.27.2 
csslint 1.2.0 
emmet 2.4.3 
language-ejs 0.4.0 
linter 3.4.0 
linter-eslint 9.0.0 
pigments 0.40.6 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by SilentGlasses** [comment]
If you still need this and are looking for something to fill the spot that Atom left, I am using [Pulsar](https://pulsar-edit.dev/) _the successor to Atom_...   This package is working except for one deprecated error listed in #2605

If you don't need this anymore, can you please close this out so it's not just sitting there? Thanks
