### ISSUE TITLE
Unable to beautify vanilla Javascript or HTML or JSON. No eligible build target.: No configuration to build this project exists.

### ISSUE THREAD

**Issue by bassamanator** [Glavin001/atom-beautify#2580]
# Description

I've been using atom-beautify for well over a year. My vanilla javascript and HTML code no longer beautifies. I get the following error:
```
No eligible build target.: No configuration to build this project exists.
    at /home/bassam/.atom/packages/build/lib/build.js:113:15
```
![image](https://user-images.githubusercontent.com/61985779/124685680-c0c16c00-de9f-11eb-83a6-08834d54e39a.png)

# Input Before Beautification

This is what the code looked like before:

Javascript
```
const
	CANVASWIDTH = 1020
```
HTML
```
<div class="row justify-content-center">
<div class="col-auto">
<button type="submit" class="btn btn-info">
I agree
</button>
</div>
</div>
```

# Expected Output

The beautified code should have looked like this:
Javascript
```
const CANVASWIDTH = 1020;
```
HTML
```
<div class="row justify-content-center">
	<div class="col-auto">
		<button type="submit" class="btn btn-info">
			I agree
		</button>
	</div>
</div>
```
# Actual Output

The beautified code actually looked like this:

```
No eligible build target.: No configuration to build this project exists.
    at /home/bassam/.atom/packages/build/lib/build.js:113:15
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. ~~This beautified code does not look right!~~ Gives error message posted above.

# Debug

Here is a link to the `debug.md` Gist: <https://gist.github.com/bassamanator/ccdb305fd74215bbacfa8ced25c12740>

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by bassamanator** [comment]
It seems there was a conflict between atom-beautify and another package (build). I've disabled the other package and all seems well.
