### ISSUE TITLE
PHP Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by xingkongwuhen** [Glavin001/atom-beautify#2582]
TypeError: Cannot read property 'split' of undefined
    at PHPCSFixer.module.exports.Beautifier.findFile (file:///C:/Users/longcai/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:138:25)
    at PHPCSFixer.module.exports.PHPCSFixer.beautify (file:///C:/Users/longcai/.atom/packages/atom-beautify/src/beautifiers/php-cs-fixer.coffee:65:39)
    at file:///C:/Users/longcai/.atom/packages/atom-beautify/src/beautifiers/index.coffee:363:28
    at tryCatcher (C:\Users\longcai\.atom\packages\atom-beautify\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\longcai\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\Users\longcai\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromiseCtx (C:\Users\longcai\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:641:10)
    at _drainQueueStep (C:\Users\longcai\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (C:\Users\longcai\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\longcai\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues (C:\Users\longcai\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:15:14)

**Comment by davidhealey** [comment]
Same here

**Comment by micahlt** [comment]
Same issue!

**Comment by SilentGlasses** [comment]
If you still need this and are looking for something to fill the spot that Atom left, I am using [Pulsar](https://pulsar-edit.dev/) _the successor to Atom_...   This package is working except for one deprecated error listed in #2605

If you don't need this anymore, can you please close this out so it's not just sitting there? Thanks
