### ISSUE TITLE
Undefined

### ISSUE THREAD

**Issue by ThalassaPower** [Glavin001/atom-beautify#2591]
undefined

Fail to clean temporary files on exit :  Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\skarlett\AppData\Local\Temp\apm-install-dir-2021823-21872-udcnbv.x1or\node_modules\atom-beautify\docs\code\file\src\beautifiers'
    at Object.rmdirSync (fs.js:752:3)
    at rmkidsSync (C:\Users\skarlett\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\temp\node_modules\rimraf\rimraf.js:356:25)
    at rmdirSync (C:\Users\skarlett\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\temp\node_modules\rimraf\rimraf.js:334:7)
    at rimrafSync (C:\Users\skarlett\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\temp\node_modules\rimraf\rimraf.js:304:9)
    at C:\Users\skarlett\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\temp\node_modules\rimraf\rimraf.js:342:5
    at Array.forEach (<anonymous>)
    at rmkidsSync (C:\Users\skarlett\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\temp\node_modules\rimraf\rimraf.js:341:26)
    at rmdirSync (C:\Users\skarlett\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\temp\node_modules\rimraf\rimraf.js:334:7)
    at rimrafSync (C:\Users\skarlett\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\temp\node_modules\rimraf\rimraf.js:304:9)
    at C:\Users\skarlett\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\temp\node_modules\rimraf\rimraf.js:342:5 {
  errno: -4051,
  syscall: 'rmdir',
  code: 'ENOTEMPTY',
  path: 'C:\\Users\\skarlett\\AppData\\Local\\Temp\\apm-install-dir-2021823-21872-udcnbv.x1or\\node_modules\\atom-beautify\\docs\\code\\file\\src\\beautifiers'
}

C:\Users\skarlett\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\temp\lib\temp.js:112
            throw err;
            ^

Error: ENOTEMPTY: directory not empty, rmdir 'C:\Users\skarlett\AppData\Local\Temp\apm-install-dir-2021823-21872-udcnbv.x1or\node_modules\atom-beautify\docs\code\file\src\beautifiers'

    at Object.rmdirSync (fs.js:752:3)

    at rmkidsSync (C:\Users\skarlett\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\temp\node_modules\rimraf\rimraf.js:356:25)

    at rmdirSync (C:\Users\skarlett\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\temp\node_modules\rimraf\rimraf.js:334:7)

    at rimrafSync (C:\Users\skarlett\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\temp\node_modules\rimraf\rimraf.js:304:9)

    at C:\Users\skarlett\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\temp\node_modules\rimraf\rimraf.js:342:5

    at Array.forEach (<anonymous>)

    at rmkidsSync (C:\Users\skarlett\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\temp\node_modules\rimraf\rimraf.js:341:26)

    at rmdirSync (C:\Users\skarlett\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\temp\node_modules\rimraf\rimraf.js:334:7)

    at rimrafSync (C:\Users\skarlett\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\temp\node_modules\rimraf\rimraf.js:304:9)

    at C:\Users\skarlett\AppData\Local\atom\app-1.58.0\resources\app\apm\node_modules\temp\node_modules\rimraf\rimraf.js:342:5 {

  errno: -4051,
  syscall: 'rmdir',

  code: 'ENOTEMPTY',

  path: 'C:\\Users\\skarlett\\AppData\\Local\\Temp\\apm-install-dir-2021823-21872-udcnbv.x1or\\node_modules\\atom-beautify\\docs\\code\\file\\src\\beautifiers'
}

**Comment by SilentGlasses** [comment]
If you still need this and are looking for something to fill the spot that Atom left, I am using [Pulsar](https://pulsar-edit.dev/) _the successor to Atom_...   This package is working except for one deprecated error listed in #2605

If you don't need this anymore, can you please close this out so it's not just sitting there? Thanks
