### ISSUE TITLE
Windows 11  Pro Failed to activate the atom-beautify package - Cannot find module 'request'

### ISSUE THREAD

**Issue by hwlberd** [Glavin001/atom-beautify#2598]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 11 Pro
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.33.4

### Stack Trace

Failed to activate the atom-beautify package

```
At Cannot find module 'request'
Require stack:
- C:\Users\Demir\.atom\packages\atom-beautify\node_modules\universal-analytics\lib\index.js
- C:\Users\Demir\.atom\packages\atom-beautify\node_modules\universal-analytics\index.js
- C:\Users\Demir\.atom\packages\atom-beautify\src\beautifiers\index.coffee
- C:\Users\Demir\.atom\packages\atom-beautify\src\beautify.coffee
- C:\Users\Demir\AppData\Local\atom\app-1.58.0\resources\app.asar\static\index.html

Error: Cannot find module 'request'
Require stack:
- C:\Users\Demir\.atom\packages\atom-beautify\node_modules\universal-analytics\lib\index.js
- C:\Users\Demir\.atom\packages\atom-beautify\node_modules\universal-analytics\index.js
- C:\Users\Demir\.atom\packages\atom-beautify\src\beautifiers\index.coffee
- C:\Users\Demir\.atom\packages\atom-beautify\src\beautify.coffee
- C:\Users\Demir\AppData\Local\atom\app-1.58.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:157920)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149207)
    at /packages/atom-beautify/node_modules/universal-analytics/lib/index.js:2:15)
    at /packages/atom-beautify/node_modules/universal-analytics/lib/index.js:565:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149891)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149207)
    at /packages/atom-beautify/node_modules/universal-analytics/index.js:2:18)
    at /packages/atom-beautify/node_modules/universal-analytics/index.js:4:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149891)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149207)
    at /packages/atom-beautify/src/beautifiers/index.coffee:20:8
    at exports.allowUnsafeEval (/packages/atom-beautify/node_modules/loophole/lib/loophole.js:14:14)
    at /packages/atom-beautify/src/beautifiers/index.coffee:19:1)
    at /packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at /packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149891)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149207)
    at /packages/atom-beautify/src/beautify.coffee:9:15)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149891)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:1:802772)
    at requireModule (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:1195622)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3520513)
    at Package.activateNow (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3508497)
    at ~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:1186925)
    at Emitter.emit (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:1188366)
    at PackageManager.triggerDeferredActivationHooks (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:386056)
    at ~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:384807
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
```

**Comment by hwlberd** [comment]
After reinstalling package few times solved for me
