### ISSUE TITLE
Uncaught TypeError: require(...) is not a function

### ISSUE THREAD

**Issue by PoojaShah9573** [Glavin001/atom-beautify#2600]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Home
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.33.4

### Stack Trace

Uncaught TypeError: require(...) is not a function

```
At C:\Users\pooja\.atom\packages\atom-beautify\src\beautifiers\index.coffee:6

TypeError: require(...) is not a function
    at /packages/atom-beautify/src/beautifiers/index.coffee:6:10)
    at /packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at /packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149891)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149207)
    at /packages/atom-beautify/src/beautify.coffee:9:15)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:149891)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:1:802772)
    at requireModule (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:1195622)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3520513)
    at Package.activateConfig (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:3509801)
    at PackageManager.packageHasSettings (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:908520)
    at PackageCard.hasSettings (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:2729736)
    at PackageCard.updateSettingsState (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:2720004)
    at PackageCard.updateInterfaceState (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:2719827)
    at new PackageCard (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:2711346)
    at PackageDetailView.completeInitialization (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:857941)
    at PackageDetailView.loadPackage (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:858508)
    at new PackageDetailView (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:14:855094)
    at SettingsView.getOrCreatePanel (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:930599)
    at SettingsView.showPanel (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:931320)
    at SettingsView.showDeferredPanel (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:931244)
    at SettingsView.initializePanels (~/AppData/Local/atom/app-1.58.0/resources/app/static/<embedded>:11:928701)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.18 
atom-formatter-jsbeautify 1.1.2 
auto-close-html2 0.7.0 
busy-signal 2.0.1 
emmet 2.4.3 
git-plus 8.7.1 
highlight-selected 0.17.0 
intentions 2.1.1 
language-ejs 0.4.0 
line-count 0.5.2 
linter 3.4.0 
linter-ui-default 3.4.1 
teletype 0.13.4 
```

**Comment by SilentGlasses** [comment]
If you still need this and are looking for something to fill the spot that Atom left, I am using [Pulsar](https://pulsar-edit.dev/) _the successor to Atom_...   This package is working except for one deprecated error listed in #2605

If you don't need this anymore, can you please close this out so it's not just sitting there? Thanks
