### ISSUE TITLE
permission denied on beaytify c file

### ISSUE THREAD

**Issue by WolfgangKrueger** [Glavin001/atom-beautify#2607]
# Description
I get this error when i beautify a simple c-file

Parsing: input202219-290435-1u48i28.5bkb.c as language C
do_source_file: Unable to create output202219-290435-1scrhj5.n26h.c: Permission denied (13)
Hide Stack Trace
Error: Parsing: input202219-290435-1u48i28.5bkb.c as language C
do_source_file: Unable to create output202219-290435-1scrhj5.n26h.c: Permission denied (13)
    at /home/beone/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:183:23
    at tryCatcher (/home/beone/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/beone/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/beone/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/beone/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/beone/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/home/beone/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/beone/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/beone/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues (/home/beone/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:15:14)

The file exists in /tmp, and i have rights to write.

-rw------- 1 one one 84 Feb  9 14:47 /tmp/input202219-290435-1u48i28.5bkb.c

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# 
# Checklist

I have:
- [x ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by SilentGlasses** [comment]
If you still need this and are looking for something to fill the spot that Atom left, I am using [Pulsar](https://pulsar-edit.dev/) _the successor to Atom_...   This package is working except for one deprecated error listed in #2605

If you don't need this anymore, can you please close this out so it's not just sitting there? Thanks
