### ISSUE TITLE
facing problem in installing atom beautify package

### ISSUE THREAD

**Issue by designerrrd** [Glavin001/atom-beautify#2610]
# Description

The results of beautification are not what I expect.

# Input Before Beautification

This is what the code looked like before:

```
<INSERT CODE HERE>
```

# Expected Output

The beautified code should have looked like this:

```
<INSERT CODE HERE>
```

# Actual Output

The beautified code actually looked like this:

```
<INSERT CODE HERE>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>

# Checklist

I have:
- [ ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.59.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.33.4

### Stack Trace

Failed to activate the atom-beautify package

```
At Cannot find module './lodash'
Require stack:
- C:\Users\Adeem A Usmani\.atom\packages\atom-beautify\node_modules\lodash\index.js
- C:\Users\Adeem A Usmani\.atom\packages\atom-beautify\src\beautify.coffee
- C:\Users\Adeem A Usmani\AppData\Local\atom\app-1.59.0\resources\app.asar\static\index.html

Error: Cannot find module './lodash'
Require stack:
- C:\Users\Adeem A Usmani\.atom\packages\atom-beautify\node_modules\lodash\index.js
- C:\Users\Adeem A Usmani\.atom\packages\atom-beautify\src\beautify.coffee
- C:\Users\Adeem A Usmani\AppData\Local\atom\app-1.59.0\resources\app.asar\static\index.html
    at Module._resolveFilename (internal/modules/cjs/loader.js:797:17)
    at o._resolveFilename (electron/js2c/renderer_init.js:43:689)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:11:157920)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:11:149207)
    at /packages/atom-beautify/node_modules/lodash/index.js:1:173)
    at /packages/atom-beautify/node_modules/lodash/index.js:2:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:11:149891)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:11:149207)
    at /packages/atom-beautify/src/beautify.coffee:8:5)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:11:149891)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:11:153485)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:1:789785)
    at requireModule (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:14:1173504)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:11:3542837)
    at Package.activateNow (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:11:3530836)
    at ~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.59.0/resources/app/static/<embedded>:11:1187446)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-html-preview 0.2.7 
atom-live-server 2.3.0 
atom-ternjs 0.20.0 
autoclose-html-plus 0.27.2 
csslint 1.2.0 
emmet 2.4.3 
file-icons 2.1.47 
language-ejs 0.4.0 
linter 3.4.0 
linter-eslint 9.0.0 
pigments 0.40.6 
Sublime-Style-Column-Selection 1.7.5 
```

**Comment by akstg** [comment]
I cant install atom-beauty in atom. 

This is the output message that pops up. 

Installing “atom-beautify@0.33.4” failed.[Hide output…]()

npm WARN deprecated jscs@3.0.7: JSCS has merged with ESLint! See - https://medium.com/@markelog/jscs-end-of-the-line-bc9bf0b3fdb2
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! Unexpected end of JSON input while parsing near '...remark-man":"^2.0.0",'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ATagoe\.atom\.apm\_logs\2022-03-11T07_11_21_767Z-debug.log

**Comment by SilentGlasses** [comment]
If you still need this and are looking for something to fill the spot that Atom left, I am using [Pulsar](https://pulsar-edit.dev/) _the successor to Atom_...   This package is working except for one deprecated error listed in #2605

If you don't need this anymore, can you please close this out so it's not just sitting there? Thanks
