### ISSUE TITLE
Failed to activate the atom-beautify package

### ISSUE THREAD

**Issue by HanaTran2909** [Glavin001/atom-beautify#2619]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**

**Actual behavior:**

### Versions

**Atom**: 1.60.0 x64
**Electron**: 9.4.4
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.33.4

### Stack Trace

Failed to activate the atom-beautify package

```
At ENOENT: no such file or directory, open 'C:\Users\Admin\.atom\packages\atom-beautify\node_modules\event-kit\dist\event-kit.js'

Error: ENOENT: no such file or directory, open 'C:\Users\Admin\.atom\packages\atom-beautify\node_modules\event-kit\dist\event-kit.js'
    at Object.openSync (fs.js:440:3)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Proxy.readFileSync (fs.js:342:35)
    at Proxy.fs.readFileSync (electron/js2c/asar.js:542:40)
    at compileFileAtPath (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:150809)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:153473)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:149229)
    at /packages/atom-beautify/src/beautify.coffee:7:25)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:149913)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:153507)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:74:18)
    at customRequire (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:1:802772)
    at requireModule (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:14:1175135)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:3543231)
    at Package.activateNow (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:3531230)
    at ~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:1187666)
    at Emitter.emit (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:1189107)
    at ~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:386347
    at Set.forEach (<anonymous>)
    at PackageManager.activatePackage (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:386309)
    at ~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:381221
    at Array.forEach (<anonymous>)
    at ~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:381205
    at ~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:338057
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:1187666)
    at Emitter.emit (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:1189107)
    at Config.emitChangeEvent (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:340545)
    at Config.setRawValue (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:337785)
    at Config.set (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:333579)
    at Config.removeAtKeyPath (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:335602)
    at Package.enable (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:3528351)
    at PackageManager.enablePackage (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:11:378824)
    at HTMLButtonElement.enablementButtonClickHandler (~/AppData/Local/atom/app-1.60.0/resources/app/static/<embedded>:14:2697622)
```

### Commands

```
 16x -9:52.6.0 core:backspace (input.hidden-input)
     -5:22 command-palette:toggle (summary.welcome-summary.icon.icon-keyboard)
 12x -4:16.5.0 core:backspace (input.hidden-input)
     -3:56 core:paste (input.hidden-input)
     -3:55.3.0 core:confirm (input.hidden-input)
 16x -3:10.2.0 core:backspace (input.hidden-input)
     -3:08.6.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ternjs 0.20.0 
autoclose-html 0.23.0 
csslint 1.2.0 
emmet 2.4.3 
language-ejs 0.4.0 
pigments 0.40.6 
```

### Additional Information

# Description

The results of beautification are not what I expect.

# Input Before Beautification

This is what the code looked like before:

```
<INSERT CODE HERE>
```

# Expected Output

The beautified code should have looked like this:

```
<INSERT CODE HERE>
```

# Actual Output

The beautified code actually looked like this:

```
<INSERT CODE HERE>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>

# Checklist

I have:
- [ ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by 18121A05L2** [comment]
Failed to activate the atom-beautify package

**Comment by matiashtml** [comment]
it dont work for me neither, idk what to do

**Comment by SilentGlasses** [comment]
If you still need this and are looking for something to fill the spot that Atom left, I am using [Pulsar](https://pulsar-edit.dev/) _the successor to Atom_...   This package is working except for one deprecated error listed in #2605

If you don't need this anymore, can you please close this out so it's not just sitting there? Thanks
