### ISSUE TITLE
Uncaught TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by seivan** [Glavin001/atom-beautify#304]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.196.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.26.2

### Stack Trace

Uncaught TypeError: Converting circular structure to JSON

```
At /Users/seivan/.atom/packages/atom-beautify/node_modules/analytics-node/node_modules/superagent/lib/node/index.js:801

TypeError: Converting circular structure to JSON
  at stringify (native)
  at Request.end (/Users/seivan/.atom/packages/atom-beautify/node_modules/analytics-node/node_modules/superagent/lib/node/index.js:801:29)
  at attemptRetry (/Users/seivan/.atom/packages/atom-beautify/node_modules/analytics-node/node_modules/superagent-retry/lib/index.js:38:21)
  at Request.end (/Users/seivan/.atom/packages/atom-beautify/node_modules/analytics-node/node_modules/superagent-retry/lib/index.js:48:12)
  at Analytics.flush (/Users/seivan/.atom/packages/atom-beautify/node_modules/analytics-node/lib/index.js:159:6)

```

### Commands

```
  7x -0:23.8.0 core:move-right (atom-text-editor.editor)
  3x -0:23.1.0 core:move-left (atom-text-editor.editor)
     -0:22.2.0 editor:move-to-end-of-line (atom-text-editor.editor)
     -0:22 editor:newline (atom-text-editor.editor)
     -0:20.8.0 core:undo (atom-text-editor.editor)
 16x -0:20.8.0 core:move-down (atom-text-editor.editor)
     -0:19.8.0 editor:newline (atom-text-editor.editor)
     -0:18 core:backspace (atom-text-editor.editor)
     -0:16.2.0 autocomplete-plus:confirm (atom-text-editor.editor)
     -0:13.7.0 editor:move-to-end-of-line (atom-text-editor.editor)
     -0:12.7.0 core:move-down (atom-text-editor.editor)
     -0:12.5.0 core:save (atom-text-editor.editor)
     -0:12.5.0 linter:lint (atom-text-editor.editor)
     -0:11.2.0 command-palette:toggle (atom-text-editor.editor)
     -0:09.8.0 core:confirm (atom-text-editor.editor.mini)
     -0:09.8.0 typescript:output-file-execute-in-iojs (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "railscast-theme"
    ],
    "disabledPackages": [
      "deprecation-cop",
      "feedback",
      "exception-reporting",
      "language-clojure",
      "language-csharp",
      "language-less",
      "language-php",
      "language-perl",
      "language-toml"
    ]
  },
  "atom-beautify": {
    "analytics": false
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-beautify, v0.26.2
atom-typescript, v4.1.0
autocomplete-css, v0.6.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.12.1
autocomplete-ruby, v0.1.0
autocomplete-snippets, v1.3.0
ember-cli-helper, v0.7.2
ember-snippets, v1.2.1
language-ember-script, v0.1.0
language-emblem, v0.1.0
language-swift, v0.4.0
linter, v0.12.1
linter-coffeelint, v0.2.2
linter-coffeescript, v0.1.1
linter-ruby, v0.1.4
linter-scss-lint, v0.0.14
linter-swiftc, v1.0.0
preview, v0.13.8
railscast-theme, v0.3.0
ruby-bundler, v0.2.1
script, v2.20.0

# Dev
No dev packages
```

**Comment by Glavin001** [comment]
Would you be able to run `Beautify - Help Debug Editor` in the same file that caused this error? Thank you.

**Comment by Glavin001** [comment]
There have been many releases after v0.26.2 and this bug has been unreproducible and unconfirmed by other users including myself.

If this issue is still applicable in latest versions, please let me know and we can reopen this. Thanks.

**Comment by Rulsky** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.0
**System**: Unknown Windows Version
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.28.19


### Stack Trace

Uncaught TypeError: Converting circular structure to JSON

```
At /C:/Users/Ruslan/.atom/packages/atom-ternjs/lib/atom-ternjs-client.coffee:46

TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at Client.module.exports.Client.update (C:\Users\Ruslan\.atom\packages\atom-ternjs\lib\atom-ternjs-client.coffee:46:29)
    at Type.module.exports.Type.queryType (file:///C:/Users/Ruslan/.atom/packages/atom-ternjs/lib/atom-ternjs-type.coffee:126:21)
    at Manager.onDidChangeCursorPosition (C:/Users/Ruslan/.atom/packages/atom-ternjs/lib/atom-ternjs-manager.js:309:17)
    at later (C:\Users\Ruslan\AppData\Local\atom\app-1.3.0\resources\app.asar\node_modules\underscore-plus\node_modules\underscore\underscore.js:724:25)
```

### Commands

```
     -7:45.7.0 tree-view:add-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -7:43.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -7:40.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 23x -7:10.8.0 atom-terminal-panel:toggle-autocompletion (atom-text-editor.editor.is-focused)
     -6:58.1.0 settings-view:open (input.autocomplete.autocomplete-input.autocomplete-text)
     -5:58.5.0 tree-view:open-selected-entry-right (span.name.icon.icon-file-text)
     -4:28.7.0 core:save (atom-text-editor.editor.is-focused)
     -4:10.5.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -4:10.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -4:09.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -4:09.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:28.1.0 settings-view:open (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/users/rulsky/dev_workspace",
    "disabledPackages": [
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-python",
      "language-yaml",
      "welcome",
      "atom-terminal-panel",
      "atom-ternjs"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.19
autocomplete-modules, v1.3.1
color-picker, v2.0.14
emmet, v2.3.17
file-icons, v1.6.13
jshint, v1.8.3
linter, v1.11.3
linter-csslint, v1.1.0
linter-htmlhint, v0.2.1
linter-jshint, v1.2.1
linter-jsonlint, v1.1.1
linter-scss-lint, v2.4.0
minimap, v4.18.0
pigments, v0.19.3
Remote-FTP, v0.7.14
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by Glavin001** [comment]
> At /C:/Users/Ruslan/.atom/packages/atom-ternjs/lib/atom-ternjs-client.coffee:46

@Rulsky looks like a atom-ternjs-client issue.
