### ISSUE TITLE
Unsupported language for grammar 'Null Grammar' with extension ''.

### ISSUE THREAD

**Issue by mingjunyang** [Glavin001/atom-beautify#313]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.196.0
**System**: linux 3.16.7-21-desktop
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.26.4

### Stack Trace

Unsupported language for grammar 'Null Grammar' with extension ''.

```
At Unsupported language for grammar 'Null Grammar' with extension ''.

Error: Unsupported language for grammar 'Null Grammar' with extension ''.
  at /home/mingjunyang/.atom/packages/atom-beautify/src/beautifiers/index.coffee:351:28
  at tryCatcher (/home/mingjunyang/.atom/packages/atom-beautify/node_modules/bluebird/js/main/util.js:24:31)
  at Promise._resolveFromResolver (/home/mingjunyang/.atom/packages/atom-beautify/node_modules/bluebird/js/main/promise.js:427:31)
  at new Promise (/home/mingjunyang/.atom/packages/atom-beautify/node_modules/bluebird/js/main/promise.js:53:37)
  at Beautifiers.module.exports.Beautifiers.beautify (/home/mingjunyang/.atom/packages/atom-beautify/src/beautifiers/index.coffee:230:20)
  at Object.beautify (/home/mingjunyang/.atom/packages/atom-beautify/src/beautify.coffee:133:16)
  at TextBuffer.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/emissary/lib/emitter.js:118:15)
  at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:910:14)
  at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:899:19)
  at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:592:26)
  at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:523:18)
  at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:506:19)
  at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:585:35)
  at atom-workspace.atom.commands.add.core:save (/usr/share/atom/resources/app.asar/src/workspace-element.js:310:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -2:25.7.0 command-palette:toggle (atom-pane.pane.active)
     -2:23.5.0 core:confirm (atom-text-editor.editor.mini)
     -2:23.5.0 settings-view:uninstall-themes (atom-pane.pane.active)
     -2:15.9.0 application:open-your-keymap (atom-workspace.workspace.scrollbars-visible-always.theme-solarized-dark-syntax.theme-atom-dark-ui)
     -1:00.6.0 key-binding-resolver:toggle (atom-pane.pane.active)
 21x -0:51.3.0 core:save (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "welcome",
      "javascript-snippets",
      "git-diff-details",
      "go-plus",
      "gocode",
      "language-csharp"
    ],
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ],
    "projectHome": "/home/mingjunyang/git"
  },
  "atom-beautify": {
    "_analyticsUserId": "9821831b-a2aa-4903-a52f-3599aea0f6c0",
    "js_keep_function_indentation": true,
    "css_newline_between_rules": true,
    "css_selector_separator_newline": true,
    "beautifyOnSave": true
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.1.0
atom-beautify, v0.26.4
atom-color-highlight, v3.0.9
autoclose-html, v0.15.0
autocomplete-css, v0.6.0
autocomplete-html, v0.6.0
autocomplete-plus, v2.12.1
language-cmake, v0.1.3
language-cython, v0.3.0
language-lua, v0.9.2
language-nginx, v0.5.2
language-r, v0.2.0
minimap, v4.8.0
minimap-git-diff, v4.1.2
pretty-json, v0.3.3
python-isort, v0.0.6

# Dev
No dev packages
```

**Comment by Glavin001** [comment]
Atom had not detected a language and your file had no extension to indicate what language it could be, so there is nothing Atom Beautify could do to detect which language and how to beautify it. 

I will be making this notification less aggressive with #317.

Closing this as it is expected behaviour and not an error.
