### ISSUE TITLE
Uncaught Error: Cannot find module 'lodash'

### ISSUE THREAD

**Issue by PaulBGD** [Glavin001/atom-beautify#329]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.196.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.27.0

### Stack Trace

Uncaught Error: Cannot find module 'lodash'

```
At module.js:330

Error: Cannot find module 'lodash'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/paul-mac/.atom/packages/atom-beautify/src/beautify.coffee:7:5)
  at Object.<anonymous> (/Users/paul-mac/.atom/packages/atom-beautify/src/beautify.coffee:3:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:691:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:239:12)
  at PackageDetailView.module.exports.PackageDetailView.activate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:163:26)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:201:12)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:235:24
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:155:30
  at Array.forEach (native)
  at PackageManager.module.exports.Emitter.emitSlow (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:154:47)
  at PackageManager.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:107:30)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:414:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:323:26
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:41:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
     -9:12.8.0 application:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -8:29 editor:consolidate-selections (atom-text-editor.editor)
     -4:17.2.0 window:install-shell-commands (atom-text-editor.editor)
     -3:15.7.0 settings-view:uninstall-packages (atom-text-editor.editor)
     -3:07.3.0 settings-view:install-packages-and-themes (div.settings-view.pane-item)
  2x -3:01.3.0 core:select-all (atom-text-editor.editor.mini)
  3x -2:55.7.0 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
language-ejs, v0.1.0

# Dev
No dev packages
```

**Comment by Glavin001** [comment]
This is weird. Lodash is a dependency: https://github.com/Glavin001/atom-beautify/blob/master/package.json#L66

Could you try uninstalling and re-installing Atom Beautify?

**Comment by Glavin001** [comment]
Let me know if a clean install did not work and we can reopen this issue.

**Comment by simonneutert** [comment]
same problem here :-(

happens when trying to install

**Comment by Glavin001** [comment]
Uninstall and re-install. See if that helps. Also you could go into where the Atom packages are stored and run `npm install` under `atom-beautify` package.

**Comment by krothu** [comment]
I had the same problem and running 'npm install' in the Atom packages folder fixed it.
