### ISSUE TITLE
Failed to load the atom-beautify package

### ISSUE THREAD

**Issue by v3ss0n** [Glavin001/atom-beautify#355]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.201.0-5ae0ae7
**System**: linux 3.17.0-sabayon
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.6.3

### Stack Trace

Failed to load the atom-beautify package

```
At Cannot find module 'strip-json-comments'

Error: Cannot find module 'strip-json-comments'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/opt/atom/resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/v3ss/atom-beautify/lib/beautify.coffee:8:9)
  at Object.<anonymous> (/home/v3ss/atom-beautify/lib/beautify.coffee:3:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/opt/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/opt/atom/resources/app.asar/src/package.js:709:34)
  at /opt/atom/resources/app.asar/src/package.js:186:28
  at Package.module.exports.Package.measure (/opt/atom/resources/app.asar/src/package.js:163:15)
  at Package.module.exports.Package.load (/opt/atom/resources/app.asar/src/package.js:177:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/opt/atom/resources/app.asar/src/package-manager.js:355:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/opt/atom/resources/app.asar/src/package-manager.js:434:30)
  at /opt/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:292:29
  at exit (/opt/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:41:16)
  at triggerExitCallback (/opt/atom/resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/opt/atom/resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
     -5:11.3.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.cursor-bordered-box.theme-steam-pirate-syntax.theme-steam-pirate-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-ruby-on-rails",
      "mobile-preview",
      "atom-html-preview",
      "color-picker",
      "run-command",
      "runcoderun",
      "whitespace",
      "svg-preview",
      "autosave",
      "autocomplete-jedi",
      "autocomplete-plus-async",
      "cute-cursor",
      "pulsing-cursor",
      "neon-selection",
      "atom-lint",
      "animation-showcase",
      "tree-view-open-files",
      "autocomplete",
      "ease-blink",
      "highlight-line",
      "minimap-highlight-selected",
      "minimap",
      "markdown-writer",
      "atom-alignment",
      "autocomplete-atom-api",
      "fancy-input",
      "auto-reveal-in-sidebar",
      "sublime-tabs",
      "spell-check"
    ],
    "ignoredNames": [
      "*.pyc",
      "/home/v3ss/workspace/phwa.be/condaenv",
      "/home/v3ss/workspace/phwa.be/pypyenv",
      "*.zip",
      "*.tar",
      ".hg"
    ],
    "autoHideMenuBar": true,
    "audioBeep": false,
    "themes": [
      "steam-pirate-ui",
      "steam-pirate-syntax"
    ]
  },
  "atom-beautify": {
    "_analyticsUserId": "1b3ce0cd-794f-4b7e-b94d-d4c413fd852a",
    "analytics": false,
    "python_autopep8_path": "/usr/bin/autopep8",
    "html_indent_inner_html": true,
    "js_indent_size": 2
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.27.4
autocomplete-plus-python-jedi, v0.3.5
block-cursor, v0.12.5
block-travel, v1.0.2
build, v0.33.0
editorconfig, v1.0.0
file-type-icons, v0.6.0
flex-tool-bar, v0.2.1
highlight-column, v0.4.0
highlight-selected, v0.9.3
linter, v0.12.6
linter-coffeelint, v0.2.3
linter-csslint, v0.0.12
linter-flake8, v1.4.1
linter-jshint, v0.1.4
linter-tidy, v1.0.1
linter-xmllint, v0.0.5
local-history, v3.1.0
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.2.0
minimap-selection, v4.2.0
pdf-view, v0.22.0
pigments, v0.3.1
script, v2.23.0
script-runner, v1.8.3
steam-pirate-syntax, v0.2.0
steam-pirate-ui, v0.3.1
symbols-tree-view, v0.9.3
tabs-to-spaces, v0.10.0
tool-bar, v0.1.1
tool-bar-main, v0.0.8
web-browser, v1.4.4

# Dev
No dev packages
```

**Comment by Glavin001** [comment]
> Thrown From: atom-beautify package, v0.6.3

Looks like Atom has not properly reloaded Atom Beautify. Please restart.

Let me know if this issue is still applicable and I can reopen.

**Comment by v3ss0n** [comment]
yes reloading fixed, thanks
