### ISSUE TITLE
Failed to activate the atom-beautify package: "Cannot find module './lib/_stream_readable.js'"

### ISSUE THREAD

**Issue by tknerr** [Glavin001/atom-beautify#381]
I reproducably get this error after opening atom and then trying to beautify something:

![image](https://cloud.githubusercontent.com/assets/365744/7902052/17998e92-07a9-11e5-80fb-8b0717f00008.png)

This is on Atom 0.199.0 with atom-beautify 0.27.1

Stacktrace here:
```
Failed to activate the atom-beautify package

Cannot find module './lib/_stream_readable.js'
Hide Stack Trace
Error: Cannot find module './lib/_stream_readable.js'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (W:\tools\atom\Atom\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (W:\home\.atom\packages\atom-beautify\node_modules\analytics-node\node_modules\superagent-proxy\node_modules\proxy-agent\node_modules\pac-proxy-agent\node_modules\get-uri\node_modules\readable-stream\readable.js:2:28)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (W:\tools\atom\Atom\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (W:\home\.atom\packages\atom-beautify\node_modules\analytics-node\node_modules\superagent-proxy\node_modules\proxy-agent\node_modules\pac-proxy-agent\node_modules\get-uri\data.js:7:16)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (W:\tools\atom\Atom\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (W:\home\.atom\packages\atom-beautify\node_modules\analytics-node\node_modules\superagent-proxy\node_modules\proxy-agent\node_modules\pac-proxy-agent\node_modules\get-uri\index.js:20:9)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (W:\tools\atom\Atom\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (W:\home\.atom\packages\atom-beautify\node_modules\analytics-node\node_modules\superagent-proxy\node_modules\proxy-agent\node_modules\pac-proxy-agent\index.js:16:14)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (W:\tools\atom\Atom\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (W:\home\.atom\packages\atom-beautify\node_modules\analytics-node\node_modules\superagent-proxy\node_modules\proxy-agent\index.js:10:21)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (W:\tools\atom\Atom\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (W:\home\.atom\packages\atom-beautify\node_modules\analytics-node\node_modules\superagent-proxy\index.js:6:18)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (W:\tools\atom\Atom\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (W:\home\.atom\packages\atom-beautify\node_modules\analytics-node\lib\index.js:6:1)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (W:\tools\atom\Atom\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at W:\home\.atom\packages\atom-beautify\src\beautifiers\index.coffee:19:15
  at exports.allowUnsafeEval (W:\home\.atom\packages\atom-beautify\node_modules\loophole\lib\loophole.js:14:14)
  at Object.<anonymous> (W:\home\.atom\packages\atom-beautify\src\beautifiers\index.coffee:18:1)
  at Object.<anonymous> (W:\home\.atom\packages\atom-beautify\src\beautifiers\index.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (W:\tools\atom\Atom\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (W:\home\.atom\packages\atom-beautify\src\beautify.coffee:8:15)
  at Object.<anonymous> (W:\home\.atom\packages\atom-beautify\src\beautify.coffee:2:2)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (W:\tools\atom\Atom\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (W:\tools\atom\Atom\resources\app.asar\src\package.js:707:34)
  at Package.module.exports.Package.activateConfig (W:\tools\atom\Atom\resources\app.asar\src\package.js:255:12)
  at Package.module.exports.Package.activateNow (W:\tools\atom\Atom\resources\app.asar\src\package.js:234:14)
  at W:\tools\atom\Atom\resources\app.asar\src\package.js:770:25
  at Emitter.module.exports.Emitter.emit (W:\tools\atom\Atom\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (W:\tools\atom\Atom\resources\app.asar\src\command-registry.js:219:20)
  at W:\tools\atom\Atom\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (W:\tools\atom\Atom\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (W:\tools\atom\Atom\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (W:\tools\atom\Atom\resources\app.asar\src\window-event-handler.js:178:20)
```

Interestingly, the directory `W:\tools\atom\Atom\resources\app.asar\` does not exist, so the complaint in the stacktrace is totally valid. There is only `app.asar.unpacked` but it does not have a `src` directory either...

![image](https://cloud.githubusercontent.com/assets/365744/7902072/99c61d0e-07a9-11e5-97dc-033a00b7a7bf.png)

Any ideas?

**Comment by tknerr** [comment]
This is what `apm list` says, if that helps:
```
C:\Repos\_github\bills-kitchen>apm list
Built-in Atom packages (88)
├── archive-view@0.57.0
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.49.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.41.0
├── autocomplete-atom-api@0.9.0
├── autocomplete-css@0.7.2
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.16.3
├── autocomplete-snippets@1.6.1
├── autoflow@0.23.0
├── autosave@0.20.0
├── background-tips@0.24.0
├── base16-tomorrow-dark-theme@0.26.0
├── base16-tomorrow-light-theme@0.9.0
├── bookmarks@0.35.0
├── bracket-matcher@0.74.0
├── command-palette@0.36.0
├── deprecation-cop@0.48.0
├── dev-live-reload@0.46.0
├── encoding-selector@0.20.0
├── exception-reporting@0.24.0
├── find-and-replace@0.163.0
├── fuzzy-finder@0.85.0
├── git-diff@0.55.0
├── go-to-line@0.30.0
├── grammar-selector@0.47.0
├── image-view@0.54.0
├── incompatible-packages@0.24.0
├── keybinding-resolver@0.32.0
├── language-c@0.44.0
├── language-clojure@0.14.0
├── language-coffee-script@0.40.0
├── language-csharp@0.5.0
├── language-css@0.29.0
├── language-gfm@0.74.0
├── language-git@0.10.0
├── language-go@0.26.0
├── language-html@0.37.0
├── language-hyperlink@0.13.0
├── language-java@0.15.0
├── language-javascript@0.77.0
├── language-json@0.14.0
├── language-less@0.27.0
├── language-make@0.14.0
├── language-mustache@0.11.0
├── language-objective-c@0.15.0
├── language-perl@0.24.0
├── language-php@0.22.0
├── language-property-list@0.8.0
├── language-python@0.34.0
├── language-ruby@0.52.0
├── language-ruby-on-rails@0.21.0
├── language-sass@0.38.0
├── language-shellscript@0.14.0
├── language-source@0.9.0
├── language-sql@0.15.0
├── language-text@0.6.0
├── language-todo@0.20.0
├── language-toml@0.16.0
├── language-xml@0.28.0
├── language-yaml@0.22.0
├── link@0.30.0
├── markdown-preview@0.148.0
├── metrics@0.48.0
├── notifications@0.46.0
├── one-dark-syntax@0.5.0
├── one-dark-ui@0.8.1
├── one-light-syntax@0.6.0
├── one-light-ui@0.8.1
├── open-on-github@0.36.0
├── package-generator@0.39.0
├── release-notes@0.52.0
├── settings-view@0.199.0
├── snippets@0.89.0
├── solarized-dark-syntax@0.35.0
├── solarized-light-syntax@0.21.0
├── spell-check@0.58.0
├── status-bar@0.72.0
├── styleguide@0.44.0
├── symbols-view@0.96.0
├── tabs@0.68.0
├── timecop@0.31.0
├── tree-view@0.171.0
├── update-package-dependencies@0.10.0
├── welcome@0.27.0
├── whitespace@0.29.0
└── wrap-guide@0.33.0

W:\home\.atom\packages (6)
├── atom-beautify@0.27.1
├── language-batchfile@0.4.0
├── language-chef@0.4.0
├── line-ending-converter@1.1.0
├── minimap@4.8.0
└── sublime-tabs@0.5.6
```

**Comment by Glavin001** [comment]
From the error:
> analytics-node\node_modules\superagent-proxy\node_modules\proxy-agent\node_modules\pac-proxy-agent\node_modules\get-uri

Looks like it's a problem with dependency `analytics-node`, or more accurately `get-uri` requiring `_stream_readable`.

**Comment by Glavin001** [comment]
- [`get-uri` package](https://www.npmjs.com/package/get-uri).

Could you uninstall and reinstall Atom Beautify? Hopefully some of these dependent packages are updated / fixed.

**Comment by tknerr** [comment]
@Glavin001 just reinstalled atom-beautify (now 0.27.9) on top of Atom 0.204.0 and the issue is fixed.

Thanks!

**Comment by Glavin001** [comment]
Sounds like a bug in [apm](https://github.com/atom/apm). I've been seeing this around a lot. I'd recommend reporting it to them and letting them know that package installation sometimes does not work / completely install all dependencies. 

Similar issues:
- https://github.com/Glavin001/atom-beautify/issues/355
- https://github.com/Glavin001/atom-beautify/issues/329
