### ISSUE TITLE
Uncaught Error: Cannot find module 'formidable'

### ISSUE THREAD

**Issue by cjteuben** [Glavin001/atom-beautify#407]
[Enter steps to reproduce below:]
1. ...Installed
2. ...Error thrown

**Atom Version**: 0.210.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.28.5
### Stack Trace

Uncaught Error: Cannot find module 'formidable'

```
At module.js:330

Error: Cannot find module 'formidable'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/cjteuben/.atom/packages/atom-beautify/node_modules/analytics-node/node_modules/superagent/lib/node/index.js:7:18)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/cjteuben/.atom/packages/atom-beautify/node_modules/analytics-node/lib/index.js:5:15)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at /Users/cjteuben/.atom/packages/atom-beautify/src/beautifiers/index.coffee:20:15
  at exports.allowUnsafeEval (/Users/cjteuben/.atom/packages/atom-beautify/node_modules/loophole/lib/loophole.js:14:14)
  at Object.<anonymous> (/Users/cjteuben/.atom/packages/atom-beautify/src/beautifiers/index.coffee:19:1)
  at Object.<anonymous> (/Users/cjteuben/.atom/packages/atom-beautify/src/beautifiers/index.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/cjteuben/.atom/packages/atom-beautify/src/beautify.coffee:8:15)
  at Object.<anonymous> (/Users/cjteuben/.atom/packages/atom-beautify/src/beautify.coffee:2:2)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:257:12)
  at PackageDetailView.module.exports.PackageDetailView.activate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:163:26)
  at PackageDetailView.module.exports.PackageDetailView.initialize (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:146:12)
  at PackageDetailView.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new PackageDetailView (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:38:54)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:256:22
  at SettingsView.module.exports.SettingsView.getOrCreatePanel (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:261:19)
  at SettingsView.module.exports.SettingsView.showPanel (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/settings-view.js:306:24)
  at space-pen-div.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:260:26)
  at space-pen-div.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at space-pen-div.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```
### Commands

```
     -9:58.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -9:58.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -9:54 core:move-right (atom-text-editor.editor.is-focused)
     -9:53.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -9:50.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -9:50.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -9:44.8.0 core:save (atom-text-editor.editor.is-focused)
     -2:39.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -2:34.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -0:22.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by Glavin001** [comment]
Try uninstalling and reinstalling Atom Beautify package.

**Comment by prettydiff** [comment]
If this is still a problem please reopen this issue.
