### ISSUE TITLE
Uncaught Error: Cannot find module '../logger'

### ISSUE THREAD

**Issue by czqlfy** [Glavin001/atom-beautify#427]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.28.7

### Stack Trace

Uncaught Error: Cannot find module '../logger'

```
At module.js:330

Error: Cannot find module '../logger'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/chen/.atom/packages/atom-beautify/src/beautifiers/index.coffee:6:10)
  at Object.<anonymous> (/Users/chen/.atom/packages/atom-beautify/src/beautifiers/index.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/chen/.atom/packages/atom-beautify/src/beautify.coffee:8:15)
  at Object.<anonymous> (/Users/chen/.atom/packages/atom-beautify/src/beautify.coffee:2:2)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:709:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:257:12)
  at PackageDetailView.module.exports.PackageDetailView.activate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:163:26)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:201:12)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:235:24
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:155:30
  at Array.forEach (native)
  at PackageManager.module.exports.Emitter.emitSlow (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:154:47)
  at PackageManager.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/emitter.js:107:30)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:546:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:369:26
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:166:7)
  at Pipe.close (net.js:464:12)

```

### Commands

```
  4x -4:51.8.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -4:20.4.0 autoflow:reflow-selection (atom-text-editor.editor.is-focused)
     -4:03.0 editor:unfold-current-row (atom-text-editor.editor.is-focused)
     -4:00.0 editor:fold-current-row (atom-text-editor.editor.is-focused)
     -3:50.5.0 editor:auto-indent (atom-text-editor.editor.is-focused)
     -3:22.6.0 pane:split-up (atom-text-editor.editor.is-focused)
     -3:16.7.0 pane:split-right (atom-text-editor.editor.is-focused)
     -3:08.5.0 pane:split-up (atom-text-editor.editor.is-focused)
     -2:46.9.0 pane:split-right (atom-text-editor.editor.is-focused)
     -2:30.6.0 encoding-selector:show (atom-text-editor.editor.is-focused)
     -1:22.5.0 editor:auto-indent (atom-text-editor.editor.is-focused)
     -1:20 core:select-all (atom-text-editor.editor.is-focused)
     -1:13.4.0 editor:auto-indent (atom-text-editor.editor.is-focused)
     -0:53.9.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:51.2.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:50.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.0.0
angularjs, v0.3.0
atom-html-preview, v0.1.8
language-jade, v0.4.0

# Dev
No dev packages
```

**Comment by Glavin001** [comment]
Try uninstalling and reinstalling Atom Beautify package.

**Comment by Glavin001** [comment]
The only reason this would happen is if apm did not successfully install the package dependencies, which is out of my control. If reinstalling Atom Beautify and restarting Atom does not work, then best to talk to the apm team: https://github.com/atom/apm Thanks!
