### ISSUE TITLE
Uncaught Error: Cannot find module 'underscore'

### ISSUE THREAD

**Issue by zoosky** [Glavin001/atom-beautify#432]
[Enter steps to reproduce below:]

1. install atom-beautify
2. error occurs

**Atom Version**: 1.0.0
**System**: CM014514
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.28.7

### Stack Trace

Uncaught Error: Cannot find module 'underscore'

```
At module.js:330

Error: Cannot find module 'underscore'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Tools\prg\atom-windows\Atom\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (C:\Users\U80829024\.atom\packages\atom-beautify\node_modules\underscore-plus\lib\underscore-plus.js:5:7)
    at Object.<anonymous> (C:\Users\U80829024\.atom\packages\atom-beautify\node_modules\underscore-plus\lib\underscore-plus.js:522:4)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (C:\Tools\prg\atom-windows\Atom\resources\app.asar\src\babel.js:162:21)
    at Module.load (module.js:347:32)
```

### Commands

```
     -5:11 core:backspace (atom-text-editor.editor.mini.is-focused)
  2x -5:07.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
language-scala, v1.1.3
scala-format, v0.1.8

# Dev
No dev packages
```

**Comment by jmenges** [comment]
Have you already tried to remove and install atom-beautify once again?
Beautify depends on underscore-plus which depends on underscore. Therefor it should be installed during the atom-beautify installation process if everything goes well...

**Comment by Glavin001** [comment]
@jmenges is right on the mark. Reinstalling Atom Beautify will fix this. If it does not, it is either a network or npm issue, and potentially worthwhile talking to the apm team since this is happening a lot for users... See https://github.com/atom/apm
