### ISSUE TITLE
v0.28.7 -> 0.28.8 upgrade FAILS at spawn-sync

### ISSUE THREAD

**Issue by pgnd** [Glavin001/atom-beautify#467]
Running

```
atom --version
	1.0.3-9774b20
node -v
	v2.4.0
npm -v
	2.13.0
```
Upgrading atom-beautify from installed v0.28.7 to v0.28.8 FAILs:
```
Updating to “atom-beautify@0.28.8” failed.

> spawn-sync@1.0.13 postinstall /tmp/apm-install-dir-115617-5652-1i1ck6n/node_modules/atom-beautify/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall

module.js:340
    throw err;
          ^
Error: Cannot find module '/tmp/apm-install-dir-115617-5652-1i1ck6n/node_modules/atom-beautify/node_modules/cross-spawn/node_modules/spawn-sync/postinstall'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
npm ERR! Linux 4.1.1-2.gcac28b3-desktop
npm ERR! argv "/usr/local/share/atom/resources/app/apm/bin/node" "/usr/local/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/pgnd/.atom/.apm/.apmrc" "--userconfig" "/home/pgnd/.atom/.apmrc" "install" "/tmp/d-115617-5652-1qpfmy7/package.tgz" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! spawn-sync@1.0.13 postinstall: `node postinstall`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the spawn-sync@1.0.13 postinstall script 'node postinstall'.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-115617-5652-1i1ck6n/npm-debug.log

ls -al /tmp/apm-install-dir-115617-5652-1i1ck6n/npm-debug.log
	ls: cannot access /tmp/apm-install-dir-115617-5652-1i1ck6n/npm-debug.log: No such file or directory
```

**Comment by Glavin001** [comment]
Please let @ForbesLindesay know by forwarding this issue over to https://github.com/ForbesLindesay/spawn-sync

**Comment by pgnd** [comment]
Sure.  Is there an actual forward function?  Or just copy/resubmit manually over there?

**Comment by Glavin001** [comment]
Copy and re-create the Issue manually over there. Thanks.
