### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of null

### ISSUE THREAD

**Issue by kelvix** [Glavin001/atom-beautify#482]
Not sure if this is intentional or not but if the file we try to debug on does not have a name yet we get this exception.

1. Attempt to use Atom Beautiy: Help Debug Editor in a new file that has not been saved. 

**Atom Version**: 1.0.2
**System**: "Fedora release
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.28.8

### Stack Trace

Uncaught TypeError: Cannot read property 'name' of null

```
At /home/jgarcia/.atom/packages/atom-beautify/src/beautify.coffee:325

TypeError: Cannot read property 'name' of null
  at atom-workspace.debug (/home/jgarcia/.atom/packages/atom-beautify/src/beautify.coffee:325:45)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-li.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:139:19)
  at HTMLOListElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLOListElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -4:35.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:34.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -4:34.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -4:28.2.0 command-palette:toggle (a.stack-toggle)
  2x -4:27.3.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -4:11.7.0 command-palette:toggle (a.stack-toggle)
     -4:11 core:paste (atom-text-editor.editor.mini.is-focused)
     -4:08.5.0 editor:move-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -4:06.2.0 core:save (atom-text-editor.editor.mini.is-focused)
     -4:03.9.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -4:03.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:00.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -4:00.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:00.4.0 atom-beautify:help-debug-editor (a.stack-toggle)
     -0:04.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:01.8.0 atom-beautify:help-debug-editor (atom-text-editor.editor)
```

### Config

```json
{
  "core": {},
  "atom-beautify": {
    "_analyticsUserId": "7c25f398-2252-4a3f-97e5-8003c3149a92",
    "language_js_beautify_on_save": true,
    "language_css_beautify_on_save": true,
    "language_css_default_beautifier": "Pretty Diff"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.8
highlight-line, v0.11.0
javascript-snippets, v1.0.0
linter-csslint, v0.0.14
tree-view, v0.179.0

# Dev
atom-beautify, v0.28.8
```

**Comment by Glavin001** [comment]
Definitely a bug. Thanks for finding it. Atom Beautify should definitely work on untitled files.

I would love to review a Pull Request for this bug, if anyone is interested.

**Comment by Glavin001** [comment]
Published to v0.28.10

**Comment by sybrenstuvel** [comment]
I just got this error:

```
Uncaught TypeError: Cannot read property 'name' of null
/home/sybren/.atom/packages/atom-beautify/src/beautify.coffee:364
Hide Stack Trace
TypeError: Cannot read property 'name' of null
    at atom-workspace.debug (/home/sybren/.atom/packages/atom-beautify/src/beautify.coffee:364:51)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1109:28)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app.asar/src/application-delegate.js:329:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```

using atom-beautify 0.29.11 on Atom 1.10.2, running on Kubuntu Linux 16.04.

**Comment by Glavin001** [comment]
@sybrenstuvel are you still experience this? If so, since the line numbers have changed, maybe it is https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L361 ?

**Comment by sybrenstuvel** [comment]
Nope, I cannot reproduce any more.

**Atom Version**: 1.12.7

**Atom Beautify Version**: 0.29.16
