### ISSUE TITLE
Uncaught Error: Cannot find module './dateRange'

### ISSUE THREAD

**Issue by WithoutRegret** [Glavin001/atom-beautify#523]
Steps to Reproduce:

1. Attempted Package Install

**Atom Version**: 1.0.7
**System**: Microsoft Windows 8.1
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.28.11

### Stack Trace

Uncaught Error: Cannot find module './dateRange'

```
At module.js:330

Error: Cannot find module './dateRange'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Users\...\AppData\Local\atom\app-1.0.7\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (C:\Users\...\.atom\packages\atom-beautify\node_modules\analytics-node\node_modules\superagent-proxy\node_modules\proxy-agent\node_modules\pac-proxy-agent\node_modules\pac-resolver\index.js:16:17)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (C:\Users\...\AppData\Local\atom\app-1.0.7\resources\app.asar\src\babel.js:163:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (C:\Users\...\.atom\packages\atom-beautify\node_modules\analytics-node\node_modules\superagent-proxy\node_modules\proxy-agent\node_modules\pac-proxy-agent\index.js:35:19)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (C:\Users\...\AppData\Local\atom\app-1.0.7\resources\app.asar\src\babel.js:163:21)
    at Module.load (module.js:347:32)
```

### Commands

```
     -7:21.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -7:20.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -7:20.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -7:20.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -7:20.5.0 editor:indent (atom-text-editor.editor.is-focused)
     -7:19.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -7:16.9.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -7:15.3.0 core:move-down (atom-text-editor.editor.is-focused)
     -6:09.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -6:09.3.0 core:paste (atom-text-editor.editor.is-focused)
     -5:28 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -5:17.2.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -5:15.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:15.7.0 settings-view:install-packages-and-themes (atom-text-editor.editor)
     -4:50.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:59.7.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-material-ui, v0.5.21
autoclose-html, v0.18.0

# Dev
No dev packages
```

**Comment by Glavin001** [comment]
Could you try uninstalling Atom Beautify, re-installing Atom Beautify, and reloading Atom, then try again? Looks like a problem with [`node-pac-resolver`](https://github.com/TooTallNate/node-pac-resolver) not having loaded the `dateRange.js` file, however it is available, if you look at their code: https://github.com/TooTallNate/node-pac-resolver/blob/master/dateRange.js So sounds like the real issue is that Atom / apm did not problem install all of Atom Beautify's dependencies fully.

**Comment by WithoutRegret** [comment]
That worked, thanks!
