### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/Users/kayone/git/plex-web-client/.jsbea...

### ISSUE THREAD

**Issue by kayone** [Glavin001/atom-beautify#530]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.9
**System**: Mac OS X 10.10.5
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.28.11

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/Users/kayone/git/.jsbeautifyrc'

```
At fs.js:519

Error: ENOENT: no such file or directory, open '/Users/kayone/git/.jsbeautifyrc'
  at Error (native)
  at Object.fs.openSync (fs.js:544:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
  at Object.fs.readFileSync (fs.js:396:15)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:369:29)
  at Beautifiers.module.exports.Beautifiers.getConfig (/Users/kayone/.atom/packages/atom-beautify/src/beautifiers/index.coffee:624:21)
  at Beautifiers.module.exports.Beautifiers.getOptionsForPath (/Users/kayone/.atom/packages/atom-beautify/src/beautifiers/index.coffee:714:15)
  at atom-workspace.beautify (/Users/kayone/.atom/packages/atom-beautify/src/beautify.coffee:163:27)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -1:00.3.0 core:save (atom-text-editor.editor.is-focused)
     -0:59.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:58.7.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:41.2.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:39.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:38.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:38.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:38.5.0 editor:indent (atom-text-editor.editor.is-focused)
  9x -0:34.4.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:24 core:move-left (atom-text-editor.editor.is-focused)
     -0:11.2.0 core:paste (atom-text-editor.editor.is-focused)
     -0:07.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:07.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:05.7.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:04.9.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -0:04.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-objective-c",
      "language-c",
      "language-clojure",
      "language-java",
      "language-php",
      "welcome",
      "git-control",
      "wrap-guide",
      "autoflow",
      "background-tips",
      "omnisharp-atom",
      "language-go",
      "language-perl",
      "language-ruby-on-rails",
      "language-sass",
      "language-toml"
    ],
    "openEmptyEditorOnStart": false
  },
  "atom-beautify": {
    "_analyticsUserId": "00b7817f-b16f-4250-94c6-70e2f50b5702",
    "language_js_beautify_on_save": false,
    "language_json_beautify_on_save": false,
    "language_handlebars_beautify_on_save": false,
    "language_less_beautify_on_save": false,
    "language_html_beautify_on_save": false,
    "language_xml_beautify_on_save": false,
    "css_convert_quotes": "single",
    "css_newline_between_rules": true,
    "css_preserve_newlines": true,
    "css_selector_separator_newline": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.11
atom-handlebars, v1.1.0
atom-ternjs, v0.7.2
auto-reveal-in-sidebar, v0.5.0
autocomplete-paths, v1.0.2
clipboard-history, v0.6.6
color-picker, v2.0.11
esformatter, v1.9.0
file-icons, v1.6.9
file-types, v0.5.1
flex-tool-bar, v0.5.0
highlight-selected, v0.10.1
json-schema, v0.1.13
language-diff, v0.3.1
linter, v1.4.3
linter-jscs, v2.0.4
linter-jshint, v1.1.5
linter-less, v2.1.0
local-history, v3.2.3
minimap, v4.13.2
minimap-find-and-replace, v4.3.0
minimap-git-diff, v4.1.8
minimap-hide, v0.3.0
minimap-highlight-selected, v4.3.0
pigments, v0.13.0
project-manager, v2.0.1
recent-files-fuzzy-finder, v0.1.4
sync-settings, v0.6.0
tool-bar, v0.1.8
underscorejs-snippets, v0.2.2
zentabs, v0.8.6

# Dev
No dev packages
```

**Comment by Glavin001** [comment]
Please provide reproducible instructions for this Issue. I do not know what is going on from this information.

**Comment by kayone** [comment]
sorry about that, think it has to do with a missing `jsbeautifyrc' file, if the file is delete while atom is running any future attempts at formatting the file using keyboard shortcuts causes this error.
