### ISSUE TITLE
Uncaught Error: Cannot find module 'winston'

### ISSUE THREAD

**Issue by vingorius** [Glavin001/atom-beautify#553]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.13
**System**: Unknown Windows Version
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.28.12

### Stack Trace

Uncaught Error: Cannot find module 'winston'

```
At module.js:336

Error: Cannot find module 'winston'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (C:\Users\김종호\AppData\Local\atom\app-1.0.13\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at C:\Users\김종호\.atom\packages\atom-beautify\src\logger.coffee:10:13
  at Object.<anonymous> (C:\Users\김종호\.atom\packages\atom-beautify\src\logger.coffee:4:18)
  at Object.<anonymous> (C:\Users\김종호\.atom\packages\atom-beautify\src\logger.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\김종호\AppData\Local\atom\app-1.0.13\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\김종호\.atom\packages\atom-beautify\src\beautifiers\index.coffee:6:10)
  at Object.<anonymous> (C:\Users\김종호\.atom\packages\atom-beautify\src\beautifiers\index.coffee:1:1)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\김종호\AppData\Local\atom\app-1.0.13\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (C:\Users\김종호\.atom\packages\atom-beautify\src\beautify.coffee:9:15)
  at Object.<anonymous> (C:\Users\김종호\.atom\packages\atom-beautify\src\beautify.coffee:2:2)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (C:\Users\김종호\AppData\Local\atom\app-1.0.13\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\김종호\AppData\Local\atom\app-1.0.13\resources\app.asar\src\package.js:761:34)
  at Package.module.exports.Package.activateConfig (C:\Users\김종호\AppData\Local\atom\app-1.0.13\resources\app.asar\src\package.js:263:14)
  at PackageDetailView.module.exports.PackageDetailView.activateConfig (C:\Users\김종호\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:212:26)
  at PackageDetailView.module.exports.PackageDetailView.completeInitialzation (C:\Users\김종호\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:156:12)
  at PackageDetailView.module.exports.PackageDetailView.loadPackage (C:\Users\김종호\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:168:21)
  at C:\Users\김종호\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:298:17
  at Emitter.module.exports.Emitter.emit (C:\Users\김종호\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (C:\Users\김종호\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\settings-view\lib\package-manager.js:588:27)
  at C:\Users\김종호\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\settings-view\lib\package-manager.js:379:26
  at exit (C:\Users\김종호\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\settings-view\lib\package-manager.js:60:16)
  at triggerExitCallback (C:\Users\김종호\AppData\Local\atom\app-1.0.13\resources\app.asar\src\buffered-process.js:213:47)
  at C:\Users\김종호\AppData\Local\atom\app-1.0.13\resources\app.asar\src\buffered-process.js:220:18
  at Socket.<anonymous> (C:\Users\김종호\AppData\Local\atom\app-1.0.13\resources\app.asar\src\buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)

```

### Commands

```
  2x -4:28.2.0 jade-beautify:convert (atom-text-editor.editor.is-focused)
     -4:25.6.0 core:save (atom-text-editor.editor.is-focused)
 13x -4:25.2.0 core:move-down (atom-text-editor.editor.is-focused)
  5x -4:23.7.0 core:move-up (atom-text-editor.editor.is-focused)
 30x -4:22.7.0 core:move-down (atom-text-editor.editor.is-focused)
 21x -4:20.8.0 core:move-up (atom-text-editor.editor.is-focused)
 11x -4:18.4.0 core:move-down (atom-text-editor.editor.is-focused)
  6x -3:53.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:47.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:08.6.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -2:05.2.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -2:04.7.0 core:move-up (atom-text-editor.editor.is-focused)
  3x -2:04.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:02.5.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:01.1.0 core:save (atom-text-editor.editor.is-focused)
     -1:59.8.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "jshint"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
jade-beautify, v0.0.11

# Dev
No dev packages
```

**Comment by Glavin001** [comment]
Sounds like `apm` in Atom did not properly install all of the dependencies, such as winston. Please uninstall and reinstall Atom Beautify and try again.

**Comment by vingorius** [comment]
I tried to reinstall atom, atom-beautify many times. but failed.
Finally i  create new windows account.
As you mentioned, It was not caused from atom-beautify.
All is fine. i don't know what's problem.

Many things left to do after moving.....

tks.
