### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, uv_chdir

### ISSUE THREAD

**Issue by rohanray** [Glavin001/atom-beautify#579]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Microsoft Windows 10 Home Single Language
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.28.14

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, uv_chdir

```
At /C:/Users/rohan/.atom/packages/jshint/index.js:245

Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at lint (C:/Users/rohan/.atom/packages/jshint/index.js:226:10)
    at complete (C:\Users\rohan\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:7697:25)
    at delayed (C:\Users\rohan\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:7707:11)
```

### Commands

```
     -6:31.1.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
  2x -6:29.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "destroyEmptyPanes": false
  },
  "atom-beautify": {
    "_analyticsUserId": "53a5ef3d-81e7-4d23-abe1-00e83a0dddb9"
  }
}
```

### Installed Packages

```coffee
# User
atom-handlebars, v1.2.0
atom-jshint, v2.0.0
color-tabs, v0.1.8
css-color-underline, v1.0.1
file-types, v0.5.1
jshint, v1.8.0
language-spacebars, v0.2.2
linter, v1.7.0
linter-handlebars, v2.1.0
meteor-api, v2.20.0
webbox-color, v0.5.8

# Dev
No dev packages
```

**Comment by Glavin001** [comment]
> At /C:/Users/rohan/.atom/packages/jshint/index.js:245
>
> Error: ENOENT: no such file or directory, uv_chdir
    at Error (native)
    at lint (C:/Users/rohan/.atom/packages/jshint/index.js:226:10)

Looks like a jshint issue.
