### ISSUE TITLE
TypeError: prettydiff.api is not a function

### ISSUE THREAD

**Issue by jwldnr** [Glavin001/atom-beautify#589]
Trying to beautify app.scss gives me the following error: 

`TypeError: prettydiff.api is not a function`

Stack Trace:

`TypeError: prettydiff.api is not a function
    at /Users/jwldnr/.atom/packages/atom-beautify/src/beautifiers/prettydiff.coffee:106:27
    at tryCatcher (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:70:37)
    at PrettyDiff.module.exports.PrettyDiff.beautify (/Users/jwldnr/.atom/packages/atom-beautify/src/beautifiers/prettydiff.coffee:55:16)
    at /Users/jwldnr/.atom/packages/atom-beautify/src/beautifiers/index.coffee:452:24
    at tryCatcher (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:70:37)
    at /Users/jwldnr/.atom/packages/atom-beautify/src/beautifiers/index.coffee:322:18
    at tryCatcher (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:133:10)`

I have tried reinstalling both through settings view in atom and cli `apm install atom-beautify`

Beatifying the following files produces no errors, only .scss:

`.css`
`.html`
`.php`
`.js`

**Comment by jwldnr** [comment]
On second thought this might be an issue meant for you instead @prettydiff (?)

**Comment by prettydiff** [comment]
Probably related to https://github.com/Glavin001/atom-beautify/issues/588 but I am not sure how. There is still a prettydiff.js file in the prettydiff NPM module and it still exports a method named API.

I am investigating though

**Comment by prettydiff** [comment]
Damn,  in prettydiff.coffee on line 56 when

    prettydiff = require("prettydiff")

Instead becomes

    prettydiff = require("/Users/acheney/.atom/packages/atom-beautify/node_modules/prettydiff/prettydiff.js")

I no longer get problems.  I am working a solution and a pull request.

**Comment by prettydiff** [comment]
Pull requested created: https://github.com/Glavin001/atom-beautify/pull/590

**Comment by prettydiff** [comment]
As @Glavin001 pointed out in the pull request this issue is likely due to a change to the package.json file.  This change is regressed and the problem appears to be solved with Pretty Diff v1.14.2.

**Comment by jwldnr** [comment]
Awesome! thanks

**Comment by Glavin001** [comment]
Uninstalling and reinstalling Atom Beautify should install a fresh copy of Pretty Diff and fix this problem. Thanks.

**Comment by jwldnr** [comment]
It did, thank you @Glavin001
