### ISSUE TITLE
Uncaught Error: Cannot find module 'event-kit'

### ISSUE THREAD

**Issue by JackCheung1300** [Glavin001/atom-beautify#626]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11.1
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.28.15
### Stack Trace

Uncaught Error: Cannot find module 'event-kit'

```
At module.js:336

Error: Cannot find module 'event-kit'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/Jack/.atom/packages/atom-beautify/src/beautify.coffee:7:25)
  at Object.<anonymous> (/Users/Jack/.atom/packages/atom-beautify/src/beautify.coffee:2:2)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:761:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:263:14)
  at PackageDetailView.module.exports.PackageDetailView.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:212:26)
  at PackageDetailView.module.exports.PackageDetailView.completeInitialzation (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:156:12)
  at PackageDetailView.module.exports.PackageDetailView.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:168:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:298:17
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:588:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:379:26
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:60:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

```
### Commands

```
     -0:19.4.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:19.4.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:19.4.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:18.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:18.1.0 core:move-up (atom-text-editor.editor.is-focused)
  7x -0:16.6.0 core:move-down (atom-text-editor.editor.is-focused)
  4x -0:13.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:12.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:12 core:move-left (atom-text-editor.editor.is-focused)
  2x -0:11.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:11.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:10.7.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:10.3.0 core:move-left (atom-text-editor.editor.is-focused)
  3x -0:09.7.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:03.1.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:01.9.0 core:backspace (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by Glavin001** [comment]
Could you try uninstalling and reinstalling Atom Beautify?

**Comment by Glavin001** [comment]
Please let me know if this resolves your problem. Thank you.

**Comment by saiboten** [comment]
I just downloaded the package from github (manually), placed it under the .atom/packages, restarted atom and got the exact same error. This is on windows. Fixed it by doing npm install on the package manually.

**Comment by Glavin001** [comment]
> Fixed it by doing npm install on the package manually.

Yes, this would be required and expected, given you wanted to install manually. `apm install` will also run `npm install` once the package has been cloned. So this is expected.

**Comment by modytiger123** [comment]
Umm, guys i know that's stupid but i cannot find where to put that command ^_^ :D

**Comment by prettydiff** [comment]
@modytiger123 The go to your command promp, which is Terminal on OSX and cmd.exe on Windows.  Once Atom is installed `apm` should become a global command, so you don't need to be any specific directory location.  The apm module system appears to be based upon npm as they look similar and work in similar fashions.  NPM comes with Node.js and it should also be a global command.

**Comment by modytiger123** [comment]
Umm, Okay but a little point, npm gives me an error ! doesn't matter.
but there's a problem here, beatufy doesn't format .php files whatever code in it it formats html code only in .html files but doesn't even beautify html in .php files !!?

**Comment by nord1dea** [comment]
Same problem with last update on Aton 1.18.0 x64 (Windows 10)

**Comment by jonjie0317** [comment]
Hi I am having this error right now. Do have any idea on how to solve this? Thanks

**Comment by jonjie0317** [comment]
Hi guys. I'm having this issue right now. Do you have any idea how can I fix this? Thanks

**Comment by Glavin001** [comment]
@jonjie0317 : If you are seeing this error:

```
Error: Cannot find module 'event-kit'
```

It is usually an issue during installation. A bug in `apm` or `npm` maybe.

Try reinstalling with `apm install atom-beautify`. Try uninstalling first. And be sure to restart Atom.

**Comment by jonjie0317** [comment]
Hi @Glavin001 , I just used the settings of atom to install the package.
