### ISSUE TITLE
Failed to activate the atom-beautify package

### ISSUE THREAD

**Issue by n7Sense** [Glavin001/atom-beautify#638]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.28.14

### Stack Trace

Failed to activate the atom-beautify package

```
At Cannot find module 'C:\Users\jaideep\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\emissary'

Error: Cannot find module 'C:\Users\jaideep\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\emissary'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\jaideep\AppData\Local\atom\app-1.1.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\jaideep\.atom\packages\atom-beautify\src\beautify.coffee:447:16)
    at Object.<anonymous> (C:\Users\jaideep\.atom\packages\atom-beautify\src\beautify.coffee:2:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\jaideep\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Package.module.exports.Package.requireMainModule (C:\Users\jaideep\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:725:34)
    at Package.module.exports.Package.activateConfig (C:\Users\jaideep\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:250:14)
    at Package.module.exports.Package.activateNow (C:\Users\jaideep\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:228:14)
```

### Commands

```
  2x -0:33 core:backspace (atom-text-editor.editor.is-focused)
     -0:15.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.3
atom-beautify, v0.28.14
atom-jshint, v2.0.0
color-picker, v2.0.13
jquery-snippets, v11.0.0
jshint, v1.8.3
linter, v1.8.1
linter-csslint, v1.1.0
minimap, v4.16.0

# Dev
No dev packages
```

**Comment by Glavin001** [comment]
Please update to Atom Beautify v0.28.16

**Comment by dbortoluzzi** [comment]
+1

**Comment by Glavin001** [comment]
@dbortoluzzi did updating work? This error should not occur if you are up-to-date.

**Comment by dbortoluzzi** [comment]
Yes, I've updated last week and the problem persists.

**Comment by Glavin001** [comment]
The use of emissary has been removed. 

Looking at your stack trace:

>     at Object.<anonymous> (C:\Users\jaideep\.atom\packages\atom-beautify\src\beautify.coffee:447:16)

The old code at line 447: https://github.com/Glavin001/atom-beautify/blob/df569a9f4ed80dc22d4bcd345ba709851067fa16/src/beautify.coffee#L447

The current (latest) code at line 447: https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L447
Note that emissary is not to be found, because it has since been removed in commit https://github.com/Glavin001/atom-beautify/commit/a8abbbb1a20a630a377ad26f8f46630f859a70a8

If this problem is persisting, maybe try uninstalling Atom Beautify completely, and then reinstall Atom Beautify. Also be sure to either reload Atom or restart it entirely, to make sure the Node.js require cache is cleared. Atom can get problematic when updating or installing packages, so I always make it a habit to reload Atom after installing to ensure there is no caching problems.

**Comment by jwerre** [comment]
Uninstalling and then reinstalling worked for me.

**Comment by JamesIves** [comment]
I keep getting this error after uninstalling/reinstalling.

**Comment by Glavin001** [comment]
@JamesIves always be sure to reload / restart Atom. Not sure if that will help you, but it often helps me resolve issues with Atom packages.

**Comment by rhughesjr** [comment]
Just to confirm that advice - I just had the same issue when coming back to Atom after a few months. I could not get past it until I uninstalled Beautify, restarted Atom, then re-installed Beautify. Now it works as expected!

**Comment by Glavin001** [comment]
Thanks for confirming! Glad to hear that is working consistently.

**Comment by OakstonePub** [comment]
I did what rhughesjr suggested and it worked for me as well.
Thanks.
