### ISSUE TITLE
Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by Razum** [Glavin001/atom-beautify#662]
Hi,

Trying to format jsx file. 

OS: Ubuntu 14.04
Atom version: 1.1.0
Atom-beautify version: 0.28.18

Stack Trace:

Cannot read property 'push' of undefined

TypeError: Cannot read property 'push' of undefined
  at jspretty__algorithm_operator_assignTest (/home/roman/.atom/packages/atom-beautify/node_modules/prettydiff/lib/jspretty.js:3024:73)
  at jspretty__algorithm_operator (/home/roman/.atom/packages/atom-beautify/node_modules/prettydiff/lib/jspretty.js:3030:30)
  at jspretty__algorithm (/home/roman/.atom/packages/atom-beautify/node_modules/prettydiff/lib/jspretty.js:3304:21)
  at jspretty_ (/home/roman/.atom/packages/atom-beautify/node_modules/prettydiff/lib/jspretty.js:3331:10)
  at commonjs (/home/roman/.atom/packages/atom-beautify/node_modules/prettydiff/lib/jspretty.js:4960:16)
  at core_ (/home/roman/.atom/packages/atom-beautify/node_modules/prettydiff/prettydiff.js:972:41)
  at prettydiff_ (/home/roman/.atom/packages/atom-beautify/node_modules/prettydiff/prettydiff.js:1643:12)
  at Object.commonjs [as api] (/home/roman/.atom/packages/atom-beautify/node_modules/prettydiff/prettydiff.js:1678:16)
  at /home/roman/.atom/packages/atom-beautify/src/beautifiers/prettydiff.coffee:110:27
  at tryCatcher (/opt/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/util.js:26:23)
  at Promise._resolveFromResolver (/opt/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:480:31)
  at new Promise (/opt/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:70:37)
  at PrettyDiff.module.exports.PrettyDiff.beautify (/home/roman/.atom/packages/atom-beautify/src/beautifiers/prettydiff.coffee:59:16)
  at /home/roman/.atom/packages/atom-beautify/src/beautifiers/index.coffee:455:24
  at tryCatcher (/opt/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/util.js:26:23)
  at Promise._resolveFromResolver (/opt/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:480:31)
  at new Promise (/opt/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:70:37)
  at /home/roman/.atom/packages/atom-beautify/src/beautifiers/index.coffee:325:18
  at tryCatcher (/opt/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/util.js:26:23)
  at Promise._settlePromiseFromHandler (/opt/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:507:31)
  at Promise._settlePromiseAt (/opt/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:581:18)
  at Promise._settlePromises (/opt/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:697:14)
  at Async._drainQueue (/opt/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:123:16)
  at Async._drainQueues (/opt/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:133:10)
  at MutationObserver.Async.drainQueues (/opt/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:15:14)

**Comment by Glavin001** [comment]
> Cannot read property 'push' of undefined
>
> TypeError: Cannot read property 'push' of undefined
at jspretty__algorithm_operator_assignTest (/home/roman/.atom/packages/atom-beautify/node_modules/**prettydiff/lib/jspretty.js**:3024:73)

@prettydiff

**Comment by prettydiff** [comment]
There was no code sample provided, so I could not perform a deep dive to determine if there were any deeper underlying concerns, but this is now resolved in published version v1.15.17.

**Comment by Glavin001** [comment]
Thanks @prettydiff ! Great work.
