### ISSUE TITLE
Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by nmaggioni** [Glavin001/atom-beautify#686]
When trying to beautify the following CoffeeScript snippet, an exception is thrown:

``` coffeescript
winston = require('winston')

exports.info = (message) ->
  timestamp = (new Date).toISOString().replace(/T/, ' ').replace(/\..+/, '')
  winston.log 'info', '[' + timestamp + '] %s', message
  return
```

```
Cannot read property 'toString' of null

TypeError: Cannot read property 'toString' of null
    at Object.exports.flag (/home/nmaggioni/.atom/packages/atom-beautify/node_modules/coffee-fmt/frontend/coffeescript/CoffeeErrorHandler.js:28:15)
    at Object.parse (/home/nmaggioni/.atom/packages/atom-beautify/node_modules/coffee-fmt/frontend/coffeescript/CoffeeParserTD.js:40:17)
    at Object.exports.format (/home/nmaggioni/.atom/packages/atom-beautify/node_modules/coffee-fmt/Coffeescript.js:137:10)
    at /home/nmaggioni/.atom/packages/atom-beautify/src/beautifiers/coffee-fmt.coffee:27:23
    at tryCatcher (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:70:37)
    at CoffeeFmt.module.exports.CoffeeFmt.beautify (/home/nmaggioni/.atom/packages/atom-beautify/src/beautifiers/coffee-fmt.coffee:20:16)
    at /home/nmaggioni/.atom/packages/atom-beautify/src/beautifiers/index.coffee:455:24
    at tryCatcher (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._resolveFromResolver (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:480:31)
    at new Promise (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:70:37)
    at /home/nmaggioni/.atom/packages/atom-beautify/src/beautifiers/index.coffee:325:18
    at tryCatcher (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:133:10)
    at MutationObserver.Async.drainQueues (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:15:14)
```

On larger CoffeeScript files (vanilla JS works fine) the editor just hangs when I call the beautifier, forcing me to kill and restart it.

I'm not able to paste the debug log as the palette command seems to do nothing at all...
I'm running Manjaro Linux (Arch-based), Atom _1.2.4_ and `atom-beautify` _0.28.19_ .

**Comment by Glavin001** [comment]
>     at Object.exports.flag (/home/nmaggioni/.atom/packages/atom-beautify/node_modules/coffee-fmt/frontend/coffeescript/CoffeeErrorHandler.js:28:15)

CoffeeScript is beautified using coffee-fmt in Atom Beautify.
I recommend making an issue over at https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/coffee-fmt.coffee

For reference, Coffee-fmt beautifier in Atom Beautify: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/coffee-fmt.coffee

**Comment by nmaggioni** [comment]
@Glavin001 thanks for the heads up!

**Comment by jervtub** [comment]
I get the same issue with the following code

```
for x in [0..10]
  console.log x
```

**Comment by alyssamichelle** [comment]
I'm having the same issue as @nmaggioni. Did you ever find a work around?

**Comment by Glavin001** [comment]
Closing this as a third-party bug: https://github.com/sterpe/coffee-fmt/issues/17
