### ISSUE TITLE
Uncaught TypeError: Cannot read property 'querySelector' of null

### ISSUE THREAD

**Issue by MateuszFlisikowski** [Glavin001/atom-beautify#698]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.0
**System**: Unknown Windows Version
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.28.19

### Stack Trace

Uncaught TypeError: Cannot read property 'querySelector' of null

```
At /D:/Users/mflisikowski/.atom/packages/jshint/index.js:185

TypeError: Cannot read property 'querySelector' of null
    at addReasons (D:/Users/mflisikowski/.atom/packages/jshint/index.js:168:41)
    at displayError (D:/Users/mflisikowski/.atom/packages/jshint/index.js:194:2)
    at D:/Users/mflisikowski/.atom/packages/jshint/index.js:201:24
    at arrayEach (D:\Users\mflisikowski\AppData\Local\atom\app-1.3.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:1289:13)
    at Function.<anonymous> (D:\Users\mflisikowski\AppData\Local\atom\app-1.3.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:3345:13)
    at displayErrors (D:/Users/mflisikowski/.atom/packages/jshint/index.js:201:4)
    at complete (D:\Users\mflisikowski\AppData\Local\atom\app-1.3.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:7697:25)
    at delayed (D:\Users\mflisikowski\AppData\Local\atom\app-1.3.0\resources\app.asar\node_modules\babel-core\node_modules\lodash\index.js:7707:11)
```

### Commands

```
  5x -3:08.1.0 core:undo (input.hidden-input)
     -3:02.8.0 core:close (input.hidden-input)
     -2:40.8.0 grammar-selector:show (atom-text-editor.editor.editor-colors)
  6x -2:36.5.0 core:backspace (input.hidden-input)
     -1:57.5.0 core:confirm (input.hidden-input)
 14x -1:44.4.0 core:backspace (input.hidden-input)
     -1:41.3.0 core:confirm (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autoprefixer",
      "atom-sync",
      "git-diff",
      "dev-live-reload",
      "keybinding-resolver",
      "markdown-preview",
      "package-generator"
    ],
    "openEmptyEditorOnStart": false,
    "autoHideMenuBar": true,
    "packagesWithKeymapsDisabled": [
      "gulp-control"
    ]
  },
  "atom-beautify": {
    "_analyticsUserId": "799f91ed-869a-4cf1-ab1a-03b88e91ac25",
    "analytics": false,
    "html_preserve_newlines": false,
    "js_indent_with_tabs": true,
    "js_preserve_newlines": false,
    "js_space_before_conditional": true,
    "css_indent_comments": false
  }
}
```

### Installed Packages

```coffee
# User
atom-jade, v0.3.0
atom-lorempixel, v0.1.0
autoclose-html, v0.19.0
bezier-curve-editor, v0.7.2
compare-files, v0.6.2
css-comb, v2.4.0
editor-stats, v0.17.0
editorconfig, v1.2.2
file-type-icons, v0.7.4
git-hide, v0.1.2
highlight-line, v0.11.0
jshint, v1.8.3
language-babel, v2.6.0
language-javascript-jsx, v0.3.7
language-log, v1.1.0
minimap, v4.17.0
pigments, v0.19.2
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by Glavin001** [comment]
> At /D:/Users/mflisikowski/.atom/packages/jshint/index.js:185


Looks like a `jshint` package error.
