### ISSUE TITLE
Uncaught Error: Adding a pane item with URI xxx that has already been destroyed

### ISSUE THREAD

**Issue by maxgrass** [Glavin001/atom-beautify#723]
[Enter steps to reproduce below:]

1. install ext. fcharron/last-cursor-position. (@fcharron)
2. navigate through code, navigate back (Alt + "-"). After 20th time that error pops up. Many tabs open, but the navigation occurs in the same tab.

**Atom Version**: 1.3.2
**System**: Microsoft Windows 10 Enterprise
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.28.19

### Stack Trace

Uncaught Error: Adding a pane item with URI 'x\controls.js' that has already been destroyed

```
At D:\users\x\Apps32\atom\app-1.3.2\resources\app.asar\src\pane.js:331

Error: Adding a pane item with URI 'x\controls.js' that has already been destroyed
    at Pane.module.exports.Pane.addItem (D:\users\x\Apps32\atom\app-1.3.2\resources\app.asar\src\pane.js:331:15)
    at Pane.module.exports.Pane.activateItem (D:\users\x\Apps32\atom\app-1.3.2\resources\app.asar\src\pane.js:315:14)
    at Object.module.exports.jumpTo (file:///C:/Users/Maxx/.atom/packages/navigation-history/lib/main.coffee:42:23)
    at Object.module.exports.jumpBack (file:///C:/Users/Maxx/.atom/packages/navigation-history/lib/main.coffee:29:6)
    at atom-text-editor.disposables.add.atom.commands.add.navigation-history:back (file:///C:/Users/Maxx/.atom/packages/navigation-history/lib/main.coffee:18:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (D:\users\x\Apps32\atom\app-1.3.2\resources\app.asar\src\command-registry.js:260:29)
    at D:\users\x\Apps32\atom\app-1.3.2\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (D:\users\x\Apps32\atom\app-1.3.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (D:\users\x\Apps32\atom\app-1.3.2\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (D:\users\x\Apps32\atom\app-1.3.2\resources\app.asar\src\window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (D:\users\x\Apps32\atom\app-1.3.2\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -1:57.5.0 refactor:done (atom-text-editor.editor.is-focused)
     -1:57.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:55.1.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:46.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:45.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:44.3.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  5x -1:41.4.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:33.1.0 core:save (atom-text-editor.editor.is-focused)
     -1:20 core:delete (atom-text-editor.editor.is-focused)
  5x -1:19.1.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
  3x -1:17.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:16.1.0 core:delete (atom-text-editor.editor.is-focused)
     -0:56.1.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:40.6.0 core:delete (atom-text-editor.editor.is-focused)
  2x -0:36.4.0 core:copy (atom-text-editor.editor.is-focused)
 27x -0:10.5.0 navigation-history:back (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "projectHome": "<redacted>",
    "ignoredNames": [
      "bin",
      "dist",
      ".svn",
      "node_modules"
    ],
    "disabledPackages": [
      "metrics",
      "dev-live-reload",
      "encoding-selector",
      "exception-reporting",
      "auto-indent",
      "auto-detect-indentation",
      "highlight-selected",
      "linter",
      "linter-jsonlint",
      "linter-jshint",
      "linter-csslint",
      "uglify",
      "about",
      "background-tips",
      "git-diff",
      "grammar-selector",
      "language-c",
      "language-clojure",
      "language-coffee-script",
      "language-gfm",
      "language-git",
      "language-go",
      "language-java",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-php",
      "language-python",
      "language-ruby",
      "language-ruby-on-rails",
      "language-sass",
      "language-shellscript",
      "language-sql",
      "language-toml",
      "language-yaml",
      "markdown-preview",
      "open-on-github",
      "package-generator",
      "release-notes",
      "welcome",
      "styleguide",
      "spell-check",
      "build-gulp",
      "build"
    ]
  },
  "atom-beautify": {
    "_analyticsUserId": "<stripped>"
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.19
atom-ternjs, v0.12.1
highlight-selected, v0.11.1
js-refactor, v0.6.0
last-cursor-position, v0.9.0
minimap, v4.18.4
minimap-find-and-replace, v4.4.0
minimap-highlight-selected, v4.3.1
minimap-pigments, v0.1.7
navigation-history, v0.1.8
pigments, v0.19.5
refactor, v0.6.0

# Dev
No dev packages
```

**Comment by Glavin001** [comment]
This issue looks like it is not applicable to Atom Beautify and instead another package.
