### ISSUE TITLE
Error: spawn ENOTDIR

### ISSUE THREAD

**Issue by C-Bouthoorn** [Glavin001/atom-beautify#745]
Okay, so step 1) doesn't work for some reason. I tried it multiple times, but my clipboard wouldn't change.

I'm currently running into a problem with Beautify in general. Every time I try to run it over my files, I get [this error](https://gist.github.com/C-Bouthoorn/fb0dc56b0ecb9d40636c).

More information:

`$ uname -a`
`Linux XXX 4.2.0-23-generic #28-Ubuntu SMP Sun Dec 27 17:47:31 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux`

`$ atom-beta -v`
`1.4.0-beta3`

**Comment by prettydiff** [comment]
@C-Bouthoorn Would you mind providing a detailed list of steps on how you came to that error so that we can attempt to reproduce the problem?  Once the problem can be reproduced somebody can work backwards to the cause and issue an appropriate solution.

**Comment by C-Bouthoorn** [comment]
Okay,
1) Open Atom Beta 2) Open a file (In this case main.cpp in a Git repository on my Desktop [
/home/charlie/Desktop/repo/main.cpp ] ) 3) Open command palette ( CTRL - SHIFT - P ) 4) Enter "Beautify" 5) Run Beautify: Beautify File

Let me know if you need more information


On Wed, Jan 13, 2016 at 9:14 p.m., Glavin001/atom-beautify
<reply@reply.github.com>
wrote:
@C-Bouthoorn [https://github.com/C-Bouthoorn] Would you mind providing a detailed list of steps on how you came to that error
so that we can attempt to reproduce the problem? Once the problem can be
reproduced somebody can work backwards to the cause and issue an appropriate
solution.

—
Reply to this email directly or view it on GitHub
[https://github.com/Glavin001/atom-beautify/issues/745#issuecomment-171419813] .[https://github.com/notifications/beacon/AJ3nAToO14OaawvzpRfYSamuIxOh3hsTks5pZqeGgaJpZM4HELEL.gif]

**Comment by turigeza** [comment]
I get the same issue. Or it looks like similar. I am on a Mac. Latest version of everything.

The stack trace is below see if it helps. It happens to me on PHP files. Not on javascript. 

`spawn ENOTDIR
Hide Stack Trace
Error: spawn ENOTDIR
    at exports._errnoException (util.js:890:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)
    at exports.spawn (child_process.js:379:9)
    at /Users/geza/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:314:13
    at Promise._execute (/Users/geza/.atom/packages/atom-beautify/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/Users/geza/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:475:18)
    at new Promise (/Users/geza/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:77:14)
    at PHPCSFixer.module.exports.Beautifier.spawn (/Users/geza/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:311:16)
    at /Users/geza/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:273:10
    at tryCatcher (/Users/geza/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/geza/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/Users/geza/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromise0 (/Users/geza/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/Users/geza/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:685:18)
    at Promise._fulfill (/Users/geza/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:630:18)
    at PromiseArray._resolve (/Users/geza/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/Users/geza/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/Users/geza/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:566:26)
    at Promise._settlePromise0 (/Users/geza/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:606:10)
    at Promise._settlePromises (/Users/geza/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:685:18)
    at Async._drainQueue (/Users/geza/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/geza/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:148:10)
    at Async.drainQueues (/Users/geza/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)`

**Comment by DiegoTavares** [comment]
Same problem in here. MacOS Sierra.

**Comment by limeandcoconut** [comment]
Same, ElCap.
Trace: 
```
Error: spawn ENOTDIR
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:392:9)
    at /Users/jacob/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:322:13
    at Promise._execute (/Users/jacob/.atom/packages/atom-beautify/node_modules/bluebird/js/release/debuggability.js:299:9)
    at Promise._resolveFromExecutor (/Users/jacob/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/Users/jacob/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:77:14)
    at PHPCSFixer.module.exports.Beautifier.spawn (/Users/jacob/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:319:16)
    at /Users/jacob/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:281:10
    at tryCatcher (/Users/jacob/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jacob/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/jacob/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/jacob/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/jacob/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/jacob/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:636:18)
    at PromiseArray._resolve (/Users/jacob/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/Users/jacob/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/Users/jacob/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:572:26)
    at Promise._settlePromise0 (/Users/jacob/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/jacob/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/jacob/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/jacob/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:148:10)
    at Async.drainQueues (/Users/jacob/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
```

**Comment by IceManbp** [comment]
I've got the same problem when I try to beautify a python file

`Error: spawn ENOTDIR
    at exports._errnoException (util.js:1026:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at exports.spawn (child_process.js:392:9)
    at /Users/stefano/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:349:13
    at Promise._execute (/Users/stefano/.atom/packages/atom-beautify/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/stefano/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/stefano/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:79:10)
    at Autopep8.module.exports.Beautifier.spawn (/Users/stefano/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:346:16)
    at /Users/stefano/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:308:10
    at tryCatcher (/Users/stefano/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/stefano/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/stefano/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/stefano/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/stefano/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/stefano/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/Users/stefano/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/Users/stefano/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/Users/stefano/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Users/stefano/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/stefano/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/stefano/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/stefano/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/Users/stefano/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)`

**Comment by jaylee185** [comment]
Interesting enough, I saw this post because my colleague has same issue. After checking with him, he is using rvm 2.4.1, and I'm using rvm 2.4.0. Once he changes to 2.4.0 the issue is gone.
