### ISSUE TITLE
Failed to activate the atom-beautify package - Cannot find module 'grim'

### ISSUE THREAD

**Issue by leocamello** [Glavin001/atom-beautify#765]
Stack Trace

Error: Cannot find module 'grim'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (C:\Users\Leonardo\AppData\Local\atom\app-1.4.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (C:\Users\Leonardo\AppData\Local\atom\app-1.4.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Leonardo\.atom\packages\atom-beautify\node_modules\event-kit\lib\disposable.js:4:10)
    at Object.<anonymous> (C:\Users\Leonardo\.atom\packages\atom-beautify\node_modules\event-kit\lib\disposable.js:43:4)
    at Module._compile (C:\Users\Leonardo\AppData\Local\atom\app-1.4.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Leonardo\AppData\Local\atom\app-1.4.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Leonardo\AppData\Local\atom\app-1.4.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Leonardo\.atom\packages\atom-beautify\node_modules\event-kit\lib\emitter.js:4:16)
    at Object.<anonymous> (C:\Users\Leonardo\.atom\packages\atom-beautify\node_modules\event-kit\lib\emitter.js:134:4)
    at Module._compile (C:\Users\Leonardo\AppData\Local\atom\app-1.4.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Leonardo\AppData\Local\atom\app-1.4.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Leonardo\AppData\Local\atom\app-1.4.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Leonardo\.atom\packages\atom-beautify\node_modules\event-kit\lib\event-kit.js:2:21)
    at Object.<anonymous> (C:\Users\Leonardo\.atom\packages\atom-beautify\node_modules\event-kit\lib\event-kit.js:8:4)
    at Module._compile (C:\Users\Leonardo\AppData\Local\atom\app-1.4.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Leonardo\AppData\Local\atom\app-1.4.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Leonardo\AppData\Local\atom\app-1.4.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Leonardo/.atom/packages/atom-beautify/src/beautify.coffee:7:25)
    at Object.<anonymous> (file:///C:/Users/Leonardo/.atom/packages/atom-beautify/src/beautify.coffee:2:1)
    at Module._compile (C:\Users\Leonardo\AppData\Local\atom\app-1.4.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Leonardo\AppData\Local\atom\app-1.4.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Leonardo\AppData\Local\atom\app-1.4.0\resources\app.asar\src\native-compile-cache.js:50:27)

**Comment by prettydiff** [comment]
Grim appears to be: https://www.npmjs.com/package/grim

These NPM atom prefixed packages use it directly:

* atom-utils
* atom-keymap
* atom-highlights

I am trying to find the resolution chain for that missing module to determine if its due to this package directly or requested from an included module.  I am still looking.

**Comment by prettydiff** [comment]
It is coming from event-kit: https://www.npmjs.com/package/event-kit

Maybe a sub-component failed to download.  @leocamello Would you mind trying this from the command line and see if it resolves the problem: `apm install atom-beautify`

**Comment by leocamello** [comment]
I think you are right. It was NPM package Grim.

I tried `npm install grim -g` from the command line and it seems that the problem is solved.

**Comment by ULTIMATEUPGRADE** [comment]
Today I got this error

TypeError: Beautifiers is not a function
    at Object.<anonymous> (/home/harmony-12/.atom/packages/atom-beautify/src/beautify.coffee:10:18)
    at Object.<anonymous> (/home/harmony-12/.atom/packages/atom-beautify/src/beautify.coffee:2:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:720:27)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:172:16)
    at /usr/share/atom/resources/app.asar/src/package.js:800:25
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:20)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
