### ISSUE TITLE
Uncaught Error: Cannot find module './util.js'

### ISSUE THREAD

**Issue by standardhuman** [Glavin001/atom-beautify#784]
[Enter steps to reproduce below:]

1. Install atom-beautify from Atom package manager.
2. ...

**Atom Version**: 1.4.3
**System**: Mac OS X 10.11.3
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.28.21

### Stack Trace

Uncaught Error: Cannot find module './util.js'

```
At module.js:338

Error: Cannot find module './util.js'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at module.exports (/Users/brian/.atom/packages/atom-beautify/node_modules/bluebird/js/main/promise.js:13:12)
    at Object.<anonymous> (/Users/brian/.atom/packages/atom-beautify/node_modules/bluebird/js/main/bluebird.js:9:39)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/brian/.atom/packages/atom-beautify/src/beautifiers/index.coffee:3:11)
    at Object.<anonymous> (/Users/brian/.atom/packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/brian/.atom/packages/atom-beautify/src/beautify.coffee:9:15)
    at Object.<anonymous> (/Users/brian/.atom/packages/atom-beautify/src/beautify.coffee:2:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:722:27)
    at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:222:12)
    at PackageDetailView.module.exports.PackageDetailView.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:216:26)
    at PackageDetailView.module.exports.PackageDetailView.completeInitialzation (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:159:12)
    at PackageDetailView.module.exports.PackageDetailView.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:171:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:302:17
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:664:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:452:26
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
     -3:54.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:53.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:56.2.0 editor:select-line (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-dark-syntax.theme-one-dark-ui)
  5x -1:46.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:43.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -1:26.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:24.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
auto-detect-indentation, v0.4.2
build, v0.54.1
highlight-selected, v0.11.2
jshint, v1.8.3

# Dev
No dev packages
```

**Comment by prettydiff** [comment]
Can you try the following command from the command line and see if it resolves the problem?

    apm install atom-beautify

**Comment by standardhuman** [comment]
That resolved it. Thanks Austin!
