### ISSUE TITLE
Uncaught TypeError: winston.transports.Console is not a function

### ISSUE THREAD

**Issue by lkdsub0** [Glavin001/atom-beautify#785]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.3
**System**: Microsoft Windows 10 Home
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.28.21

### Stack Trace

Uncaught TypeError: winston.transports.Console is not a function

```
At C:\Users\Laurent\.atom\packages\atom-beautify\node_modules\winston\lib\winston\container.js:24

TypeError: winston.transports.Console is not a function
    at new exports.Container (C:\Users\Laurent\.atom\packages\atom-beautify\node_modules\winston\lib\winston\container.js:24:7)
    at Object.<anonymous> (C:\Users\Laurent\.atom\packages\atom-beautify\node_modules\winston\lib\winston.js:51:19)
    at Module._compile (C:\Users\Laurent\AppData\Local\atom\app-1.4.3\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\Laurent\AppData\Local\atom\app-1.4.3\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Laurent\AppData\Local\atom\app-1.4.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at file:///C:/Users/Laurent/.atom/packages/atom-beautify/src/logger.coffee:10:13
    at Object.<anonymous> (file:///C:/Users/Laurent/.atom/packages/atom-beautify/src/logger.coffee:4:18)
    at Object.<anonymous> (file:///C:/Users/Laurent/.atom/packages/atom-beautify/src/logger.coffee:1:1)
    at Module._compile (C:\Users\Laurent\AppData\Local\atom\app-1.4.3\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Laurent\AppData\Local\atom\app-1.4.3\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Laurent\AppData\Local\atom\app-1.4.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Laurent/.atom/packages/atom-beautify/src/beautifiers/index.coffee:6:10)
    at Object.<anonymous> (file:///C:/Users/Laurent/.atom/packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at Module._compile (C:\Users\Laurent\AppData\Local\atom\app-1.4.3\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Laurent\AppData\Local\atom\app-1.4.3\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Laurent\AppData\Local\atom\app-1.4.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Laurent/.atom/packages/atom-beautify/src/beautify.coffee:9:15)
    at Object.<anonymous> (file:///C:/Users/Laurent/.atom/packages/atom-beautify/src/beautify.coffee:2:1)
    at Module._compile (C:\Users\Laurent\AppData\Local\atom\app-1.4.3\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\Laurent\AppData\Local\atom\app-1.4.3\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (C:\Users\Laurent\AppData\Local\atom\app-1.4.3\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\Laurent\AppData\Local\atom\app-1.4.3\resources\app.asar\src\package.js:722:27)
    at Package.module.exports.Package.activateConfig (C:\Users\Laurent\AppData\Local\atom\app-1.4.3\resources\app.asar\src\package.js:222:12)
    at PackageDetailView.module.exports.PackageDetailView.activateConfig (C:\Users\Laurent\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:216:26)
    at PackageDetailView.module.exports.PackageDetailView.completeInitialzation (C:\Users\Laurent\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:159:12)
    at PackageDetailView.module.exports.PackageDetailView.loadPackage (C:\Users\Laurent\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:171:21)
    at C:\Users\Laurent\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\settings-view\lib\package-detail-view.js:302:17
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Laurent\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Laurent\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (C:\Users\Laurent\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\settings-view\lib\package-manager.js:664:27)
    at C:\Users\Laurent\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\settings-view\lib\package-manager.js:452:26
    at exit (C:\Users\Laurent\AppData\Local\atom\app-1.4.3\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\Laurent\AppData\Local\atom\app-1.4.3\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\Laurent\AppData\Local\atom\app-1.4.3\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.13
autoclose-html, v0.20.0
color-picker, v2.1.1
emmet, v2.4.1
file-icons, v1.6.14
javascript-snippets, v1.2.0
minimap, v4.19.0

# Dev
No dev packages
```

**Comment by prettydiff** [comment]
Maybe a module failed to reload.  Would you mind running `apm install atom-beautify` and restarting Atom to see if this resolves the issue.  If not then we have a defect.

**Comment by lkdsub0** [comment]
Hi Galvin,

I am using the Windows version of atom, so I uninstalled and reinstalled
your package. (I didn't use the apm method because I don't know how to to
that on windows)
I'm glad to report it worked.
Strangely enough, I reinstalled it twice yesterday and it didn't solve the
problem back then.

Thanks for your help!

Laurent

2016-02-05 23:22 GMT+01:00 Austin Cheney <notifications@github.com>:
