### ISSUE TITLE
Unable to install atom-beautify

### ISSUE THREAD

**Issue by agiertli** [Glavin001/atom-beautify#788]
Installing atom-beautify on Ubuntu 14.x fails with following message:

```
osirissk@osirissk-VirtualBox:/var/log/apache2$ sudo apm install atom-beautify
Installing atom-beautify to /home/osirissk/.atom/packages ✗

> spawn-sync@1.0.15 postinstall /tmp/apm-install-dir-11617-2706-ku7r8h/node_modules/atom-beautify/node_modules/cross-spawn/node_modules/spawn-sync
> node postinstall


npm WARN deprecated lodash@2.4.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0

module.js:340
    throw err;
          ^
Error: Cannot find module '/tmp/apm-install-dir-11617-2706-ku7r8h/node_modules/atom-beautify/node_modules/cross-spawn/node_modules/spawn-sync/postinstall'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
npm ERR! Linux 3.19.0-47-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/osirissk/.atom/.apm/.apmrc" "--userconfig" "/home/osirissk/.atom/.apmrc" "install" "/tmp/d-11617-2706-14pvn9s/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! spawn-sync@1.0.15 postinstall: `node postinstall`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the spawn-sync@1.0.15 postinstall script 'node postinstall'.
npm ERR! This is most likely a problem with the spawn-sync package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls spawn-sync
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11617-2706-ku7r8h/npm-debug.log
```

**Comment by prettydiff** [comment]
Try this command from the command line, restart Atom, and let me know if this works.  If it doesn't then I we need to investigate further.  Right now it just looks like a missing component:

    apm install atom-beautify

**Comment by magykjames** [comment]
Thanks, I had the same problem and this fixed it for me. Centos 7.2.

**Comment by kofimokome** [comment]
It did not work on my machine. I am using ubuntu 16.04 LTS

**Comment by prettydiff** [comment]
@kofimokome Did you get a similar error to the one posted above?
