### ISSUE TITLE
Language named 'Riot.js' has an already used namespace html.

### ISSUE THREAD

**Issue by gnestor** [Glavin001/atom-beautify#844]
### Description

I get the following error just opening a regular JS (not Riot.js) file: 

"Language named 'Riot.js' has an already used namespace html."

### Steps to Reproduce

1. Open a JS file

### Stack trace

Error: Language named 'Riot.js' has an already used namespace html.
    at Beautifiers.module.exports.Beautifiers.buildOptionsForBeautifiers (/Users/grant/.atom/packages/atom-beautify/src/beautifiers/index.coffee:267:21)
    at new Beautifiers (/Users/grant/.atom/packages/atom-beautify/src/beautifiers/index.coffee:99:17)
    at Object.<anonymous> (/Users/grant/.atom/packages/atom-beautify/src/beautify.coffee:10:18)
    at Object.<anonymous> (/Users/grant/.atom/packages/atom-beautify/src/beautify.coffee:2:1)
    at Module._compile (/Users/grant/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:92:30)
    at Object.defineProperty.value [as .coffee] (/Users/grant/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:204:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/grant/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:41:21)
    at Package.module.exports.Package.requireMainModule (/Users/grant/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:721:27)
    at Package.module.exports.Package.activateNow (/Users/grant/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:173:16)
    at /Users/grant/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:801:25
    at Emitter.module.exports.Emitter.emit (/Users/grant/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/grant/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
    at /Users/grant/Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/grant/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/grant/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Users/grant/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Users/grant/Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)

**Comment by Glavin001** [comment]
This should be fixed in the same commit that added this error message: https://github.com/Glavin001/atom-beautify/commit/3f51b02e256bf959050d3d293cd9a5833e58dba1

Could you please uninstall and reinstall Atom Beautify, and then reload Atom and try again, to make sure no older files have been cached. Thanks.

**Comment by gnestor** [comment]
Seems to be fine now! I'll close and reopen if anything comes back. Thanks.

**Comment by Glavin001** [comment]
Thanks! Glad to hear it is working now. It is good to have this issue created here for any others that have similar issues.

**Comment by gnestor** [comment]
Dang it came back, this time saving an Obj-C .m file?

**Comment by Glavin001** [comment]
I am going to remove the check at runtime and put it into unit testing instead. So at least Pull Requests won't submit bugs however users like yourself will not have to receive error messages like this... Strange that it is occurring.

**Comment by Glavin001** [comment]
Moved it to the spec:

![image](https://cloud.githubusercontent.com/assets/1885333/13514007/5068fcce-e17b-11e5-811e-783d91e3aa7a.png)


Much more informative and targets the developers/contributors instead of the user.

Publishing soon.

**Comment by Glavin001** [comment]
Published fix to v0.28.26

Thank you for your patience.

**Comment by gnestor** [comment]
Thanks @Glavin001
