### ISSUE TITLE
Cannot find module 'prettydiff' on .less file

### ISSUE THREAD

**Issue by gluons** [Glavin001/atom-beautify#853]
I try to reinstall many time but this error still appear.

```
Error: Cannot find module 'prettydiff'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (C:\Users\<username>\AppData\Local\atom\app-1.5.4\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (C:\Users\<username>\AppData\Local\atom\app-1.5.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at file:///C:/Users/<username>/.atom/packages/atom-beautify/src/beautifiers/prettydiff.coffee:63:20
    at tryCatcher (C:\Users\<username>\AppData\Local\atom\app-1.5.4\resources\app.asar\node_modules\babel-core\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._resolveFromResolver (C:\Users\<username>\AppData\Local\atom\app-1.5.4\resources\app.asar\node_modules\babel-core\node_modules\bluebird\js\main\promise.js:480:31)
    at new Promise (C:\Users\<username>\AppData\Local\atom\app-1.5.4\resources\app.asar\node_modules\babel-core\node_modules\bluebird\js\main\promise.js:70:37)
    at PrettyDiff.module.exports.PrettyDiff.beautify (file:///C:/Users/<username>/.atom/packages/atom-beautify/src/beautifiers/prettydiff.coffee:62:16)
    at file:///C:/Users/<username>/.atom/packages/atom-beautify/src/beautifiers/index.coffee:463:24
    at tryCatcher (C:\Users\<username>\AppData\Local\atom\app-1.5.4\resources\app.asar\node_modules\babel-core\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._resolveFromResolver (C:\Users\<username>\AppData\Local\atom\app-1.5.4\resources\app.asar\node_modules\babel-core\node_modules\bluebird\js\main\promise.js:480:31)
    at new Promise (C:\Users\<username>\AppData\Local\atom\app-1.5.4\resources\app.asar\node_modules\babel-core\node_modules\bluebird\js\main\promise.js:70:37)
    at file:///C:/Users/<username>/.atom/packages/atom-beautify/src/beautifiers/index.coffee:389:18
    at tryCatcher (C:\Users\<username>\AppData\Local\atom\app-1.5.4\resources\app.asar\node_modules\babel-core\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\<username>\AppData\Local\atom\app-1.5.4\resources\app.asar\node_modules\babel-core\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\Users\<username>\AppData\Local\atom\app-1.5.4\resources\app.asar\node_modules\babel-core\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (C:\Users\<username>\AppData\Local\atom\app-1.5.4\resources\app.asar\node_modules\babel-core\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (C:\Users\<username>\AppData\Local\atom\app-1.5.4\resources\app.asar\node_modules\babel-core\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\Users\<username>\AppData\Local\atom\app-1.5.4\resources\app.asar\node_modules\babel-core\node_modules\bluebird\js\main\async.js:133:10)
    at MutationObserver.Async.drainQueues (C:\Users\<username>\AppData\Local\atom\app-1.5.4\resources\app.asar\node_modules\babel-core\node_modules\bluebird\js\main\async.js:15:14)
```

**Comment by prettydiff** [comment]
Twice in one week now!!!!!! https://github.com/npm/npm/issues/5082

Resolved by bumping the version.  Reinstall Atom Beautify or update the Pretty Diff NPM dependency.  I am going to create a new NPM package to test for this problem and reinstall in a loop until the solution is verified solved.

**Comment by prettydiff** [comment]
Here is my attempt to an automated mitigation: https://github.com/prettydiff/5082

**Warning!! I have not tested this in production yet**
