### ISSUE TITLE
Fails to load ... 

### ISSUE THREAD

**Issue by ksnyde** [Glavin001/atom-beautify#865]
I'm running Atom on OSX (latest non-beta Yosemite) on both my iMac at home and my MBP. In both cases I now get the following error when I start Atom. 

[Enter steps to reproduce below:]

1. Start Atom

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.3
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.28.26

### Stack Trace

Failed to activate the atom-beautify package

```
At Cannot find module 'delayed-stream'

Error: Cannot find module 'delayed-stream'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/kensnyder/Dropbox/atom/packages/atom-beautify/node_modules/analytics-node/node_modules/superagent/node_modules/form-data/node_modules/combined-stream/lib/combined_stream.js:3:21)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/kensnyder/Dropbox/atom/packages/atom-beautify/node_modules/analytics-node/node_modules/superagent/node_modules/form-data/lib/form_data.js:1:101)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/kensnyder/Dropbox/atom/packages/atom-beautify/node_modules/analytics-node/node_modules/superagent/lib/node/index.js:8:16)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/kensnyder/Dropbox/atom/packages/atom-beautify/node_modules/analytics-node/lib/index.js:5:15)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at /Volumes/PEGASUS/Dropbox/atom/packages/atom-beautify/src/beautifiers/index.coffee:20:15
    at exports.allowUnsafeEval (/Users/kensnyder/Dropbox/atom/packages/atom-beautify/node_modules/loophole/lib/loophole.js:14:14)
    at Object.<anonymous> (/Volumes/PEGASUS/Dropbox/atom/packages/atom-beautify/src/beautifiers/index.coffee:19:1)
    at Object.<anonymous> (/Volumes/PEGASUS/Dropbox/atom/packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Volumes/PEGASUS/Dropbox/atom/packages/atom-beautify/src/beautify.coffee:9:15)
    at Object.<anonymous> (/Volumes/PEGASUS/Dropbox/atom/packages/atom-beautify/src/beautify.coffee:2:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:720:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:172:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:800:25
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -1:39.7.0 command-palette:toggle (atom-pane.pane.active)
     -1:36.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:36.8.0 project-manager:save-project (atom-pane.pane.active)
     -1:35.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:28 core:select-right (atom-text-editor.editor.is-focused)
     -0:25.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:04.2.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "ember-cli-helper",
      "autocomplete-snippets",
      "autocomplete-ctags",
      "ember-snippets",
      "git-plus",
      "linter-jshint"
    ],
    "openEmptyEditorOnStart": false,
    "projectHome": "~/repos/mine"
  },
  "atom-beautify": {
    "_analyticsUserId": "9508f980-3c5c-48ba-b399-eb4232d42836"
  }
}
```

### Installed Packages

```coffee
# User
Handlebars, v1.4.1
api-workbench, v0.8.23
atom-beautify, v0.28.26
atom-chai-snippets, v0.3.0
atom-handlebars, v1.3.0
atomatigit, v1.5.5
autoclose-html, v0.23.0
autocomplete-modules, v1.4.1
autocomplete-paths, v1.0.2
bezier-curve-editor, v0.7.2
browser-plus, v0.0.54
color-picker, v2.1.1
docblockr, v0.7.3
editor-settings, v1.0.4
editorconfig, v1.2.4
emmet, v2.4.3
emmet-snippets-compatibility, v1.0.4
external-open, v0.6.3
figlet, v0.5.3
highlight-selected, v0.11.2
html-entities, v0.4.0
jshint, v1.8.3
language-babel, v2.16.0
language-diff, v0.4.0
linter, v1.11.4
linter-coffeelint, v1.1.2
linter-eslint, v7.1.3
linter-handlebars, v2.3.4
linter-js-yaml, v1.2.5
linter-php, v1.2.0
linter-sass-lint, v1.2.0
linter-xmllint, v1.3.4
markdown-mindmap, v0.2.4
minimap, v4.21.0
minimap-bookmarks, v0.3.0
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.5.0
minimap-highlight-selected, v4.4.0
pigments, v0.24.5
project-manager, v2.7.6
set-syntax, v0.3.0
terminal-plus, v0.14.5
travis-ci-status, v1.0.0

# Dev
No dev packages
```

**Comment by prettydiff** [comment]
Would you mind trying `apm install atom-beautify` from the command line?  It just looks like an NPM package failed to download.

**Comment by ksnyde** [comment]
Hmmm. Ok seems like you're right. I'll close this and reopen if it reoccurs. Thanks for the prompt reply.
