### ISSUE TITLE
Failed to activate the atom-beautify package: "Converting circular structure to JSON"

### ISSUE THREAD

**Issue by Glavin001** [Glavin001/atom-beautify#879]
### Description

Activating Atom Beautify fails.

### Expected Results

Atom Beautify should activate without errors.

### Steps to Reproduce

1. Run command `Atom Beautify: Beautify Editor`, trigger activation
2. Error appears:

  ```
Converting circular structure to JSON

TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at Config.module.exports.Config.setDefaults (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:669:143)
    at Config.module.exports.Config.setDefaults (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:661:16)
    at Config.module.exports.Config.setSchema (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:406:12)
    at Package.module.exports.Package.registerConfigSchemaFromMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:209:23)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:174:54)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:800:25
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

# Checklist

- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues 
so I know this is not a duplicate issue

**Comment by Glavin001** [comment]
Published to v0.29.0

**Comment by chengfang1103** [comment]
Error: Cannot find module 'event-kit'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/chengfang526/.atom/packages/atom-beautify/src/beautify.coffee:7:25)
    at Object.<anonymous> (/Users/chengfang526/.atom/packages/atom-beautify/src/beautify.coffee:2:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:720:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:172:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:800:25
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)

**Comment by Glavin001** [comment]
> Cannot find module 'event-kit'

@chengfang1103 : I recommend that you uninstall and re-install Atom-Beautify. This error indicates to me that the dependency, `event-kit`, was not properly installed by `apm` of Atom.

**Comment by tajobe** [comment]
This issue happens when "installing" from Github and using `apm link`, because this is not an install and therefore apm never runs `npm install`. Unfortunately, the only way I am able to install packages is by manual install and npm does not work behind a corp proxy.

**Comment by Lanceloft** [comment]
Error: Cannot find module 'bluebird'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (D:\Atom\Atom\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (D:\Atom\Atom\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Lanceloft/.atom/packages/atom-beautify/src/beautifiers/index.coffee:3:11)
    at Object.<anonymous> (file:///C:/Users/Lanceloft/.atom/packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at Module._compile (D:\Atom\Atom\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (D:\Atom\Atom\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (D:\Atom\Atom\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/Lanceloft/.atom/packages/atom-beautify/src/beautify.coffee:9:15)
    at Object.<anonymous> (file:///C:/Users/Lanceloft/.atom/packages/atom-beautify/src/beautify.coffee:2:1)
    at Module._compile (D:\Atom\Atom\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (D:\Atom\Atom\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (D:\Atom\Atom\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (D:\Atom\Atom\resources\app.asar\src\package.js:715:27)
    at Package.module.exports.Package.activateNow (D:\Atom\Atom\resources\app.asar\src\package.js:173:16)
    at D:\Atom\Atom\resources\app.asar\src\package.js:795:25
    at Function.module.exports.Emitter.simpleDispatch (D:\Atom\Atom\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (D:\Atom\Atom\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (D:\Atom\Atom\resources\app.asar\src\command-registry.js:241:20)
    at D:\Atom\Atom\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (D:\Atom\Atom\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (D:\Atom\Atom\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)

**Comment by Glavin001** [comment]
@Lanceloft : You should try reinstalling Atom-Beautify or if you are cloning the repository then be sure to run `apm install`, which will run `npm install` and install the required dependencies such as `bluebird`.

**Comment by rizidoro** [comment]
**Atom Version**: 1.7.3
**System**: Mac OS X 10.11.3
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.29.7


### Stack Trace

Failed to activate the atom-beautify package

```
At Cannot find module './lib/colors'

Error: Cannot find module './lib/colors'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/rizidoro/.atom/packages/atom-beautify/node_modules/winston/node_modules/colors/safe.js:8:14)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/rizidoro/.atom/packages/atom-beautify/node_modules/winston/lib/winston/config.js:9:14)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/rizidoro/.atom/packages/atom-beautify/node_modules/winston/lib/winston/common.js:15:14)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/rizidoro/.atom/packages/atom-beautify/node_modules/winston/lib/winston.js:24:26)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at /Users/rizidoro/.atom/packages/atom-beautify/src/logger.coffee:10:13
    at Object.<anonymous> (/Users/rizidoro/.atom/packages/atom-beautify/src/logger.coffee:4:18)
    at Object.<anonymous> (/Users/rizidoro/.atom/packages/atom-beautify/src/logger.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/rizidoro/.atom/packages/atom-beautify/src/beautifiers/index.coffee:6:10)
    at Object.<anonymous> (/Users/rizidoro/.atom/packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/rizidoro/.atom/packages/atom-beautify/src/beautify.coffee:9:15)
    at Object.<anonymous> (/Users/rizidoro/.atom/packages/atom-beautify/src/beautify.coffee:2:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:173:16)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:795:25
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:20)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:12.3.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
  3x -0:12.2.0 vim-mode:repeat-prefix (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:11.9.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:11.7.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:11.7.0 vim-mode:move-to-previous-word (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:11.5.0 vim-mode:move-to-beginning-of-line (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:10.8.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -0:10.4.0 vim-mode:repeat-prefix (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:10.1.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  3x -0:09.9.0 vim-mode:repeat-prefix (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:09.5.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:04.1.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:03.3.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:03.1.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:02.9.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:01.6.0 core:save (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.7
language-ansible, v0.1.6
linter, v1.11.4
linter-erb, v1.0.2
linter-ruby, v1.2.2
vim-mode, v0.65.0
vim-surround, v0.8.1

# Dev
No dev packages
```

**Comment by kabircse** [comment]
Failed to activate the atom-beautify package
Cannot find module 'form-data'
Hide Stack Trace
Error: Cannot find module 'form-data'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (C:\Users\reality\AppData\Local\atom\app-1.8.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (C:\Users\reality\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\reality\.atom\packages\atom-beautify\node_modules\analytics-node\node_modules\superagent\lib\node\index.js:8:16)
    at Module._compile (C:\Users\reality\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\reality\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\reality\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\reality\.atom\packages\atom-beautify\node_modules\analytics-node\lib\index.js:5:15)
    at Module._compile (C:\Users\reality\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\reality\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\reality\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at file:///C:/Users/reality/.atom/packages/atom-beautify/src/beautifiers/index.coffee:20:15
    at exports.allowUnsafeEval (C:\Users\reality\.atom\packages\atom-beautify\node_modules\loophole\lib\loophole.js:14:14)
    at Object.<anonymous> (file:///C:/Users/reality/.atom/packages/atom-beautify/src/beautifiers/index.coffee:19:1)
    at Object.<anonymous> (file:///C:/Users/reality/.atom/packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at Module._compile (C:\Users\reality\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\reality\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\reality\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/reality/.atom/packages/atom-beautify/src/beautify.coffee:9:15)
    at Object.<anonymous> (file:///C:/Users/reality/.atom/packages/atom-beautify/src/beautify.coffee:2:1)
    at Module._compile (C:\Users\reality\AppData\Local\atom\app-1.8.0\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\reality\AppData\Local\atom\app-1.8.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
The error was thrown from the atom-beautify package. This issue has already been reported.

**Comment by OlegLustenko** [comment]
Failed to activate the atom-beautify package
Cannot find module 'core-util-is'
Hide Stack Trace
Error: Cannot find module 'core-util-is'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (C:\Users\admin\AppData\Local\atom\app-1.7.4\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (C:\Users\admin\AppData\Local\atom\app-1.7.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\admin\.atom\packages\atom-beautify\node_modules\analytics-node\node_modules\superagent\node_modules\readable-stream\lib\_stream_duplex.js:39:12)
    at Module._compile (C:\Users\admin\AppData\Local\atom\app-1.7.4\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\admin\AppData\Local\atom\app-1.7.4\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\admin\AppData\Local\atom\app-1.7.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\admin\.atom\packages\atom-beautify\node_modules\analytics-node\node_modules\superagent\node_modules\readable-stream\lib\_stream_transform.js:67:14)
    at Module._compile (C:\Users\admin\AppData\Local\atom\app-1.7.4\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\admin\AppData\Local\atom\app-1.7.4\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\admin\AppData\Local\atom\app-1.7.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\admin\.atom\packages\atom-beautify\node_modules\analytics-node\node_modules\superagent\node_modules\readable-stream\lib\_stream_passthrough.js:28:17)
    at Module._compile (C:\Users\admin\AppData\Local\atom\app-1.7.4\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\admin\AppData\Local\atom\app-1.7.4\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\admin\AppData\Local\atom\app-1.7.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\admin\.atom\packages\atom-beautify\node_modules\analytics-node\node_modules\superagent\node_modules\readable-stream\passthrough.js:1:97)
    at Module._compile (C:\Users\admin\AppData\Local\atom\app-1.7.4\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\admin\AppData\Local\atom\app-1.7.4\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\admin\AppData\Local\atom\app-1.7.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\admin\.atom\packages\atom-beautify\node_modules\analytics-node\node_modules\superagent\lib\node\part.js:9:19)
    at Module._compile (C:\Users\admin\AppData\Local\atom\app-1.7.4\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\Users\admin\AppData\Local\atom\app-1.7.4\resources\app.asar\src\compile-cache.js:208:21)
The error was thrown from the atom-beautify package. This issue has already been reported.
View Issue

**Comment by kabircse** [comment]
Hey....... My problem is solved. There is a new version 0.29.8.

First uninstall your atom-beautify.
Second, run this command from your terminal:    apm install atom-beautify
