### ISSUE TITLE
Uncaught Error: Cannot find module '../../package.json'

### ISSUE THREAD

**Issue by neelusb** [Glavin001/atom-beautify#906]
[Enter steps to reproduce below:]
1. Search for `atom-beautify` in the `Install` Section of Settings.
2. Click `Install`
3. Let package download.
4. Error appears after the package finishes downloading.

**Atom Version**: 1.6.2
**System**: Mac OS X 10.11
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.29.2
### Stack Trace

Uncaught Error: Cannot find module '../../package.json'

```
At module.js:338

Error: Cannot find module '../../package.json'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/neelusb/.atom/packages/atom-beautify/src/beautifiers/index.coffee:21:7)
    at Object.<anonymous> (/Users/neelusb/.atom/packages/atom-beautify/src/beautifiers/index.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/neelusb/.atom/packages/atom-beautify/src/beautify.coffee:9:15)
    at Object.<anonymous> (/Users/neelusb/.atom/packages/atom-beautify/src/beautify.coffee:2:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:720:27)
    at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:220:12)
    at PackageDetailView.module.exports.PackageDetailView.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:216:26)
    at PackageDetailView.module.exports.PackageDetailView.completeInitialzation (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:159:12)
    at PackageDetailView.module.exports.PackageDetailView.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:171:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:302:17
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:664:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:452:26
    at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
### Commands

```
  4x -9:33.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -9:31 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "atom-beautify": {}
}
```
### Installed Packages

``` coffee
# User
color-picker, v2.1.1
emmet, v2.4.3
highlight-selected, v0.11.2
linter, v1.11.4
linter-csslint, v1.3.2
linter-htmlhint, v1.1.1
linter-jshint, v2.0.4
linter-php, v1.2.0
linter-pylint, v1.2.0
minimap, v4.21.0
minimap-highlight-selected, v4.4.0
minimap-linter, v1.1.1
minimap-pigments, v0.2.0
pigments, v0.26.0

# Dev
No dev packages
```

**Comment by Glavin001** [comment]
>     at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)

Maybe a caching issue in Atom. Does uninstall and reinstalling Atm-Beautify fix this? Or restarting Atom?
