### ISSUE TITLE
Parsing error when beautifing a C++ code 

### ISSUE THREAD

**Issue by tarek2** [Glavin001/atom-beautify#914]
### Description

I get the following error when I try to beautify a C++ code:

Parsing: /tmp/input116312-6987-1qeqaaq as language CPP make_folders: Unable to create /tmp: File exists (17)
Parsing: /tmp/input116312-6987-1qeqaaq as language CPP
make_folders: Unable to create /tmp: File exists (17)

**Comment by Glavin001** [comment]
Please follow the issue template. Specifically adding the debugging information: https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md#how-to-create-debugmd-gist

**Comment by shakram02** [comment]
I have the same problem, here is the stack trace 

`Error: Parsing: /tmp/input117030-8478-n5c0sx.sa9h82rzfr as language CPP
    at /home/ahmed/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:295:27
    at tryCatcher (/home/ahmed/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ahmed/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/ahmed/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/ahmed/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/ahmed/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/ahmed/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/ahmed/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/home/ahmed/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)`

**Comment by Mayshy** [comment]
Changing your environment path "xxx/tmp"  to "%SystemRoot%\TEMP" could maybe solve it,though I didn't get the reason.
