### ISSUE TITLE
Ruby beautification doesn't work with ruby-beautify and rubocop

### ISSUE THREAD

**Issue by kannanr** [Glavin001/atom-beautify#970]
### Description

Beautification of Ruby code (.rb) is not working. With ruby-beautify as the default beautifier - it results in exception.
With rubocop - it does nothing.

Same case when tried with beautifyOnSave and when running the command Atom Beautify: Beautify Editor

### Expected Results

To beautify the ruby code.

### Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. Beautification either results in exception (incase of ruby-beautify) or does nothing (incase of rubocop)

### Debug
Here is a link to the `debug.md` Gist: https://gist.github.com/kannanr/a06234b7b3ac524a392d63a094c174ff

- [ Y] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ Y] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [ Y] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues 
so I know this is not a duplicate issue
- [ N] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment]
Please add a link to the required `debug.md` Gist which includes debugging information that answers our most commonly asked questions: https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md#how-to-create-debugmd-gist
Thank you.

**Comment by kannanr** [comment]
Hi Glavin,

Added link to the debug.md. 

Sorry - it wasn't adding anything to clipboard - but i only saw the popup with the error yesterday - today it actually copied the debug details to clipboard.

Hope this debug.md helps.

**Comment by kannanr** [comment]
I also tried to create another debug.md with ruby-beautifier as the selected beautifier - but that does nothing (no clipboard changes) like i mentioned in previous comment.

**Comment by Glavin001** [comment]
I see in the logs:
```
2016-05-13T08:31:07.996Z - debug: [beautifiers/beautifier.coffee] spawn /Users/kannan/.rvm/gems/jruby-9.0.4.0@digital_services_hub/bin/rubocop 0=--auto-correct, 1=--config, 2=/var/folders/5v/2wdh66fs5jx6h3v4bvmwvq9w0000gn/T/rubocop-config116413-39116-57t3ar, 3=/var/folders/5v/2wdh66fs5jx6h3v4bvmwvq9w0000gn/T/temp116413-39116-ez3tvn
2016-05-13T08:31:08.297Z - debug: [beautifiers/beautifier.coffee] spawn done 1 Exception in thread "main" java.lang.ExceptionInInitializerError
    at org.jruby.util.log.LoggerFactory.<clinit>(LoggerFactory.java:35)
    at org.jruby.Main.<clinit>(Main.java:78)
Caused by: java.lang.NumberFormatException: For input string: ""
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:592)
    at java.lang.Integer.parseInt(Integer.java:615)
    at com.headius.options.IntegerOption.reloadValue(IntegerOption.java:44)
    at com.headius.options.IntegerOption.reloadValue(IntegerOption.java:20)
    at com.headius.options.Option.reload(Option.java:433)
    at com.headius.options.Option.load(Option.java:424)
    at org.jruby.util.cli.Options.<clinit>(Options.java:114)
    ... 2 more
```

It looks like a Java error when calling Rubocop. Must have something to do with [JRuby](http://jruby.org/).
This is either a Rubocop or JRuby error. Please ask them for assistance:
- JRuby: http://jruby.org/
- Rubocop: https://github.com/bbatsov/rubocop

From an Atom-Beautify perspective, we can change the arguments used to call the command-line interface of `rubocop`. Let me know if that would help, however this error is being throw from Rubocop/JRuby.
