### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getStackClasses' of null

### ISSUE THREAD

**Issue by kadzik** [Glavin001/atom-beautify#972]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.29.7

### Stack Trace

Uncaught TypeError: Cannot read property 'getStackClasses' of null

```
At /C:/Users/kadzik/.atom/packages/atom-symfony2/lib/providers/service-provider.coffee:40

TypeError: Cannot read property 'getStackClasses' of null
    at ServiceProvider.module.exports.ServiceProvider.getSuggestions (file:///C:/Users/kadzik/.atom/packages/atom-symfony2/lib/providers/service-provider.coffee:31:33)
    at D:\Lukasz\Programy\Atom\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:310:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (D:\Lukasz\Programy\Atom\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:289:17)
    at AutocompleteManager.getSuggestionsFromProviders (D:\Lukasz\Programy\Atom\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (D:\Lukasz\Programy\Atom\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:276:19)
    at D:\Lukasz\Programy\Atom\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3:61
```

### Commands

```
     -2:10.9.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
  6x -2:02.4.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -2:00.4.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -2:00.0 core:save (atom-text-editor.editor.is-focused)
  3x -1:51.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:48.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:54.4.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:53.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:43.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:42.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:39.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:39.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:30 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:29.6.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:26.7.0 autoclose-html:close-and-complete (atom-text-editor.editor.is-focused)
     -0:19.7.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-autocomplete-php",
      "linter-twig"
    ]
  },
  "atom-beautify": {
    "general": {
      "_analyticsUserId": "96df2e02-f44c-419d-a76d-984998386d3d"
    }
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.7
atom-symfony2, v0.2.1
autoclose-html, v0.23.0
autocomplete-json, v1.9.1
autocomplete-php, v0.3.7
autocomplete-project-paths, v2.2.0
color-picker, v2.1.1
emmet, v2.4.3
emmet-snippets-compatibility, v1.0.6
gitlab, v0.1.3-7
highlight-line, v0.11.1
highlight-selected, v0.11.2
hyperclick-php, v0.2.1
keyboard-localization, v1.4.18
linter, v1.11.4
linter-csslint, v1.3.2
linter-htmlhint, v1.1.4
linter-js-yaml, v1.2.5
local-history, v3.2.3
minimap, v4.23.2
minimap-git-diff, v4.3.0
minimap-highlight-selected, v4.4.0
minimap-pigments, v0.2.0
php-integrator-linter, v0.2.2
php-twig, v4.0.0
pigments, v0.26.0
remote-sync, v4.1.0
run-in-browser, v0.1.3
symfony-snippets, v0.3.0
sync-settings, v0.7.2
yaml-path, v0.1.0

# Dev
No dev packages
```

**Comment by Glavin001** [comment]
> At /C:/Users/kadzik/.atom/packages/atom-symfony2/lib/providers/service-provider.coffee:40

This is an error throw from `atom-symfony2`.
