### ISSUE TITLE
Uncaught TypeError: Beautifier is not a function

### ISSUE THREAD

**Issue by Ptival** [Glavin001/atom-beautify#978]
I just installed atom-beautify, and immediately after this pops up.

**Atom Version**: 1.7.3
**System**: linux 4.4.10
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.29.7
### Stack Trace

Uncaught TypeError: Beautifier is not a function

```
At /home/ptival/.atom/packages/atom-beautify/src/beautifiers/index.coffee:98

TypeError: Beautifier is not a function
    at /home/ptival/.atom/packages/atom-beautify/src/beautifiers/index.coffee:98:11
    at arrayMap (/home/ptival/.atom/packages/atom-beautify/node_modules/lodash/lodash.js:595:23)
    at Function.map (/home/ptival/.atom/packages/atom-beautify/node_modules/lodash/lodash.js:8778:14)
    at new Beautifiers (/home/ptival/.atom/packages/atom-beautify/src/beautifiers/index.coffee:96:22)
    at Object.<anonymous> (/home/ptival/.atom/packages/atom-beautify/src/beautify.coffee:10:18)
    at Object.<anonymous> (/home/ptival/.atom/packages/atom-beautify/src/beautify.coffee:2:1)
    at Module._compile (/nix/store/szadfv521c45dqvb0c0z2cgmnaj9ppyb-atom-1.7.3/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/nix/store/szadfv521c45dqvb0c0z2cgmnaj9ppyb-atom-1.7.3/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/nix/store/szadfv521c45dqvb0c0z2cgmnaj9ppyb-atom-1.7.3/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/nix/store/szadfv521c45dqvb0c0z2cgmnaj9ppyb-atom-1.7.3/share/atom/resources/app.asar/src/package.js:715:27)
    at Package.module.exports.Package.activateConfig (/nix/store/szadfv521c45dqvb0c0z2cgmnaj9ppyb-atom-1.7.3/share/atom/resources/app.asar/src/package.js:222:12)
    at PackageDetailView.module.exports.PackageDetailView.activateConfig (/nix/store/szadfv521c45dqvb0c0z2cgmnaj9ppyb-atom-1.7.3/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:220:26)
    at PackageDetailView.module.exports.PackageDetailView.completeInitialzation (/nix/store/szadfv521c45dqvb0c0z2cgmnaj9ppyb-atom-1.7.3/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:163:12)
    at PackageDetailView.module.exports.PackageDetailView.loadPackage (/nix/store/szadfv521c45dqvb0c0z2cgmnaj9ppyb-atom-1.7.3/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:175:21)
    at PackageDetailView.module.exports.PackageDetailView.initialize (/nix/store/szadfv521c45dqvb0c0z2cgmnaj9ppyb-atom-1.7.3/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:150:19)
    at PackageDetailView.View [as constructor] (/nix/store/szadfv521c45dqvb0c0z2cgmnaj9ppyb-atom-1.7.3/share/atom/resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
    at PackageDetailView.ScrollView [as constructor] (/nix/store/szadfv521c45dqvb0c0z2cgmnaj9ppyb-atom-1.7.3/share/atom/resources/app.asar/node_modules/atom-space-pen-views/lib/scroll-view.js:12:47)
    at new PackageDetailView (/nix/store/szadfv521c45dqvb0c0z2cgmnaj9ppyb-atom-1.7.3/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:42:54)
    at /nix/store/szadfv521c45dqvb0c0z2cgmnaj9ppyb-atom-1.7.3/share/atom/resources/app.asar/node_modules/settings-view/lib/settings-view.js:269:22
    at SettingsView.module.exports.SettingsView.getOrCreatePanel (/nix/store/szadfv521c45dqvb0c0z2cgmnaj9ppyb-atom-1.7.3/share/atom/resources/app.asar/node_modules/settings-view/lib/settings-view.js:274:19)
    at SettingsView.module.exports.SettingsView.showPanel (/nix/store/szadfv521c45dqvb0c0z2cgmnaj9ppyb-atom-1.7.3/share/atom/resources/app.asar/node_modules/settings-view/lib/settings-view.js:320:24)
    at space-pen-div.<anonymous> (/nix/store/szadfv521c45dqvb0c0z2cgmnaj9ppyb-atom-1.7.3/share/atom/resources/app.asar/node_modules/settings-view/lib/package-card.js:276:83)
    at space-pen-div.jQuery.event.dispatch (/nix/store/szadfv521c45dqvb0c0z2cgmnaj9ppyb-atom-1.7.3/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-div.elemData.handle (/nix/store/szadfv521c45dqvb0c0z2cgmnaj9ppyb-atom-1.7.3/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```
### Commands

```
     -3:19.1.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
     -3:15.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -3:15.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:10 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
  4x -3:07.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -3:06.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:00.8.0 editor:move-to-previous-subword-boundary (atom-text-editor.editor.is-focused)
  5x -2:39.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:26.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {},
  "atom-beautify": {
    "_analyticsUserId": "3bd9e32e-a08b-467b-aabf-7a8dfd564448"
  }
}
```
### Installed Packages

``` coffee
# User
atom-typescript, v8.10.1
autohide-tree-view, v0.25.1
block-travel, v1.0.4
language-haskell, v1.7.15
language-ocaml, v1.1.2
linter, v1.11.4
nix, v2.1.0
pain-split, v1.4.0
polymer-atom, v0.0.8
project-manager, v2.9.7

# Dev
No dev packages
```

**Comment by Glavin001** [comment]
I've seen reinstalling and/or restarting Atom helps. See https://github.com/Glavin001/atom-beautify/issues/952#issuecomment-214869463 for one example. Let me know how that goes.

**Comment by Ptival** [comment]
Will give it a try, atom has indeed been acting up around this package!
