### ISSUE TITLE
Uncaught TypeError: Cannot read property 'mainModule' of undefined

### ISSUE THREAD

**Issue by JuniorLOL** [Glavin001/atom-beautify#988]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Unknown Windows Version
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.29.7

### Stack Trace

Uncaught TypeError: Cannot read property 'mainModule' of undefined

```
At /C:/Users/Junior/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:146

TypeError: Cannot read property 'mainModule' of undefined
    at OpenInBrowsersView.open (file:///C:/Users/Junior/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:84:9)
    at OpenInBrowsersView.openBrowser (file:///C:/Users/Junior/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:54:8)
    at atom-workspace.<anonymous> (file:///C:/Users/Junior/.atom/packages/open-in-browsers/lib/open-in-browsers.coffee:165:33)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Junior\AppData\Local\atom\app-1.7.3\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\Junior\AppData\Local\atom\app-1.7.3\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Junior\AppData\Local\atom\app-1.7.3\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\Junior\AppData\Local\atom\app-1.7.3\resources\app.asar\src\atom-environment.js:1106:28)
    at EventEmitter.outerCallback (C:\Users\Junior\AppData\Local\atom\app-1.7.3\resources\app.asar\src\application-delegate.js:327:25)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
```

### Commands

```
     -4:48 open-in-browsers:toggle (atom-text-editor.editor.is-focused)
  4x -4:24.8.0 window:toggle-full-screen (atom-text-editor.editor.is-focused)
     -2:08.2.0 window:run-package-specs (atom-text-editor.editor.is-focused)
     -1:58.1.0 symbols-tree-view:toggle (atom-text-editor.editor.is-focused)
     -1:56.1.0 window:run-package-specs (atom-text-editor.editor.is-focused)
  2x -1:07.3.0 open-in-browsers:toggle (atom-text-editor.editor.is-focused)
  4x -0:44.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:14.3.0 open-in-browsers:Chrome (span.name.icon.icon-file-text)
     -0:09.9.0 open-in-browsers:Safari (span.name.icon.icon-file-text)
     -0:02.8.0 open-in-browsers:BrowserPlus (span.name.icon.icon-file-text)
```

### Config

```json
{
  "core": {
    "packagesWithKeymapsDisabled": [
      "open-in-browsers"
    ]
  },
  "atom-beautify": {
    "general": {
      "_analyticsUserId": "3aa5f738-69c5-44d5-8371-c4e6e4f82115"
    },
    "html": {}
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.1.1
emmet, v2.4.3
file-icons, v1.7.12
highlight-selected, v0.11.2
livestyle-atom, v0.1.3
minimap, v4.24.0
minimap-find-and-replace, v4.5.1
minimap-pigments, v0.2.1
open-in-browsers, v0.0.15
pigments, v0.26.3
regex-railroad-diagram, v0.16.0
Remote-FTP, v0.8.3
Stylus, v3.0.0
symbols-tree-view, v0.12.0

# Dev
No dev packages
```

**Comment by Glavin001** [comment]
> At /C:/Users/Junior/.atom/packages/open-in-browsers/lib/open-in-browsers-view.coffee:146

This is an error from the `open-in-browsers` package.
