### ISSUE TITLE
Uncaught TypeError: Cannot read property 'substr' of null

### ISSUE THREAD

**Issue by JakeTheSnake3p0** [Glavin001/atom-beautify#990]
[Steps to reproduce below:]

1. Update the package
2. Fail

**Atom Version**: 1.7.4
**System**: Microsoft Windows 7 Ultimate 
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.29.7

### Stack Trace

Uncaught TypeError: Cannot read property 'substr' of null

```
At C:\Users\Administrator\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\settings-view\lib\package-card.js:709

TypeError: Cannot read property 'substr' of null
    at C:\Users\Administrator\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\settings-view\lib\package-card.js:709:80
    at C:\Users\Administrator\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\settings-view\lib\package-manager.js:376:51
    at C:\Users\Administrator\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\settings-view\lib\package-manager.js:403:20
    at exit (C:\Users\Administrator\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\Administrator\AppData\Local\atom\app-1.7.4\resources\app.asar\src\buffered-process.js:215:47)
    at C:\Users\Administrator\AppData\Local\atom\app-1.7.4\resources\app.asar\src\buffered-process.js:222:18
    at Socket.<anonymous> (C:\Users\Administrator\AppData\Local\atom\app-1.7.4\resources\app.asar\src\buffered-process.js:100:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "ruby-block",
      "linter-htmlhint"
    ],
    "packagesWithKeymapsDisabled": [],
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
file-icons, v1.7.12
highlight-selected, v0.11.2
less-than-slash, v0.13.0
linter, v1.11.4
linter-csslint, v1.3.2
linter-erb, v1.0.2
linter-eslint, v7.2.2
linter-js-standard, v3.3.2
linter-reek, v2.1.5
linter-rubocop, v0.4.7
linter-ruby, v1.2.2
minimap, v4.24.1
minimap-highlight-selected, v4.4.0
rest-client, v1.1.0
ruby-syntax-replacer, v0.5.1

# Dev
No dev packages
```

**Comment by Glavin001** [comment]
> At C:\Users\Administrator\AppData\Local\atom\app-1.7.4\resources\app.asar\node_modules\settings-view\lib\package-card.js:709

The error looks to be coming from `settings-view` instead: https://github.com/atom/settings-view
